### ISSUE TITLE
Add GAE devserver provided libraries to the Application Servers window

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1042]
It is currently empty.

At the moment, I think dev_appserver only provides servlet-api.jar?

![screenshot from 2016-10-19 11 13 12](https://cloud.githubusercontent.com/assets/3290856/19524865/2460615e-95ed-11e6-8e0d-748325869623.png)

**Comment by etanshaul** [comment]
some more motivation for not adding the servlet / jsp jars to the classpath manually: 

http://stackoverflow.com/questions/4076601/how-do-i-import-the-javax-servlet-api-in-my-eclipse-project/4076706#4076706  (see the last section of that answer, "Never carry around loose server-specific JAR files").

**Comment by etanshaul** [comment]
@akerekes on the IJ side we are going to go ahead an try to add both the servlet and jsp libs automatically to the app server provided libs (without a UI to opt-out).

**Comment by ludoch** [comment]
Are you ready to support Servlet 3.1 and Java8?
on the config side, it will be indicated with a <runtime>java8</runtime> in
appengine-web.xml.
In this case, you would want to put servlet 3.1 in the path.

**Comment by patflynn** [comment]
On the other hand, 99% of actual JEE based projects are Maven or Gradle
based and do not use the server provided libraries but instead specify the
spec API libraries in provided scope. Even when they do use server specific
libraries, I believe they're still getting them from Maven central rather
than a local server install.

It definitely fits better into the Native IJ and Eclipse project
architecture to configure those libraries from the server install, but I
suspect it's not much utilized, and not a huge priority.

**Comment by etanshaul** [comment]
closed as stale / "won't fix"
