### ISSUE TITLE
App Engine deployments do not provide regular progress feedback

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#1071]
Steps to reproduce:
1) use our plugin to deploy via standard or flex

observe:
Our console spends seconds and sometimes minutes (for flex) without output.  It's not clear to users whether deployment has completed, has failed, or what..

Expected outcome:
- deployment spinner continues spinning
- console output indicates that work is still happening, ideally with some kind of percentage completion.

**Comment by etanshaul** [comment]
closed as "won't fix" due to limited enhancements for ae flex
