### ISSUE TITLE
In 2016.3, the App Engine plugin conflict notification pop-up does not appear

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/cloud-code-intellij#1105]
In prior versions, a notification is shown on the application welcome screen if the old app engine plugin is installed. In 2016.3, the notification does not pop up, though it appear within the "Events" list if the user clicks on it.

We should investigate if it's possible to still show this as a pop up.

**Comment by etanshaul** [comment]
closed as obsolete
