### ISSUE TITLE
mvn clean followed by standard deploy causes java.io.FileNotFoundException

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1138]
mvn clean seems to mess up IJ's native artifact generation.

Doing mvn clean and then trying to deploy the automatically generated exploded war artifact causes a java.io.FileNotFoundException. The reason is that the WEB-INF contents are no longer all copied. In particular, only web.xml is copied. i.e., appengine-web.xml and logging.properties, for example, aren't copied.

Deleting the automatically generated artifact and creating a new one works, and the new artifact is resilient to this issue. Using the Maven artifact also resists this issue.

**Comment by etanshaul** [comment]
closed as "wont' fix"
