### ISSUE TITLE
End to end test

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-code-intellij#121]
We need one end-to-end test that builds and installs the plugin, runs IDEA, and verifies that the relevant menu items show up and can be selected and do what we expect them to do.

This can be built in pieces. E.g. a first step might be to verify that IDEA starts up and doesn't crash and burn when our plugin is installed.

**Comment by elharo** [comment]
Request for assistance at JetBrains forums: https://devnet.jetbrains.com/thread/473640?tstart=0

devBuild task in master build.gradle may be helpful here.

**Comment by elharo** [comment]
Some options: Marathon: http://marathontesting.com/marathon/
JFCUnit (abandoned? does this still work?)
UISpec4J https://github.com/UISpec4J/UISpec4J

http://stackoverflow.com/questions/79891/what-is-the-best-testing-tool-for-swing-based-applications

**Comment by elharo** [comment]
The gradle application plugin adds a run task to run an application:

https://docs.gradle.org/current/userguide/application_plugin.html

**Comment by elharo** [comment]
Linux_Desktop_Testing_Project http://ldtp.freedesktop.org/wiki/  looks interesting. requires accessibility enabled app. Is IDEA such?

**Comment by elharo** [comment]
Option 3: Launch IntelliJ from the test (perhaps in different classloader) then use
IdeFrame[] frames = WindowManager.getInstance().getAllProjectFrames();
and start mucking with the API. For once all the global static state might actually help us.

**Comment by elharo** [comment]
Possibly JMX, JVMTI, and/or JDI might help here. Explore.

**Comment by patflynn** [comment]
Definitely take a look at what Android Studio is doing if you haven't
already.

**Comment by etanshaul** [comment]
closing in favor a new issue to track this work. this is very old
