### ISSUE TITLE
Update release process to deploy to 'beta' channel

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#1245]
We should have a one/two week beta channel for release candidates.  

Our release process should be updated to deploy first to 'beta' channel, and wait some time for validation.

For this to be useful we need users on the 'beta' channel.  We should update cloud docs to suggest using this channel for users willing to tolerate some slight instability.

**Comment by etanshaul** [comment]
closed as won't fix. we use the `alpha` channel for this.
