### ISSUE TITLE
Set module in module selector to artifact's module in the Flexible Deployment UI, if a direct relationship exists

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1287]
Currently, for the case where there are multiple modules with the Flexible facet in the same project and a deployment run configuration is created, it's possible to select the deployable for module A and module B is selected by default in the module selector.

We should probably match the artifact's name to the module and, if it matches any, select that one by default.

**Comment by etanshaul** [comment]
closed as won't fix
