### ISSUE TITLE
Inspect appengine-web.xml and warn for <vm>true</vm> or <env>flex</env> or incompatible combinations

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1292]
We should probably be popping up a warning if the user adds <vm>true</vm> or <env>flex</env> to appengine-web.xml.

There are also combinations where we could be failing earlier, such as using <runtime>java8</runtime> and <env>flex</env>.

@ludoch please add more combinations if you come across them, given there's no formal list of incompatible combinations.

**Comment by etanshaul** [comment]
closed as stale / won't fix
