### ISSUE TITLE
Use PsiFiles on the facet generate button, if file already exists

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1298]
To get rid of the "file change on the file system" warning.

@etanshaul is this what you were working on in the Generate buttons?

**Comment by joaoandremartins** [comment]
Besides the generate buttons, the app.yaml generation on Add Framework Support should also be changed to stop using FileUtil.

**Comment by etanshaul** [comment]
closed as won't fix
