### ISSUE TITLE
2017.1: Before launch goals include both maven build and artifact build for app engine standard deployment

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#1317]
It looks like there's been a change in 2017 in how it configures before launch goals. 

If your deployment source is the intellij artifact it includes both the maven and the artifact as before launch build tasks.

If your deployment source is the maven artifact it includes both the maven build and a 'Build Artifacts' build step.

**Comment by joaoandremartins** [comment]
I think this has been the case before. If you select a native artifact as a deployable and then select a Maven one, there will be both the new Maven rule and the old one isn't deleted, so it stays there.

When the run config is created, I can only see one rule.

**Comment by etanshaul** [comment]
Yes, if that is indeed what you were doing (selecting a native source then switching to maven, or the other way around) then this is always how it worked. The IJ model, for whatever reason, is only to append before launch tasks, not to remove them.

**Comment by etanshaul** [comment]
closed as obsolete
