### ISSUE TITLE
Move App Engine standard option from under Web to top level, in New Project section

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1328]
Right now, the flexible and standard options are very far from each other on the New Project menu.

Moving standard away from under Web also makes standard support possible on IC again, where you could deploy a Maven deployable. Local run might not possible, though, since there's no exploded war option, and I don't think Maven deployables can be used to run devappserver.

This should also fix #1203. I'm wondering if this should launch with the Flexible release?

**Comment by patflynn** [comment]
We initially changed this because users including Les and someone in UX
testing included the app engine standard support but not web support, and
ended up with an application that couldn't be run. I think we'd need to
solve that problem before we changed it back

**Comment by etanshaul** [comment]
closed as won't fix
