### ISSUE TITLE
Maven projects' dependencies not automatically added to exploded war's WEB-INF/lib

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1337]
This can result in some user friction, particularly in non-expert IJ users.

For Maven projects, I found myself having to manually copy the Maven libraries to WEB-INF/lib. We could probably copy these dependencies to the exploded war's WEB-INF/lib directory (or even create a new artifact, App Engine exploded war, to be used with the App Engine's devappserver) at add framework support time.
Keeping the artifact dependencies in sync with the Maven ones might be a bit trickier, but there might be a way (or else, we should at least document this behaviour in our docs and workarounds in our docs).

**Comment by etanshaul** [comment]
Yeah, there isn't support yet for managed dependencies in Maven projects. I thought we had an issue for this, but I can't immediately find it.

**Comment by joaoandremartins** [comment]
At the very least, I think we should add a "Development server" menu entry to https://cloud.google.com/tools/intellij/docs/ that explains how to manually add Maven/Gradle/etc. to the artifact. Even though this is an IDE idiosyncrasy, we should make it easier for users to use devappserver.

**Comment by etanshaul** [comment]
it would also apply to deployment though, not just devappserver

**Comment by patflynn** [comment]
I might need to be walked through this. I don't understand the issue. If I import a maven war project using app engine standard,local build and run seem to work fine.

**Comment by etanshaul** [comment]
Maybe I misunderstood too, but I interpreted this as referring to supporting or "managed" app engine libraries (those you can choose when creating a project or via the facet) in Maven based projects.

**Comment by joaoandremartins** [comment]
Importing https://cloud.google.com/appengine/docs/flexible/java/using-cloud-storage and trying to run it fails, because the Maven dependencies aren't added to the exploded war artifact.

**Comment by patflynn** [comment]
you mean by adding it natively to the project or adding it to the pom.xml?

**Comment by joaoandremartins** [comment]
They're added to the pom.xml, but aren't added to the exploded war artifact that is created.
If you look at Module Settings -> Artifacts -> WEB-INF/lib, you won't find the Maven dependencies there. They're on the right hand side menu and need to be manually added to the artifact.

I also found that, for that project, if we select all of the GAE standard dependencies from the menu, they clash with the ones imported by Maven. i.e., HttpServletRequest isn't gotten from the correct javax.servlet. But this is probably another issue.

**Comment by patflynn** [comment]
This sounds like a bug in IntelliJ Maven sync.  Perhaps you just have to
recreate the artifact.

**Comment by etanshaul** [comment]
closing as won't fix
