### ISSUE TITLE
Default Web resources directory not in sync with the one created by the App Engine standard support

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1338]
I just added standard framework support on an existing project. For that, I had to remove the Web facet and then add GAE standard support, that re-added Web support by consequence.

Previously, the project had a src/main/webapp folder only containing an index.html. The Web facet's Web resource directory pointed to that folder.

However, the web resources folder added by App Engine standard is simply "web".

After the Web support was re-added, the old src/main/webapp folder was being used as the Web resources directory, which didn't contain the appengine-web.xml file and, therefore, made devappserver not runnable (because it couldn't find appengine-web.xml).

I had to manually make the Web facet point from the old src/main/webapp to web, in order for it to start including the standard resources there, and work.

**Comment by etanshaul** [comment]
closed as stale
