### ISSUE TITLE
Ideally release notes commit would be on the same PR as the release. 

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#1357]
It's kind of uncool the way we merge the release notes in to master before we actually cut the release tag that matches it.  Ideally these would happen at the same time.  An automated task that merges that updates CHANGELOG.md against the tag name and merges that into plugin.xml would be ideal.

**Comment by etanshaul** [comment]
this is outdated given our new repo structure
