### ISSUE TITLE
Deploy to App Engine menu item should only be enabled for projects with correct facet

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-code-intellij#1541]
I.e. this dialog shouldn't be needed:

![screenshot from 2017-07-05 16 15 22](https://user-images.githubusercontent.com/1005544/27883169-a3531dfe-619d-11e7-91f8-dae6cd71a1a6.png)

**Comment by etanshaul** [comment]
I think the reason we decided to do this is to help with plugin discoverability: if the item was just disabled the user may not know that framework support is needed. But this does feel a little clunky so I'll leave it open to see if there is a better approach.

**Comment by etanshaul** [comment]
stale. won't fix
