### ISSUE TITLE
Add support for Flexible local run

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#1623]
In order to support local run with Flexible, we could inspect an app.yaml and see what kind of runtime_config an app is using. If jetty, spin up an jetty-runtime Docker container, it tomcat, tomcat-runtime, otherwise openjdk-runtime.

This process can be made easier with our new runtime builder.

**Comment by etanshaul** [comment]
won't fix
