### ISSUE TITLE
layout issue when deploying to flex

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#1656]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: master
- OS: ubuntu
**What did you do?**
1)imported a spring boot hello world app
2)added flex framework support with generated app.yaml
3) opened the flex deployment run config
result:
pricing warning is rendering on top of some label text

![layout-bug-flex-deployment](https://user-images.githubusercontent.com/7862557/30816771-ddfc5588-a1e4-11e7-9ede-3847767ce0dc.png)

**Comment by patflynn** [comment]
also related:
![screenshot from 2017-09-26 16 35 12](https://user-images.githubusercontent.com/7862557/30882971-bcb5f218-a2d8-11e7-9d0d-8e02f33d0ca7.png)

**Comment by patflynn** [comment]
i.e.. the app engine region warning message.

**Comment by etanshaul** [comment]
not reproducible anywhere else. backlogging for now

**Comment by etanshaul** [comment]
closed as not reproducible
