### ISSUE TITLE
App engine local run target appears but complains that facet is missing

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#1799]
see https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1625#issuecomment-352481440 for details

**Comment by lilianaziolek** [comment]
Thanks @etanshaul for opening this new thread. I am currently on version 20171230 of the plugin and it appears to be working at the moment - but as I've seen a number of times, that doesn't always last. I'll ping you here if at any point I see anything going wrong again. Touch wood it continues to work though!

**Comment by etanshaul** [comment]
closed as old. no longer seen / reported
