### ISSUE TITLE
Disable flaky IDEA 'leaked unit test projects' check until we figure out its usefulness

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#1829]
Time to time unit tests fail with TooManyProjectLeakedException from internal IDEA project test system.
The behaivour is non-deterministic: 
* rarely happen on local Ubuntu/Mac builds
* never happens on Windows
* more frequently happens with Ubuntu, especially when IDE Project is used in new tests.

I spent a couple of hours checking for solution and it doesn't seem obvious.
Here is the code IDEA uses:
```java
  private static final boolean LOG_PROJECT_LEAKAGE_IN_TESTS = Boolean.parseBoolean(System.getProperty("idea.log.leaked.projects.in.tests", "true"));
  private static final int MAX_LEAKY_PROJECTS = 5;


    if (ApplicationManager.getApplication().isUnitTestMode()) {
      //noinspection AssignmentToStaticFieldFromInstanceMethod
      TEST_PROJECTS_CREATED++;
      //noinspection TestOnlyProblems
      checkProjectLeaksInTests();
    }

  @TestOnly
  private void checkProjectLeaksInTests() {
    if (!LOG_PROJECT_LEAKAGE_IN_TESTS || getLeakedProjects().count() < MAX_LEAKY_PROJECTS) {
      return;
    }

    if (Math.random() >= 0.05) {
      return; // Check for leaked projects ~ every 20 tests
    }

    for (int i = 0; i < 3 && getLeakedProjects().count() >= MAX_LEAKY_PROJECTS; i++) {
      GCUtil.tryGcSoftlyReachableObjects();
    }

    System.gc();

    if (getLeakedProjects().count() >= MAX_LEAKY_PROJECTS) {
      List<Project> copy = getLeakedProjects().collect(Collectors.toCollection(UnsafeWeakList::new));
      myProjects.clear();
      if (ContainerUtil.collect(copy.iterator()).size() >= MAX_LEAKY_PROJECTS) {
        throw new TooManyProjectLeakedException(copy);
      }
    }
  }
```
From the code:
* It's only used for unit-tests test project tracking. No relation to production issues
* It's based on Math.random (heavily depends on JVM/OS)
* It's based on System.gc() (again, total dependency on JVM implementation)

I don't see any usefulness in tracking why test project reference was not GCed after each (x*random) unit test.

It only was enabled after IDEA 2017.1, at that point we already had ~500 unit tests. Error messages do not provide much help to see where and in which tests projects 'leaked' (i.e. not GCed after unit test done).

Check can be disabled with system property "idea.log.leaked.projects.in.tests"=false (true by default).

**Comment by etanshaul** [comment]
If a project is indeed leaking in non-unit tests, won't this mechanism discover it (if sufficient # of projects are leaked and the unit test is calling that piece of production code)?

**Comment by ivanporty** [comment]
It's only enabled in unit tests. That means we are randomly checking unit tests generated test projects are not GCed (yet). This does not seem to check any production projects or actual code - only unit test code itself.

**Comment by ivanporty** [comment]
It also seems to be related to Mockito mocks (from discussions on their forums)

**Comment by etanshaul** [comment]
right, but say I artificially leak a Project in some non-unit-test code. And then create a unit test that covers this code. You are saying this mechanism won't uncover the leak?

**Comment by ivanporty** [comment]
It probably will (with proper random value and luck in System.gc()). What would be an example of leaking a Project?

**Comment by etanshaul** [comment]
a simple example could just be a strong reference to the Project that can't be released. Or perhaps incorrect disposal of a dialog. 

In past digging into this, I have uncovered leaks in non-test code by analyzing the heap dump. The initial indication of the problem came from this unit test mechanism (however poorly its actually implemented).

**Comment by etanshaul** [comment]
I'm not saying we shouldn't do what you suggest here. Just trying to make sure we understand everything.

**Comment by ivanporty** [comment]
As discussed, existing base of unit tests need to be evaluated against this check and approach in order to find a cleaner way to fix this. In the meanwhile disabling this.

**Comment by etanshaul** [comment]
havne't seen this in a while. so closing.
