### ISSUE TITLE
Blank cloud SDK location in the Add Google App Engine Standard Framework Support dialog

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/cloud-code-intellij#1874]
**What did you do?**
- Create a project and configure the cloud sdk location
- Create a new (non-App Engine) module in this project
- Go to Tools -> Google Cloud Tools -> Add App Engine Support -> Google App Engine Standard 
- The Choose Module dialog opens up. Select the new module. Click OK
- The Add Google App Engine Standard Framework Support dialog opens up

**What did you expect to see?**
The Cloud SDK directory field has been populated with the cloud sdk location

**What did you see instead?**
The Cloud SDK directory field is blank

<img width="589" alt="screen shot 2018-01-31 at 11 33 15 am" src="https://user-images.githubusercontent.com/6805942/35634844-a5c46e80-067a-11e8-92d5-7b2aad6f24ea.png">

**Comment by etanshaul** [comment]
closed as obsolete. not reproducible
