### ISSUE TITLE
Error message displayed when clicking on GAE Deployment config help icon 

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/cloud-code-intellij#1889]
**What did you do?**
Clicked on the Run/Debug Configurations help icon (bottom left) when on the GAE Deployment config tab

**What did you expect to see?**
https://cloud.google.com/tools/intellij/docs/deploy-local

**What did you see instead?**
<img width="1079" alt="screen shot 2018-02-06 at 2 19 44 pm" src="https://user-images.githubusercontent.com/6805942/35879475-4e526584-0b49-11e8-81ed-a2b428a621c4.png">

**Comment by etanshaul** [comment]
closed as stale
