### ISSUE TITLE
Some projects are not shown when trying to deploy an artifact

### ISSUE THREAD

**Issue by JoseCazalilla** [GoogleCloudPlatform/cloud-code-intellij#1973]
- Cloud Tools for IntelliJ version: 18.2.1
- Google Cloud SDK version : 183.0.0
- OS: Windows 10

**What did you do?**
I created a new Google Cloud Platform Project and updated Cloud Tools for IntelliJ from version 17.12.2 to version 18.2.1

**What did you expect to see?**
I expect to see all the projects (old and new ones)

**What did you see instead?**
I cannot see the new project created.

**More Information**
With the version 17.12.2, I can see the 3 projects (as I expect) I have:
![image](https://user-images.githubusercontent.com/16207314/37901064-6c2b79fc-30f0-11e8-82ed-8e35ccb3e3ce.png)

However, with the new version of  Cloud Tools for IntelliJ (18.2.1), I cannot see the new project created
![image](https://user-images.githubusercontent.com/16207314/37901301-1c2e01c6-30f1-11e8-9cb6-e0813a541ba4.png)

If I list my projects using `gcloud projects list`, I can see the 3 projects, as expected.

As a last thing (I don't know if it could be the root cause of the issue, or at least, could help), the old projects (the only ones I can see with the version 18.2.1) were created in Google Cloud Platform under "No organization".
![image](https://user-images.githubusercontent.com/16207314/37901696-5d007bc4-30f2-11e8-8cee-feeeac58a50c.png)

While the new project has been created under a custom Organization
![image](https://user-images.githubusercontent.com/16207314/37902136-c31af852-30f3-11e8-97d7-a217824635dd.png)

I tried to Log-out, log-in again, uninstall the plugin, install it again, type it manually, etc, with no luck.

If you guys need more information, please, let me know.

Thanks,
Jose

**Comment by ivanporty** [comment]
Hi,
thank you for your report.

One of the reasons might be that project you don't see is scheduled for deletion. Project names might still be visible in the console after that but we filter them out. Old version didn't always do that.

Can you please try adding another project under your custom organization and see if it appears in the project selector list after that?

**Comment by JoseCazalilla** [comment]
Hi Ivan.

Thanks for the quick answer. 

As you proposed, I created a new project and **I was able to see it in both versions of the plugin**.
I also checked the projects in "scheduled for deletion" and I found the troublemacker there (the situation is a bit tricky).

1. I have a running project with **name**: opxxxis-2 and **id** opxxxis-2
2. I have in the "scheduled for deletion" a project with name:  **name**: opxxxis-2 and **id** opxxxis-2-13245

Based on you feedback about filtering projects scheduled for deletion (actually, a good idea), I think this filtering is not working as expected in this situation (please, correct me if I'm wrong). 

Just guessing... is the filtering done based on the name of the project? If yes, it would explain this behaviour, as I have 2 projects (one running and another scheduled for deletion) with same name, but different id. If you are filtering by id... I couldn't explain this behaviour.

Thanks!
Jose

**Comment by ivanporty** [comment]
Thank you, that clarifies things a bit.
Let us investigate this case a bit more about projects with the same name and different deletion status and we'll update you on that.

**Comment by ivanporty** [comment]
We did a small test based on your input, trying out two cases:
1. Project with `name` created, deleted, then re-created with a different id, but a same `name`. It seems to work correct and shows up in the project list.
2. Project with `name` and `id` created, deleted, then project with `id` used as a name is re-created (with a different ID assigned of course). Again, everything seems to be normal.

Just a follow up question - two projects that you mentioned (with name and id matching, and one of them deleted), are they in the different custom organizations?

**Comment by JoseCazalilla** [comment]
Yes. One of them is inside of a custom organization and the other one is under "No organization"

**Comment by jmah-cc** [comment]
This should be resolved. Please re-open if this is still an issue
