### ISSUE TITLE
Investigate thread leak check usefulness in ThreadTracker

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#1997]
IJ IDEA calls `ThreadTracker` class to check for non-finished threads in `HeavyIdeaTestFixture#tearDown`. It does not seem to be useful for isolated unit test, it's possible we don't need to base our unit tests on `HeavyIdeaTestFixture` to avoid multiple checks and layered teardowns if unit test is simple.

**Comment by etanshaul** [comment]
obsolete now due to much refactoring of our test infra
