### ISSUE TITLE
Default cloud project selection not set in deploy

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2083]
I was testing things out and selected the Cloud Project several times from different UIs including VCS, and GCS. 

Then, I went to deploy the project my project selection wasn't defaulted. In fact, every time I swap  the Deployment artifact in the UI (from native to a maven based build), the cloud project is cleared out.

Is this known behavior? Presumably it could still keep the default cloud project even when the deploy configuration is cleared.

**Comment by ivanporty** [comment]
What happens if you create a new deployment target? It should be preset I think, must be something related to deployment artifact logic.

**Comment by etanshaul** [comment]
I thought that changing deployment artifacts is the same thing as creating a new deployment target - it creates an entirely new configuration.

Oddly though when I create a new one the default project _is_ selected.

**Comment by etanshaul** [comment]
closing as stale
