### ISSUE TITLE
Cloud SDK Support: extract common interfaces and modularize

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2128]
Cloud SDK functionality is currently tightly coupled into Java functionality and App Engine Java component presence. In order to support more languages and deployments, we could split it into runtime agnostic part, introduce modular language/runtime support (starting with existing Java component support), and extract the Cloud SDK into its own independent plugin module.

**Comment by etanshaul** [comment]
it has since moved into core. closing
