### ISSUE TITLE
Support for Cloud SQL databases in database viewer

### ISSUE THREAD

**Issue by anuraaga** [GoogleCloudPlatform/cloud-code-intellij#2181]
Just a feature request.

Thanks to [cloud-sql-jdbc-socket-factory](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory), it's very easy to connect to Cloud SQL from any Java application, including IntelliJ. I currently use it effectively by manually setting up a data source driver which is just the normal mysql-connector-j, with the socket factory jars on the classpath as in the below screenshot. I suspect it would be quite easy to implement this straight into the cloud tools plugin so users don't have to manually set up this driver. Ideally, it would list Cloud SQL databases and when a user selects one, the data source gets configured, along with the socket factory. It'd be extremely useful for users IMO.

![image](https://user-images.githubusercontent.com/198344/41639664-b0416c18-7499-11e8-845a-549f8cc7938c.png)

**Comment by etanshaul** [comment]
thanks @anuraaga 

I agree that this would be useful. I'll keep this open to track and consider with our other features in the pipeline.

Thanks for the suggestion.
