### ISSUE TITLE
Can't auth from Crostini

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#2210]
to reproduce:
1. get a pixelbook with crostini enabled
1. Install IntelliJ + GCT
1. Attemp to login
1. observe that the auth redirect will fail to make a connect

this is to be expected because the redirect is to localhost which is opened in the chromeos browser and not in the crostini container.  However if you change 'localhost' to the crostini ip or 'linuxhost' it still fails.  I believe this is because we only accept connections from localhost.  

solution:
1. detect crostini and set redirect url to use 'linuxhost' base path.
   1. potentially do this by checking for existence of /opt/google/cros-containers/
2. somehow accept traffic from the chrome OS IP w/o opening to all.

**Comment by etanshaul** [comment]
just curious how you were able to work on crostini with the plugin previously?

**Comment by patflynn** [comment]
copy + paste + curl :)

**Comment by etanshaul** [comment]
closed as outdated (and not reproducible) @patflynn feel free to reopen if still an issue
