### ISSUE TITLE
Add App Engine plugin blocks for Maven/Gradle

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-code-intellij#2231]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_)
- Cloud Tools for IntelliJ version: 18.7.1
- Google Cloud SDK version: 210.0.0
- OS: Mac OS X 10.13.6

**What did you do?**
Wanted to add App Engine Maven plugin.

**What did you expect to see?**
When adding App Engine support through GCT, automatically add the plugin; Or, through the tool menu to easily add the plugin.

**What did you see instead?**
Manually copied/pasted the plugin from doc.

**Comment by matthewmichihara** [comment]
It doesn't look like we'll ever get to this unfortunately. Closing.
