### ISSUE TITLE
Gradle dependency resolution problem

### ISSUE THREAD

**Issue by hosswald** [GoogleCloudPlatform/cloud-code-intellij#2282]
- Cloud Tools for IntelliJ version: 18.10.1
- Google Cloud SDK version: 179.0.0
- OS: Windows 10

Our project has a gradle structure:
```
Root project 'ourproject' (contains no sources)
+--- Project ':common' (library)
+--- Project ':cloud' (library)
+--- Project ':gae' (defines a deployable)
+--- Project ':another' (defines a deployable)
+--- Project ':non-cloud' (defines a deployable)
```
All other projects depend on `:common` (build.gradle: `dependencies{compile(project(':common'))}`).
`:gae` and `:another` additionally depend on `:cloud`.
The hierarchy is flat, not as hierarchical as it probably should be, but all gradle tasks work so there is no reason to refactor it.
When any task in the `:gae` project is executed using gradle, dependencies are resolved such that first `:common`, then `:cloud` and then `:gae` are compiled. `:another` and `:non-cloud` remain untouched.

Now the problem:
If I use the `Google App Engine Standard Local Server` run configuration with the only selectable "Artifact to deploy" `Gradle : ourproject : gae.war (exploded)`, it tries to compile all subprojects of `ourproject`. Since some of them are currently not compilable, the process fails.

The current work around to get local debugging to work is using a "Remote" run configuration with "Before launch" containing `Run Gradle task 'gae: appengineStart`.

**Comment by etanshaul** [comment]
Interesting. thanks for the report. will investigate and update.

**Comment by etanshaul** [comment]
@hosswald closing this as we we aren't prioritizing this update. if this is still causing major painpoints for you please comment (and others please upvote). Closing for now.
