### ISSUE TITLE
Session.removeAttribute throws NullPointerException

### ISSUE THREAD

**Issue by brandon-rentpingmedia** [GoogleCloudPlatform/cloud-code-intellij#2283]
- Cloud Tools for IntelliJ version: 18.10.1
- Google Cloud SDK version _(run `gcloud version` on the command line)_: 220.0.0
- OS: macOS 10.13.6

**What did you do?**
Updated to the newest version of Google Cloud Tools for IntelliJ. Now all instances where we remove session attributes throw a NullPointerException.

**What did you expect to see?**
Session variable should be removed.

**What did you see instead?**
NullPointerException

java.lang.NullPointerException
	at com.google.apphosting.runtime.jetty94.AppEngineSession.setAttribute(AppEngineSession.java:81)
	at org.eclipse.jetty.server.session.Session.removeAttribute(Session.java:786)

Same issue if you try to use session.setAttribute("someattribute", null);

**Comment by etanshaul** [comment]
hi @brandon-rentpingmedia thanks for the report

Could you please provide a bit more detail so that we can help diagnose? What operation were you trying to perform using the plugin (local-run, deployment etc.)? Are you using App Engine standard?

Also you mentioned this happened after updating the plugin; so I assume you were using the same workflow with the previous version of the plugin and not running into this?

**Comment by brandon-rentpingmedia** [comment]
Running app engine java locally (standard). And yes, this code has been in place for years, so it was specific to the update.

**Comment by etanshaul** [comment]
Update: rolling back to gcloud version `219.0.1` fixes the problem:

`gcloud components update --version 219.0.1`

**Comment by etanshaul** [comment]
issue filed internally, will update here when I have some more info

**Comment by etanshaul** [comment]
+ @ludoch

**Comment by champenois** [comment]
Sorry about that, I think a temp workaround it is to add

 ```
 <sessions-enabled>true</sessions-enabled>
```

 in appengine-web.xml

**Comment by brandon-rentpingmedia** [comment]
FWIW, I had that sessions-enabled xml attribute in my appengine-web.xml when I reported the issue.

**Comment by champenois** [comment]
Thanks for the info, this helps a lot....
I found the issue where we should support null in setAttribute, but we currently do not...
For now, keep the previous SDK as a workaround... I can do the fix, but no guarantee it will become public in next Cloud SDK push,  but definitely in the one after.

**Comment by champenois** [comment]
BTW, this is not affecting apps in production, so deployments with old or new Cloud SDKs are fine, only local execution.

**Comment by brandon-rentpingmedia** [comment]
Thanks for the quick responses on this. We appreciate it!

**Comment by MuffinTheMan** [comment]
Appears to be fixed now!

**Comment by etanshaul** [comment]
thats great. thanks for updating us @MuffinTheMan
