### ISSUE TITLE
Unrecognized Cloud SDK Version / Switch to manual SDK message in case of managed SDK corruption

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2306]
When managed SDK gets corrupted for some reason (in this case, for issue reproduction), new warning message suggests switching to manual since it's broken:
```
Unrecognized Cloud SDK Version
				Operations may have unintended results. You can install the Cloud SDK manually and set the path via:
				Settings -> Google -> Cloud Sdk -> Use a custom local installation
```

However, most of the time managed SDK will be able to detect it's broken and re-install/fix itself.

**Comment by etanshaul** [comment]
closing as "won't fix", very low priority
