### ISSUE TITLE
Running an external war as a secondary service from IntelliJ

### ISSUE THREAD

**Issue by pcavadas** [GoogleCloudPlatform/cloud-code-intellij#2339]
- IntelliJ IDEA: Ultimate 2018.3
- Cloud Tools for IntelliJ version: 19.2.1
- Google Cloud SDK version: 234.0.0
- OS: macOS 10.14.3

I'm trying to run 2 services from IntelliJ with the AppEngine Standard local server:

- 1 service is my IntelliJ project module
- The second one is an external exploded war

I can't figure out how to achieve this.

I can do it easily from the command line with `mvn appengine:run` and the `appengine-maven-plugin` plugin, with the service configuration:

```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>appengine-maven-plugin</artifactId>
	<version>1.3.2</version>
	<configuration>
		<services>
			<service>${project.build.directory}/${project.name}-${project.version}</service>
			<service>/path/to/the/exploded/war</service>
		</services>
	</configuration>
</plugin>
```

Is it possible to do so from IntelliJ with the Google Cloud Tools plugin?

**Comment by etanshaul** [comment]
hi @cedla, thanks for the post. Currently the IntelliJ integration only supports deploying a single exploded war.

I'm curious though to know more about your use-case: how is your intellij project structured? is it an exploded-war with an `appengine-web.xml` in the WEB-INF dir? Are you able to deploy that service from the plugin successfully?

**Comment by cedla** [comment]
The first app a classic AppEngine Java Standard project in IntelliJ: single project module, default setup.

The second service is a Play 1.x app that needs to be packaged as war (with the `play war ...` command line) to run in an AppEngine Standard server. The generated war contains indeed a `WEB-INF` dir, with the `appengine-web.xml` file.

Both services runs fine on local dev server with `mvn appengine:run` and the use of the `appengine-maven-plugin` plugin with the `services` configuration properly set up.

I only wanted both services to run from IntelliJ to have easy hot swap for recompiled classes of the 1st project.

**Comment by etanshaul** [comment]
I see. The plugin only supports running the current project in the dev app server. One alternative is that you can run the project as you are doing now from the command line, adding the debug configuration:

```
<jvmFlags>
  <jvmFlag>-Xdebug</jvmFlag>
  <jvmFlag>-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n</jvmFlag>
</jvmFlags>
```

And then attach a remote debugger from the IDE to give you debugging and hotswap functionality.

**Comment by cedla** [comment]
I was already doing this, I only wanted to run all from IntelliJ to get easy hot swap for changed classes. It would be great to add this feature to the plugin.

Anyway, thank you for your support!

**Comment by jmah-cc** [comment]
After reviewing this again, we've decided not to implement this in favor of other higher priority asks.
