### ISSUE TITLE
Add Kotlin Ktor RESTful getting started example

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2367]
Since project is using Kotlin, it could make sense to include simple RESTful application based on Kotlin Ktor framework to lure Kotlin growing backend developers. Functionality could be similar to one in https://github.com/GoogleContainerTools/google-container-tools-intellij/issues/133 and it should use Jib to build images.

**Comment by etanshaul** [comment]
obsolete, we've decide to host docs on cloud.google.com
