### ISSUE TITLE
Add non-Java getting started example to demo non-Java IDE functionality

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2368]
Similar to https://github.com/GoogleContainerTools/google-container-tools-intellij/issues/135 and https://github.com/GoogleContainerTools/google-container-tools-intellij/issues/135, priority should probably be Golang / GoLand IDE since it seems to be the most popular choice for microservices. Again, something similar to other getting started examples, but using Dockerfile since Jib is Java only.

**Comment by etanshaul** [comment]
obsolete, we've decided to host docs on cloud.google.com
