### ISSUE TITLE
Create and use Skaffold action icons.

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2369]
The following icons, aside from the original Kubernetes deployment icon (made from logo) are needed:
* K8s with Skaffold continuous run image, separating it from single run configuration
* K8s with Skaffold action icon for manual trigger to re-deploy (action on opened console window when deployment is in the process)

**Comment by etanshaul** [comment]
closing as I think this is stale. We have another issue tracking ideas around consolidating both run configurations which will make this obsolete.
