### ISSUE TITLE
Track usage of Skaffold live templates

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2371]
When a user opts in, send pings when live templates are used, such as typing "skaffold" to create initial Skaffold template.

Originally part of https://github.com/GoogleContainerTools/google-container-tools-intellij/issues/110

**Comment by sllewely** [comment]
Looking in to it
https://www.jetbrains.org/intellij/sdk/docs/tutorials/live_templates/template_support.html

**Comment by sllewely** [comment]
Asked a [question](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003476580-Hook-on-Live-Template-generation) on Jetbrains' support forum.  Found only one [similar question](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206141579-Is-there-any-way-to-know-that-there-is-a-Live-Template-is-working-).  Doesn't seem supported.

See [Live Templates](https://www.jetbrains.org/intellij/sdk/docs/tutorials/live_templates/template_support.html)

**Comment by etanshaul** [comment]
fixed via #123
