### ISSUE TITLE
Explore how to surface additional Skaffold flags to the user

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2390]
Which additional flags if any should we surface? Should we surface them as a structured UI or a freeform textfield etc. ...

**Comment by venux92** [comment]
I think a freeform text field will be more convenient 
Is there any workaround at the moment except set/unset the ENV VARIABLE for each user/computer in his bash profile? #2512

**Comment by etanshaul** [comment]
Thanks @venux92. 

For reference, see equivalent user request here with details: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2512

**Comment by sageprice** [comment]
Technically, this functionality is provided by https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2497. That change enables setting environment variables for the shell IntelliJ opens to run Skaffold commands. Based on [Skaffold CLI docs](https://skaffold.dev/docs/references/cli/), it looks like all command-specific flags can be controlled via environment variables (possible exception of setting log verbosity). So with release of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2497 in `19.5.1` users should be able to set any Skaffold flags they need. Here's a preview:

![env_variables_demo](https://user-images.githubusercontent.com/9577120/57033162-2d82b100-6c1a-11e9-90af-ab9579b9b7ff.png)

So users won't have to modify their local environments -- each run configuration can have specific flags. Does this sound sufficient? I can't tell if it is clear from the UI, and there is a question of whether it is worth having a specific field for Skaffold flags only (I'd lean no, better to have just one way of doing things).

**Comment by etanshaul** [comment]
@sageprice I think the environment variable support is a great start, and will go out in the upcoming release.

As far as exposing more structured fields (or perhaps a freeform field) for Skaffold options - this is something I'd like to discuss more (including with the Skaffold team to get their thoughts). Definitely still leaving this issue open though for tracking.

**Comment by etanshaul** [comment]
I missed the part that _every_ skaffold flag is exposed as an environment variable as well.

@venux92 does this environment variable support sound sufficient to you (this will go out in the next release - likely next week).

**Comment by venux92** [comment]
> I missed the part that _every_ skaffold flag is exposed as an environment variable as well.
> 
> @venux92 does [this environment variable support](https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2390#issuecomment-488363175) sound sufficient to you (this will go out in the next release - likely next week).

That's perfect. Looking forward to it. Will make our life much better at work 😀

**Comment by etanshaul** [comment]
@venux92 just updating you that we released Cloud Tools version 19.5.1 that contains this environment variable support. Please do let us know if you have any other requests or run into any issues. Thanks!

**Comment by venux92** [comment]
> @venux92 just updating you that we released Cloud Tools version 19.5.1 that contains this environment variable support. Please do let us know if you have any other requests or run into any issues. Thanks!

Sorry for my late answer. I just updated the plugin. Looks great. Will keep you updated if any issues ;) Thanks.

**Comment by etanshaul** [comment]
thanks for the update @venux92 - glad its working for you now.

**Comment by etanshaul** [comment]
closing in favor of more specific issues for certain skaffold flags. We have enhanced the Run Config to allow setting arbitrary environment variables which is a good workaround.
