### ISSUE TITLE
Detect k8s project and suggest to add Skaffold configuration

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2395]
For example, this could be based on the manifests, or usage of the JB k8s plugin etc.

**Comment by ivanporty** [comment]
Implemented by https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/64
Jib support is probably better to be implemented as part of `skaffold init` and will be handled separately.
