### ISSUE TITLE
group with id "GoogleCloudTools.AppEngine.General" isn't registered

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2403]
noticed this on master:

```
com.intellij.diagnostic.PluginException: com.intellij.openapi.actionSystem.DefaultActionGroup (GoogleCloudTools.AppEngineLocalRun): group with id "GoogleCloudTools.AppEngine.General" isn't registered; action will be added to the "Other" group [Plugin: com.google.gct.core]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:337)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:332)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getParentGroup(ActionManagerImpl.java:822)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.java:788)
```

**Comment by ivanporty** [comment]
This is the same loading order / optional dependencies ordering issue we've seen before with this action. Group exists and name is correct in plugin.xml configuration.
@etanshaul filed and issue with JetBrains here: https://youtrack.jetbrains.com/issue/IDEA-203089

**Comment by ivanporty** [comment]
I suggest we create the empty App Engine group as part of the main plugin declaration so the action adds there regardless of loading order. It will be empty for non-Java IDEs, but this seems to be a better trade-off comparing to IDE error. @etanshaul WDYT?

**Comment by etanshaul** [comment]
I’m ok with that. One potential improvement to this:

For the case where AE is not available, can we add a muted/disabled action with something like ‘App Engine not available’?

I guess for this to be possible, the modules supporting App Engine would then have to remove this action. 

Just a thought.

**Comment by etanshaul** [comment]
workaround in #2403
