### ISSUE TITLE
Force quitting the IDE leaves Skaffold process hanging

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2419]
When running one of the Kubernetes run configurations and then force quitting the IDE (shutting it down and selecting `disconnect` instead of `terminate` for the running process in the popup that appears) leave the Skaffold process running without proper cleanup.

This results in, for one, used ports that need to be force shutdown.

We should add an IDE shutdown hook which gracefully terminates the process (we do something similar for `gcloud` I believe).

**Comment by matthewmichihara** [comment]
I think with https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/commit/e6d207eca5c0b0d869c90cef528f4f183d5f4010, we've done all we reasonably can to mitigate this scenario.
