### ISSUE TITLE
Create a service to list available clusters

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2421]
This is issue is around creating a service that will return a list of available clusters according to the user's local .kube config.

It should return a new Cluster type that has at a minimum:
- _name_
- _isActive_ - a boolean that determines if this is the current active cluster

Note on how this will be consumed (not for this PR, but just for context):
This service will be used to display clusters in the Kubernetes resource browser. Clusters will be shown in a tree view by name, with the active cluster shown in an active state (a separate icon).

**Comment by etanshaul** [comment]
I _think_ we need to use kubectl for this. For example,

`kubectl config view` returns a list of available clusters which can be parsed.

**Comment by ivanporty** [comment]
Implemented by https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/11
