### ISSUE TITLE
Create a service to set a current cluster as active

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2422]
When executing Kubernetes commands and actions, like listing pods, or running a skaffold deploy, the operation acts against an active cluster (called the "current context" in kubectl terminology).

This PR is about creating a service that, given a cluster, sets the cluster to be active.

See this page for more details on cluster contexts:
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

Note on how this will be consumed from the UI:
One way is that in the tree view, the user will be able to right click on a cluster and select "make active".

**Comment by ivanporty** [comment]
Implemented by https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/11
