### ISSUE TITLE
Find Skaffold in well-known locations

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2426]
We can at least add install locations for Linux and Mac - those are the ones used for majority of installs: Mac and Linux: `/usr/local/bin`. Windows just says use PATH, so we need to test if it works when launched from the UI menu.

_Originally posted by @ivanporty in https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/2388#issuecomment-469306627_

**Comment by etanshaul** [comment]
@ivanporty were you working on this one?

**Comment by ivanporty** [comment]
not yet. My idea was to just include `/usr/local/bin` into PATH of the running Skaffold. I think it still could be beneficial for some cases, WDYT?

**Comment by etanshaul** [comment]
yeah. that approach could work. e.g. adding it to the path if there is no skaffold override set in the UI and the executable is not already detected in the path. sgtm.

**Comment by ivanporty** [comment]
First attempt with GeneralCommandLine environment didn't work, researching why.

**Comment by ivanporty** [comment]
So we cannot modify PATH per se for spawned process, so the solution could be checking if `/usr/local/bin/skaffold` exists and executable, and then use this as an absolute PATH. 
Cons: we might override actual PATH location of Skaffold, if they have it in multiple locations, including `/usr/local/bin`, but PATH points to some other location. This could lead to unpleasant issues using Skaffold version a user doesn't want to use. @etanshaul WDYT? I'm leaning towards skipping this and rely on PATH, and then most of this is going to be alleviated by managed tools.

**Comment by etanshaul** [comment]
> we might override actual PATH location of Skaffold

Shouldn't it only use the known location as an absolute path if we've already checked that its not already on the PATH?

**Comment by etanshaul** [comment]
but - regardless, I think we are OK skipping this now that 1) the system-path issues are resolved on all OSs and 2) we have the GUI to select a custom path.

We can still do it, but just remove from the milestone

**Comment by ivanporty** [comment]
Yeah, we check the Skaffold in PATH first and then do hard fail if it's not there, so adding another run using additional absolute path might be tricky. I agree on skipping this from alpha, this may introduce unpleasant side-effect.

**Comment by etanshaul** [comment]
cool. removing from this milestone

**Comment by etanshaul** [comment]
I think this is less of a priority now that we have 1) a skaffold override selecter, and 2) workarounds for the system PATH issues.

Removing from the next milestone

**Comment by etanshaul** [comment]
closing this as we will have managed dependency installation soon so this will be irrelevant.
