### ISSUE TITLE
Hello World with Jib fails on Windows

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2427]
When trying to deploy the getting started project on windows, Skaffold starts, then fails with the following message:

```
time="2019-03-08T11:13:45-05:00" level=fatal msg="watching files for artifact gcr.io/gcp-dev-tools/hello-spring-boot: listing files: 
listing files: getting jibMaven dependencies: unable to stat file Found \"C:\\Users\\***\\google-cloud-intellij\\kubernetes\\examples\\hello-spring-boot\\.mvn\\wrapper\\maven-wrapper.jar\": CreateFile Found \"C:\\Users\\***\\google-cloud-intellij\\kubernetes\\examples\\hello-spring-boot\\.mvn\\wrapper\\maven-wrapper.jar\": The filename, directory name, or volume label syntax is incorrect."
```

**Comment by ivanporty** [comment]
@chanseokoh @TadCordle Could this be something related to Jib calling Maven wrapper in Windows, have you encountered this before?

**Comment by ivanporty** [comment]
Details: `skaffold dev` fails - something wrong with files watching, whereas `skaffold run` (deployment) runs fine.

**Comment by etanshaul** [comment]
@briandealwis for any insight as well

**Comment by briandealwis** [comment]
@ivanporty did you replace your user name with `***`?  What's odd is that Skaffold-Jib will never reference the maven wrapper's jar: it just invokes the `mvnw` script if found. Try running Skaffold with `-v debug` to see the debug output. Does the example work if you build  from the comm-line?

**Comment by chanseokoh** [comment]
The message "The filename, directory name, or volume label syntax is incorrect" seems like coming from the OS. Maybe there's something that Windows doesn't like about the given path string.

https://stackoverflow.com/questions/24116311/the-filename-directory-name-or-volume-label-syntax-incorrect
https://stackoverflow.com/questions/33618656/python-windowserror-error-123-the-filename-directory-name-or-volume-label-s
https://stackoverflow.com/questions/24782826/the-filename-directory-name-or-volume-label-syntax-is-incorrect-inside-batch

**Comment by chanseokoh** [comment]
Hmm... but some folks say permission problems may cause this too: https://stackoverflow.com/a/33824730/1701388, https://stackoverflow.com/a/2707804/1701388

**Comment by ivanporty** [comment]
@briandealwis to answer your question, it fails the same way with CLI call.

Debug output for dev command:
```
DEBU[0000] Using wrapper mvnw.cmd for mvn
DEBU[0000] Running command: [cmd /c C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\mvnw.cmd --non-recursive jib:_skaffold-files --quiet]
DEBU[0004] Command output: [Found "C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\.mvn\wrapper\maven-wrapper.jar"
C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\pom.xml
C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\src\main\java
C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\src\main\resources
C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\src\main\resources
C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\src\main\jib
]
FATA[0004] watching files for artifact gcr.io/gcp-dev-tools/hello-spring-boot: listing files: listing files: getting jibMaven dependencies: unable to stat file Found "C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\.mvn\wrapper\maven-wrapper.jar": CreateFile Found "C:\Users\cloud-sdk\google-cloud-intellij\kubernetes\examples\hello-spring-boot\.mvn\wrapper\maven-wrapper.jar": The filename, directory name, or volume label syntax is incorrect.
```

**Comment by ivanporty** [comment]
By the way, looking at the logs, it seems the command actually worked - we can see the list of files in the logs. Maybe some issue with checking the exit codes?

**Comment by briandealwis** [comment]
Ah! Is that dratted maven wrapper: it outputs the wrapper that it found. The shell script just echos the jar (I think) so it at least just looks like a file whereas the Windows script actually outputs quasi-helpful text.

So I think we should try updating the wrappers (and propose a fix if not already fixed). Tad's more-efficient Skaffold-Jib binding solves this by now outputting a special header.

**Comment by briandealwis** [comment]
Filed takari/maven-wrapper#115

**Comment by etanshaul** [comment]
@ivanporty as discussed, on our end lets do the following:

- Create a Skaffold profile for the hello-world example that uses Docker instead of Jib
- Add an FAQ entry on how to switch to this profile if running into this maven wrapper issue.

**Comment by etanshaul** [comment]
@ivanporty I can tackle this if you are working on the other issue in the milestone?

**Comment by etanshaul** [comment]
I'm closing this issue as we've implemented the workarounds on our end.
