### ISSUE TITLE
Support terminal style colors for Skaffold run configuration console

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2460]
Standard console we use for running Skaffold doesn't support colors by default. Need IDE investigation, there is most probably existing solution.

**Comment by etanshaul** [comment]
there is the following plugin:
https://plugins.jetbrains.com/plugin/7125-grep-console

We can probably optionally depend on this, giving users that have this installed colorized logs

**Comment by ivanporty** [comment]
Interesting option, definitely worth evaluating.

I also think there's a support for standard console escape chars based highlighting (i.e. if you run any Java program it'll do console colors using standard IDEA functionality) - we miss some piece in our console handler, probably a few lines of setup. Couldn't find that easily though yet.

**Comment by etanshaul** [comment]
grep console works well. Gives you a lot of flexibility.

**Comment by patflynn** [comment]
If we can make it work natively using the platform support rather than a
3rd party plugin it definitely seems preferrable.  Most people won't have
the grep console plugin installed.

**Comment by ivanporty** [comment]
It looks like Skaffold disables colors when running in non-terminal mode. We might want to ask them to provide us a flag to always use colors even if it's not real terminal.

**Comment by etanshaul** [comment]
@ivanporty if they create this flag for us, then there is still some work for us to do in the plugin to get them to display right?

Could you create an issue with Skaffold for this?

**Comment by ivanporty** [comment]
https://github.com/GoogleContainerTools/skaffold/issues/2021

**Comment by etanshaul** [comment]
just fyi this was merged into Skaffold and will probably make the next release. we can then test and close, and hopefully have some cool log colorization

**Comment by ivanporty** [comment]
Confirmed colors are working with the latest Skaffold dev build, will test again with the official release.

**Comment by ivanporty** [comment]
Works with 0.28.0, with a small caveat though - earlier versions of Skaffold fail if we supply this flag. Options:

1. Rely on users to have the latest (at least 0.28.0)
2. Add version logic and only apply the flag after 0.28.0, skip the flag for earlier versions.

Second option adds considerable amount of work though.

**Comment by etanshaul** [comment]
And unfortunately we will run into this issue any time we add new flags to our integration (which is why I don't think we should go down the road of option 2).

It probably wouldn't be too much work to add logic to require a minimum version of skaffold and execute the check on every skaffold run? Separately we can look at the data (I can check with the Skaffold team to see if they have any info) to decide at what point would be a good time to require skaffold version > x. wdyt?

**Comment by ivanporty** [comment]
Yes, if they keep the version format the same, we should probably be good supporting it pretty easily. Waiting for the managed Skaffold implementation - it should make things easier.

**Comment by etanshaul** [comment]
moving out of this next milestone, since there is nothing we can do now
