### ISSUE TITLE
Automate Skaffold schema updates.

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2465]
It might make sense to write a script to pull the latest Skaffold schema from their repo, update live template and examples, and create a branch with changes, unless we are planning on doing it dynamically via GCS (including live template) - then only examples remain, and we can create schema for them automatically using resource generation.

**Comment by etanshaul** [comment]
I think at one point @dgageot mentioned creating a skaffold command that would generate its own schema. That would at least solve the schema update part of this.

**Comment by etanshaul** [comment]
closing as we this will be coming from the language server soon, and this will be the wrong repo to track this issue
