### ISSUE TITLE
Unclear which IntelliJ to use

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-code-intellij#2469]
sorry I don't use intellij but this readme https://github.com/GoogleCloudPlatform/google-cloud-intellij/tree/master/kubernetes#installing-the-plugin-into-your-ide confused me.

What is "JetBrains IDE version 2018.2+, either Ultimate or Community editions"?

There are way too many options here:
![image](https://user-images.githubusercontent.com/159209/55110853-3cfc6080-5096-11e9-9365-547972dc863f.png)

**Comment by etanshaul** [comment]
thanks @ahmetb we will clarify this.

**Comment by ivanporty** [comment]
I think we addressed this in both https://github.com/GoogleCloudPlatform/cloud-code-intellij and cloud docs by listing specific IDEs with the links to their pages.
