### ISSUE TITLE
Enhance standard app engine language support (pretty please)

### ISSUE THREAD

**Issue by kewilson** [GoogleCloudPlatform/cloud-code-intellij#2475]
- Cloud Tools for IntelliJ version: 19.3.1
- Google Cloud SDK version _(run `gcloud version` on the command line)_: N/A
- OS: Linux

**What did you do?**
Desire to use plugin for a node.js standard app engine project. Would also like the plugin to support all languages supported by the standard app engine.

**What did you expect to see?**
Support for languages in the plugin other than Java

**What did you see instead?**
Only support for Java

https://cloud.google.com/appengine/docs/standard/runtimes - Second Generation

**Comment by jmah-cc** [comment]
We're prioritizing other features over AppEngine currently. I've added this to our backlog and keeping this issue open so other users can upvote this.

**Comment by jmah-cc** [comment]
Closing to clean up backlog. Please continue upvoting as we'll re-visit if there's > certain number of upvotes.
