### ISSUE TITLE
Errors when running howto app .. Creating an App for the App Engine Standard Environment

### ISSUE THREAD

**Issue by kewilson** [GoogleCloudPlatform/cloud-code-intellij#2476]
- Cloud Tools for IntelliJ version: 19.3.1
- Google Cloud SDK version _(run `gcloud version` on the command line)_: N/A - my understanding is that a gcloud cmd line tool installation is not needed when using the intellij plugin
- OS: Linux

**What did you do?**
Using starter howto pages to create and run an app engine std example via the plugin .. https://cloud.google.com/tools/intellij/docs/deploy-local

**What did you expect to see?**
The local cloud server start the project generated by cloud std app engine plugin without errors

**What did you see instead?**

Starting the App Engine local development server...
Connected to the target VM, address: '127.0.0.1:35203', transport: 'socket'
2019-03-31 10:49:35.927:INFO::main: Logging initialized @5382ms to org.eclipse.jetty.util.log.StdErrLog
2019-03-31 10:49:36.316:WARN:oejs.AbstractConnector:main: Ignoring deprecated socket close linger time
Connected to server
Mar 31, 2019 3:49:37 PM com.google.appengine.tools.development.jetty9.JettyContainerService initContext
WARNING: Adding jar org.apache.taglibs.taglibs-standard-impl-1.2.5.jar to WEB-INF/lib. You might want to add a dependency in your project build system to avoid this warning.
Mar 31, 2019 3:49:37 PM com.google.appengine.tools.development.jetty9.JettyContainerService initContext
WARNING: Cannot copy org.apache.taglibs.taglibs jar file to WEB-INF/lib.
java.io.FileNotFoundException: <snip>/appengine-std-intellij/out/artifacts/appengine_std_intellij_war_exploded/WEB-INF/lib/org.apache.taglibs.taglibs-standard-impl-1.2.5.jar (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
        <snip>

**Comment by etanshaul** [comment]
Thanks for reporting. What version for IntelliJ are you using?

**Comment by etanshaul** [comment]
related eclipse issue: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1919

**Comment by kewilson** [comment]
@etanshaul  .. using latest and greatest of everything Intellij.

**Comment by etanshaul** [comment]
thanks @kewilson I was able to reproduce this as well. Just curious - the local server still runs, and the app loads correctly right? Either way, we'll look into adding the necessary jars automatically to avoid this warning.

**Comment by kewilson** [comment]
it does run just emits this error regardless if you selected the JSP tags option when creating the new project using the plugin. The "servlet api" is the default checked option so my first test I wanted a headless app engine service (a plain api service - no ui) so only had the default option checked and the jsp tags reference error was emitted which tipped me off that something was amiss. I then selected all the options and they didn't stick after the new project was created. I had to go into module properties and selection all the option boxes again but it doesn't look like that did anything, running the container debug again showed same as before.

**Comment by etanshaul** [comment]
yep. I noticed that too. Likely a platform API change that is causing this. We are looking into it. thanks again.

**Comment by etanshaul** [comment]
adding internally to our 19.10.1 milestone

**Comment by axmerc** [comment]
@etanshaul please confirm this!

**Comment by etanshaul** [comment]
checking this today..

**Comment by etanshaul** [comment]
noting that this issue still exists. will add to our next milestone to see if we can fix this.

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/4042)

**Comment by etanshaul** [comment]
closing as we will probably not be able to get to this. please comment if this is a problem for you and we'll reprioritize.
