### ISSUE TITLE
Investigate workaround for environment variables from shell for Linux/2019.1

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2482]
See https://youtrack.jetbrains.com/issue/IDEA-210291 for details.

Internal issue for investigations/ results/ suggestions.

**Comment by ivanporty** [comment]
While it seems the reason for 2019/Linux behavior is yet unknown, we should change this call and treat it as non-synchronous and do not call from UI thread - no guarantee on time of its execution.

**Comment by etanshaul** [comment]
moved over to this milestone since you are already fixing this :)
