### ISSUE TITLE
Create a service to list namespaces in a cluster

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2484]
Incremental feature to support the Kubernetes Resource Browsing experience.

Given a cluster, returns the available namespaces and relevant metadata (what is relevant needs to be investigated - should be UI driven - i.e. what do we want to show the users?).

**Comment by ZariaHoward** [comment]
@etanshaul I think this is done with the recent addition to the kubectl api. by calling setActiveCluster() then getNamespaces() from the API

**Comment by etanshaul** [comment]
Yep! feel free to close. Thanks
