### ISSUE TITLE
Show currently active K8s cluster in the K8s run configurations

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2489]
This is a slightly smaller scope of #2370 and can be a first step in preparing UI for it. VS Code plugin already implemented specifying a cluster per deployment target.

UX studies showed many developers would like to be sure where exactly the deployment goes once they hit the run button. For now we can at least show them the current active cluster when they check their target. We can add a (disabled) drop-down box named `Kubernetes cluster`, and for now just show the default (active) one using new implemented API from #2421.

**Comment by etanshaul** [comment]
+1 this is a nice start

**Comment by matthewmichihara** [comment]
![image](https://user-images.githubusercontent.com/79073/55988527-16335200-5c72-11e9-83f3-c5d6cc1c419d.png)

How do you feel about this UI / combobox placement?

**Comment by ivanporty** [comment]
Excellent, great start! The only thing it might make sense to place it after Skaffold config and profile, since those are the two major moving parts. Then we could add a separator line called `Kubernetes options:`, similar to "image options", and put cluster name and "tail logs" under it. At the end goes "image options". What do you think?

**Comment by matthewmichihara** [comment]
That works for me! Something like...

![image](https://user-images.githubusercontent.com/79073/55990032-a8d4f080-5c74-11e9-8fe0-09d7f1b4a120.png)

What do you think of removing the `:` in the separator line text? Been browsing some of the other run configuration templates and they seem to omit that.

**Comment by ivanporty** [comment]
Looks neat, very nice! Agreed on removal of `:` on the line separator titles (not on the ones describing fields, right?), let's get rid of them.

**Comment by matthewmichihara** [comment]
yeah just the ones on the line separator titles, ok
