### ISSUE TITLE
Need to fix KubectlExecutorService.runKubectlCommand()

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2493]
It runs command and its arguments as a single string, which means the system tries to execute `kubectl config ...` instead of `kubectl` with arguments. See `SkaffoldExecutorService` on how to pass a list of strings into process builder.

**Comment by etanshaul** [comment]
does this mean that our current availability check is broken?

**Comment by etanshaul** [comment]
oh oops nvm. Looks like this is specifically with the kubectl executor.
