### ISSUE TITLE
Add environment variable config to Skaffold (Support multiple docker engines)

### ISSUE THREAD

**Issue by corneliusweig** [GoogleCloudPlatform/cloud-code-intellij#2497]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: v19.4.1
- OS: linux

## My configuration
I run a local k8s cluster in an LXC container. In order to use Skaffold with it, I need to set up environment variables for docker, in particular
```
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/home/wherever/
DOCKER_HOST=tcp://my-lxc:2376
DOCKER_API_VERSION=1.37
```

When trying out could-code, I didn't find any way to pass additional env variables to Skaffold.

## Feature request
Allow to configure additional environment variables to be passed to Skaffold in the tool configuration, e.g. in `Other Settings` -> `Cloud Code` -> `Kubernetes`

**Comment by ivanporty** [comment]
Thanks for the report and feature request, @corneliusweig!
We agree, this is pretty standard for IntelliJ run targets to allow adding a set of environment variables, we'll be looking into that and update the issue.

**Comment by etanshaul** [comment]
@corneliusweig thanks for the feature request

Just to confirm - you need these environment variables available to the Skaffold process? We definitely can add configuration to the Run Configuration as @ivanporty suggested, but just want to make sure I understand your use-case.

**Comment by corneliusweig** [comment]
@etanshaul Exactly, those env variables need to be set for Skaffold. Thanks in advance! And great product btw

**Comment by etanshaul** [comment]
@sageprice if you wanted to take a look as you mentioned this fr

**Comment by etanshaul** [comment]
example configuration in a different run configuration. We should be able to use the same pieces rather than building this from scratch:

<img width="859" alt="Screen Shot 2019-04-15 at 12 00 11 PM" src="https://user-images.githubusercontent.com/1735744/56158140-184d2780-5f76-11e9-80ca-b69a16abe9c0.png">

<img width="600" alt="Screen Shot 2019-04-15 at 12 00 21 PM" src="https://user-images.githubusercontent.com/1735744/56158138-16836400-5f76-11e9-9df7-618ddfbcad50.png">

**Comment by sageprice** [comment]
Discussed a bit offline, the standard place to configure env variables seems to be in the `Run Configurations` themselves rather than in IDE/plugin settings, so we're gonna start by trying to add this configuration there.
