### ISSUE TITLE
Cloud Code should interact with Skaffold to allow users to configure if you want to perform the cleanup step

### ISSUE THREAD

**Issue by Alos** [GoogleCloudPlatform/cloud-code-intellij#2502]
- Cloud Code for IntelliJ version: v19.4.1
- OS: MacOS 10.14.3

**What did you do?**
Stop the `Development with Kubernetes` run
**What did you expect to see?**
Cloud Code and Skaffold should check if I actually want to delete my deployment and services at the end.
**What did you see instead?**
Cloud Code terminated and Skaffold deletes my latest version running in my development cluster. 

I've created: GoogleContainerTools/skaffold/issues/1962

**Comment by etanshaul** [comment]
this is actually timely feedback @Alos as we have been discussing the behavior here. My take has been that `Develop on Kubernetes` is sort of like a local dev server; when you are done developing, you'd expect the resources to be cleaned up for you.

However, I recognize that people may have other workflows and it would be nice to add a configuration option (perhaps a checkbox in the run configuration) that lets you control this.

Just curious - what is the workflow you are following that leads you to want the resources to remain when running in `dev` mode?

**Comment by ivanporty** [comment]
Thanks for the feature request! This looks like a viable use case when you develop on a cluster where previous deployment of the same type/name exists and you do not want to clean it after you're done with development mode. Does this sounds right?

**Comment by Alos** [comment]
Yes! I would develop in my dev K8s cluster. I would continue to work on my changes until I am happy. At this point I would submit a PR and have my CI/CD tool pick up my changes and deploy it to my integration/QA instance.

I would then also have to deploy the already deployed version to my dev instance again. If clean up was optional I could turn it off and my local development flow would by simple and my CI/CD workflow would not have to also make sure my dev instance has the last version.

**Comment by etanshaul** [comment]
ah. yeah that definitely makes sense. thanks for clarifying

**Comment by Alos** [comment]
Referencing issue in Skaffold has been closed: GoogleContainerTools/skaffold/issues/1962

**Comment by etanshaul** [comment]
thanks @alos we will work on this

**Comment by etanshaul** [comment]
closed via https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/86
