### ISSUE TITLE
Refactor all stackdriver-debugger tests to properly use test rules and UI test annotations.

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2508]
```
> Task :stackdriver-debugger:test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0

com.google.cloud.tools.intellij.stackdriver.debugger.actions.CloudDebugHelpActionTest > testUpdate FAILED
    java.lang.IllegalStateException at CloudDebugHelpActionTest.java:54

82 tests completed, 1 failed, 2 skipped

> Task :stackdriver-debugger:test FAILED
```

**Comment by sageprice** [comment]
Haven't been able to reproduce this. Ran the test in question 10,000 times from IntelliJ and didn't see any flakes. Has this been occurring regularly?

![CloudDebugHelpActionTest10000](https://user-images.githubusercontent.com/9577120/57024981-eee1fc00-6c03-11e9-9784-f516c974cb39.png)

**Comment by etanshaul** [comment]
Not regularly. Let’s close for now after the thorough testing you did. We can reopen if needed later.

**Comment by ivanporty** [comment]
I see it time to time and it only happens via CI. But we do need to fix this tests:
1. Use our test rule instead of deprecated runner
2. Mark its tests with `@UiTest` to ensure the UI is handled properly.

**Comment by ivanporty** [comment]
It seems (almost) all tests in this module are very old and fail time to time randomly in CI. We should rework them to use our test rules, and also ensure all UI testing is done under `@UiTest` annotation.

**Comment by matthewmichihara** [comment]
From what I hear, the tests seem more stable. Planning on closing this unless anyone objects. @GoogleCloudPlatform/cloud-tools-for-intellij

**Comment by etanshaul** [comment]
yes go ahead! thanks for doing this..I haven't seen any flakiness since your updates!
