### ISSUE TITLE
Add customize flags to skaffold

### ISSUE THREAD

**Issue by venux92** [GoogleCloudPlatform/cloud-code-intellij#2512]
Right now when I hit the run button this command is automatically generated

`/usr/local/bin/skaffold dev --filename skaffold.yaml --label ide=PhpStorm --label ideVersion=2019.1.0.0 --label ijPluginVersion=unknown`

For different projects and users, I need to be able to add customize label such as 
```
--no-prune
--cleanup
--label etc..
```

Is there any way this can be included inside the configuration? so I don't need to run the command manually as we are using a different setup for different users and computers.

Probably related to #2390

**Comment by etanshaul** [comment]
Thanks for the request @venux92 

This is the same as #2390 so I will close this one. We'll have the link to this one to view the details still for future reference.

This is definitely something we want to add. We will discuss and determine if its something we can get in on the next release.

In the meantime, unfortunately, the best approach is as you mentioned: set the env vars on the user's machine. A side note related to this, we are also implementing a feature to set environment variables directly on the Skaffold process: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2497 . This will allow you to set environment variables directly on the run config, and even share them across the team by persisting the settings in VCS.
