### ISSUE TITLE
Deploying with run configuration created via `Skaffold detected` balloon fails

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2518]
![out](https://user-images.githubusercontent.com/79073/56768281-f3c62c00-677b-11e9-8b2d-fa3b109a9b8a.gif)

This happens because the run configuration that is created when clicking this balloon [doesn't include a kubernetes context ](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/blob/master/kubernetes/skaffold/src/main/kotlin/com/google/cloud/tools/intellij/kubernetes/skaffold/SkaffoldConfigurationDetector.kt#L208-L210), so when we try to switch to this context when deploying, [it fails](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/blob/master/kubernetes/skaffold/src/main/kotlin/com/google/cloud/tools/intellij/kubernetes/skaffold/run/SkaffoldCommandLineState.kt#L97-L100).

Looking for feedback on the best fix for this. I could:
1. Attempt to determine the current k8s context at the time of creating these configurations, and set the context for those configs to that. If it fails, don't create the configs, and surface an error balloon.
2. Implement the checkbox + combobox UI in https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2517, and have the checkbox *unchecked*, meaning use whatever the active cluster is at the time of deploy.
3. Something else?

**Comment by matthewmichihara** [comment]
@GoogleCloudPlatform/cloud-tools-for-intellij

**Comment by etanshaul** [comment]
> This happens because the run configuration that is created when clicking this balloon doesn't include a kubernetes context 

Clicking which balloon?

**Comment by matthewmichihara** [comment]
the one that pops up after a skaffold file is detected for the first time.

this is the associated text from the event log:
```
Kubernetes with Cloud Code
Skaffold configuration detected. Use Skaffold to Deploy your applications to Kubernetes Update your deployed application continually during development
Create Cloud Code Kubernetes Run Configurations (show balloon)
```

**Comment by matthewmichihara** [comment]
I'm going to go with setting the configuration context with the current context at the time that the 'skaffold file detected' balloon pops up.

If we can successfully get the current context, great. 

If not, we can just leave the configuration context as null, and surface it in the run configuration UI as a warning as opposed to the current behavior, which will just select the first context in the list of all contexts without showing any warnings.

**Comment by ivanporty** [comment]
This is related to #2517 in some sense, since previously we would just deploy to whatever active cluster is, correct? If we make it active cluster by default, this will go away by itself?

**Comment by matthewmichihara** [comment]
Yes, it is related to https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2517.

Making it active cluster by default would prevent this. Another alternative is pinning to whatever the current context is at the time of creating the run configs: https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/101.
