### ISSUE TITLE
The run console output should log that we're changing the active k8s context

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2519]
https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/90#discussion_r278294929

**Comment by matthewmichihara** [comment]
![image](https://user-images.githubusercontent.com/79073/57039703-565f7200-6c2b-11e9-98c4-1053e4b8446d.png)

Still unclear to me how to get text to show up in this skaffold run output window. I've tried adding `processHandler.notifyTextAvailable("TESTING", ProcessOutputTypes.STDOUT)` at https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/blob/master/kubernetes/skaffold/src/main/kotlin/com/google/cloud/tools/intellij/kubernetes/skaffold/run/SkaffoldCommandLineState.kt#L129-L132, with no luck.

However, it seems like the run output window only shows up after skaffold is started (with the first line printed being the skaffold command itself), and after skaffold starts, it'd be awkward to say that we're changing the active kubernetes context in the same output screen because it was done before invoking skaffold.

My only other thought for surfacing that we're changing the active kubernetes context is maybe showing an informational balloon, but I could see that becoming annoying. Any thoughts @etanshaul @ivanporty ?

**Comment by etanshaul** [comment]
One approach - until we can figure out how to write to the console - is to display a message in the event log (which I think will also show the message in the gutter.

**Comment by matthewmichihara** [comment]
good idea, i'll give that a try

**Comment by ivanporty** [comment]
Agree, event log might be a good idea.

**Comment by matthewmichihara** [comment]
![Screen Recording 2019-05-02 at 11 06 32 AM](https://user-images.githubusercontent.com/79073/57085975-48612e00-6ccb-11e9-95fa-35becab5967e.gif)

How's this?

**Comment by etanshaul** [comment]
To align more with VS Code (which I don't think shows these popup notifications anymore), could we keep it like you are showing, but only with the message in the gutter and the event log?

This is something we can also put in front of ux designers to get feedback.

**Comment by ivanporty** [comment]
Popping up a baloon on each run might be a bit disturbing - I recall there's a way to say what kind of notification it is - and make it a message in the log then? Needs a bit of research

**Comment by ivanporty** [comment]
Or might be event simpler, `NotificationDisplayType.NONE` and `logByDefault` set to `true`. Tool window option may need a tool window ID...

**Comment by matthewmichihara** [comment]
Alright here's the latest. It uses `NotificationDisplayType.None` and `logByDefault=true`, thanks for the tip @ivanporty 

![Screen Recording 2019-05-02 at 4 36 19 PM](https://user-images.githubusercontent.com/79073/57105597-2da5ae00-6cf9-11e9-90c7-a8b15c867332.gif)

**Comment by etanshaul** [comment]
excellent!
