### ISSUE TITLE
"Cannot find Kubernetes file on system" error 

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2520]
Sometimes when trying to deploy (I just click play or debug on the existing Kubernetes run config - without opening the run config settings) I get the following

<img width="404" alt="Screen Shot 2019-04-26 at 3 06 15 PM" src="https://user-images.githubusercontent.com/1735744/56830674-f8025000-6834-11e9-875f-346d20dc91ca.png">

Two things probably need to be done here:
1) Make the error a bit clearer. I'm not sure exactly what "Kubernetes file" means. @ZariaHoward is this kubectl?
2) Fix the root cause of this error:
    If I open the run config, then save it, then redeploy - things work. Therefore this error probably shouldn't have happened in the first place.

**Comment by etanshaul** [comment]
@GoogleCloudPlatform/cloud-tools-for-intellij anyone up for tackling this?

**Comment by etanshaul** [comment]
@matthewmichihara I wonder if this is related to the context switching update? (i.e. updating the context using `kubectl` prior to running skaffold)?

**Comment by etanshaul** [comment]
Looking at this a bit more I suspect its related to the logic here:

```
    fun isKubectlAvailable(): Boolean =
        try {
            val command = listOf(kubectlExecutablePath)
            val process = runKubectlCommand(command)
            process.waitFor(1, TimeUnit.SECONDS)
            process.exitValue() == 0
        } catch (e: Exception) {
            false
        }
```

If the check times out, then we assume that its not available and then fail (throw an exception in `KubectlExecutorService#executeKubectlBlocking`) which in turns now causes skaffold not to run. I think its very possible that it would take longer than a second to execute.

This is in contrast to `SkaffoldExecutorService#isSkaffoldAvailable` where I purposefully did not fail on timeouts to avoid false negatives (see the logic and comment in that function). I suspect we want to do the same thing in `KubectlExecutorService@isKubectlAvailable`.

**Comment by matthewmichihara** [comment]
I think you're right, and that it makes sense to unify how the two commands are called. I can take a look, unless anyone else wants to.

**Comment by etanshaul** [comment]
Feel free. Thanks @matthewmichihara
