### ISSUE TITLE
Update docs with steps on how to manually create the k8s run configs

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2521]
Just in case the prompt is missed (or for whatever reason isn't shown).

**Comment by etanshaul** [comment]
motivation:
https://docs.google.com/document/d/1xmeS_lToEgXaij1aGk8JlCvBwmbQWGNLRUh_0WyP0_Q

**Comment by ivanporty** [comment]
This has been added a while ago in the quickstart.
