### ISSUE TITLE
Unify the way we set K8s context for run configurations

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2528]
Currently one needs to manually query `KubectlApi` in background to obtain the context name and set in on the configuration in order it to become valid.
Options:

1. Treat empty (unset) context as an active one. In UI, populate empty combobox with an active context when run configuration editor opens for the first time. Do not throw exception when run configuration doesn't have context set, just proceed with deployment to whatever active one is.

2. Move context setting logic to `SkaffoldRunConfigurationManager.addSkaffoldRunConfiguration` methods. Do not require setting the context (make it optional), and when not specifyed, query `KubectlApi` and set the context after it's available. Cons: the run configuration remains `invalid` (although it might be valid if active context is available) until kubectl job returns.

**Comment by etanshaul** [comment]
I’m not totally sure I understand option 2, but I definitely think 1 is something we should do.

**Comment by etanshaul** [comment]
Also it seems like this issue can be unified with #2529?

**Comment by matthewmichihara** [comment]
Yup I think both of these issues spawned from the same convo.

**Comment by etanshaul** [comment]
assigned to @matthewmichihara since I think you are working on this based on offline conversations
