### ISSUE TITLE
Pinning kubernetes contexts to run configurations

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2529]
There are multiple places run configurations can be created from:
- skaffold file detected balloon
- skaffold init balloon
- manually with `add new run configuration`

**Problem**
Currently, at run configuration creation time, we try to determine the current kubernetes context and set the `kubernetesContext` field of the configuration object. If we don't do this, deploys with skaffold will fail because we try to set the active kubernetes context before calling out to skaffold.

Obtaining the current kubernetes context needs to be done on a background thread because it could be a potentially expensive operation and we don't want to block the UI thread. Obtaining the context every time we want to create a run configuration is becoming cumbersome to do: https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/116#issuecomment-488420369.

**Potential changes**
1. Don't try to determine the active kubernetes context at run configuration creation time, and defer detecting the context until the run config UI is viewed. When the run config UI is viewed, if `configuration.kubernetesContext  == null`, pin to the current context.
2. If a user runs one of the dev/deploy run configurations before viewing the UI, `configuration.kubernetesContext` will be `null`. Currently this will throw an exception. We could just use the active kubernetes context instead.
3. There are currently plans (https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2517) to allow configuring a run configuration to deploy to the active context. If we are doing the context pinning at the time of viewing the run config UI, we could make the default to use the active context and surface this fact with a checkbox. This is in slight conflict with 1.

**Comment by matthewmichihara** [comment]
@ivanporty does that sound like what we discussed earlier?

**Comment by matthewmichihara** [comment]
@GoogleCloudPlatform/cloud-tools-for-intellij

**Comment by etanshaul** [comment]
We can discuss in more detail but the reality I envision looks like this:

- if no context is set in the run config settings - just use the active context for deployment
- once opening the run config for the first time, default to showing the active context in the dropdown
- any change to the run config context will then subsequently honored

Side note: I think for the case where the context hasn’t been stored in the run config, the question of when to query for the active context - at run config creation time, vs at view time and deploy time etc - is just an implementation detail. 

Does this have any gaps?

**Comment by matthewmichihara** [comment]
Duplicate of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2528
