### ISSUE TITLE
Contributor's instruction link fails to open

### ISSUE THREAD

**Issue by kiran0707** [GoogleCloudPlatform/cloud-code-intellij#2530]
**What did you do?**
I want to build the plugin from source
In https://github.com/GoogleCloudPlatform/cloud-code-intellij/blob/master/README.md
tried the link mentioned

**What did you expect to see?**
source code of plugin

**What did you see instead?**
404 - page not found

**Comment by etanshaul** [comment]
Hi @kiran0707 . 

Thanks for filing the issue. The Cloud Code source is currently private. We're working hard on creating a great Kubernetes and Cloud Native development experience and wanted to first focus on creating an open channel of communication for filing issues, requests and so on (this repo). When the time comes, we can consider opening up to community contributions. In the meantime, if you had a feature request, we'd love to hear it. (I've removed the broken link from the README).
