### ISSUE TITLE
Release 19.5.1 prep work

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2533]
- [x] Stage updated changelogs
- [x] Stage GitHub docs updates (@ivanporty)
- [ ] Stage official docs updates (@etanshaul)

**Comment by etanshaul** [comment]
@ivanporty want to take a stab at updating our GitHub docs? I'll work on the cloud.google.com docs today.

**Comment by ivanporty** [comment]
Sure.
