### ISSUE TITLE
Continuous deploy mode stops when breakpoint hit in debug mode

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2540]
Steps to reproduce:
1. Set a breakpoint in code
2. Select the `Kubernetes Continuous Deploy` run configuration.
3. Hit the debug icon.
4. Go to deployed website.
5. Wait for debugger to hit breakpoint.
6. Click 'Resume program' in debug menu.
7. Notice that continuous deploy mode has stopped, new code changes don't invoke a redeploy.

**Comment by etanshaul** [comment]
> Notice that continuous deploy mode has stopped, new code changes don't invoke a redeploy.

One small point here. New code changes shouldn't invoke a redeploy when in debug mode. This would cause the debugger to stop.

But you are saying that the entire process is killed after clicking "resume"?

**Comment by matthewmichihara** [comment]
The process continues to run. I think my expectations were wrong here. It feels a bit confusing to me that the continuous deploy functionality isn't enabled in debug mode. I wonder if there's a way to message that more clearly. Anyway, I guess this is not a blocker for 19.5.1.

**Comment by etanshaul** [comment]
Good point. Let’s discuss.

**Comment by etanshaul** [comment]
And agree. Not a blocker. As long as the skaffold process wasn’t killed (which I thought was what your were saying).

**Comment by sllewely** [comment]
I have finicky behavior.  When I kill the debug process (but left the continuous deploy running), it picked up some of my changes I had made while in debug, but then didn't pick up my next change.

![image](https://user-images.githubusercontent.com/8452651/57309954-f6e3e500-70b6-11e9-93d3-5e461608e1eb.png)

**Comment by etanshaul** [comment]
Even if you kill only the debug process, the same behavior I explained applies. This is because skaffold itself is launched in debug mode (and this controls the file watching behavior). I think perhaps better messaging here will help.

**Comment by briandealwis** [comment]
I believe IntelliJ should handle .java file changes during debugging by compiling and downloading the new bytecodes into the running JVM.  

If redeploy is enabled, then a change to .java would cause your container to be terminated and restarted, so your debugging process would disappear.

**Comment by etanshaul** [comment]
+1 to what Brian said. 

We have some messaging in the run config that says that "Continuous Deploy" watches for changes and redeploys. It would be good to clarify what happens when its run in debug mode.

**Comment by matthewmichihara** [comment]
> I believe IntelliJ should handle .java file changes during debugging by compiling and downloading the new bytecodes into the running JVM.

Does this mean that if I click `Debug` with the `Continuously Deploy` run configuration, and then make a change to the following to return "bar" and refresh localhost, it should say `bar` instead of `foo`?

```
@RestController
public final class HelloWorldController {
    @GetMapping("/")
    public String helloWorld() {
        return "foo";
    }
}
```

I'm not currently seeing that change reflected.

**Comment by etanshaul** [comment]
you need to tell intellij to recompile the class: `Build -> Recompile`. It should then pick up the changes and then prompt to propagate them over the debugger protocol.

**Comment by matthewmichihara** [comment]
Ahhh, ok I got the class reloading working. Thanks.

**Comment by etanshaul** [comment]
I think we can close this right @matthewmichihara ?

**Comment by matthewmichihara** [comment]
Yup can close. Did we have another issue tracking clarifying messaging around debugging and continuous deploy?
