### ISSUE TITLE
Continuous Deployment "Delete deployments when finished" checkbox non-functional

### ISSUE THREAD

**Issue by sageprice** [GoogleCloudPlatform/cloud-code-intellij#2541]
Deployments are always deleted when the process is stopped, regardless of whether the box is checked or unchecked.

Experienced this using the 19.5.1-rc2 alpha version, and when building from source. Still investigating.

**Comment by ivanporty** [comment]
Same for me. Checkbox unchecked, command line misses `cleanup` flag:
```
skaffold dev --filename skaffold.yaml --label ide=idea --label ideVersion=2019.1.0.0 --label ijPluginVersion=unknown --default-repo gcr.io/k8s-internal
```

**Comment by sageprice** [comment]
Looks like we aren't passing the `cleanupDeployments` configuration from the run config to the settings in `SkaffoldCommandLineState`, I'll send out a PR to fix.

**Comment by sageprice** [comment]
Fixing this leaves the deployments up, although it stops the port-forwarding since that is controlled by Skaffold. This seems correct AFAIK, but would be helpful if someone could confirm this is expected behavior.

**Comment by ivanporty** [comment]
I would say this is correct, since after skaffold finishes, there are no other ways to stop and see port-forwarding processes except by using system tools.
