### ISSUE TITLE
Pycharm 2019.1.2 backgroud process(es) using 100% CPU 

### ISSUE THREAD

**Issue by akettmann-e24** [GoogleCloudPlatform/cloud-code-intellij#2548]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 19.5.1
- OS: Fedora 29
Pycharm 2019.1.2 from a Snap

**What did you do?**
Start Pycharm

**What did you expect to see?**
Pycharm using usual amount of CPU/memory
**What did you see instead?**
1-2 background processes running: /bin/bash -l -i -c '/snap/pycharm-professional/132/bin/printenv.py' '/tmp/intellij-shell-env.6.tmp'
And maxing out a CPU each.

If I closed pycharm, they were orphaned and still running, consuming CPU. Had to use kill -9, as they were still hung on a regular kill. Rolling back to 19.4.1 fixed the issue. Running the command myself as:

`/bin/bash -l -i -c "'/snap/pycharm-professional/132/bin/printenv.py' '/tmp/intellij-shell-env.6.tmp'"`

completes immediately. Not sure the issue. Tried disabling SELinux, shutting down pycharm, killing hanging processes and starting PyCharm again, and it still did the same.

**Comment by ivanporty** [comment]
Hi @akettmann-e24, thanks for the report!
Quick question - were you doing any Cloud Code specific actions before this issue occured, i.e. continuous deployment? Does it happen when you run / debug non Cloud Code application from PyCharm?

**Comment by akettmann-e24** [comment]
I don't have to do anything other than start PyCharm itself. Even a project that contains no kubernetes definitions or run configs will still trigger it.

**Comment by ivanporty** [comment]
What if you open a project without Cloud Code run configurations? Does this happen then?

**Comment by etanshaul** [comment]
@akettmann-e24 thanks for reporting. I can reproduce this in 2019.1.2 (but not in 2019.1.1). Although I had to execute one of the cloud code run configurations first. We are looking into this.

**Comment by etanshaul** [comment]
Update - seems I didn't have to execute the run configuration.

**Comment by ivanporty** [comment]
Didn't happen to me with PyCharm community. Testing with Professional

**Comment by akettmann-e24** [comment]
Sorry folks, had started work on a ticket at work and lost track of this ticket. I am on professional, do you guys need any other info from me on this? I will try and keep an eye to the ticket. I rolled back the plugin and it isn't integral in my current work anyway. Just had the issue of my laptop sounding like it was preparing for liftoff, chased it and narrowed it down to this plugin.

**Comment by etanshaul** [comment]
@akettmann-e24 no problem. you've been really helpful. And at least one of us can reproduce this now :) so we have a place to start. We'll update you if we need any more info.

**Comment by akettmann-e24** [comment]
@etanshaul No worries, happy to help, programming is hard or all these tools wouldn't need to exist! Can't replicate everything that everyone does everywhere!

**Comment by mateuszmrozewski** [comment]
I am observing the same issue with the following setup:

IntelliJ IDEA 2018.3.3 (Ultimate Edition)
Build #IU-183.5153.38, built on January 10, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-48-generic

I can see two processes running in the background:
`
    1 26847  1212  1212 tty1      5139 R     1000   1:26 /bin/bash -l -i -c '/home/mateusz/apps/idea/bin/printenv.py' '/tmp/intellij-shell-env.tmp'
    1 26848  1212  1212 tty1      5139 R     1000   1:26 /bin/bash -l -i -c '/home/mateusz/apps/idea/bin/printenv.py' '/tmp/intellij-shell-env.1.tmp'
`
They are using practicaly whole CPU.

**Comment by etanshaul** [comment]
Thanks for confirming the issue @mateuszmrozewski . We are actively looking at this trying to find a good fix (either in the plugin itself, or in the platform).

One thing we noticed when reproducing this in Linux: this issue only seemed to occur when launching IntelliJ from the terminal. When launching it from the GUI, this didn’t occur. 

If you have a chance could you try launching from the GUI (assuming you were launching the IDE from the terminal in the first place)? Thanks again.

**Comment by akettmann-e24** [comment]
Just for the record I am launching it from the GUI, I am hitting the windows/super key and typing in pycharm in the gnome search bar and hitting enter. Though that may be doing something different than finding it in the list of apps etc.
________________________________

**Comment by mateuszmrozewski** [comment]
@etanshaul, I am launching if through .desktop file on Ubuntu with Gnome, which eventually calls idea.sh. Thus I don't think that would be a relevant difference. I am happy to try other methods if needed, just let me know what to try.

**Comment by etanshaul** [comment]
hi @akettmann-e24 and @mateuszmrozewski thanks for the help on this one.

We just released **Cloud Code version 19.5.2** which should hopefully resolve these issues.

The root of the problem was a workaround that we put in place to load the shell PATH variables when the IDE is launched from the GUI: it's possible that when launching the IDE from the GUI that it doesn't have access to the shell PATH causing certain commands executed by the plugin to fail (for example, it can't find `skaffold`, or `kubectl`). However, it turned out that this workaround wasn't intended to be used with Linux, but only OSX, and clearly was causing issues for you.

In any case, if this fix corrects the crashing / CPU consumption issues for you but then you run into PATH access issues when running Kubernetes deployments, see this FAQ entry for possible help:
https://github.com/GoogleCloudPlatform/cloud-code-intellij/blob/master/kubernetes/docs/faq.md#how-do-i-fix-executable-not-found-on-path-errors

thanks again.

**Comment by mateuszmrozewski** [comment]
I can confirm the new version does not cause any issues. Thank you :)

**Comment by akettmann-e24** [comment]
Fixed for me too! Thanks for the quick turnaround
________________________________
