### ISSUE TITLE
Surface port-forwarded deployment endpoints from Skaffold

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2550]
Currently it's hard to browse the deployment logs and application logs to see which ports are forwarded and available locally. Easy solution would be printing a link to an event log like we do for K8s context switching, so that for each opened port we can print an available local IP address pointing to that endpoint. Skaffold GRPC event server can be used to collect all forwarded ports (excluding debug ones).

More advanced solution is to build centralized diagnostics dashboard with organized logs and endpoints, but while it is in process, we can add quick feature for exposing available endpoints.

**Comment by etanshaul** [comment]
@sllewely this is related to the inner loop area you are working on. Do you want to start thinking about implementing this one? 

This could be a good concrete example to also integrate into the design you are working on (and hopefully help structure).

**Comment by etanshaul** [comment]
closed via #151
