### ISSUE TITLE
Missing Kubectl does not show a good error message in k8s run config

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2551]
The result is simply that the context list is empty (since `kubectl` is unavailable to fetch the contexts), and the error message says "no context selected".

In this case we should probably indicate that the user needs to install kubectl and have it on the path.

**Comment by sageprice** [comment]
I'm assuming that we just want to modify the error message? Not sure what else we could do with the context list dropdown.

**Comment by ivanporty** [comment]
Potentially also disable the combo box and add some effect on it (red background? might be too much) or just mark the text next to it red.

**Comment by etanshaul** [comment]
Yeah. If the underlying reason is that kubectl is unavailable, then the message in the run configuration should indicate that.

Also, it would be good to have a nice notification (when the run configuration is executed) if kubectl is unavailable. Similar to what we have already for skaffold:
<img width="1196" alt="Screen Shot 2019-05-09 at 1 29 39 PM" src="https://user-images.githubusercontent.com/1735744/57474047-3baa8000-725f-11e9-96fe-b1eabf7686f0.png">

**Comment by etanshaul** [comment]
> maybe just mark the text next to it red

I'm a bit skeptical of this (doing it one-off). Unless we find a reusable way to do it for any error'd field (which seems like it would be better for a different PR).

**Comment by ivanporty** [comment]
Agree, it might be too much, too standing out. Just disabling it and showing an error message is a great addition.

**Comment by sageprice** [comment]
Did some local testing, realized we actually already have the warning for when kubectl is not available:

![kubernetes-not-displayed-error](https://user-images.githubusercontent.com/9577120/57550254-d4aacb00-7333-11e9-8a15-69902bece1a9.png)

**Comment by etanshaul** [comment]
Oh interesting. I'm not sure what I was seeing now..

**Comment by sageprice** [comment]
I take it back - I broke my environment in an interesting way...

**Comment by sageprice** [comment]
Nvm, fixed my environment and still saw the same warning. Looks like the run configurations trigger a call to `SkaffoldCommandLineState.startProcess`, which checks if kubectl is available prior to executing any skaffold commands. So it seems like we're good on the notification side now -- though https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2553 remains open.

**Comment by etanshaul** [comment]
cool. does this mean we can close this one now?

**Comment by sageprice** [comment]
I think so, since we have other issues open for related problems. Closing.

**Comment by sageprice** [comment]
Actually, should this be removed from the 19.6.1 milestone? It was released in 19.5.2.
