### ISSUE TITLE
--cleanup flag does not seem to be allowed on skaffold's run command

### ISSUE THREAD

**Issue by dramentol** [GoogleCloudPlatform/cloud-code-intellij#2556]
- Cloud Code for IntelliJ version: 19.5.1
- Google Cloud SDK version: 245.0.0
- OS: Mac OS X 10.14.4

**What did you do?**
I've created a "Deploy to Kubernetes" configuration and ran it.
(console output: "skaffold run --filename skaffold.yaml --label ide=PhpStorm --label ideVersion=2019.1.2.0.0 --label ijPluginVersion=unknown --cleanup=false")

**What did you expect to see?**
A successful deployment.

**What did you see instead?**
time="2019-05-11T12:11:50+02:00" level=fatal msg="unknown flag: --cleanup"

Looks like --cleanup flag is only allowed with skaffold's dev and debug commands. But the plugin is adding it to the run command.

**Comment by etanshaul** [comment]
@dramentol thank you very much for reporting this! we will put out a fix for this soon!

**Comment by etanshaul** [comment]
@GoogleCloudPlatform/cloud-tools-for-intellij FYI

**Comment by etanshaul** [comment]
@dramentol in the meantime, you can run a `Kubernetes Continuous Deploy` run configuration, with `delete deployments when finished` unselected. Then after deployment completes, terminat the run configuration. This will be similar to running a `Kubernetes Deploy`.

**Comment by etanshaul** [comment]
@dramentol we are verifying a fix for this now. Will update here once it goes out.

**Comment by etanshaul** [comment]
fix merged in and planned for upcoming 15.1.2 release. We'll update once out.

**Comment by etanshaul** [comment]
hi @dramentol. we just released Cloud Code version 19.5.2 with a fix for this. Let us know if you run into any other issues, and thanks again for reporting this!

**Comment by dramentol** [comment]
thanks @etanshaul for the quick response. Will let you know if I do run in other issues.
