### ISSUE TITLE
Update Skaffold execution logic to enable port forwarding by default for dev/debug modes

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2562]
Skaffold team decided to remove automatic pod port forwarding in the next release, citing multiple issues with customers and the way the ports work with multiple replicas.
In order to keep the deployed services available in continuous development mode, we will need to add `enable port forward` option when we execute Skaffold in
* `dev` mode
* `debug` mode

Since this is a new option, it might break older versions of Skaffold if used on as a command line flag, so we should implement this as an environment variable.

**Comment by etanshaul** [comment]
thanks. Added to the 19.5.3 milestone.

I don't think `--port-forward` is a new option though. We should verify exactly when it was added though.

**Comment by etanshaul** [comment]
after confirming with Skaffold - this is not a new field. We should be safe just adding it in without consideration for version of skaffold

**Comment by etanshaul** [comment]
I'll go ahead and do this now.
