### ISSUE TITLE
Kubernetes Continuous Deploy Configuration Error

### ISSUE THREAD

**Issue by caweltjr** [GoogleCloudPlatform/cloud-code-intellij#2570]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version:  19.5.3
- OS: Windows 10

**What did you do?** I am following the instructions in this tutorial - https://cloud.google.com/code/docs/intellij/quickstart-IDEA. I have Kubernetes installed and in my path(Windows 10). When I try and edit the Kubernetes Continuous Deploy Configuration, it gives the error "Invalid Data: Could not find kubectl binary on PATH. Please install kubectl." I have researched this for quite a while and found no answer. Can you please help me identify what I need to do to get this to work?

(screenshots are helpful)
![kubectleError](https://user-images.githubusercontent.com/9030569/58283161-7d0d5600-7d5c-11e9-98fe-00b09f01c830.jpg)
![kubectleError](https://user-images.githubusercontent.com/9030569/58283188-8a2a4500-7d5c-11e9-932e-b09113b33f1e.jpg)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
HI @caweltjr thanks for reporting this! We will investigate and report back if we have any follow up questions.

**Comment by caweltjr** [comment]
Thanks!  I appreciate your help!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by etanshaul** [comment]
Hi @caweltjr,

On initial testing I wasn't able to reproduce.

Just to be sure: when you open up a command prompt, and type exactly `kubectl version` is the command found and version info returned?

**Comment by caweltjr** [comment]
Hi,

Here's a screen shot of cmd running kubectl version at the command prompt.

[cid:0da827d5-0314-49dd-ab0b-915fcf716cae]


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by etanshaul** [comment]
what version of the IDE are you using? (also looks like the screenshot didn't attach properly; but confirming that it worked should be enough :) )

**Comment by caweltjr** [comment]
[cid:16633db7-11e2-4119-a1f8-bdc2fdf3119f]

It's 2019.1.2 Ultimate Edition build #IU-191-7141.44. built on May 7 2019


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by etanshaul** [comment]
side note: I think GitHub doesn't properly capture the screenshots when replied via email (I guess you have to attach them directly from GitHub).

**Comment by caweltjr** [comment]
![image](https://user-images.githubusercontent.com/9030569/58287818-d24e6500-7d66-11e9-89dc-0d110771ccf6.png)

**Comment by caweltjr** [comment]
![image](https://user-images.githubusercontent.com/9030569/58287833-e1cdae00-7d66-11e9-8ad0-2d777c995e39.png)

**Comment by caweltjr** [comment]
Ok, thanks, I get it now.  I'll use this

**Comment by etanshaul** [comment]
thanks for the screenshots!

the part that concerns me a bit is the `unable to connect to the server` after the kubectl command completes. It may be that it is failing with a failure exit code causing the plugin to think that kubectl is not available. Will check on the logic.

**Comment by caweltjr** [comment]
Hi, I have made some progress.  I tried to correct the error with kubectl by searching google and that led me to to Docker for Desktop, where I started Kubernetes.  Once I started Kubernetes through DFD, Intellij found it and the error we're working on went away.  Now I'm trying to run it - no errors yet.

**Comment by caweltjr** [comment]
Build was a success  - it worked!

![image](https://user-images.githubusercontent.com/9030569/58289213-a634e300-7d6a-11e9-8113-3536f7644b3f.png)

**Comment by caweltjr** [comment]
Thanks for your help.  I think that was the problem - you have to get Kubernetes actually running, or at least in my case run through Docker for Desktop.

**Comment by etanshaul** [comment]
That’s great! Will close for now. Feel free to open any other issues if you encounter them (or feature requests too).

**Comment by caweltjr** [comment]
Ok, thanks for lot Etan for your helpful, prompt, friendly, and valuable support!
