### ISSUE TITLE
EAP CI is failing

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2580]
https://sponge.corp.google.com/target?id=d5b49e8f-d940-42f1-a411-249909cfef1f&target=google-cloud-intellij%2Fgcp_ubuntu%2Feap%2Fcontinuous&searchFor=

Note for testing, updating `ideaEdition` in `gradle.properties` to `LATEST-EAP-SNAPSHOT`, will pull in the current eap for dev

**Comment by matthewmichihara** [comment]
Wasn't able to reproduce on my mac setting `ideaEdition` to `LATEST-EAP-SNAPSHOT`.
