### ISSUE TITLE
Disable option to use installed dependencies on unsupported platforms

### ISSUE THREAD

**Issue by sageprice** [GoogleCloudPlatform/cloud-code-intellij#2582]
Related to https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2561

Since we can only install Cloud Code dependencies on Mac/Linux/Windows, we should not present the option to opt-in/out in settings for users running on other platforms. We need to make sure that the behavior is disabled on startup, and remove the option from the UI.

**Comment by etanshaul** [comment]
no managed dependencies for Solaris users.... :(

In seriousness though: what platforms is intellij compatible with other than those three I wonder?

**Comment by etanshaul** [comment]
not conclusive, but the wiki snippet on google search results:
![image](https://user-images.githubusercontent.com/1735744/59067800-83cdba00-8880-11e9-88b5-34c98a015140.png)

**Comment by sageprice** [comment]
I'll be very curious to see how many users are actually unable to use managed dependencies due to these restrictions. Given that we're only supporting this for platforms which IntelliJ supports we should expect 0, but platform identification is based on a text comparison of a system property (in IntelliJ anyway) so we can't be too sure.

**Comment by sageprice** [comment]
This has been done for a while, forgot to close it.
