### ISSUE TITLE
EAP 2019.2 build is broken due to apparent refactoring of java support

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2590]
In 2019.2 the build is failing with:

```
/tmpfs/src/github/google-cloud-intellij/common-test-lib/src/main/java/com/google/cloud/tools/intellij/testing/MavenTestUtils.java:73: error: cannot access SourcePathsBuilder
                    module = moduleBuilder.createModule(model);
                                          ^
  class file for com.intellij.ide.util.projectWizard.SourcePathsBuilder not found
Note: /tmpfs/src/github/google-cloud-intellij/common-test-lib/src/main/java/com/google
```

among many other failures due to java support related classes missing from the classpath.

Investigating still (and asking JB), but the fix is to add the `java` plugin to the `gradle-intellij-plugin`. e.g.:

```
intellij {
    plugins 'maven', 'java'
}
```

The problem is that this works in the EAP but is not backwards compatible with the stable release.

@matthewmichihara fyi since this is related to the EAP build failure you started to look into.

**Comment by etanshaul** [comment]
Update:

There was indeed refactoring to the Java support. And we do now need to include the `java` plugin for the EAP.

A way we can achieve backwards compatibility here is to substitute in the value into the build.gradle files (similarly to how we do for the IDE version, for example).

@matthewmichihara fyi. we can discuss offline in more detail

**Comment by etanshaul** [comment]
these details should help:
https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/

**Comment by matthewmichihara** [comment]
great find! what happens if you include the java plugin with the current intellij release?

**Comment by etanshaul** [comment]
> what happens if you include the java plugin with the current intellij release?

Gradle error: something like "cannot find plugin `java`" :(
