### ISSUE TITLE
MacOS: Could not find kubectl installation on PATH

### ISSUE THREAD

**Issue by theogravity** [GoogleCloudPlatform/cloud-code-intellij#2593]
- Cloud Code for IntelliJ version: `v19.5.3`
- OS: MacOS Mojave
- Using Webstorm `2019.1.3`

**What did you do?**

I installed the following via `brew`:

- skaffold
- minicube
- kubernetes-cli

All binaries are on the `/usr/local/bin` path.

In the `Cloud Code` plugin configuration in Webstorm, under:

`Other Settings` > `Cloud Code` > `Kubernetes`

I have `Path to Skaffold executable` registered as `/usr/local/bin/skaffold`

I have a `Kubernetes Continuous Deploy` configuration set up, but it complains about `kubectl` being missing:

![image](https://user-images.githubusercontent.com/855434/59570947-2db4ff80-9054-11e9-95fd-79e402bcb760.png)

``` 
$ which kubectl
/usr/local/bin/kubectl
```

If I try executing the configuration, I still get the error:

```
16:32	Error running 'Kubernetes Continuous Deploy'
					Could not find kubectl installation on PATH: please install kubectl.
					For more information on required dependencies, see https://cloud.google.com/code/docs/intellij/install#prerequisites
```

- I tried launching `webstorm` directly from the cli itself where `which kubectl` works
- I tried registering the `/usr/local/bin` path in webstorm in `Appearance & Behavior > Path variables`, but no go.
- The `Kubernetes Continuous Deploy` > Environment variables section does inlcude `PATH=/usr/local/bin`

![image](https://user-images.githubusercontent.com/855434/59571039-512c7a00-9055-11e9-892e-5784f9ddc0dc.png)

**What did you expect to see?**

The plugin should allow specification of the path to kubectl (and other related dependencies) if it has problems trying to locate it as the `/usr/local/bin` path

**Comment by etanshaul** [comment]
Hi @theogravity. Thank you for reporting.

I haven’t had a chance to investigate yet, but it’s possible that this is related to this issue: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2586

Do you have an active context set up? ‘kubectl config current-context’. Adding @sageprice who reported that issue. 

It’s possible that it is related to a missing context (but showing an incorrect error message).

We will definitely look into this more.

**Comment by theogravity** [comment]
I do not.

```
$ kubectl config current-context
error: current-context is not set
```

**Comment by etanshaul** [comment]
Ah. Thanks for the quick response. As an initial test / workaround I suggest creating one and then seeing if the tooling works. I suspect the bug is that we are showing the wrong message.

**Comment by theogravity** [comment]
Yep, that did it.

I didn't have `minikube` started - once it started, the default context was defined as `minikube` and I was able to run the continuous deploy config 

Thanks!

**Comment by etanshaul** [comment]
Excellent. Glad it worked.

We will make sure to fix this for the next release. Closing this one since it’s being tracked by the other issue I linked to.
