### ISSUE TITLE
App Engine Python support - feature request

### ISSUE THREAD

**Issue by shawntabai** [GoogleCloudPlatform/cloud-code-intellij#2596]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 19.5.3
- Google Cloud SDK version: 251.0.0
- OS: Windows 10 10.0

**What did you do?**
Tried to set up or use gcloud integration inside IntelliJ (mostly for deploying to App Engine)

**What did you expect to see?**
A setup screen or a terminal window starting the deploy process.

**What did you see instead?**
When clicking 'Cloud Code > App Engine > Deploy to App Engine...': 'This project is not an App Engine project: To deploy to App Engine, add App Engine standard or flexible framework support to one or more modules in your project.'

When clicking ''Cloud Code > App Engine > Add App Engine support > Google App Engine Standard|Flexible': 'All modules already have App Engine support, or no modules were found.'

**Comment by etanshaul** [comment]
hi @shawntabai thanks for filing an issue!

could you please provide a bit more information about your project so we can help debug:
- What does the module structure of your project look like?
- Do you already have an `appengine-web.xml` in your project?
- Does your project already have app engine support: 
`Open Module Settings > Modules`. Do you see something like this:
![image](https://user-images.githubusercontent.com/1735744/59866129-c7342800-9358-11e9-92fd-b275faa7e504.png)

**Comment by shawntabai** [comment]
Thanks for the reply. My project is Python, not Java. I do have an `app.yaml` file, and my module does have an App Engine facet in it though:

```
<?xml version="1.0" encoding="UTF-8"?>
<module type="PYTHON_MODULE" version="4">
  <component name="FacetManager">
    <facet type="google-appengine-python" name="Google App Engine (Python)">
      <configuration>
        <option name="rootFolder" value="D:\Users\Shawn\IdeaProjects\rpg-caster" />
        <option name="sdkFolder" value="D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine" />
      </configuration>
    </facet>
  </component>
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$" />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="Google App Engine SDK" level="project" />
  </component>
</module>
```

![image](https://user-images.githubusercontent.com/6535862/59969584-81689280-9505-11e9-8497-d78dfdcb6fb3.png)

I've been able to create External Tools in IntelliJ to do the things I want via the `gcloud` CLI or extensive tweaking with my project's Run Configurations, but it would certainly be nicer (and would have saved me a lot of time) if the builtin tools for things like deploying to App Engine and running a local server worked for Python apps.

**Comment by etanshaul** [comment]
Thanks for the details.

Cloud Code at this time only supports Java for App Engine. Python deployment is only supported for Kubernetes.

Your request for Python App Engine support is absolutely noted, however we don’t have short term plans to enable this.

Sorry I couldn’t be more helpful.

**Comment by shawntabai** [comment]
Makes sense. Thanks for the detailed replies and acknowledgement of the feature request!

**Comment by jmah-cc** [comment]
After investigating this again, this is not at the top of our priority list. Closing this out for now. 

To others who are interested in this, please upvote and we'll re-visit it in the future.
