### ISSUE TITLE
Plugin stuck downloading

### ISSUE THREAD

**Issue by marcus-sa** [GoogleCloudPlatform/cloud-code-intellij#2599]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: v19.5.3
- OS: Ubuntu Budgie 19.04

**What did you do?**
Tried to install the plugin several times.

**What did you expect to see?**
For it to successfully install.

**What did you see instead?**
It being stuck downloading.

(screenshots are helpful)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by sageprice** [comment]
Hey @marcus-sa thanks for reaching out, and sorry about the installation problems. I think we need a little more information to help.

- How are you installing the plugin?
- Is this the first time installing the plugin, or installing an updated version? If the latter, what version were you using previously?
- What does the stuck state look like?

This is not ideal, but could you try [installing from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk) and see if that produces the same error? [All versions of Cloud Code from IntelliJ are available as zips](https://plugins.jetbrains.com/plugin/8079-cloud-code/versions).

If installation is stuck when downloading directly from the plugin repository you may want to file an issue with JetBrains. Our plugin does not do anything until installation completes and IntelliJ restarts, so there isn't much we can do if that's the case.

**Comment by marcus-sa** [comment]
Installing it from disk solved the problem.
I tried installing it directly from the marketplace using 2 different PCs connected to different networks, whereas with both it left hanging in the `Download` state.

**Comment by sageprice** [comment]
Glad you were able to install from disk, though the fact regular download via IntelliJ did not work is frustrating. I'm going to go ahead and close this since we cannot do anything more, but feel free to add a link to the JetBrains issue if you decide to file one.
