### ISSUE TITLE
Deployment fails with unrelated project id in error log

### ISSUE THREAD

**Issue by hombrecz** [GoogleCloudPlatform/cloud-code-intellij#2601]
- Cloud Code for IntelliJ version: v19.5.3
- OS: Linux Mint 19.1 Cinnamon
- Intellij version: IntelliJ IDEA 2019.1.3 (Ultimate Edition), Build #IU-191.7479.19, built on May 28, 2019

**Problem description**
I have a problem with deploy to Google Cloud (App Engine Standard, Java) from the IDEA. The Run configuration, I've used have worked till the June 28th 2019 at least. Next time I've attempted to deploy was on July 1st and the deploy failed with this error:

> ERROR: (gcloud.app.deploy) PERMISSION_DENIED: Service Usage API has not been used in project 408655593417 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=408655593417 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
> - '@type': type.googleapis.com/google.rpc.Help
  links:
>  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=408655593417

I' am afraid that the problem is somewhere in the plugin, because:
- the URL link mentioned in error leads to error page, most probably due to we don't have any project with id: 408655593417
- Service Usage API is already enabled and used on our project
- deployment is successful when the checkbox "Update dos, dispatch, cron, queues, and datastore indexes" is not checked
- deployment is successful from the command line
- colleague of mine have tested deployment from the Eclipse IDE and succeeded

Can you help me, please?

**Comment by chanseokoh** [comment]
@etanshaul I was expecting this on Intellij too. See https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3503#issuecomment-507394087

**Comment by etanshaul** [comment]
Hi @hombrecz thanks for reporting and apologies for the troubles.

I'm currently on vacation and unable to give this the full attention it deserves, but I did implement the fix @chanseokoh describes above (enabling the service usage API on the intellij project for which the oauth client is defined).

Could you possibly give this another try and see if that helped? Thanks!

**Comment by cvaught** [comment]
I was having the same issue and it is now fixed. Thanks @etanshaul for getting this resolved.

**Comment by hombrecz** [comment]
Hi @etanshaul , thanks for the fix! It helped and now it works again.

Also big thanks for fixing it, while on vacation!
