### ISSUE TITLE
Add support for IntelliJ prompting to install Cloud Code on seeing a skaffold.yaml file

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2604]
http://www.jetbrains.org/intellij/sdk/docs/plugin_repository/feature_extractor.html#file-type

**Comment by etanshaul** [comment]
Good find. Dup of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2391

Feel free to close either one

**Comment by etanshaul** [comment]
Actually, the question I have now is if this works (somehow) even if Cloud Code is not installed. This is the idea end point.

**Comment by etanshaul** [comment]
Note the above comment does not indicate we shouldn’t at least do this.

**Comment by etanshaul** [comment]
Actually my comment didn’t make any sense. The notification is to install a plugin right? So this means the plugin is not yet installed. Sorry for spamming this issue :)

**Comment by matthewmichihara** [comment]
ah great, will close this one.
