### ISSUE TITLE
Add an explicit link to an event log message about localhost port forwarded by Cloud Code

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2611]
I.e. currently the message in the event log says:
`Develop on Kubernetes: Port Forwarding hello-spring-boot port 8080 -> 8080`, we can easily convert the last port number into a link which in turn opens `localhost:[port]` for a user without having to switch to a browser manually.

**Comment by etanshaul** [comment]
we should probably exclude debug releated port forwards from this, as having them linkified probably isn't helpful
