### ISSUE TITLE
Consolidate github documentation with cloud.google.com documentation

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2618]
It's confusing to have two sets of competing docs.

We should have a concise set of information on GitHub:
- Overview and feature list
- Screenshots / casts
- Links (docs, official samples, etc.)

**Comment by ivanporty** [comment]
I think overview sections/high-level features with the links to corresponding cloud code docs are the easiest and most straightforward way of doing this. Having local screenshots will also tend to become obsolete. WDYT?
