### ISSUE TITLE
We should bring back the FAQ

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2627]
I missed this during review: when we removed the GitHub docs (in favor of the Cloud Code docs) we also removed the Kubernetes FAQ, which is still very nice to have on GitHub.

I suggest bringing it back with a link near the bottom of the homepage README:

## Frequently Asked Questions

[link]

**Comment by ivanporty** [comment]
How about moving this FAQ to cloud docs as well, if we try following idea of keeping one copy of everything there that may eventually diverge?

**Comment by etanshaul** [comment]
Good idea.

**Comment by etanshaul** [comment]
And then we can link to it directly from GitHub

**Comment by ivanporty** [comment]
FAQ actually exists as "Troubleshooting": https://cloud.google.com/code/docs/intellij/troubleshooting
