### ISSUE TITLE
gcp app-engine-java & jetbrains pycharm

### ISSUE THREAD

**Issue by SandorSzalma1** [GoogleCloudPlatform/cloud-code-intellij#2632]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 19.7.2
- OS: Windows 10 64-bit

**What did you do?**
JetBrains PyCharm Professional 2019.2 - update Cloud Code plugin

**What did you expect to see?**
it goes through without a problem

**What did you see instead?**
plugin download and installs google cloud sdk AND installs app-engine-java component
This component, AFAIK, is not needed for PyCharm
(screenshots are helpful)

C:\Users\xxx\AppData\Local\Google\ct4j-cloud-sdk\LATEST>google-cloud-sdk\bin\gcloud components list

Your current Cloud SDK version is: 257.0.0
The latest available version is: 257.0.0

| Installed     | BigQuery Command Line Tool                           | bq                       |  < 1 MiB |
| Installed     | Cloud Datastore Emulator                             | cloud-datastore-emulator | 18.4 MiB |
| Installed     | Cloud SDK Core Libraries                             | core                     | 11.3 MiB |
| Installed     | Cloud Storage Command Line Tool                      | gsutil                   |  3.6 MiB |
| Installed     | gcloud app Java Extensions                           | app-engine-java          | 85.9 MiB |
| Installed     | gcloud app Python Extensions                         | app-engine-python        |  6.0 MiB |
+---------------+------------------------------------------------------+--------------------------+----------+

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
@SandorSzalma1 thanks, this is great feedback. You are right that this component is not needed for PyCharm.

In fact, `gcloud` currently is really only needed in the IDEA IDEs as App Engine is only available currently for Java. 

This will change soon as we will use gcloud for Kubernetes functionality (GKE integration), so PyCharm (and other JB IDEs) will be able to benefit from a managed gcloud installation. 

@ivanporty fyi on this

**Comment by ivanporty** [comment]
Great, thanks for the feedback. This is definitely a good idea to exclude the App Engine component for non-IDEA IDEs, we will work on this to make the installation smaller and faster!

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3136)

**Comment by jmah-cc** [comment]
Won't fix, not a priority at this time. Please upvote if you'd like to see this improvement and we'll re-visit
