### ISSUE TITLE
Can't setup k8s with JIB project

### ISSUE THREAD

**Issue by sneakythr0ws** [GoogleCloudPlatform/cloud-code-intellij#2633]
Hi!
I tried to setup k8s features of plugin.
I have project with [Google JIB](https://github.com/GoogleContainerTools/jib)(without Dockerfile) and k8s .yml files in k8s/rc(prod)/ dirs. But I can't setup k8s features of this plugin
![image](https://user-images.githubusercontent.com/1594945/63022241-26bb3980-beab-11e9-953d-3de4224b0f78.png)

**Comment by etanshaul** [comment]
Hi @sneakythr0ws , thanks for the report!

That error you are seeing is coming from the automatic Skaffold config generation - this attempts to generate a `skaffold.yaml` automatically for you based on your project. Currently, we don't have support to automatically create a `skaffold.yaml` for your project if it is a Jib project. This will be coming soon though!

In the meantime, could you try creating a `skaffold.yaml` configuration for your project and then trying again? Once you create the configuration, the plugin should prompt you to add the new Kubernetes Run Configurations which will then let you deploy to k8s.

This may be helpful: https://cloud.google.com/code/docs/intellij/using-a-k8-existing-app
And if you need more details on Skaffold, you can always visit: https://skaffold.dev

Let us know if you run into any trouble.

**Comment by patflynn** [comment]
If you take a look at our Java samples
<https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java>
you
can see how to setup Skaffold with Jib.

**Comment by sneakythr0ws** [comment]
Thank you! It works
Excuse for troubling

**Comment by etanshaul** [comment]
no trouble. happy it worked.
