### ISSUE TITLE
Request: kustomize editing support

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2639]
Do we have any updates on this issue. 
`kustomization.yaml` files don't work either

_Originally posted by @tete17 in https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2559#issuecomment-494790189_

See
https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2559

**Comment by jmah-cc** [comment]
This should now be fixed, please re-open if you're still running in to this.
