### ISSUE TITLE
Debugger window not showing

### ISSUE THREAD

**Issue by prary** [GoogleCloudPlatform/cloud-code-intellij#2642]
Hi @etanshaul kubectl error still persist but i am able to run debug mode through GUI. Ran it today debug mode ran fine but I am not getting the option to put breakpoint. 
Command it executed 

C:\Users\prashant\go\src\github.com\GoogleContainerTools\skaffold.exe debug --filename java-hello-world/skaffold.yaml --label ide=idea --label ideVersion=2019.1.3.0.0 --label ijPluginVersion=unknown --port-forward=true

_Originally posted by @prary in https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2630#issuecomment-522319487_

**Comment by etanshaul** [comment]
hi @prary 

Sorry for the delayed reply. Is this still an issue for you? I suspect what it happening is that Skaffold isn't correctly port-forwarding the debug port. Could you possibly paste the output of the events printed in IntelliJ's Event Log after you are running a deploy (in debug mode)?

**Comment by etanshaul** [comment]
Update: I just noticed that this issue was created off of a comment in the other (#2630) thread, and that you already provided the Event Log output.

Out of curiousity, when you run the exact same command from the terminal, what messages do you see around port forwarding?

**Comment by prary** [comment]
C:\Users\prashant\go\src\github.com\GoogleContainerTools\skaffold.exe debug --filename java-hello-world/skaffold.yaml --label ide=idea --label ideVersion=2019.1.3.0.0 --label ijPluginVersion=unknown --port-forward=true


8/29/2019
4:45 PM	Dockerfile detection
				You may setup Docker deployment run configuration for the following file(s): 
				java-guestbook\backend\Dockerfile
				java-guestbook\frontend\Dockerfile
				java-hello-world\Dockerfile
				Disable this notification (show balloon)

4:47 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: ...

4:48 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: ...

4:48 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: ...

**Comment by etanshaul** [comment]
hi @prary. Bumping the priority on this.

So we can narrow things down, and prior to diving deeper, am I correct in understanding that debugging does work when using the standard [release version](https://github.com/GoogleContainerTools/skaffold/releases) of Skaffold (and not a custom build / fork)?

**Comment by prary** [comment]
@etanshaul yes it work with standard release version and it works fine with custom builds as well when correct go version is used.

**Comment by etanshaul** [comment]
Thanks @prary . That sounds somewhat reassuring. Under what conditions does it not work?

**Comment by prary** [comment]
It was just a go version which we never thought could be the culprit so we switched to same go version which is used by skaffold pipeline. Just to give you some more ground can you go through linked issue as well.

Don't get distracted by the fact we build our own binary we did use skaffold official binary and then debugger window wasn't showing up. One strange thing I remember popup window showed kubectl not in path while running the cloud code it was getting the kubectl(which was in the path)

**Comment by etanshaul** [comment]
Hi @prary. just to clarify things as I am a bit confused now. About debugging, you said:

> yes it work with standard release version and it works fine with custom builds as well when correct go version is used

and then you said:

> we did use skaffold official binary and then debugger window wasn't showing up.

So I'm a bit confused if debugging is or isn't working and in which cases? Maybe the first statement was incorrect (or I misunderstood)?

And regarding the `kubectl` error, I'd encourage you to try the latest version of Cloud Code as we have made some improvements to dependency management, to see if that helps.

**Comment by prary** [comment]
Hi @etanshaul what I meant by working was skaffold debug isn't it throwing error unlike when compile with incorrect Golang version which throws error. It does proper port forwarding and transformation. No error message is emitted it's just cloud code doesn't pop up debugger window and program doesn't stop at applied breakpoint. Sorry for being so unclear, surely we can this on slack.

**Comment by etanshaul** [comment]
closing as it was reported working via a chat channel
