### ISSUE TITLE
Does cloud code speed up builds

### ISSUE THREAD

**Issue by jakubMitura14** [GoogleCloudPlatform/cloud-code-intellij#2648]
Hi I am creating kotlin multiplatform project in intellij I am considering how to speed up gradle build time -I think good idea would be to push the build into cloud servers and not doing it on far inferior laptop (of course I know that in that way i would only test common and cloud module - I suppose I will make a composite gradle build and cloud project will get common as  its dependency but it is fine). Would cloud code help me to achieve stated goal?

**Comment by sageprice** [comment]
Hey @jakubMitura14, thanks for reaching out. Sorry to say that Cloud Code by itself can not accelerate your builds. Right now, the primary benefits of Cloud Code are simplified container deployment, debugging, development, and Kubernetes resource monitoring. AFAIK Cloud Code does not do anything to speed up builds.

Out of curiosity, what do you mean when you say "multiplatform project"? If you are interested in building containers, I'd recommend checking out [Jib](https://github.com/GoogleContainerTools/jib), which can substantially speed up builds while enforcing best practices. If that's what you're looking for, it has a [Gradle plugin](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin) which is straightforward to incorporate into a build.

**Comment by jakubMitura14** [comment]
Thanks for a reply ! by multiplatform i mean 
https://kotlinlang.org/docs/reference/multiplatform.html

**Comment by sageprice** [comment]
Got it, thanks for the link. While we'd like to add more GCP integrations in future, I think Cloud Code is currently focused on improving Kubernetes support first. At this point I wouldn't recommend waiting on Cloud Code for your use case.

Cloud Code currently enables building containerized apps on Cloud Build via [skaffold](https://skaffold.dev), but we don't have support for non-containerized apps -- if you want to use GCP for build performance then you should probably look into using [Cloud Build](https://cloud.google.com/cloud-build/) directly. Best of luck!

**Comment by etanshaul** [comment]
@jakubMitura14 also worth mentioning that you can configure Cloud Code to build with Cloud Build (via Skaffold) as well, and then deploy your application to GKE with Cloud Code. (see this example on how to configure you `skaffold.yaml` file https://github.com/GoogleContainerTools/skaffold/tree/master/examples/google-cloud-build).

I will close this issue tentatively as well, but please feel free to follow up with questions or re-open if you run into any issues.
