### ISSUE TITLE
Does this plugin work with a local installation of kubernetes?

### ISSUE THREAD

**Issue by greencat3** [GoogleCloudPlatform/cloud-code-intellij#2649]
Will this plugin work with a non GCP installation of kuberntest? I'm thinking something like pointing this plugin to a local installation of kubernetes running on a local network machine?

**Comment by etanshaul** [comment]
Hi @greencat3 yes it will. As long as you have the cluster/context defined locally in you kubeconfig (‘kubectl config view’) then you should be good to go.  More generally, the Cloud Code Kubernetes features work with any Kubernetes cluster, local or remote.

Please do let us know if you run into any friction.

**Comment by greencat3** [comment]
@etanshaul Yes, that answers my question, thanks!

**Comment by etanshaul** [comment]
@greencat3 glad it answered your question. Out of curiosity - what is your specific scenario? Based on the answer does it seem like it should work out of the box, or do you need the custom kubeconfig support (or something else)? Asking to make sure we capture any requirements you may have.

**Comment by greencat3** [comment]
I should've worded my question more precisely, but really I just had the scenario: I have a local installation of Kubernetes which I did manually and this installation is not connected to any cloud provider or anything like and I was wondering if the cloud code would work with it? My first thought was that it might not, since it might only work with Google Cloud and nothing else but looking at your answer that doesn't seem to be the case.
