### ISSUE TITLE
Remove .vscode directory from IntelliJ IDEA projects

### ISSUE THREAD

**Issue by dlsniper** [GoogleCloudPlatform/cloud-code-intellij#2651]
- Cloud Code for IntelliJ version: 19.9.2
- OS: Windows 10

**What did you do?**
- Install Cloud Code in GoLand 2019.2.2
- Create a Hello World project for Go

**What did you expect to see?**
- I expected to see an IntelliJ/GoLand specific project

**What did you see instead?**
- I saw a vscode specific project since it's a different platform.

![image](https://user-images.githubusercontent.com/607868/66103742-54755280-e5bf-11e9-99e5-81fe858c6382.png)

I guess in this case, the plugin should remove the `.vscode` folder and have it focus by default on a different file, perhaps the `main.go` one as that's the entrypoint of the project? Or maybe the `skaffold.yaml`.

**Comment by sageprice** [comment]
Thanks for pointing this out @dlsniper. These starter projects come from the [Cloud Code samples repo](https://github.com/GoogleCloudPlatform/cloud-code-samples) which is shared between Cloud Code for IntelliJ and Cloud Code for VS Code, so we have kept IDE-specific config files for both editors there for convenience. Given that, I'd assume we want to keep both the .idea and .vscode files. Though removing the VS Code specific files when creating a project from IntelliJ or vice versa seems reasonable to me. @etanshaul any thoughts?

On a related note, the .idea files should definitely be present after creating this project but I'm not seeing them present here. @dlsniper can you confirm that the .idea files are present/absent?

**Comment by dlsniper** [comment]
@sageprice thank you for the quick reply!
Yes, I confirm that the `.idea` folder is present and all predefined run configurations are there. That's great!
As for removing non-related files, it should be applied to both platforms, for sure, sorry I wasn't more obvious in my issue.

**Comment by ivanporty** [comment]
+1 to removing the other platform specific configuration when creating an app from our templates. Should reduce confusion and make the project tree look simpler.

**Comment by etanshaul** [comment]
After some internal discussion, we decided that we would not remove the `.vscode` directory. The IntelliJ integration does a `git clone` of the repo, and it seemed reasonable that it may contain extraneous metadata. Also there is the (admittedly rarer) scenario where the user may want to open the same project in both IDEs.

Feel free to re-open if you feel strongly about this and we can discuss. Thanks!
