### ISSUE TITLE
installer & binaries with proxy

### ISSUE THREAD

**Issue by SandorSzalma1** [GoogleCloudPlatform/cloud-code-intellij#2656]
Plugin cannot install the required binaries in our environment via proxy.
The settings for options with kubernetes are not complete (3 binaries versus only 2 entries)

- Cloud Code for IntelliJ version: 19.9.2
- OS: MS Windows 10 Enterprise 64-bit

**What did you do?**
Install latest version of the plugin

**What did you expect to see?**
Cloud Code initialization: Cloud Code has finished setting up managed Kubernetes dependencies.

**What did you see instead?**
Cloud Code initialization cannot be competed.

(screenshots are helpful)
idea.log with PyCharm Professional
Cloud Code Plugin is not able to download the binaries via our proxy.
2019-10-04 14:42:50,054 [  56816]   WARN - ffold.init.SkaffoldInitService - unable to check for skaffold init based configuration 
com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerFailedException: Installer exited with non-zero status code 1: cannot retrieve skaffold.exe: Get https://storage.googleapis.com/skaffold/releases/v0.39.0/skaffold-windows-amd64.exe: dial tcp 216.58.215.240:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

2019-10-04 14:58:12,534 [ 119195]   WARN - ncies.ManagedDepsInstallerTask - Managed dependencies installation failed 
com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerFailedException: Installer exited with non-zero status code 1: cannot retrieve kubectl.exe: Get https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/windows/amd64/kubectl.exe: dial tcp 216.58.215.240:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

2019-10-04 15:41:17,985 [  64343]   WARN - es.LanguageServerInstallerTask - language-server binary installation failed 
com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerFailedException: Installer exited with non-zero status code 1: cannot retrieve language-server.exe: Get https://dl.google.com/cloud-code/lsp/0.1.5/languageserver-0.1.5-win.exe: dial tcp 172.217.168.14:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

3 binaries are used but under Settings/Cloud Code/kubernetes only two of them can be defined.

**Comment by sageprice** [comment]
Thanks @SandorSzalma1 for filing this, and sorry to hear you're running into trouble with the new dependency management.

You're correct about the language server binary, we don't currently have a way of providing a path to it like we do for skaffold and kubectl. Until we have that, deployments and the resource browser should still be usable by specifying custom kubectl and skaffold binaries in settings, but all YAML editing support is going to be blocked. This is an oversight on our part. We are now looking into ways to either package the language server binary or allow you to specify a path to it.

As a follow-up, if we have the means to specify an executable for the language server we'll still need it to be provided -- are you able to manually download the executable from the `https://dl.google.com/cloud-code/lsp/0.1.5/languageserver-0.1.5-win.exe` location, or is that domain/distribution style a no-go?

**Comment by SandorSzalma1** [comment]
At the end I have used the files on my private PC, where the files was installed without any issue (no proxy...).
On my PC in the office with the browser I can download the files.
I think, that your downloader/installer should use the proxy authentication information, what I enter during starting up PyCharm.

**Comment by SandorSzalma1** [comment]
we use option "auto-detect proxy settings"

**Comment by etanshaul** [comment]
got it.

I think we have a couple takeaways:

1) We should have a way to specify a manual path to the LSP binary so at least users in this situation have an alternative to the dep. manager
2) We need to investigate having the dep. manager respect system proxy settings

You mentioned that you were able to download the files from your browser. Is this because you have the proxy settings configured in the browser? 

Are you at least unblocked (downloaded the binaries on your system and pointed Cloud Code to them manually in the settings) on the `kubectl` and `skaffold` binaries - which as @sageprice mentioned, will allow you to use all Kubernetes features except for editing support?

**Comment by SandorSzalma1** [comment]
in PyCharm for the proxy we configured 3 things :
- use option "auto-detect proxy settings"
- PyCharm trusts our certificates with the proxy
- \jbr\lib\security\cacerts file has been updated with the issuer certificates of our proxy

**Comment by sageprice** [comment]
Hey @SandorSzalma1, wanted to follow up and find out more about your setup. At this point it seems like Cloud Code may not be plumbing the `HTTP_PROXY` environment variable through properly.

You've noted you're using the "auto-detect proxy settings" option -- does this also reference a PAC file?
Is the `HTTP_PROXY`/`HTTPS_PROXY` env variable already configured in your environment, and how are you opening PyCharm? It may be that the IDE cannot find the env variables unless opened from a shell environment where they are already configured. Do you get the same error when running PyCharm from a shell?

**Comment by SandorSzalma1** [comment]
Hi @sageprice,
auto detect proxy uses system proxy defined with windows 10.
We just switched to a new proxy so I used the option with the PAC-file, too.
(And sometimes with Fiddler I use the manual proxy config.)

I do not like using HTTP_PROXY/HTTPS_PROXY environment variables, because they are used by the requests Python package, too. (And this is not always what you want.)

I will have a look on the new version of the plugin this week and let you know!

**Comment by sageprice** [comment]
Thanks for the helpful explanation @SandorSzalma1, we're trying to figure out how IntelliJ is managing proxy information so we can plumb it to Cloud Code properly so knowing the problematic use cases helps towards that.

Unfortunately fixes are not out yet, but we are working on it now -- I'll update this issue once we have something working in nightly.

**Comment by sageprice** [comment]
Hey @SandorSzalma1, we've now implemented proxy support for the installer using IntelliJ's settings. The changes will be out in the next release, but if you want to check it out a little early you can check out the [nightly build](https://plugins.jetbrains.com/plugin/8079-cloud-code/versions). Either way, I'll leave this open until we can confirm this is working.

**Comment by etanshaul** [comment]
@sageprice they should be out now in 19.11.2 unless I’m missing something? It should have been released yesterday.

**Comment by sageprice** [comment]
Whoops good point, still waking up. Thanks @etanshaul.

**Comment by etanshaul** [comment]
@SandorSzalma1 I'm going to close this issue for now as we've added initial proxy support. feel free to reopen if you are still experiencing issues.
