### ISSUE TITLE
Unable to remove the Kubernetes Explorer tool from the sidebar

### ISSUE THREAD

**Issue by knoan** [GoogleCloudPlatform/cloud-code-intellij#2659]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 19.10.1
- IntelliJ IDEA version: Ultimate 2019.2
- OS: macOS 10.15

**What did you do?**

I'm trying to remove the Kubernetes Explorer tool from the sidebar

![Screenshot 2019-10-18 at 09 08 16](https://user-images.githubusercontent.com/6105462/67073433-5c202400-f187-11e9-9aeb-8851b75ee7b5.png)

**What did you expect to see?**

- the Kubernetes Explorer tool is permanently removed from the sidebar 

**What did you see instead?**

- after quitting and reopening IntelliJ IDEA the Kubernetes Explorer tool is still present in the sidebar at the last selected position

**Comment by etanshaul** [comment]
thanks for reporting @knoan , we will investigate and make sure to fix this.

**Comment by jmah-cc** [comment]
Unable to repro, please re-open if you're still seeing this.
