### ISSUE TITLE
Kubernetes Explorer shows contexts, but no namespaces, nodes

### ISSUE THREAD

**Issue by hosswald** [GoogleCloudPlatform/cloud-code-intellij#2670]
- Cloud Code for IntelliJ version: 19.11.1
- OS: Windows 10 v1903 18362.388

**What did you do?**
Opened Kubernetes Explorer in IntelliJ

**What did you expect to see?**
All of my contexts and for each of them a list of namespaces and nodes.
Before expanding:
![image](https://user-images.githubusercontent.com/32925139/68377406-9bb8ab00-014a-11ea-83aa-b96a09c4b75e.png)

**What did you see instead?**
After expanding:
![image](https://user-images.githubusercontent.com/32925139/68377480-bc810080-014a-11ea-807b-ce4789042b1e.png)

An example command that works fine in PowerShell without admin privilege:
![image](https://user-images.githubusercontent.com/32925139/68377693-2a2d2c80-014b-11ea-9d10-78c0ed06e0a0.png)

**Comment by etanshaul** [comment]
@hosswald thanks for reporting. Did this start happening after upgrading the plugin to version 19.11.1? 

As a test could you try manually browsing to your kubeconfig file and selecting it, and letting us know if that solves the problem? (The drop down at the top of the explorer that shows “default”)

**Comment by etanshaul** [comment]
@sageprice fyi - this _may_ be related to the kubeconfig feature.

Also one other question @hosswald - was the explorer working as expected prior to upgrading to Cloud Code 19.11.1?

**Comment by etanshaul** [comment]
@hosswald also, if you can, grabbing the output of the IDE logs around when you try to expand the nodes would be really helpful.

**Comment by sageprice** [comment]
Thanks @etanshaul for pointing this out. The window should also display the error when hovering over the error indicator, do you see any message there?

**Comment by sageprice** [comment]
Wondering if this is a timeout/network issue as we expect in https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2682. Since the contexts were found it is not a kubeconfig issue. Un-assigning myself pending any new information here.

**Comment by etanshaul** [comment]
I suspect this is timeout related. If so, it is a dup of: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2682

Closing for now under the assumption that it is a duplicate. If not, @hosswald feel free to reopen and provide more details.
