### ISSUE TITLE
[Migrated issue] GoLand debugger freezes randomly

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2674]
Text from https://youtrack.jetbrains.com/issue/IDEA-225924

I am trying to debug a Go Project (Go Modules enabled) and at some point the debugger just freezes, the dlv process also seems to freeze (API not responding anymore) and GoLand is not responding anymore.
I restarted GoLand, reimported my project, tried all of that stuff and it didn't help.
The issue reoccurs some minutes after I start the debug session and it keeps appearing after restarts of GoLand.
But I am not quite sure how to reproduce the issue.
I ran into this issue and look into the idea logs and I discovered something along the lines of: (see first logs attachment)

**Comment by tim-ebert** [comment]
Just for context: I was actually debugging my go app with the integrated Run Configurations of GoLand (local debugging).
I then disabled the Cloud Code Plugin and the issue did not appear again.

As someone from the JetBrains team pointed me to the notion, that the issue does not seem to be related to the debugger and rather the Cloud Code Plugin, I realized that I have also experienced some slow performance in editing multiple yaml files (with third-party/unknown Kinds/schemes to the Plugin) side-by-side.
I actually think, that the debugger froze in exactly that moment when I tried to edit some yamls while debugging and the problem might be related to that...

Don't know if this actually helps, but I can try to give some more details, if you point me in the right direction.

**Comment by etanshaul** [comment]
Thanks @tim-ebert this is very helpful.

Do you recall if you were editing a ‘skaffold.yaml’ config file? We think this might be the culprit but are still investigating.

**Comment by tim-ebert** [comment]
Actually, I didn't even have a `skaffold.yaml` file in my project.
I was just using the local debugging configuration and editing some Kubernetes yamls (of Custom Resources).

I updated my Cloud Code Plugin to the latest version two days ago, reenabled it and never saw the issue again.
I think it might actually be solved in the newest version, but I'll ping you here if I see the issue again.

/close

**Comment by etanshaul** [comment]
Thanks @tim-ebert. I'm going to close this issue for now, but we'll open an internal issue to investigate speeding up read actions across the plugin (in case that happened to be the problem here). Feel free to reopen if anything else comes up.

**Comment by dekiel** [comment]
In my case I had to upgrade cloud SDK by hitting upgrade now button in cloud code plugin settings. Despite plugin was set to do it automatically.

**Comment by etanshaul** [comment]
@dekiel I believe the plugin will only check for update on IDE load, and when you manually click the button, like you mentioned.

Were you also seeing some sort of slow down as described in this issue? If so would you mind elaborating on it to help us hone in on the problem?

**Comment by etanshaul** [comment]
@tim-ebert our release today - 19.11.3 - contains a fix that should hopefully address this. Would be great if you could let us know if it helps.

The issue was overly long reads by certain features of our YAML editing support which could cause the UI thread to lock up. We’ve optimized the reads to address this.

**Comment by tim-ebert** [comment]
@etanshaul Thank you for the information.
I update my Cloud Code plugin and I have not seen the issue again so far. 👍
