### ISSUE TITLE
Add support for Python Debugging

### ISSUE THREAD

**Issue by loripino21** [GoogleCloudPlatform/cloud-code-intellij#2675]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 19.1.1
- OS: Windows 10

**What did you do?**
Prepared skaffold.yaml config, packaged a Python app.
Dockerfile launches python in standard way: 
`CMD python3 server_auth.py`
Run cloud code deploy by pressing debug.

**What did you expect to see?**
IntelliJ Python debugger attach to pod running Python app.

**What did you see instead?**
Building logs. Deploying logs (all ok).
And then:
`time="2019-11-13T12:17:40+01:00" level=warning msg="Skipping \"api-auth\" as does not appear to invoke python"`
After, port forwarding messages for exposed pod ports, but nothing related to debugging.

**Comment by etanshaul** [comment]
Hi @loripino21. We don’t yet have support for Python debugging, but are working on it :) Stay tuned for an upcoming release (no timeline at the moment - Python is a bit trickier to get working than it was for Java, Node, and Go - but it is on the roadmap).

**Comment by chuber1986** [comment]
Hi, @etanshaul. Are there any uptades on this feature? Would it be possible the get the source code?

BR Christian

**Comment by etanshaul** [comment]
Hey @chuber1986 the source is currently closed, if anything changes on that front we'll update you. Regarding Python debugging support - no updates yet: this feature is still pending but high priority in the backlog. Will update on this once things speed back up after the holidays last week.

**Comment by chuber1986** [comment]
Thanks for the (fast) information!

**Comment by shahargl** [comment]
Hey!
Any progress? I wish I could debug python on Cloud Run 🙏

**Comment by etanshaul** [comment]
sorry @shahargl no update yet on this. This is still in our backlog. How has the Cloud Run support been working out for you otherwise? Any other feature requests? Thanks!

**Comment by etanshaul** [comment]
Hi all. I'm happy to report that with the [release today of Cloud Code](https://github.com/GoogleCloudPlatform/cloud-code-intellij/releases/tag/v21.5.1), version `21.5.1`, we now support debugging your Python apps on Kubernetes & Cloud Run local emulator.

Please try it out if you are interested and feel free to report back any issues or questions. 

Some notes to help ensure you debug successfully (these requirements are also captured in the [Docs](https://cloud.google.com/code/docs/intellij/kubernetes-debugging), as well as reinforced with notifications in-plugin):
- Python debugging requires either IntelliJ Ultimate + python plugin OR Pycharm Professional. The reason for the limitation is that these editions support remote debugging, a prerequisite for Kuberenetes / Cloud Run debugging.
- Ensure that you have Python SDK configured in your project. [Steps here](https://cloud.google.com/code/docs/intellij/kubernetes-debugging#python).

**Comment by etanshaul** [comment]
@shahargl , @chuber1986, @loripino21 just a friendly reminder that Python debugging was released in the second to last Cloud Code release. If you had a chance to try it out and have any questions or concerns, we'd be happy to help you out!

**Comment by cpvandehey** [comment]
So far so good on my end @etanshaul. My team is using it and will report back with issues

**Comment by shahargl** [comment]
@etanshaul, my use case is to debug remote Cloud Run containers, and it doesn't seem to be supported, isn't it?

**Comment by etanshaul** [comment]
@shahargl debugging remote cloud run containers is not supported in general (all languages) due to limitations in the Cloud Run platform (inability to forward a port locally, for example). We do, however, support debugging workloads locally on the Cloud Run emulator, including Python. If this alternative works for you and you had questions about it, let us know.

**Comment by talboren** [comment]
@etanshaul I am having trouble debugging the application on my GKE cluster from **PyCharm**, it seems like the debugger is attached but no breakpoint is hit.
I've tried source mappings with different remote paths but it still doesn't seem to work and the only reference I see here: https://cloud.google.com/code/docs/intellij/kubernetes-debugging#python is for java based projects..

I am debugging the application just fine from VSCode though.. any idea what may be the cause?

**Comment by peterlin741** [comment]
@talboren, could you share any error messages from the logs that you've seen?

**Comment by talboren** [comment]
@peterlin741 Actually, there are not errors at all.
The only differences I can see between VSCode and PyCharm are:

- PyCharm uses pydevd while VSCode uses debugpy
- VSCode starts more than just debugpy server (port 5678) and listens on couple of more ports

![image](https://user-images.githubusercontent.com/68807791/125419423-4ba5f235-a053-4354-bcfb-e165e8ad2dd1.png)
![image](https://user-images.githubusercontent.com/68807791/125419445-c0971d89-392f-4b7a-b092-8848f152b803.png)

**Comment by etanshaul** [comment]
Hi @talboren. You may have seen it, but on the doc page you linked (https://cloud.google.com/code/docs/intellij/kubernetes-debugging#python) there is some Python specific info in the table down a bit. Just confirming:

- do you have Pycharm Professional edition? Debugging won’t work in community due to the lack of support for remote debugging
- Did you configure the Python interpreter for your project as outlined in that doc?

(I’d any of these are violated, you _should_ see some messages printed to the event log after launching the session)

if all of the above looks good, could you please try adding the environment variable PYCHARM_DEBUG=true to your app (in your Dockerfile for example) and share the logs of the Skaffold debug session.

**Comment by talboren** [comment]
Hey @etanshaul! Thanks for your comment.

Of course I've gone through the entire documentation page and also covered most of [Skaffold debug documentation](https://skaffold.dev/docs/workflows/debug/) to see that I am not missing anything out.

PyCharm is Professional edition of course
![image](https://user-images.githubusercontent.com/68807791/125483197-b984a759-dbf1-4085-bac6-c69bf89e95ef.png)
And interpreter is configured as well
![image](https://user-images.githubusercontent.com/68807791/125483285-f5c87371-a293-4ef0-84e2-846046be1d53.png)

This is a screenshot from a live debug session, of both the "Debug" screen and the "Event Log":
![image](https://user-images.githubusercontent.com/68807791/125483942-ca5a6e90-657a-4198-ae8c-76113e7b1b31.png)

**Comment by talboren** [comment]
I've set `PYCHARM_DEBUG=true` and I can see breakpoints getting set/removed but still, nothing has changed and "Debug Log" is still empty (while in my Kubernetes Debug log I can see some pydevd/pycharm debugging stuff):

![image](https://user-images.githubusercontent.com/68807791/125485526-2764bd7d-f5ae-47d2-93df-e7a20ab48c76.png)

some of the logs:
`[api] Connection (from wait_for_attach) accepted.
[api] debugger: received >>501	1	0.1	UNIX<<
[api] 
[api] Received command: CMD_VERSION 501	1	0.1	UNIX
[api] 
[api] sending cmd (quoted-line) -->          CMD_VERSION @@BUILD_NUMBER@@
[api] 
[api] debugger: received >>501	3	0.1	UNIX<<
[api] 
[api] Received command: CMD_VERSION 501	3	0.1	UNIX
[api] 
[api] sending cmd (quoted-line) -->          CMD_VERSION @@BUILD_NUMBER@@
[api] 
[api] Connection (from wait_for_attach) accepted.
[api] pydevd.Reader received kill signal
[api] pydevd.Writer received kill signal
[api] WriterThread: CMD_EXIT received
[api] WriterThread: exit
[api] debugger: received >>501	1	0.1	UNIX<<
[api] 
[api] Received command: CMD_VERSION 501	1	0.1	UNIX
[api] 
[api] sending cmd (quoted-line) -->          CMD_VERSION @@BUILD_NUMBER@@
[api] 
[api] debugger: received >>111	3	python-line	/app/tests/test_service_endpoint.py	55	test_add_new_service	THREAD	None	None<<`

![image](https://user-images.githubusercontent.com/68807791/125485746-dca5c093-36dd-405a-94ca-c5e3cedcc74e.png)

**Comment by etanshaul** [comment]
Thanks @talboren for the info - all that looks normal so far - a couple more quick questions to help get to the bottom of this:

- when you set a breakpoint, does the IDE indicate any error? Sometimes it will convert the breakpoint icon to an error icon and the hover text will explain the error. Or does it look like a normal working breakpoint?
- You mentioned it works in VS Code - is it exactly the same app? And in VS Code did you have to configure any source mapping?

**Comment by etanshaul** [comment]
And a couple other thoughts @talboren . I see you are using pycharm version 2020.2. That is the lowest version in our support range and _should_ work fine - but I will double check myself.

And lastly - this may be too difficult of an ask - but if you have a sample app that reproduces this that you can link to that would really help.

**Comment by talboren** [comment]
> Thanks @talboren for the info - all that looks normal so far - a couple more quick questions to help get to the bottom of this:
> 
> * when you set a breakpoint, does the IDE indicate any error? Sometimes it will convert the breakpoint icon to an error icon and the hover text will explain the error. Or does it look like a normal working breakpoint?
> * You mentioned it works in VS Code - is it exactly the same app? And in VS Code did you have to configure any source mapping?

- No errors at all, breakpoint seems to be working fine and container logs seems to be pointing out that the breakpoint was also set fine and mapped to the relevant source file on that container (I think)
- It is exactly the same app, VSCode like PyCharm asked to me select the source mapping (which was /app for both of them)

> And a couple other thoughts @talboren . I see you are using pycharm version 2020.2. That is the lowest version in our support range and _should_ work fine - but I will double check myself just in case there is a bug.
> 
> And lastly - this may be too difficult of an ask - but if you have a sample app that reproduces this that you can link to that would really help.

Will try to update my PyCharm right away, if it keeps reproducing after that -- I'll share an app for example.

Thanks for everything!

**Comment by talboren** [comment]
@etanshaul unfortunately, also after updating PyCharm to 2021.1.3 it still doesn't seem to be working :(
Will try to provide a sample app tomorrow.

**Comment by talboren** [comment]
@etanshaul I've just tried https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/python/python-hello-world and successfully attached and got my breakpoint to work when working in a remote GKE cluster.

I'll further investigate my specific service and the reason debugging is not working properly and will update upon any result.

Thanks for all the help!

P.S: 1 small thing I've noticed is that for some reason, in python-hello-world it seems like traffic in to the running container is being forwarded as well (internal port 80 to some random port on my local machine, automatically, without any configuration), don't know if that has anything to do with my problem but I'll check that.

**Comment by etanshaul** [comment]
> P.S: 1 small thing I've noticed is that for some reason, in python-hello-world it seems like traffic in to the running container is being forwarded as well (internal port 80 to some random port on my local machine, automatically, without any configuration), don't know if that has anything to do with my problem but I'll check that.

Skaffold has [automatic port-forwarding](https://skaffold.dev/docs/pipeline-stages/port-forwarding/) (which we take advantage of from the plugin). Among others, Skaffold will autoomatically forward all container ports for images built by Skaffold (e.g. [port `8080` in the hello-world sample](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/python/python-hello-world/kubernetes-manifests/hello.deployment.yaml#L24)). Skaffold will usually try to match the local port - but if its not available, a random port will be chosen.

**Comment by etanshaul** [comment]
@talboren if you don't mind, let's take this chat over to this new issue I created: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2961
