### ISSUE TITLE
Goland freeze when Cloud Code plugin enabled.

### ISSUE THREAD

**Issue by dekiel** [GoogleCloudPlatform/cloud-code-intellij#2677]
When editing yaml files Goland freeze and has to be forced to quit. With disabled Cloud Code plugin Goland works fine. Didn't found any errors in Goland logs around the time of freeze.
- Cloud Code for IntelliJ version: 19.11.1
- OS: macOS Catalina 10.15.1

**What did you do?**
Edit yaml files.
**What did you expect to see?**
Goland is not freeze.
**What did you see instead?**
Goland freeze and has to be restarted.

Recently issue disappear for one day after manual upgrade of cloudSDK despite plugin was set to do it automaticaly. After recent Goland upgrade issue is back.

**Comment by etanshaul** [comment]
Thanks @dekiel does your project happen to have a ‘skaffold.yaml’ file? And if so, was it open around the time of the freezes?

**Comment by etanshaul** [comment]
Also could you please let us know which version of GoLand you are using?

**Comment by ivanporty** [comment]
Do you see any processes running when freeze happens (maybe a process indicator in the IDE status bar)? There should not be any connection between YAML files and managed dependencies / SDK, if you remove managed SDK and dependencies (make it manual), and edit YAML files, does it happen?

**Comment by dekiel** [comment]
I'm using Goland 2019.2.5 and I don't have skaffold.yaml files.
There is no any processes running in an IDE indicator bar, but when Goland freeze it use 750% cpu on quad core i7. Disabled plugin managing Cloud SDK an dprovided manual path. It ask for installation of app-engine-java component. After installing component Goland still freeze.

**Comment by matthewmichihara** [comment]
Would it be possible for you to share a sample project or yaml file that reproduces the issue?

**Comment by dekiel** [comment]
Editing any of following files is causing freeze. These are files with which I was working recently

https://github.com/dekiel/test-infra/blob/master/prow/jobs/kyma/kyma-integration.yaml
https://github.com/dekiel/test-infra/blob/master/prow/config.yaml

**Comment by matthewmichihara** [comment]
I was able to confirm GoLand freezing when editing both of these files. Taking a look.

**Comment by matthewmichihara** [comment]
I believe we were able to fix this in the latest 19.11.3 release: https://github.com/GoogleCloudPlatform/cloud-code-intellij/releases/tag/v19.11.3).

@dekiel Please try it out and let us know if it fixed your issues.

**Comment by dekiel** [comment]
Hi, looks problem solved. Thanks for help!!!!
