### ISSUE TITLE
FR: Support Google Cloud Run, Debug and Deploy

### ISSUE THREAD

**Issue by ZeroCool2u** [GoogleCloudPlatform/cloud-code-intellij#2679]
Would be awesome to see support for managed Google Cloud Run deployments! I'm sure it's not super high on the list of priorities, because the service is so new, but would be happy if this FR was tracked/added to the backlog. 😃

**Comment by etanshaul** [comment]
@ZeroCool2u that is definitely is in the backlog! I’ll share more info as we progress. Thanks for the FR

**Comment by etanshaul** [comment]
Hi @ZeroCool2u .

Just wanted to updated you that [we released Cloud Code IntelliJ 20.4.1](https://github.com/GoogleCloudPlatform/cloud-code-intellij/blob/master/CHANGELOG.md#2041---latest-release) with Cloud Run Support today!

Please try it out and let us know what you think - we'd love to hear and feedback / feature requests (you can file them as issues on this repo).

https://cloud.google.com/code/docs/intellij/quickstart-cloud-run

**Comment by ZeroCool2u** [comment]
@etanshaul That's awesome, thanks so much for the heads up!!! I was just about to start writing a new service with GCR anyways, great timing! I'll definitely leave any feedback I've got. Hope you and the team are staying safe and healthy!

**Comment by etanshaul** [comment]
Thanks, and same to you @ZeroCool2u ! 

And we're here to help if anything is needed.
