### ISSUE TITLE
Kubernetes Explorer java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by catycatylee** [GoogleCloudPlatform/cloud-code-intellij#2682]
- Cloud Code for IntelliJ version: 19.11.3
- Google Cloud SDK version: 269.0.0
- OS: Windows 10 10.0

**What did you do?**
I am trying link to my kubernetes cluster or GKE/EKS cluster,
sometimes I got java.util.concurrent.TimeoutException.
But using kubectl CLI to get cluster info is OK!

**What did you expect to see?**
has anywhere could set the timeoiut seconds?
Thanks!

**Comment by sageprice** [comment]
Hey @catycatylee, thanks for filing this. I believe we currently have a 5s timeout configured for all kubectl actions, so you're likely running into that. What actions are you doing which trigger timeouts?

We don't yet have a way of configuring this timeout, maybe @ivanporty wants to weigh in here?

**Comment by ivanporty** [comment]
Agree, we would be interested to know if you are seeing the timeout for specific actions rather than at random ones? I.e. specific cluster (remote one or local), network (wi-fi vs. wired vs. work, etc.), which resources listing results in timeouts (how many of them, i.e. do you have a lot of pods, or namespace is particularly large and has a lot of resources)? 
Do you ever see a problem with a local cluster like Docker or Minikube, if you are using them?

**Comment by etanshaul** [comment]
Hi @catycatylee. thanks for reporting. Any more info you could provide (see above questions) would be super helpful for us to know how we might improve things. One additional question:

- How often approximately are you seeing the timeouts? Is it on every execution of the same operation, or just occasionally?

**Comment by kann181** [comment]
Timeout should be configurable. There could be so many reasons due to which slowness can happen. it could be network or it can accessing from a different geographical location as to where cluster is running etc.  Is there a way i can change the 5s timeout pls ?

**Comment by ivanporty** [comment]
Hi @kann181, thank you for your suggestion. There are many reasons, if you do see timeouts, how often they happen and do you see any reasons behind them - network or cluster specific?

Currently there is no way of configuring timeout. We will think more about this, and if you could add a few more observations on when they happen for you, that'd be really helpful. Thanks!

**Comment by kann181** [comment]
The plugin is practically useless for me at this point, as our clusters are in United States and I am based out of Asia. So I would expect it to be a configurable value to take into consideration of latencies

**Comment by etanshaul** [comment]
@kann181 could you help us understand a bit how much latency you are experiencing? e.g. if you run something like `kubectl get pods` from the command line, how much time does it take?

**Comment by jmah-cc** [comment]
@ivanporty Should we keep this issue open or close it out?

**Comment by ivanporty** [comment]
Too little information to confirm the problem.

**Comment by harkhanna** [comment]
> @kann181 could you help us understand a bit how much latency you are experiencing? e.g. if you run something like `kubectl get pods` from the command line, how much time does it take?

Hi, myself also working from Asia and trying to access my cluster pods in US/EU regions. It shows timeout several times. We have to refresh it many times for it to load the namespaces/pods.

The ask here is just to increase the timeout internal to something lets say 20 seconds or make it configurable.

**Comment by etanshaul** [comment]
reopening so we can consider solutions for this.

Thank you @harkhanna for the report

**Comment by singhgur** [comment]
I have same issue with Docker-desktop but i can see everything within Intellij default services window but kubernetes explorer plugin not working

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2086)

**Comment by etanshaul** [comment]
thanks for the info @harkhanna and @singhgur . We are triaging this internally.

**Comment by etanshaul** [comment]
@singhgur could you possibly share which region are located in and which region(s) the cluster you are accessing is in?

**Comment by ivanporty** [comment]
> I have same issue with Docker-desktop but i can see everything within Intellij default services window but kubernetes explorer plugin not working

@singhgur could you please clarify what do you mean by `within Intellij default services window`? Does it work with the delay for you but doesn't time out?

**Comment by sachinsharma** [comment]
I am working from India. Accessing cluster in US. I face this problem everytime I try to access Namespaces or Nodes.
![Capture](https://user-images.githubusercontent.com/157912/94268583-00dfdf80-ff5b-11ea-9a55-151db0bfa715.JPG)

**Comment by etanshaul** [comment]
hi @sachinsharma thanks for the message. What version of Cloud Code are you on? We added a feature where you can configure the timeout value of call made in the explorer. Just visit Settings > Cloud Code > Kubernetes : 

<img width="524" alt="Screen Shot 2020-09-25 at 10 11 35 AM" src="https://user-images.githubusercontent.com/1735744/94277425-8a6dbe00-ff17-11ea-99d3-b61cc2940ec8.png">

As you can see, the default is 5 seconds. But you can increase it as needed. Let us know if this works.

Also fyi to @harkhanna , @catycatylee , and @kann181 on this.

**Comment by etanshaul** [comment]
closing for now since we have a configurable timeout, but please reopen if you run into issues.
