### ISSUE TITLE
GoLand with local kubernetes cloud

### ISSUE THREAD

**Issue by OmegaRogue** [GoogleCloudPlatform/cloud-code-intellij#2686]
- Cloud Code for IntelliJ version: 19.12.1
- OS: Windows 10 Pro Version 2004 Build 19041.1

**What did you do?** Start "Run on Kubernetes" in the Hello World Template

**What did you expect to see?** a successful build and deployment

**What did you see instead?**
```
time="2019-12-30T17:22:53+01:00" level=fatal msg="exiting dev mode because first build failed: build failed: build failed: building [go-hello-world]: build artifact: docker build: error during connect: Post https://192.168.99.100:2376/v1.24/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=docker.io%2Fomegarogue%2Fgo-hello-world%3Alatest&target=&ulimits=null&version=: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
```
The Run Configuration:
![image](https://user-images.githubusercontent.com/24958536/71590606-80a26000-2b29-11ea-92f8-8269685c29a6.png)

**Comment by ivanporty** [comment]
Thanks for using Cloud Code and for the report @OmegaRogue! 
It looks like a network issue accessing your Docker, while attempting to push the image to it.

Could you please check a few things and report back?
- are you able to push images using `docker push` from a terminal?
- what happens if you change `Deployment profile` in your above run configuration to `Dockerfile`?

Also, could you please clarify what "local kubernetes cloud" means? Are you using something like `minikube` or your own local Kubernetes cluster?

**Comment by OmegaRogue** [comment]
> Thanks for using Cloud Code and for the report @OmegaRogue!
> It looks like a network issue accessing your Docker, while attempting to push the image to it.
> 
> Could you please check a few things and report back?
> 
> * are you able to push images using `docker push` from a terminal?
> * what happens if you change `Deployment profile` in your above run configuration to `Dockerfile`?
> 
> Also, could you please clarify what "local kubernetes cloud" means? Are you using something like `minikube` or your own local Kubernetes cluster?

1. when trying to build an image to push, i got this error:
```
D:\Projects\GoKubeTest>docker build .
error during connect: Post https://192.168.99.100:2376/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=kg9
1n16eyagya6qmvh3zkwkd8&shmsize=0&target=&ulimits=null&version=1: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected hos
t has failed to respond.
```
2. These are the only available options for `Deployment profile`:
![image](https://user-images.githubusercontent.com/24958536/71593089-e6dfb080-2b32-11ea-8af3-72b736131e28.png)

3. with Local Kubernetes Cloud i mean my own local Kubernetes cluster running on 5 Raspberry Pi 3s

**Comment by ivanporty** [comment]
> 1. when trying to build an image to push, i got this error:

It looks like there is a problem with Docker connectivity, since this seems to be the same problem outside of Cloud Code plugin.

Quick research yielded the following interesting issue specifically for Windows: https://github.com/docker/for-win/issues/2575

It looks very similar to yours. Could you please follow up with suggestions there (it seems increasing resource limits could help?) and try to get `docker build` command working, and then try Cloud Code again? Thanks!

**Comment by OmegaRogue** [comment]
ah, that issue, ive had it before, i remembered that all of those solutions in the issue didnt work for me and searched for another one, back then i was using virtualbox because i didnt have Windows 10 Pro yet, now i use HyperV, i found working solutions on stackoverflow: https://stackoverflow.com/questions/37527888/docker-commands-fails-in-windows
after that, the run configuration worked mostly fine, except for that im getting this output and the logs in the deployment arent showing any hello world:
```
Watching for changes...
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by ivanporty** [comment]
Great that the deployments started working! 

As for the new issue, it seems that the executable format is not correct, I would suspect this is a incompatibility between the executable built by `docker` on your machine and your Raspberry Pi runtime? Try running the image locally with `docker run`, and if it works, then you probably need to build the binary in the `Dockerfile` differently to target your cluster, potentially with some Go build flags for Raspberry Pi.

**Comment by OmegaRogue** [comment]
i ran it locally and didnt see anything in the logs either, so i looked into the code and its not supposed to print anything into the log, but as an http reponse, so i forwarded the port of the local image, accessed it and it worked
![image](https://user-images.githubusercontent.com/24958536/71595545-658d1b80-2b3c-11ea-8599-abec500e0aa0.png)

**Comment by OmegaRogue** [comment]
Also, the Run Terminal in GoLand is still periodically outputting
```
[go-hello-world-74b9c45b8d-vtxxw server] standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by ivanporty** [comment]
I would say this has something to do with the system in general - maybe a Windows Go build thing.. Hard to say, but it seems to be outside of Cloud Code specifically and rather in the Go build / execution realm, worth looking for the same error message on SO.

**Comment by OmegaRogue** [comment]
I tried running the Guestbook template to see if it had something to do with the hello world template, and the guestbook image build failed
with this error:
```
time="2019-12-30T20:34:06+01:00" level=fatal msg="exiting dev mode because first build failed: build failed: build failed: building [guestbook-backend]: build artifact: denied: requested access to the resource is denied"
```

**Comment by ivanporty** [comment]
> I tried running the Guestbook template to see if it had something to do with the hello world template, and the guestbook image build failed
> with this error:

This specifically has to do with the access to the image repository - did you specify default image repository for the run configuration like you did in the screenshot above (`docker.io/omegarogue`)?

**Comment by OmegaRogue** [comment]
yes, i forgot it, i added that back and it built but got these errors:
```
rpc error: code = Unknown desc = no matching manifest for linux/arm/v7 in the manifest list entries
Back-off pulling image "mongo:4"
rpc error: code = Unknown desc = no matching manifest for linux/arm/v7 in the manifest list entries
[guestbook-frontend-855cf85f55-xlb4j frontend] standard_init_linux.go:211: exec user process caused "exec format error"
[guestbook-frontend-855cf85f55-xlb4j frontend] standard_init_linux.go:211: exec user process caused "exec format error"
Back-off pulling image "mongo:4"
rpc error: code = Unknown desc = no matching manifest for linux/arm/v7 in the manifest list entries
[guestbook-frontend-855cf85f55-xlb4j frontend] standard_init_linux.go:211: exec user process caused "exec format error"
Back-off pulling image "mongo:4"
[guestbook-frontend-855cf85f55-xlb4j frontend] standard_init_linux.go:211: exec user process caused "exec format error"
rpc error: code = Unknown desc = no matching manifest for linux/arm/v7 in the manifest list entries
Back-off pulling image "mongo:4"
[guestbook-frontend-855cf85f55-xlb4j frontend] standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by ivanporty** [comment]
Cool, thanks. I think this looks like the same issues - the resulting binaries are not suitable for your Raspberry Pi runtime. Maybe try this: https://www.thepolyglotdeveloper.com/2017/04/cross-compiling-golang-applications-raspberry-pi/? Specifically, they mention these flags should target Raspberry Pi: `env GOOS=linux GOARCH=arm GOARM=5 go build`.

**Comment by ivanporty** [comment]
Ah, this is error messages for `mongo`.. I am not sure if it's possible to run Mongo DB on Raspberry Pi, I suggest to do some research on that. Alternatively, to prove it's working on a usual Linux-style cluster, could you also try deployments to `Docker Kubernetes cluster` or `Minikube`?

**Comment by OmegaRogue** [comment]
![image](https://user-images.githubusercontent.com/24958536/71598909-07b30080-2b49-11ea-8f07-3b5a0db4b55a.png)
i got hello world working, i added a line to the dockerfile before the build action is run:
```dockerfile
# Set Compiler Flags for ARM (for example Raspberry Pi) compilation
ENV GOOS=linux GOARCH=arm GOARM=5

# Compile the application to /app.
RUN go build -o /app -v ./cmd/hello-world
```

**Comment by ivanporty** [comment]
Awesome news! Let us know how Cloud Code works for you otherwise, we are always open for more feedback!

**Comment by ivanporty** [comment]
@OmegaRogue I think it's safe to close this issue, but feel free to re-open if you think we missed something here. For other feedback, please file feature requests or just let us know if Cloud Code is useful to you and leave your thoughts here. Thanks!
