### ISSUE TITLE
cloud code: Kubernetes - run configuration keeps reverting to defaults

### ISSUE THREAD

**Issue by wimdetroyer** [GoogleCloudPlatform/cloud-code-intellij#2693]
- Cloud Code for IntelliJ version: 3.8
- OS: ubuntu 19.10

**What did you do?**
configure settings of one skaffold run configuration 
![image](https://user-images.githubusercontent.com/58472100/72977298-84e23600-3dd4-11ea-9159-a174ae0c0a62.png)

**What did you expect to see?**
 
The same settings should persist after exiting intelliJ and restarting.

**What did you see instead?**

The defaults...
(screenshots are helpful)
![image](https://user-images.githubusercontent.com/58472100/72977398-c4108700-3dd4-11ea-900c-c5078cdfcc0c.png)

This is happening on a brand new laptop. The initial run configurations were generated based on the skaffold.yaml file but new configurations were added since.

**Comment by etanshaul** [comment]
Hi @wimdetroyer.

Was it the “current system context” that was changed or other values as well? If the system context changes externally (by running a kubectl command, that can affect the setting, as that option basically says to use whatever the system context is). If you want it to pin to a certain context, you can use the “switch context and deploy to” option and select the desired context. This will ensure that the selected context is always used.

**Comment by etanshaul** [comment]
Update: I just noticed the change in the kubeconfig setting. Taking a closer look.

**Comment by etanshaul** [comment]
Also - you mentioned that new configurations were added since. Do you mean new run configurations? If so, whenever a new a run config is generated it starts with default values. When you edit an existing run configuration is when the persisted value should remain (with the caveats mentioned above).

**Comment by wimdetroyer** [comment]
Hi @etanshaul , thanks for your fast response.

I just tried to use the option 'switch context and deploy to' instead of deploy to current system context. The only selectable value there was microk8s. After that, I closed and restarted IntelliJ. The deployment profile & kubeconfig were set to default again.

The changes in the skaffold.yaml are new deployment profiles. These are all listed under 'deployment profile'. 

My colleagues do not seem to have this problem. Are *all* run configurations saved somewhere in the .idea directory? Perhaps it's an IntelliJ issue, not the fault of the plug-in.

**Comment by etanshaul** [comment]
> Are all run configurations (maven, spring boot,...) saved somewhere in the .idea directory? 

Run configs are only persisted in the .idea folder if you have the `Share through VCS` option selected:
<img width="721" alt="Screen Shot 2020-01-23 at 11 09 30 AM" src="https://user-images.githubusercontent.com/1735744/73001683-de486600-3dd0-11ea-8516-4d7198ae78fb.png">

Otherwise, the values are persisted somewhere outside the project directory (in the idea installation folder / metadata folder).

Nothing jumps out at me immediately here that could be the culprit but I will investigate more today when I have a chance and follow up.

**Comment by etanshaul** [comment]
In the meantime if you could confirm:
- Even when you keep all things constant (i.e. set some non-default config in the Run Configuration, save it, and change nothing else at all), the values are reset to do default after you re-open the run config? Is it just after a restart, or does this also happen if you just close the run config and reopen it?

**Comment by ivanporty** [comment]
+1 to last question by @etanshaul, I know this might be a bit much to ask, but could you please record a short GIF video (no source code of course, just run configuration) of how you change the settings, save, re-open, and the result?

**Comment by ivanporty** [comment]
Also, you mention logs - they might be useful to quickly check for hidden errors. You can get the IDE log by using `Help -> Show Log in Files`, then please attach and zip that log file (`idea.log`) for us.

**Comment by wimdetroyer** [comment]
https://webm.red/view/EkrX.webm

and

https://webm.red/view/RNOX.webm

So to recap: changes only get lost after **exiting** intellij.

And my logs:

[idea.zip](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/4107298/idea.zip)

**Comment by etanshaul** [comment]
thanks @wimdetroyer these were super helpful. I think I _may_ have found the culprit in the logs:

```
2020-01-24 08:57:46,754 [   8738]   WARN - com.intellij.util.xmlb.Binding - no accessors for class com.google.cloud.tools.intellij.kubernetes.configs.KubeconfigFile 
2020-01-24 08:57:46,755 [   8739]   WARN - d.run.SkaffoldDevConfiguration - Error parsing saved Skaffold run configuration 
com.intellij.util.xmlb.XmlSerializationException: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.google.cloud.tools.intellij.kubernetes.configs.KubeconfigFile.<init>()
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:84)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.SkaffoldDevConfiguration.readExternal(SkaffoldRunConfigurations.kt:100)
```

We'll investigate further.

**Comment by etanshaul** [comment]
We have a theory based on the stacktrace I pasted above showing a deserialization issue with the Kubeconfig state:

At one point, we released an update to the Kubeconfig model that is persisted. It's possible that if you created a run configuration using the old version of the plugin (with the old Kubeconfig format), and then updated to the new version of the plugin, that the IDE is failing to parse the old format; and ultimately failing to deserialize any of the state. 

An easy way to confirm this is to remove all of your existing run configurations, recreate one with some state, and then test to make sure its persisted across IDE reboot.

But if that is too invasive (you don't want to delete them), you could create a new test project using our Kubernetes samples quite easily and see if the state is stored for that project (File > New Project > Cloud Code: Kubernetes).

**Comment by wimdetroyer** [comment]
@etanshaul Wouldn't surprise me if that were the case. I'll get back to you on monday.

**Comment by wimdetroyer** [comment]
@etanshaul 

Deleted all my run configurations and made a new one starting from the Run/Debug configurations dialog. Made one for one of my deployment profiles, hit apply. Exited intellij and my changes did not persist once again. I will go thru the logs myself and see if there's still an error message and upload it.

**Comment by wimdetroyer** [comment]
[idea.zip](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/4116633/idea.zip)


The FileNotFoundException and NoSuchMethodException seem interesting. I'll do a reinstall of the plug-in and get back to you.

**Comment by NickDeGraeve** [comment]
I'm a colleague of Wim.

As a workaround maybe editing the "Shared through VCS" run configuration XML by hand might work.
Is there a DTD or Schema we can take a look at to see what property goes where?

**Comment by etanshaul** [comment]
Sorry for the delay on responding. We have an open internal bug around persisting one of the complex data types in the run config (the custom kubeconfig) where it is not persisting properly. I'm not 100% sure yet, but I suspect this may be related, or perhaps leading to the issue @wimdetroyer is seeing. 

@wimdetroyer by any chance, are you using a custom kubeconfig file? It is configured in this part of the Kubernetes Run Config UI:
![image](https://user-images.githubusercontent.com/1735744/75987888-b44d8d80-5ebe-11ea-941d-541f87705db7.png)

If you do, this _might_ explain why you are seeing the issue and others' are not. Just a theory at the moment though. We will investigate.

@NickDeGraeve There is no Schema per se for these fields. They are serialized in the standard IntelliJ way into metadata (either project metadata if using `shared through VCS`, or IDE metadata otherwise). You can find the project level metadata after clicking `share through VCS` in the `.idea/runConfigurations` folder of your project. There should be an xml file with the stored values. Checking to see what is in that file is a good idea.

**Comment by wimdetroyer** [comment]
@etanshaul as seen in the first screenshot i'm using the default kubeconfig shipped with microk8s.

**Comment by matthewmichihara** [comment]
I think we've found the issue here. This should be resolved in the next IntelliJ release.

**Comment by wimdetroyer** [comment]
Great, thank you for the follow-up!

**Comment by wimdetroyer** [comment]
The issue seems to be resolved. Thanks a lot!
