### ISSUE TITLE
Cloud Code is not offering completions for some memory settings

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2695]
In a Kubernetes pod manifest file, no completions are offered for this path:
`spec.containers[].resources.{request,limit}.xxxxxx`

This also seems to occur for the JetBrains Kubernetes plugin.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container

https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/254

**Comment by etanshaul** [comment]
reduced priority.

**Comment by jmah-cc** [comment]
@matthewmichihara Was this copied to the VSCode repo, for the language server?

**Comment by matthewmichihara** [comment]
Just created
https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/254 to do
that

**Comment by matthewmichihara** [comment]
Closing as won't fix (https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/254#issuecomment-693562022
