### ISSUE TITLE
Update auto-installed skaffold version to 1.2

### ISSUE THREAD

**Issue by josteinAtProresult** [GoogleCloudPlatform/cloud-code-intellij#2696]
- Cloud Code for IntelliJ version: 20.1.1

Please update the skaffold version the plugin dependency manager installs to version 1.2.

**Reason:**
Tried to use portForward definition with address property in skaffold.yaml. This require apiVersion skaffold/v2alpha2. Needs skaffold version 1.2 for this to work.

**Comment by etanshaul** [comment]
@josteinAtProresult thanks for the request. This will come in the next release - likely today.

**Comment by etanshaul** [comment]
And just to note: if you wanted it even sooner you can always point to a local version of Skaffold by visiting Settings > Cloud Code > Kubernetes

**Comment by etanshaul** [comment]
Release `20.1.2` was just put out which should resolved this. Let us know if you have any other questions or requests.
