### ISSUE TITLE
Unable to use Kubernetes Explorer without permission to read namespaces

### ISSUE THREAD

**Issue by phueper** [GoogleCloudPlatform/cloud-code-intellij#2697]
- Cloud Code for IntelliJ version: 20.1.1
- OS: Linux, ubuntu 19.10

Trying to use Kubernetes Explorer, i have a kubeconfig file that works on the commandline, however my user does *not* have permission to read all namespaces, only allowed to use the context namespace
kubectl get namespaces resuts in:
```
Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:xxx:namespace-admin" cannot list resource "namespaces" in API group "" at the cluster scope
```
however, running `kubectl config view -o jsonpath='{.contexts[0].context.namespace}'` allows me to see my default and readable namespace

My Explorer looks like this

![image](https://user-images.githubusercontent.com/113417/73455484-74036880-4370-11ea-8187-3b595881fb4d.png)

Maybe it would be an idea to put the context namespace (if set) into the namespace list by default, so at least that namespace would be usable? 

Thanks, Pattrick

**Comment by etanshaul** [comment]
Thanks for the request @phueper . We’ll investigate and triage.

When you hover over the error in the Kubernetes explorer does it match the error from the command line? (...namespaces is forbidden...)

**Comment by phueper** [comment]
Hi @etanshaul,

yes, hovering the error icon shows the same error message as the command. (i can't seem to screenshot it ... but it is the same message)

Thanks, Pattrick

**Comment by etanshaul** [comment]
ok. great. we'll look into improving this.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2005)
