### ISSUE TITLE
Stackdriver debugger support for local gitlab instance

### ISSUE THREAD

**Issue by wwadge** [GoogleCloudPlatform/cloud-code-intellij#2703]
- Cloud Code for IntelliJ version: 20.1.3
- OS: Mac

**What did you do?**
Attempt to use stackdriver debug on a locally installed gitlab instance

**What did you expect to see?**
Same behaviour as public gitlab instance

**What did you see instead?**
Trying to launch stackdriver using a git remote pointing to a private git repo is not currently supported even though the console UI supports passing in a gitlab personal token for that same effect. No debug breakpoints are hit and , no tool window comes up. When attempting to launch, we get a warning saying this is not supported yet so take this as a feature request to provide the same support as the google cloud console UI please.

**Comment by etanshaul** [comment]
hi @wwadge thanks for the request. we'll discuss this internally and see where this fits in with our backlog.

**Comment by jmah-cc** [comment]
After triaging this, it doesn't seem to be a priority at this point. Closing for now, will re-review if more users upvote this in the future.
