### ISSUE TITLE
Plugin Change Notes for Version 20.2.1 has empty bullet points

### ISSUE THREAD

**Issue by aallbrig** [GoogleCloudPlatform/cloud-code-intellij#2719]
- Cloud Code for IntelliJ version: 20.2.1
- OS: OSX

**What did you do?**
Looked at the plugin release notes

**What did you expect to see?**
No blank bullet points

**What did you see instead?**
Blank bullet points

<img width="416" alt="Screenshot 2020-02-26 21 40 23" src="https://user-images.githubusercontent.com/3106250/75407414-f126ec80-58e0-11ea-967c-fb6b9c6b5521.png">

---

This is a very exciting plugin! I just heard about it from the Kubernetes Podcast within the past couple days. I decided to install it and play around. Currently I'm using it with `minikube`

Later, I'm planning on using it for a kubernetes pi cluster I'm writing Ansible scripts for (WIP). I wanted to let the team know about these blank bullet points to help contribute in a small way to this plugin. Cheers 🍻

**Comment by etanshaul** [comment]
thanks for reporting this @aallbrig. We'll fix it. You new project sounds cool! Let us know if you run into any issues or have feature requests.
