### ISSUE TITLE
Support setting the working directory for a Run Configuration 

### ISSUE THREAD

**Issue by dkirrane** [GoogleCloudPlatform/cloud-code-intellij#2723]
I have a IntelliJ Project with 2 different Cloud Code: Kubernetes modules.

My current Run Configuration currently has:
`<option name="skaffoldConfigurationFilePath" value="$PROJECT_DIR$/../my-project/skaffold.yaml" />`

BUT I need a way to configure the Working Directory in the Run Configuration (Similar to Spring Boot Run Configurations). e.g.:

`<option name="skaffoldConfigurationFilePath" value="$MODULE_WORKING_DIR$/skaffold.yaml" />`

**Comment by etanshaul** [comment]
hi @dkirrane trying to wrap my head around the request:

Is it that you basically want to execute skaffold from a working directory that is different from the directory where the `skaffold.yaml` lives?

**Comment by etanshaul** [comment]
@dkirrane is this still something that you need? If you could provide a bit more details (as mentioned above) that would be super helpful. If not, we'll go ahead and close this for now.

**Comment by jmah-cc** [comment]
No feedback from issue creator. Closing for now.
