### ISSUE TITLE
Cloud Code Kubernetes - Run Configuration option to enable Skaffold debug

### ISSUE THREAD

**Issue by dkirrane** [GoogleCloudPlatform/cloud-code-intellij#2724]
*Feature request*:  add an option to enable skaffold debug i.e.
`skaffold dev -v debug 2>&1`

**Comment by etanshaul** [comment]
hi @dkirrane thanks for the extremely timely request. Funny enough we were just in the middle of discussing this and have some code in review. This should be out in the next release.

**Comment by ivanporty** [comment]
@etanshaul do you recall if this is talking about enabling debug log level for Skaffold? If so, this is done and let's close it.

**Comment by ivanporty** [comment]
@dkirrane the verbosity level for Skaffold is now available via run configuration advanced settings. Let us know if it works for you!
