### ISSUE TITLE
Intellij 2020.1 - Cloud Code plugin is not generating skafold.yaml file

### ISSUE THREAD

**Issue by james-freitas** [GoogleCloudPlatform/cloud-code-intellij#2737]
Hi, my machine is an Ubuntu 18.  I have installed the Cloud Code plugin. When I go from the Tools menu, select: Cloud Code -> Kubernetes -> Add Kubernetes Support. This should automatically add a Skaffold YAML to my application and set up a few things for me so that I could deploy to my cluster by clicking a button.  But the skaffold file is not being generated.  Could you take a look please?  tkia

**Comment by ivanporty** [comment]
Hi @james-freitas! We are sorry for inconvenience, we introduced many new exciting features in the new release and could potentially change the existing things a bit.

A few clarifications would be great:
* I assume the version is the latest (released yesterday, 20.4.1)? If not, what is version?
* Did it generate configuration for your project before, with older versions?
* Do you have a Dockerfile? Or Jib?

**Comment by ivanporty** [comment]
Lowering priority since we confirmed generation of skaffold.yaml is working unless you have both Jib and Dockerfile. Waiting for further information.

**Comment by james-freitas** [comment]
Hi @ivanporty !    After updating to the version 20.4.2 the problem was solved. Thank you for your return.  You can close this issue.
