### ISSUE TITLE
Error when starting run config after upgrade to 20.4.1

### ISSUE THREAD

**Issue by josteinAtProresult** [GoogleCloudPlatform/cloud-code-intellij#2738]
- Cloud Code for IntelliJ version: 20.4.1
- OS: Windows 10

**What did you do?** Upgrade cloud code plugin 20.2.1 => 20.4.1

**Problem:**
When starting a cloud code run config after upgrade to 20.4.1 Intellij immediatly fails with following error message in event log:

**Error running '&lt;run config name&gt;': org/jetbrains/plugins/gradle/settings/GradleSettings**

Attached file is Intellij log from restart after plugin install.

[intellij-cloud-code-plugin.log.txt](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/4475185/intellij-cloud-code-plugin.log.txt)

Downgrading to version 20.1.2 resolves the issue.

**Comment by etanshaul** [comment]
Thanks for reporting. Was that the full error message? Could you provide a screenshot by any chance?

Also what version of the IDE are you on?

**Comment by josteinAtProresult** [comment]
That is the full error message, yes. In the event log. The run window does not appear.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/49986790/79225760-7e0c1200-7e5d-11ea-9841-00c7f6c0507b.png)

Intellij Ultimate version 2020.1 Was on version 2019.3.4 when it failed the first time. Tried upgrading Intellij but  that did not help.

**Comment by etanshaul** [comment]
Thanks. We’ll investigate and include a fix in our upcoming follow up patch release.

**Comment by etanshaul** [comment]
hi @josteinAtProresult one more question:

when you go to the plugin page, and search for "Gradle", do you see the plugins installed:

<img width="361" alt="Screen Shot 2020-04-14 at 8 56 04 AM" src="https://user-images.githubusercontent.com/1735744/79227430-ddeac480-7e2d-11ea-8cb6-40cb2ab93462.png">

**Comment by josteinAtProresult** [comment]
Yes, they are both installed and enabled. I believe that is also indicated (with version numbers) in the log file I attached.

I tried disabling them also to see if that had any effect, but it did not as far as I could tell.

**Comment by etanshaul** [comment]
I think I may have a fix for this. There was a mistake in the way we were optionally importing modules dependent on Gradle.

Although I am still a bit confused as I would have expected this error to occur when the Gradle plugin is _not_ installed. Yet you are clearly getting it even when it is installed.

In any case, once I have one ready, would you be will to try out a pre-release build to see if it fixes the issue? Thanks in advance for helping us diagnose this.

**Comment by josteinAtProresult** [comment]
Yes, I should be able to test the pre-release. Just let me know when it's available.

**Comment by etanshaul** [comment]
hi @josteinAtProresult 

I have a prerelease for you to try:

- you can either download it directly from here and install it using Plugin settings > Install plugin from disk: https://plugins.jetbrains.com/plugin/8079-cloud-code/update/83611
- or you can go to plugin settings > manage plugin repositories, and add this URL: `https://plugins.jetbrains.com/plugins/alpha/8079`, then search for Cloud Code (you may have to first uninstall your existing version.

You should then see version `20.4.2-RC0.1` installed:
<img width="177" alt="Screen Shot 2020-04-14 at 9 52 14 AM" src="https://user-images.githubusercontent.com/1735744/79232810-fe1e8180-7e35-11ea-960c-096156d03521.png">

Let me know if this resolves the issue! We'll then do some final validation and put out a patch release together with some other fixes.

**Comment by josteinAtProresult** [comment]
Hi @etanshaul 

I can confirm that the 20.4.2-RC0.1 fixes my issue.

Thank you for the quick response!

**Comment by etanshaul** [comment]
great! expect a new patch release `20.4.2` either later today or tomorrow. Thank you for your help here.

**Comment by etanshaul** [comment]
hi @josteinAtProresult just an update that we released Cloud Code version `20.4.2` containing this fix.

Will close the issue, but don't hesitate to reach out or open issues.
