### ISSUE TITLE
Wrong font style for links in Darcula theme

### ISSUE THREAD

**Issue by pahan35** [GoogleCloudPlatform/cloud-code-intellij#2739]
- Cloud Code for IntelliJ version: 20.4.1
- OS: Mac OS Catalina 10.15.14

**What did you do?**
View Welcome screen in Darcula theme

**What did you expect to see?**
I expect to see link in Darcula style like in terminal

**What did you see instead?**
Links have light theme color and it's hard to read them

![image](https://user-images.githubusercontent.com/13823215/79254353-4917b380-7e8d-11ea-88e6-146844c34c63.png)

**Comment by ivanporty** [comment]
Thanks @pahan35 for your suggestion, we will improve our rendering there, and let us know if you have any other suggestion and feedback for the plugin, we are always here to help and listen!

**Comment by etanshaul** [comment]
@matthewmichihara this is fixed right?

(will be out in the next release of Cloud Code)

**Comment by matthewmichihara** [comment]
Fixed, closing.
