### ISSUE TITLE
Goland 2020.1 - Cloud Code Plugin Not Attaching Debugger to Service

### ISSUE THREAD

**Issue by miwasyk-gr8** [GoogleCloudPlatform/cloud-code-intellij#2740]
- Cloud Code for Goland version: 20.4.2
- OS: Windows 10

I ran Develop On Kuebernetes in debug mode with my service-based application.

I expect the debugger for my go application to be attached and events to be captured within the debugger.

The debugger was not started and it looks like it is having trouble finding a file. The live manifest for my pod looks correct as dlv and all the go install tools are there. I saw the command with args:
```
    - /dbg/go/bin/dlv
    - exec
    - --headless
    - --continue
    - --accept-multiclient
    - --listen=localhost:56268
    - --api-version=2
    - /server
``` 

but get the error message:
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

Note that I am able to run /server without the debug mode so I'm wondering why I'm getting this message.

If you need any more details let me know.

**Comment by etanshaul** [comment]
hi @miwasyk-gr8 thanks for the issue. One initial thing that might help us is to provide the verbose debug-level output of the attempt:

In the `Develop on Kubernetes` Run Config, near the bottom, change `Verbosity` to `DEBUG`:
<img width="813" alt="Screen Shot 2020-04-16 at 9 49 59 AM" src="https://user-images.githubusercontent.com/1735744/79464159-b92a5480-7fc7-11ea-94de-63586f6a4b36.png">

Then right the session in debug mode again and if you could provide the output that would be great. Note: this `verbosity` setting is available in Cloud Code version 20.4.1 or higher.

Also, are you able to show what your Dockerfile looks like?

**Comment by miwasyk-gr8** [comment]
> hi @miwasyk-gr8 thanks for the issue. One initial thing that might help us is to provide the verbose debug-level output of the attempt:
> 
> In the `Develop on Kubernetes` Run Config, near the bottom, change `Verbosity` to `DEBUG`:
> <img alt="Screen Shot 2020-04-16 at 9 49 59 AM" width="813" src="https://user-images.githubusercontent.com/1735744/79464159-b92a5480-7fc7-11ea-94de-63586f6a4b36.png">
> 
> Then run the session in debug mode again and if you could provide the output that would be great. Note: this `verbosity` setting is available in Cloud Code version 20.4.1 or higher.
> 
> Also, are you able to show what your Dockerfile looks like?

I attached my debug log run of skaffold. I also attached my DockerFile. Let me know of any other questions.
[skaffold_debug_log.txt](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/4488213/skaffold_debug_log.txt)

[DockerFile.txt](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/4488214/DockerFile.txt)

**Comment by etanshaul** [comment]
hi @miwasyk-gr8 those details were very helpful.

We think the root of the issue here is the multi-stage docker build; specifically, the final `FROM scratch` phase. `dlv` currently cannot be run standalone and requires some libraries to be present. Could you try changing as follows:

`FROM scratch`
to
`FROM gcr.io/distroless/base`

**Comment by miwasyk-gr8** [comment]
> FROM gcr.io/distroless/base

That worked! Thank you. Is there any timeline of supporting scratch and alpine in the future as I will proably have to make a separate DockerFile for this? Unless there is a specific way I can tell skaffold to run with a specific dockerfile for debugging.

**Comment by etanshaul** [comment]
Great!

@briandealwis should be able to provide more details on this.

**Comment by etanshaul** [comment]
@miwasyk-gr8 we are tracking the work to improve this here: https://github.com/GoogleContainerTools/container-debug-support/pull/35

That should help with your use-case.

Closing this bug for now, but will update once it is ready to try out.

**Comment by briandealwis** [comment]
@miwasyk-gr8 we've committed the fix (GoogleContainerTools/container-debug-support#35) and the debug images have been updated.  Please give it a try again.

**Comment by miwasyk-gr8** [comment]
> @miwasyk-gr8 we've committed the fix ([GoogleContainerTools/container-debug-support#35](https://github.com/GoogleContainerTools/container-debug-support/pull/35)) and the debug images have been updated. Please give it a try again.

Thank you! It works for us now without needing to change the image. The only line we had to add to our DockerFile was the

` ENV GOTRACEBACK=single`

 line for self-identification.
