### ISSUE TITLE
Error running 'Develop on Kubernetes': Non-null value 'clusters' was null at $.clusters

### ISSUE THREAD

**Issue by james-freitas** [GoogleCloudPlatform/cloud-code-intellij#2744]
Hi, here are the version of the tools I am using:
- Cloud Code for IntelliJ version: 20.4.2
- Google Cloud SDK version: 289.0.0
- About my OS
```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**What did you do?**
I am following this tutorial:  https://www.infoq.com/articles/spring-boot-tutorial/?utm_campaign=infoq_content&utm_source=infoq&utm_medium=feed&utm_term=Java

I am in the step when I click on the **Develop on Kubernets** play button.  

**What did you expect to see?**
My expectation according to the tutorial: 
> Cloud Code will build the app, create the image, deploy the application to your GKE cluster and stream the logs from Stackdriver into your local machine.

**What did you see instead?**
When I do that I get this error:
```bash
Error running 'Develop on Kubernetes': Non-null value 'clusters' was null at $.clusters
```
Here are some images:

![image](https://user-images.githubusercontent.com/4712453/79643123-c0906000-8177-11ea-8075-e0bb6d103e24.png)

![image](https://user-images.githubusercontent.com/4712453/79643144-eb7ab400-8177-11ea-8751-ee8c24c8cb11.png)

![image](https://user-images.githubusercontent.com/4712453/79643149-f897a300-8177-11ea-8fef-e4f7f6420280.png)

Thanks in advance,
James

**Comment by ivanporty** [comment]
Thanks for your report @james-freitas! It looks like you don't have a Kubernetes cluster configured - it is required for deployments. What do you see in the Kubernetes explorer (tool window, available on the right side of the IDE window)? In case you don't have any Kubernetes clusters, you could install either Minikube or Docker for Desktop local clusters, and try again. Your deployments will then appear in the Kubernetes explorer as well.

**Comment by ivanporty** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1774)

**Comment by james-freitas** [comment]
Hi @ivanporty !!  

My Kubernetes Explorer windows shows an exclamation symbol next to "Cluster Explorer"
I already have **Minikube** installed.  Before I do those steps I need to start minikube in command line?

![image](https://user-images.githubusercontent.com/4712453/79821524-61903e00-8365-11ea-85ef-43b5dddc954a.png)

**Comment by james-freitas** [comment]
Issue solved, so I am closing it.
