### ISSUE TITLE
unable to run with Cloud Code: Kubernetes

### ISSUE THREAD

**Issue by coolyrat** [GoogleCloudPlatform/cloud-code-intellij#2747]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- OS: MacOS
- IDE: GoLand
- K8s: Local docker-desktop

![image](https://user-images.githubusercontent.com/1881159/79829624-22e69c00-83d6-11ea-91c3-6a340988e176.png)

**What did you do?**
Run/Debug Cloud Code: Kubernetes

**What did you expect to see?**
up and running

**What did you see instead?**
```
time="2020-04-21T13:35:12+08:00" level=fatal msg="exiting dev mode because first deploy failed: reading manifests: kubectl create: running [kubectl --context docker-desktop create --dry-run -oyaml -f $GOPATH/dir/skaffold-test/k8s-deployment.yaml]\n - stdout: \n - stderr: \"Unable to connect to the server: EOF\\n\": exit status 1"
```
[full log](https://gist.github.com/coolyrat/f95ef161d6f7fd5bc98a30596a9aafb6)

(screenshots are helpful)
![image](https://user-images.githubusercontent.com/1881159/79829778-91c3f500-83d6-11ea-80a0-942b6201102c.png)

It works fine if I execute skaffold debug in the terminal.

**Comment by etanshaul** [comment]
Hi @coolyrat 

What happens if you run ‘kubectl get all’ from the command line?

Also could please you show a screenshot of the settings page: Cloud Code > Kubernetes ?

**Comment by coolyrat** [comment]
Hi @etanshaul 

![image](https://user-images.githubusercontent.com/1881159/79876086-2b15fa00-841d-11ea-9552-15338d306303.png)

![image](https://user-images.githubusercontent.com/1881159/79876600-d58e1d00-841d-11ea-8d34-a9d79c3f59cb.png)

**Comment by etanshaul** [comment]
thanks! This was actually the settings page I was after (just trying to see the versions of `kubectl` that the plugin is using):

Its under Settings > Cloud Code > Kubernetes

<img width="884" alt="Screen Shot 2020-04-21 at 10 18 31 AM" src="https://user-images.githubusercontent.com/1735744/79876842-8b735000-83b9-11ea-822d-c1b72601bc58.png">

**Comment by coolyrat** [comment]
![image](https://user-images.githubusercontent.com/1881159/79877554-f145f300-841e-11ea-9a3d-de72ae3e2037.png)

![image](https://user-images.githubusercontent.com/1881159/79877580-facf5b00-841e-11ea-8474-9f73778454c7.png)

**Comment by coolyrat** [comment]
![image](https://user-images.githubusercontent.com/1881159/79878021-83e69200-841f-11ea-991f-4da81acd4b74.png)

@etanshaul I tried your config, but still not working

**Comment by coolyrat** [comment]
Yes and no. I need to add this flag `--status-check=false`, [please see](https://github.com/GoogleContainerTools/skaffold/issues/3934)

![image](https://user-images.githubusercontent.com/1881159/79879336-22bfbe00-8421-11ea-8b4e-bc15a9b541d0.png)

**Comment by etanshaul** [comment]
Interesting. Why are you disabling the status check?

If you run `/usr/local/bin/skaffold debug --filename skaffold.yaml --label ide=GoLand --label ideVersion=2020.1.0.0 --label ijPluginVersion=unknown --rpc-port 50053 --port-forward=true --status-check=true --enable-rpc=true --verbosity trace` 

from the command line, what is the output? does it match the IDE in that case?

Sorry if you covered that already - I'm just trying to establish if it is a skaffold issue vs a Cloud Code issue to help us hone in on the problem.

**Comment by coolyrat** [comment]
running in the terminal works fine. But with the status check equals to true, there is some repeated output... [see the full output](https://gist.github.com/coolyrat/eec39bcacece7b67e88276dc6197ecde)

**Comment by etanshaul** [comment]
odd indeed!

One more question: does the Kubernetes explorer in Cloud Code work for you? E.g. after you successfully deploy your app from the command line, can you dig into the cluster and see the pods from the explorer? e.g. (note, I don't have any pods running in this screenshot):

<img width="480" alt="Screen Shot 2020-04-21 at 10 55 53 AM" src="https://user-images.githubusercontent.com/1735744/79881006-b6ac6e00-83be-11ea-8b46-4a1ac7ecd07c.png">

**Comment by coolyrat** [comment]
nope, it used to work though. 

![image](https://user-images.githubusercontent.com/1881159/79881296-995dbb00-8423-11ea-9e9b-28ac5dc07d46.png)

**Comment by coolyrat** [comment]
I have the newest version docker for mac.

![image](https://user-images.githubusercontent.com/1881159/79881470-cf9b3a80-8423-11ea-95ed-8705f7f60fdf.png)

**Comment by etanshaul** [comment]
if you hover over the `!` in the k8s explorer it should give you some more info on the error. could you please share that? thanks again.

**Comment by coolyrat** [comment]
![image](https://user-images.githubusercontent.com/1881159/79881641-0d985e80-8424-11ea-9562-77c26a2d77de.png)

**Comment by etanshaul** [comment]
thanks. we'll get back to you. I'm not immediately sure why `kubectl` from the IDE is failing (when it works from the terminal).  @ivanporty any ideas? this happens both when using custom deps as well as deps from the PATH.

**Comment by coolyrat** [comment]
OK, thanks for helping btw =)

**Comment by coolyrat** [comment]
@etanshaul any updates?

**Comment by briandealwis** [comment]
@coolyrat Is it possible you have a different kubectl on your `PATH`?

If you're using `bash`, please report back on `type -a kubectl` and `type -a skaffold`.

Also, how are you starting IntelliJ?  If you're launching the app from the desktop vs from the command-line, could you try the opposite?  Your PATH from the command-line may be different from that inherited from the desktop.

**Comment by briandealwis** [comment]
Also, @coolrat, could you please report back on your `KUBECONFIG` environment variable, and the result of `kubectl config get-contexts`?

It really feels like you're executing from a different context from the command-line.

**Comment by briandealwis** [comment]
Also, @coolrat, could you please report back on your `KUBECONFIG` environment variable, and the result of `kubectl config get-contexts`?  It really feels like you are running under a different configuration on the command-line.

Did CloudCode ever work for you?

**Comment by etanshaul** [comment]
@coolyrat to add to what @briandealwis said. He’s theory that you are using a non-default kubeconfig sounds quite plausible.

If this is the case, you can point to alternative kubeconfig files by going into settings > Cloud Code > Kubernetes. There is a UI to select your kubeconfig file. There is also a UI directly from the Kubernetes explorer to do this as well.

**Comment by coolyrat** [comment]
Hi @briandealwis 

> please report back on type -a kubectl and type -a skaffold.

```
~/.kube » type -a kubectl
kubectl is /usr/local/bin/kubectl
kubectl is /usr/local/bin/kubectl

~/.kube » type -a skaffold
skaffold is /usr/local/bin/skaffold
skaffold is /usr/local/bin/skaffold
```
> Also, how are you starting IntelliJ? If you're launching the app from the desktop vs from the command-line, could you try the opposite? Your PATH from the command-line may be different from that inherited from the desktop.

I launch it from the desktop.

> could you please report back on your KUBECONFIG environment variable, and the result of kubectl config get-contexts

```
~/.kube » echo $KUBECONFIG


~/.kube » kubectl config get-contexts
CURRENT   NAME                         CLUSTER                      AUTHINFO             NAMESPACE
          cnc-kubernetes-admin         cnc-kubernetes               kubernetes-admin     gloo-system
*         docker-desktop               docker-desktop               docker-desktop       hrmsv3
          xiao-k8s-uat                 xiao-k8s-uat                 xiao-k8s-uat         hrmsv3
          xiao-serverless-kubernetes   xiao-serverless-kubernetes   201351173553217959   hrms-demo
```

> Did CloudCode ever work for you?

Yes. It used to work from the previous version.

**Comment by coolyrat** [comment]
Hi @etanshaul 

> @coolyrat to add to what @briandealwis said. His theory that you are using a non-default kubeconfig sounds quite plausible.
> 
> If this is the case, you can point to alternative kubeconfig files by going into settings > Cloud Code > Kubernetes. There is a UI to select your kubeconfig file. There is also a UI directly from the Kubernetes explorer to do this as well.
> 
> We don’t yet auto detect changes configured via env vars for kubeconfig settings, but have an open enhancement issue tracking this.

![image](https://user-images.githubusercontent.com/1881159/80329526-35008880-8875-11ea-9ae3-78349bf1f93b.png)

![image](https://user-images.githubusercontent.com/1881159/80329475-08e50780-8875-11ea-8190-e72c27d3f6d6.png)

**Comment by etanshaul** [comment]
@coolyrat I'm a bit at a loss as to what is going on.

Would you mind trying the previous version before our recent large release and confirming that it starts working upon downgrading?

The version to try is `20.2.1`, you can get it by visiting this page: https://plugins.jetbrains.com/plugin/8079-cloud-code/versions and downloading `20.2.1`.

Then, in the IDE's plugin settings you can select`Install plugin from disk..` and select the zip:
<img width="300" alt="Screen Shot 2020-04-27 at 11 25 06 AM" src="https://user-images.githubusercontent.com/1735744/80389951-c8d45380-8879-11ea-966e-44e8fae27279.png">

This will help us narrow it down a bit. Thanks.

**Comment by coolyrat** [comment]
> @coolyrat I'm a bit at a loss as to what is going on.
> 
> Would you mind trying the previous version before our recent large release and confirming that it starts working upon downgrading?
> 
> The version to try is `20.2.1`, you can get it by visiting this page: https://plugins.jetbrains.com/plugin/8079-cloud-code/versions and downloading `20.2.1`.
> 
> Then, in the IDE's plugin settings you can select`Install plugin from disk..` and select the zip:
> <img alt="Screen Shot 2020-04-27 at 11 25 06 AM" width="300" src="https://user-images.githubusercontent.com/1735744/80389951-c8d45380-8879-11ea-966e-44e8fae27279.png">
> 
> This will help us narrow it down a bit. Thanks.

It works.
![image](https://user-images.githubusercontent.com/1881159/80394402-66fd0380-88e4-11ea-9699-d0ee4bc0a715.png)

**Comment by coolyrat** [comment]
but for the version `20.2.1`, run with debugging also not working.


![image](https://user-images.githubusercontent.com/1881159/80395481-da534500-88e5-11ea-990d-02bd8243928e.png)

wait around 1min, delve started, but keep retrying something

![image](https://user-images.githubusercontent.com/1881159/80395603-0b337a00-88e6-11ea-9a2e-b0db0741546e.png)

**Comment by fsladkey** [comment]
Hey @coolyrat thanks for confirming that!

One thing we introduced in the last release that could be causing your problem is that `kubectl` commands now honor proxy settings in IntelliJ. Could you let us know if you have a proxy set up in `Settings -> Appearance & Behavior -> System Settings -> HTTP Proxy`? Also, if possible, you could try temporarily disabling the proxy see how the behavior changes.

Thanks!

**Comment by coolyrat** [comment]
@fsladkey I think that's why. I am using a proxy, I will disable it and give it a try.

**Comment by coolyrat** [comment]
@fsladkey I think that's why. I am using a proxy, I will disable it and give it a try.

**Comment by coolyrat** [comment]
@fsladkey it works! But the retrying problem is still not solved

![image](https://user-images.githubusercontent.com/1881159/80396221-ec81b300-88e6-11ea-96cf-726aa2e9eacd.png)

**Comment by etanshaul** [comment]
this latest error is related to issues with `skaffold debug`, @briandealwis fyi. See this comment as well:
https://github.com/GoogleContainerTools/container-debug-support/pull/36#issuecomment-619615025

I'm glad at least we got past the `kubectl` / proxy issue!

**Comment by coolyrat** [comment]
@fsladkey Is there a way to take control of the proxy setting? I need to use a proxy to download dependency, so I can't really disable it. Is there a way to make them both happy?

**Comment by fsladkey** [comment]
Hey @coolyrat. You should be able to override the proxy related environment variables in the skaffold run configuration. Go to advanced settings in the run configuration and add both `http_proxy` and `https_proxy` but leave the values blank. It should look like this

![Screen Shot 2020-04-29 at 11 00 57 AM](https://user-images.githubusercontent.com/12353283/80611744-04e9ee80-8a09-11ea-8dae-04ac384a54fd.png)

Unfortunately, this will not solve the problem for the Kubernetes explorer, but will hopefully unblock you for now! Let me know if that helps.

**Comment by coolyrat** [comment]
@fsladkey Yes, it works. 

Thank you all, problem solved.
