### ISSUE TITLE
google cloud storage bucket listing is slow if has many bucket

### ISSUE THREAD

**Issue by kamarton** [GoogleCloudPlatform/cloud-code-intellij#2751]
- Cloud Code for IntelliJ version: 20.4.2
- Google Cloud SDK version: 290.0.0
- OS: Linux 4.15.0-96-generic

**What did you do?**

Listing buckets

**What did you expect to see?**

Loading first page, and show immediately

**What did you see instead?**

Load all, and show list.

**Additional note**

Used project contains more than 5000 buckets.

**Comment by etanshaul** [comment]
thanks @kamarton that is a lot of buckets indeed.

Just to get a feel - how long did it take to load for you?

**Comment by kamarton** [comment]
> how long did it take to load for you?

~30-50sec. It may depend quite on the network you are using. Basically, for me, the first page would be enough for the most part (e.g. the first 50 buckets).

**Comment by etanshaul** [comment]
got it. thanks.

**Comment by kamarton** [comment]
I will pick up a separate issue if necessary, but there is a similar problem with listing the contents of the bucket. For example, if i have a bucket that contains 1 million objects (or 100 million), then loading it at once, even though most likely 99.999% (and more) of the object information will not be used.

For better usability, I recommend the solution used in the GCP console (bucket and object listing):
- load only the first page with limited results (e.g. max results 100)
- load more at the end of the loaded list (scroll down)
- search by prefix, this also allows you to specify a specific item

**Comment by etanshaul** [comment]
apologies for the delay. closing for now as we have higher priority items we are working. Feel free to reply with additional questions (and any other users welcome to upvote this to help influence our priorities).
