### ISSUE TITLE
Cloud Code prevents IntelliJ from importing composite projects with more than one buildSrc

### ISSUE THREAD

**Issue by AlexCzar** [GoogleCloudPlatform/cloud-code-intellij#2756]
- Cloud Code for IntelliJ version: 20.4.3
- OS: OpenSUSE Tumbleweed

**What did you do?**
Opened gradle composite project, several comprising projects of which contain `buildSrc` sub-projects.

**What did you expect to see?**
Composite project should be fully imported and indexed

**What did you see instead?**
Only some modules get displayed in Project window and following error is shown in intellij log:
[error.log](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/4580032/error.log)

**Repro project**
https://github.com/AlexCzar/double-build-src-cloud-code-repro

**Comment by etanshaul** [comment]
thanks @AlexCzar for reporting. the repro project should be extremely useful. We'll investigate this.

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1830)

**Comment by etanshaul** [comment]
@AlexCzar I am able to reproduce this quite easily thanks to your sample project. 

We should be able to get in a fix in the next release (basically need to dedup module names).

**Comment by etanshaul** [comment]
After the fix (locally - not yet released), the project resolves as follows:

<img width="693" alt="Screen Shot 2020-05-05 at 11 42 39 AM" src="https://user-images.githubusercontent.com/1735744/81085725-97850480-8ec5-11ea-9a5f-afafdee20565.png">

**Comment by etanshaul** [comment]
@AlexCzar a fix for this was merged in and will be available in our next release towards the end of the month. 

If this is blocking your workflow you can grab a nightly build (tomorrow after the build runs) by following these instructions:
https://github.com/GoogleCloudPlatform/cloud-code-intellij#installation
(adding this URL to the plugin settings: https://plugins.jetbrains.com/plugins/nightly/8079)

**Comment by AlexCzar** [comment]
@etanshaul This is much appreciated. Thanks a lot!

**Comment by etanshaul** [comment]
hi @AlexCzar just an update that we released Cloud Code version `20.5.1` yesterday with a fix for this. Closing for now, but feel free to reopen if you run into any trouble. Thanks.
