### ISSUE TITLE
JAVA_TOOL_OPTION not being set by Cloud Code 

### ISSUE THREAD

**Issue by odavidlara** [GoogleCloudPlatform/cloud-code-intellij#2760]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version:
- OS: Mac OS Catalina 10.15.4

**What did you do?**
Set up a project with Skaffold, installed the cloud-code extension on Intellij
This is a Spring boot service and I'm able to run it without any issues, it's just that I'm unable to debug it 

**What did you expect to see?**
Being able to debug my service

**What did you see instead?**
It runs just fine, but it doesn't start the debug session, I noticed that the JAVA_TOOL_OPTION is not being set up, so the debug port (default 5005) is never forwarded, just the basic ports of the service.

**Comment by ivanporty** [comment]
Thanks for your report, @odavidlara! How do you debug your service exactly, did you choose `Debug` option for `Developer on Kubernetes` run configuration?

**Comment by odavidlara** [comment]
Hi @ivanporty Yes, I choose that one. And it is weird I was making tests adding the JAVA_TOOL_OPTIONS env var myself in Kubernetes configuration, and it works in VS Code (cloud code extension) but not in IntelliJ, in IntelliJ it doesn't forward the port 50005 and I don't see the env var within the container

**Comment by etanshaul** [comment]
@odavidlara to help us diagnose, do you think you could rerun the debug session with `DEBUG` level verbosity and share the output? To do this, in the run config set the following:
<img width="702" alt="Screen Shot 2020-05-08 at 11 15 56 AM" src="https://user-images.githubusercontent.com/1735744/81420079-60a92b80-911d-11ea-9af6-891ca8fb2680.png">

**Comment by odavidlara** [comment]
Sure 

`time="2020-05-08T08:20:11-07:00" level=info msg="starting gRPC server on port 50051"
time="2020-05-08T08:20:11-07:00" level=info msg="starting gRPC HTTP server on port 50052"
time="2020-05-08T08:20:11-07:00" level=info msg="Skaffold &{Version:v1.7.0 ConfigVersion:skaffold/v2beta1 GitVersion: GitCommit:145f59579470eb1f0a7f40d8e0924f8716c6f05b GitTreeState:clean BuildDate:2020-04-02T21:49:58Z GoVersion:go1.14 Compiler:gc Platform:darwin/amd64}"
time="2020-05-08T08:20:11-07:00" level=debug msg="Update check not enabled, skipping."
time="2020-05-08T08:20:11-07:00" level=debug msg="config version (skaffold/v2alpha3) out of date: upgrading to latest (skaffold/v2beta1)"
time="2020-05-08T08:20:11-07:00" level=debug msg="Defaulting build type to local build"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct SkaffoldConfig"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct Metadata"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct Pipeline"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct BuildConfig"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct Artifact"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct ArtifactType"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct DockerArtifact"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct TagPolicy"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct GitTagger"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct BuildType"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct LocalBuild"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct DeployConfig"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct DeployType"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct KubectlDeploy"
time="2020-05-08T08:20:11-07:00" level=debug msg="validating yamltags of struct KubectlFlags"
time="2020-05-08T08:20:11-07:00" level=info msg="Using kubectl context: docker-desktop"
time="2020-05-08T08:20:11-07:00" level=debug msg="Using builder: local"
time="2020-05-08T08:20:11-07:00" level=debug msg="setting Docker user agent to skaffold-v1.7.0"
time="2020-05-08T08:20:11-07:00" level=debug msg="push value not present, defaulting to false because localCluster is true"
time="2020-05-08T08:20:11-07:00" level=info msg="List generated in 47.604µs"
time="2020-05-08T08:20:11-07:00" level=debug msg="Running command: [git describe --tags --always]"
Listing files to watch...
Generating tags...
 - oddlara/v2-services -> time="2020-05-08T08:20:11-07:00" level=debug msg="Command output: [v3.36.0_20200331_1585674539-125-g1cda6a05\n]"
time="2020-05-08T08:20:11-07:00" level=debug msg="Running command: [git status . --porcelain]"
oddlara/v2-services:v3.36.0_20200331_1585674539-125-g1cda6a05-dirty
Checking cache...
time="2020-05-08T08:20:11-07:00" level=debug msg="Command output: [ M Dockerfile\n M deploy/development.yaml\n M docker/start-app.sh\n M skaffold.yaml\n M src/main/java/com/ibm/esil/es/tss/resource/RequestGridResource.java\n M src/main/resources/application.properties\n]"
time="2020-05-08T08:20:11-07:00" level=info msg="Tags generated in 43.367474ms"
time="2020-05-08T08:20:11-07:00" level=debug msg="Found dependencies for dockerfile: [{resources /resources true} {build/libs/v2-services.jar /app.jar false} {docker/start-app.sh /start-app.sh false}]"
 - oddlara/v2-services: Found Locally
Tags used in deployment:
 - oddlara/v2-servicess -> oddlara/v2-services:d0d5e963668a27ebc084ba65bdcfebfe44f8208d21bfd78867ac51935055514c
   local images can't be referenced by digest. They are tagged and referenced by a unique ID instead
Starting deploy...
time="2020-05-08T08:20:11-07:00" level=info msg="Cache check complete in 225.873004ms"
time="2020-05-08T08:20:11-07:00" level=debug msg="Running command: [kubectl version --client -ojson]"
time="2020-05-08T08:20:11-07:00" level=debug msg="Command output: [{\n  \"clientVersion\": {\n    \"major\": \"1\",\n    \"minor\": \"17\",\n    \"gitVersion\": \"v1.17.0\",\n    \"gitCommit\": \"70132b0f130acc0bed193d9ba59dd186f0e634cf\",\n    \"gitTreeState\": \"clean\",\n    \"buildDate\": \"2019-12-07T21:20:10Z\",\n    \"goVersion\": \"go1.13.4\",\n    \"compiler\": \"gc\",\n    \"platform\": \"darwin/amd64\"\n  }\n}\n]"
time="2020-05-08T08:20:11-07:00" level=debug msg="Running command: [kubectl --context docker-desktop create --dry-run -oyaml -f /Users/davidlara/dev/projects/services/v2-services/deploy/development.yaml]"
time="2020-05-08T08:20:12-07:00" level=debug msg="Command output: [apiVersion: v1\nkind: Service\nmetadata:\n  labels:\n    app: v2-services\n  name: v2-services\n  namespace: default\nspec:\n  ports:\n  - name: http\n    port: 8080\n    protocol: TCP\n    targetPort: 8080\n  selector:\n    app: v2-services\n  type: ClusterIP\n---\napiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  labels:\n    app: v2-servicess\n  name: v2-services\n  namespace: default\nspec:\n  minReadySeconds: 60\n  replicas: 1\n  revisionHistoryLimit: 10\n  selector:\n    matchLabels:\n      app: v2-services\n  strategy:\n    rollingUpdate:\n      maxSurge: 25%\n      maxUnavailable: 25%\n    type: RollingUpdate\n  template:\n    metadata:\n      labels:\n        app: v2-services\n      name: v2-services\n    spec:\n      containers:\n
        image: oddlara/v2-services:latest\n        imagePullPolicy: IfNotPresent\n        name: v2-services\n        ports:\n        - containerPort: 8080\n        resources:\n          limits:\n            cpu: 1512m\n            memory: 1512Mi\n          requests:\n            cpu: 500m\n            memory: 1024Mi\n        volumeMounts:\n        - mountPath: /resources/truststores/\n          name: es-db2-trust-store\n      imagePullSecrets:\n      - name: regsecret\n      volumes:\n      - name: es-db2-trust-store\n        secret:\n          secretName: es-db2-trust-store\n]"
time="2020-05-08T08:20:12-07:00" level=debug msg="manifests with tagged images: apiVersion: v1\nkind: Service\nmetadata:\n  labels:\n    app: v2-services\n  name: ev2-services\n  namespace: default\nspec:\n  ports:\n  - name: http\n    port: 8080\n    protocol: TCP\n    targetPort: 8080\n  selector:\n    app: v2-services\n  type: ClusterIP\n---\napiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  labels:\n    app: v2-services\n  name: v2-services\n  namespace: default\nspec:\n  minReadySeconds: 60\n  replicas: 1\n  revisionHistoryLimit: 10\n  selector:\n    matchLabels:\n      app: v2-services\n  strategy:\n    rollingUpdate:\n      maxSurge: 25%\n      maxUnavailable: 25%\n    type: RollingUpdate\n  template:\n    metadata:\n      labels:\n        app: v2-services\n      name: v2-services\n    spec:\n      containers:\n      - envFrom:\n        - configMapRef:\n            name: hosts\n        - configMapRef:\n            name: v2-services\n        - secretRef:\n            name: database\n        image: oddlara/v2-services:d0d5e963668a27ebc084ba65bdcfebfe44f8208d21bfd78867ac51935055514c\n        imagePullPolicy: IfNotPresent\n        name: v2-services\n        ports:\n        - containerPort: 8080\n        resources:\n          limits:\n            cpu: 1512m\n            memory: 1512Mi\n          requests:\n            cpu: 500m\n            memory: 1024Mi\n 
time="2020-05-08T08:20:12-07:00" level=debug msg="no debug transformation for: service/v2-services"
time="2020-05-08T08:20:12-07:00" level=debug msg="no debug transformation for: deployment.extensions/v2-services"
time="2020-05-08T08:20:12-07:00" level=debug msg="manifests with labels apiVersion: v1\nkind: Service\nmetadata:\n  labels:\n    app: v2-services\n    app.kubernetes.io/managed-by: skaffold-v1.7.0\n    ide: Idea\n    ideVersion: 2020.1.1.0.0\n    ijPluginVersion: unknown\n    skaffold.dev/builder: local\n    skaffold.dev/cleanup: \"true\"\n    skaffold.dev/deployer: kubectl\n    skaffold.dev/docker-api-version: \"1.40\"\n    skaffold.dev/run-id: 75f57ed2-6ecb-4073-aa49-bf8ae7f590f4\n    skaffold.dev/tag-policy: git-commit\n    skaffold.dev/tail: \"true\"\n  name: v2-services\n  namespace: default\nspec:\n  ports:\n  - name: http\n    port: 8080\n    protocol: TCP\n    targetPort: 8080\n  selector:\n    app: v2-services\n  type: ClusterIP\n---\napiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  labels:\n    app: v2-services\n    app.kubernetes.io/managed-by: skaffold-v1.7.0\n    ide: Idea\n    ideVersion: 2020.1.1.0.0\n    ijPluginVersion: unknown\n    skaffold.dev/builder: local\n    skaffold.dev/cleanup: \"true\"\n    skaffold.dev/deployer: kubectl\n    skaffold.dev/docker-api-version: \"1.40\"\n    skaffold.dev/run-id: 75f57ed2-6ecb-4073-aa49-bf8ae7f590f4\n    skaffold.dev/tag-policy: git-commit\n    skaffold.dev/tail: \"true\"\n  name: v2-services\n  namespace: default\nspec:\n  minReadySeconds: 60\n  replicas: 1\n  revisionHistoryLimit: 10\n  selector:\n    matchLabels:\n      app: v2-services\n  strategy:\n    rollingUpdate:\n      maxSurge: 25%\n      maxUnavailable: 25%\n    type: RollingUpdate\n  template:\n    metadata:\n      labels:\n        app:v2-services\n        app.kubernetes.io/managed-by: skaffold-v1.7.0\n        ide: Idea\n        ideVersion: 2020.1.1.0.0\n        ijPluginVersion: unknown\n        skaffold.dev/builder: local\n        skaffold.dev/cleanup: \"true\"\n        skaffold.dev/deployer: kubectl\n        skaffold.dev/docker-api-version: \"1.40\"\n        skaffold.dev/run-id: 75f57ed2-6ecb-4073-aa49-bf8ae7f590f4\n        skaffold.dev/tag-policy: git-commit\n        skaffold.dev/tail: \"true\"\n      name: v2-services\n 
image: oddlara/v2-services:d0d5e963668a27ebc084ba65bdcfebfe44f8208d21bfd78867ac51935055514c\n        imagePullPolicy: IfNotPresent\n        name: v2-services\n        ports:\n        - containerPort: 8080\n        resources:\n          limits:\n            cpu: 1512m\n            memory: 1512Mi\n          requests:\n            cpu: 500m\n            memory: 1024Mi\n        
time="2020-05-08T08:20:12-07:00" level=debug msg="2 manifests to deploy. 2 are updated or new"
time="2020-05-08T08:20:12-07:00" level=debug msg="Running command: [kubectl --context docker-desktop apply -f -]"
 - service/v2-services created
 - deployment.extensions/v2-services created
Waiting for deployments to stabilize...
time="2020-05-08T08:20:12-07:00" level=info msg="Deploy complete in 414.755215ms"
time="2020-05-08T08:20:12-07:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-05-08T08:20:12-07:00" level=debug msg="checking status deployment/v2-services"
time="2020-05-08T08:20:12-07:00" level=debug msg="Running command: [kubectl --context docker-desktop rollout status deployment v2-services --namespace default --watch=false]"
time="2020-05-08T08:20:12-07:00" level=debug msg="Command output: [Waiting for deployment \"v2-services\" rollout to finish: 0 of 1 updated replicas are available...\n]"
time="2020-05-08T08:20:12-07:00" level=debug msg="Running command: [kubectl --context docker-desktop rollout status deployment v2-services --namespace default --watch=false]"
time="2020-05-08T08:21:13-07:00" level=debug msg="Command output: [Waiting for deployment \"v2-services\" rollout to finish: 0 of 1 updated replicas are available...\n]"
time="2020-05-08T08:21:13-07:00" level=debug msg="Running command: [kubectl --context docker-desktop rollout status deployment v2-services --namespace default --watch=false]"
 - deployment/v2-services is ready.
Deployments stabilized in 1m1.785268282s
Port forwarding service/v2-services in namespace default, remote port 8080 -> address 127.0.0.1 port 8080
time="2020-05-08T08:21:14-07:00" level=debug msg="Command output: [deployment \"v2-services\" successfully rolled out\n]"
time="2020-05-08T08:21:14-07:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-05-08T08:21:14-07:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-05-08T08:21:14-07:00" level=debug msg="Running command: [kubectl --context docker-desktop port-forward --pod-running-timeout 1s service/v2-services 8080:8080 --namespace default]"
time="2020-05-08T08:21:14-07:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-05-08T08:21:14-07:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-05-08T08:21:14-07:00" level=debug msg="Change detected <nil>"
time="2020-05-08T08:21:14-07:00" level=info msg="Streaming logs from pod: v2-services-68d5779f8d-zdx9v container: v2-services"
time="2020-05-08T08:21:14-07:00" level=debug msg="Running command: [kubectl --context docker-desktop logs --since=63s -f v2-services-68d5779f8d-zdx9v -c v2-services --namespace default]"
time="2020-05-08T08:21:14-07:00" level=debug msg="getting client config for kubeContext: ``"
Watching for changes...
time="2020-05-08T08:21:14-07:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-05-08T08:21:14-07:00" level=debug msg="found open port: 8081"
time="2020-05-08T08:21:14-07:00" level=debug msg="Running command: [kubectl --context docker-desktop port-forward --pod-running-timeout 1s pod/v2-services-68d5779f8d-zdx9v 8081:8080 --namespace default]"
Forwarding container v2-services-68d5779f8d-zdx9v/v2-services to local port 8081.
Port forwarding pod/v2-services-68d5779f8d-zdx9v in namespace default, remote port 8080 -> address 127.0.0.1 port 8081`

**Comment by odavidlara** [comment]
And then it starts...

**Comment by etanshaul** [comment]
aha. so I see the following:

```
time="2020-05-08T08:20:12-07:00" level=debug msg="no debug transformation for: service/v2-services"
time="2020-05-08T08:20:12-07:00" level=debug msg="no debug transformation for: deployment.extensions/v2-services"
```

Which indicates that `skaffold debug` failed to instrument the app for debugging.

Bringing in some Skaffold expertise: @briandealwis to help diagnose this as well.

@odavidlara in the meantime, would it be possible to also provide a look at what your Dockerfile and `skaffold.yaml` look like (redacted if necessary)?

**Comment by odavidlara** [comment]
skaffold.yaml look like this: 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/7753068/81422946-91329a80-9108-11ea-9ba6-611369684ac6.png">

Dockerfile doesn't have anything special going on... I have been debugging using just docker for a while now 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/7753068/81423213-07cf9800-9109-11ea-9205-d9a2cd4ce2c7.png">

**Comment by briandealwis** [comment]
@odavidlara `skaffold debug` currently looks for some key environment variables (`JAVA_TOOL_OPTIONS` or `JAVA_VERSION`, the latter is defined on the common OpenJDK images) or the presence of `java` on the entrypoint or command  to identify the runtime.  

Could you please include your kubernetes manifest?  I haven't seen `deployment.extensions` previously.

You look to be using a custom base image — can you share what it's derived from?  And could you include the output of `docker inspect oddlara/v2-services:d0d5e963668a27ebc084ba65bdcfebfe44f8208d21bfd78867ac51935055514c`?

**Comment by odavidlara** [comment]
My K8S service looks like this 
<img width="236" alt="image" src="https://user-images.githubusercontent.com/7753068/81426407-005ebd80-910e-11ea-9bb4-e604b2000b2a.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/7753068/81426454-13718d80-910e-11ea-91ed-90e95ba1fab7.png">

And my base image which i cannot share, is derived from a openjdk (9 I believe) image

**Comment by odavidlara** [comment]
inspecting the container in docker I noticed this: 

                "JAVA_VERSION=jdk8u232-b09_openj9-0.17.0",
                "JAVA_HOME=/opt/java/openjdk",
                "JAVA_TOOL_OPTIONS=-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle"

**Comment by briandealwis** [comment]
Ah ok: the deployment extensions are beta from Kubernetes 1.6 and have long been deprecated, and have been removed in [Kubernetes 1.16](https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/):
> An example of this is the Deployment resource. This was introduced under the extensions/v1beta1 group in 1.6 and as the project changed has been promoted to extensions/v1beta2, apps/v1beta2 and finally promoted to stable and moved to apps/v1 in 1.9.

`debug` doesn't support these deprecated workload objects.

I'm working on adding support to explicitly configure the image runtime detection in Skaffold (https://github.com/GoogleContainerTools/skaffold/issues/2203), but in the meantime you can just define a `JAVA_TOOL_OPTIONS` or `JAVA_VERSION` environment variable and `debug` should pick up on your image.

**Comment by odavidlara** [comment]
I'm going to try updating the api version in my K8S yamls... But did try defining the env variable myself and it didn't work in IntelliJ, it has to be both JAVA_TOOL_OPTIONS and JAVA_VERSION or just the first one should work ?

**Comment by odavidlara** [comment]
Changing my K8S yaml version worked, now I can debug, thank you!

**Comment by etanshaul** [comment]
excellent. thanks @odavidlara for the update. We'll go ahead and close this now. We will update the documentation to be clearer about this as well. Feel free to reopen if you run into anything.
