### ISSUE TITLE
appengine support not working with cloud code

### ISSUE THREAD

**Issue by gbouras** [GoogleCloudPlatform/cloud-code-intellij#2766]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version:
- OS:
mac 10.14.6 mojave
Darwin gregs-mbp.lan 18.7.0 Darwin Kernel Version 18.7.0:  root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

**What did you do?**
Tried to add appengine standard support and get the message All Modules already have app engine support or no modules were found. Literally this was a blank project following Ray Tsang:
https://www.youtube.com/watch?v=qx_T6-EKkBE

**What did you expect to see?**
Framework support should be added and I should see a appengine-web.xml file
**What did you see instead?**
Error message that it can't be added or already added. Unable to run appengine locally
(screenshots are helpful)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
Hi @gbouras. Thanks for the report.  That sample app from the video looks to be using Java 11 and is a fat jar.

Cloud Code's App Engine integration currently only support the [Java 8 runtime](https://www.google.com/search?q=app+engine+java+8+runtime&oq=app+engine+java+8+runtime&aqs=chrome..69i57j69i65l2j69i60l3.3216j0j7&sourceid=chrome&ie=UTF-8) and WAR deployments for App Engine Standard. Those kinds of applications should work though with App Engine flexible though. 

We are going to improve our documentation on https://cloud.google.com/code/docs/intellij/ to better reflect this. Also I agree that the notification that came up was not totally clear.

let me know if I mischaracterized your setup or what you were trying to achieve.

**Comment by gbouras** [comment]
@etanshaul yes that's it. Because it keeps looking for appengine-web:

12:46 PM	NoSuchFileException during local run: Error occurred during local run. Please first confirm that there is a properly placed appengine-web.xml file. If missing, either use the Cloud Code shortcut action under: 'Tools > Cloud Code > Add App Engine Support > Google App Engine Standard' Or manually generate an appengine-web.xml file in the WEB-INF directory of your module's web resource directory, (show balloon)

But in the documentation you find:
xIn the Java 11 runtime, configuration files are in the YAML format instead of the XML format. For example, you specify settings for your app in the app.yaml file instead of the appengine-web.xmlfile. You need to manually convert appengine-web.xmlfile to app.yaml file. For more information, see Creating an app.yaml file.

https://cloud.google.com/appengine/docs/standard/java11/java-differences

It does deploy to the cloud no problem so I guess I didn't expect it not to work and Ray Tsang has never led me astray before. But that's ok at least I know. But would be nice to see this work for 11.
Thank you.

**Comment by etanshaul** [comment]
thanks for the update @gbouras . at a minimum we will improve messaging so that it is clearer what is happening.
