### ISSUE TITLE
Double "for" in "Key Features" section

### ISSUE THREAD

**Issue by pahan35** [GoogleCloudPlatform/cloud-code-intellij#2773]
- Cloud Code for IntelliJ version: 20.5.1
- OS: macOS 10.15.5

Just a typo in Key features section for line starting with "Editing"
<img width="810" alt="Screenshot 2020-05-30 at 20 14 52" src="https://user-images.githubusercontent.com/13823215/83334896-409b0100-a2b2-11ea-89fc-c9747517e089.png">

**Comment by etanshaul** [comment]
thanks @pahan35 ! we'll fix this.
