### ISSUE TITLE
Cloud code doesn't create Kubernetes configuration

### ISSUE THREAD

**Issue by alexandertsukanov** [GoogleCloudPlatform/cloud-code-intellij#2777]
- Cloud Code for IntelliJ version: 
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Cloud code version: 20.5.1
Build #IU-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS:
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 5891M
Cores: 16
Registry: ide.tree.collapse.recursively=false
Non-Bundled Plugins: CMD Support, FrameSwitcher, String Manipulation, com.berzanmikaili.intellij.monokai_pro, com.floobits.unique.plugin.id, com.github.gtache.lsp, com.github.redfoos.logstash-intellij-plugin, com.herokuapp.vuesion, com.developerartemmotuzniy.LocalBranchMergedCleaner, com.weirddev.testme, Lombook Plugin, VisualVMLauncher, com.github.shiraji.findpullrequest, com.intellij.bigdecimal-folding, com.youssef.tool.idea.plugins, org.jetbrains.plugins.hocon, org.sonarlint.idea, com.intellij.nativeDebug, com.jetbrains.ChooseRuntime, com.jinsihou.react.snippets, com.sburlyaev.terminal.plugin, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.file-preview, BashSupport, com.intellij.kubernetes, org.jetbrains.kotlin, com.bruce.intellijplugin.generatesetter, com.codota.csp.intellij, com.itangcent.idea.plugin.easy-api, com.intellij.plugins.html.instantEditing, com.google.gct.core, org.jetbrains.plugins.go-template

**What did you do?**
Tools > Cloud Code > Kubernetes > Add Kubernetes Support

**What did you expect to see?**
skaffold.yaml with configuration

**What did you see instead?**
Please add a Dockerfile and Kubernetes resources in order to use the project with Cloud Code Kubernetes features.

![image](https://user-images.githubusercontent.com/17796771/83846735-be786580-a713-11ea-9343-31536983e05a.png)

As we can see Dockerfile and Kubernetes config exist. 

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
Hi @tsukanovvv . Are you using Jib by any chance as well (is it configured in your pom.xml)?

If so, we have a limitation where the initialization can only happen if only a single builder is detected: in this case, either Docker OR Jib but not both.

We are working on enhancing this to have much richer bootstrapping coming out in the next release or two.

In the meantime, you could try either temporarily removing the Jib config, or removing the Dockerfile and seeing if the generation works.

Let me know if this helps.

**Comment by etanshaul** [comment]
Another workaround is to use Cloud Code’s templating and editing support to create a Skaffold.yaml.

See: https://cloud.google.com/code/docs/intellij/using-a-k8-existing-app and the “Manually creating ...” section.

**Comment by tsukanovvv** [comment]
Hi @etanshaul!
No jib included to the project. I also did an attempt to create skaffold.yaml manually and use IDEA Live templates, and nothing was suggested by IDE. Furthermore, I have checked idea Live templates settings and can't find any added live template which corresponds to `skaffold`. Thanks.

**Comment by ivanporty** [comment]
Thanks @tsukanovvv for your report, we might indeed have issues with our live template. In the meanwhile, if you temporarily remove Dockerfile, does something show for you when you use `Add Kubernetes Support`?

**Comment by ivanporty** [comment]
It looks like we have an issue with detecting Kubernetes projects. We are working on it.

**Comment by ivanporty** [comment]
In the meanwhile, in an empty `skaffold.yaml` file, if you hit `ctrl-space`, are you able to see Skaffold template in the list?

**Comment by ivanporty** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1980)

**Comment by etanshaul** [comment]
small update @tsukanovvv : we've updated our documentation to properly reflect how to use Cloud Code live templates to quickly create `skaffold.yaml` files (and other types as well):

https://cloud.google.com/code/docs/intellij/using-a-k8-existing-app

```
To create a Skaffold YAML manually, follow these instructions to take advantage of the live templating support:

Create new file named skaffold.yaml in the root directory of your project (right-click > New > File).
With the cursor in the new file, use Ctrl+Space to bring up the live template suggestions, and choose the desired Skaffold template.
```

**Comment by ivanporty** [comment]
Technically this is not a live template per se (i.e. that would be a different key combination), but a smart completion, but the ultimate result would be the same.

**Comment by tsukanovvv** [comment]
Thank you guys for your quick response.
Hi, @ivanporty!

> In the meanwhile, in an empty `skaffold.yaml` file, if you hit `ctrl-space`, are you able to see Skaffold template in the list?

this one returns 
![image](https://user-images.githubusercontent.com/17796771/84229060-5221ab80-aaf1-11ea-92e5-7011b2ecc2ce.png)
Thanks.

> Thanks @tsukanovvv for your report, we might indeed have issues with our live template. In the meanwhile, if you temporarily remove Dockerfile, does something show for you when you use `Add Kubernetes Support`?

It works, thanks.

**Comment by alexandertsukanov** [comment]
Hi, @etanshaul ! Here is screenshots:
![image](https://user-images.githubusercontent.com/17796771/84560701-171cb380-ad4f-11ea-96b6-91ef13958ffd.png)

**Comment by ivanporty** [comment]
> Is it possible the case when another plugin blocks this suggestions to appear?

It is possible. Could you please list any other YAML/Kubernetes related plugins installed in your IDE?

**Comment by alexandertsukanov** [comment]
Hi, @ivanporty and @etanshaul ! Sorry for the long response.
The root cause was is another plugin. Not sure which one 🙂 as I have disabled half of them. Now plugin works as expected. Thanks for your support.

**Comment by ivanporty** [comment]
Thank you @alexandertsukanov for the plugin list! Most probably it's one which does some sort of YAML file editing support. We'll evaluate your list, this is very helpful.

**Comment by axmerc** [comment]
This was fixed in a prior release; Please reopen if further issues are found.
