### ISSUE TITLE
Cloud Run deployments missing some options

### ISSUE THREAD

**Issue by black-snow** [GoogleCloudPlatform/cloud-code-intellij#2790]
- Cloud Code for IntelliJ version: 20.6.1
- OS: Win10 / 2004

**What did you do?**
Created a Cloud Run deployment from the CC plugin.

**What did you expect to see?**
Options for timeout, concurrency and others.

**What did you see instead?**
No such options. I was able to choose RAM, CPU (btw, is 2 the max?) etc. but I couldn't find inputs for e.g. concurrency.

![cc_cr](https://user-images.githubusercontent.com/579733/87773464-788ae300-c823-11ea-895d-d2a824e9e708.png)

While the plugin is nice it cannot replace `gcloud CLI` or the web UI for me *atm*.

**Comment by etanshaul** [comment]
Thanks for the feedback @black-snow 

> CPU (btw, is 2 the max?)

This is currently also the max setting available from the web UI.

Regarding the other settings - makes sense. 

Aside from some missing options - is there anything else that you think could be improved with this experience? We'd love to hear how it has been working for you.

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2172)

**Comment by etanshaul** [comment]
Also (forgot to ask); regarding missing options, you mentioned `concurrency` and `request timeout`, are there other in particular that their absence is blocking your workflow?

**Comment by black-snow** [comment]
Thanks for your quick reply. I think `concurrency`, `timeout` and `max_instances` are the important bits missing atm (is max instances missing? I'm on another machine right now ;)).

**Comment by peterlin741** [comment]
The missing options will be available in the next release

**Comment by peterlin741** [comment]
Now available in `20.8.1`

**Comment by black-snow** [comment]
awesome, thanks
