### ISSUE TITLE
Cloud Debugger 

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-code-intellij#2794]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 2020.1.2 Ultimate
- OS: OSX

**What did you do?**
Try to attach a Cloud Debugger.

**What did you expect to see?**
The services appears in the drop down.

**What did you see instead?**
Nothing in the drop down and cannot attach a cloud debugger.
![image](https://user-images.githubusercontent.com/1998883/88102067-f543f700-cb6c-11ea-9a4f-2305068000f4.png)

**Comment by saturnism** [comment]
Weirdly, it works for another project.

**Comment by etanshaul** [comment]
thanks @saturnism . Any notable differences between the two projects?

**Comment by saturnism** [comment]
not that i'm aware of. For the project in question, I'm using App Engine standard, so debugger is enabled by default. In the Cloud console, I can see everything.

**Comment by saturnism** [comment]
which api endpoint/service does it call to get a list of services that I can attach to? maybe i'm missing the permission to that. I enabled `clouddebugger.googleapis.com` manually.

**Comment by etanshaul** [comment]
hmm..yeah that's the right one..anything in the logs?

**Comment by etanshaul** [comment]
or even if you could share access to the project, I could give it a try too. not sure if that is possible.

**Comment by etanshaul** [comment]
closing as not reproducible.
