### ISSUE TITLE
Make Skaffold status check configurable (env var SKAFFOLD_STATUS_CHECK=false is not working)

### ISSUE THREAD

**Issue by dwctua** [GoogleCloudPlatform/cloud-code-intellij#2795]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 20.6.1-202
- OS: windows 10

**What did you do?**
set SKAFFOLD_STATUS_CHECK=false
![image](https://user-images.githubusercontent.com/46290157/88663332-72112c80-d0a9-11ea-8436-fe2c6dbc6774.png)

**What did you expect to see?**
skaffold should skip the status check

**What did you see instead?**
Skaffold keep checking the status till time out after 2 minutes
Error: could not stabilize within 2m0s: context deadline exceeded.

(screenshots are helpful)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
hey @dwctua thanks for the report. This looks to be because we are passing in `--status-check=true` to the Skaffold invocation which is taking precedence over any environment variable you set.

We could make this field configurable in the Run Configuration UI - would that help your use-case? Also, could you help us understand why you want to disable this check (does your application take longer to stabilize?)?

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2237)

**Comment by dwctua** [comment]
unfortunately, we have some legacy app just take forever to start.

**Comment by dwctua** [comment]
I'm not sure how the new GUI looks like, but one text field to add customized skaffold cli options is sufficient.

**Comment by etanshaul** [comment]
sounds good. we will triage this. 

The enhancement will likely be a new field (under Advanced for toggling `status-check` on and off (on by default)). We prefer to use structured fields rather than freeform CLI inputs where possible - the Env Var input _should_ be the thing that allows full customization since Skaffold exposes all flags as env vars. However, in this case since we are explicitly setting the flag on the CLI with no corresponding UI field, the env var is of no use (and a general thing we should try to avoid doing).

Thanks for the input.

**Comment by dwctua** [comment]
if this is the case, I'll propose to use the environment variables to initial the skaffold command. Otherwise you'll keep adding the toggle switch for different scenario, the usability is also low.

**Comment by etanshaul** [comment]
@dwctua could you clarify what you mean by the usability being low? 

Here is one option we have in the Kubernetes Run Configuration for cleaning up deployments:

<img width="297" alt="Screen Shot 2020-07-28 at 12 24 05 PM" src="https://user-images.githubusercontent.com/1735744/88693435-4738cf80-d0cd-11ea-8548-47bb7921ff92.png">

I'm suggesting we will add a new checkbox for `Status Check`. It will default to on, but if you can easily disable it and it will be stored in the Run Config for all subsequent deployments.

**Comment by dwctua** [comment]
This will work, but my worry is the list will get longer and it still doesn't cover all the scenarios. for example, I might want to disable port-forward, or change the port number, how can I do it?

**Comment by etanshaul** [comment]
> This will work, but my worry is the list will get longer and it still doesn't cover all the scenarios. for example, I might want to disable port-forward, or change the debug port number, how can I do it?

Yeah. You make a great point here. We'll chat about this with the team here. My initial thinking was that _as long as we expose all CLI flags that we set as UI fields_ the rest can be configured as Env Vars. You are totally right that something like `port-forward` is also a gap.

**Comment by dwctua** [comment]
since you have already have a section for skaffold environment variables, it is also very confusing when to use what. I also don't feel the delete checkbox (delete deployments when finished) is actually working.  cause every time I click 'stop', the pod is still running in the backend. is this expected?

**Comment by etanshaul** [comment]
> cause every time I click 'stop', the pod is still running in the backend. is this expected?

This is not expected. Skaffold should be cleaning up your resources for you. In the logs after hitting `stop`, do you not see something like this:

```
Cleaning up...
 - deployment.apps "java-hello-world" deleted
 - service "java-hello-world-external" deleted
```

**Comment by etanshaul** [comment]
> since you have already have a section for skaffold environment variables, it is also very confusing when to use what.

Good feedback. We will scope this issue towards improving the way this works in general (how to set additional flags, UX around environment variables..).

**Comment by etanshaul** [comment]
@dwctua with the release of `20.8.1` we have fixed the blocker of setting `SKAFFOLD_STATUS_CHECK` env var not working. We are tracking separately a discussion around how better to expose all of the configuration options. Thanks.
