### ISSUE TITLE
Cluster explorer failed to open in openshift

### ISSUE THREAD

**Issue by dwctua** [GoogleCloudPlatform/cloud-code-intellij#2796]
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

**What did you do?**
browse cluster explorer

**What did you expect to see?**
expect to see the namespace/workload I have permission to access

**What did you see instead?**
![image](https://user-images.githubusercontent.com/46290157/88696021-b4019900-d0d0-11ea-8531-49baed363663.png)

Redhat openshift doesn't give user access to list namespace at cluster scope.

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
Thanks @dwctua this sounds similar to: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2697#issue-557510993, which we are investigating.

**Comment by dwctua** [comment]
yes, seems to be duplicate, I'm closing it.
