### ISSUE TITLE
do not build automatically

### ISSUE THREAD

**Issue by jimmylovelife** [GoogleCloudPlatform/cloud-code-intellij#2806]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 20.7.1
- Google Cloud SDK version: 305.0.0
- OS: Mac OS X 10.15.5

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
@sunyongjie thanks for the report! Could you please clarify what do you mean by building automatically - is it `Develop on Kubernetes` mode where we are re-building on each change?

**Comment by etanshaul** [comment]
closing this issue for now due to lack of additional information. feel free to reopen with more details and we'd be happy to address.
