### ISSUE TITLE
I want to get the Cloud SDK path installed by the Cloud Code Plugin.

### ISSUE THREAD

**Issue by i0n-** [GoogleCloudPlatform/cloud-code-intellij#2820]
- Cloud Code for IntelliJ version: 20.8.2-202
- Google Cloud SDK version: 307.0.0
- OS: Windows 10 10.0

**What did you do?**
Open Settings> Other Settings> Cloud Console> Cloud SDK

**What did you expect to see?**
The Cloud SDK managed installed path. 

**What did you see instead?**
Other Cloud SDK version info.

![image](https://user-images.githubusercontent.com/293840/92288970-ba4f1600-eec3-11ea-82dc-d06840f93bd2.png)

**Comment by etanshaul** [comment]
hey @i0n- thanks for the request! This definitely sounds like something we could do; but just to make sure we are solving the right problem.- would you mind sharing what you use case for this would be?

**Comment by i0n-** [comment]
The Cloud SDK is the tool for many tasks, so it's important be able to called from the command line.

To do that we need add the `bin` folder path of the Cloud SDK installation, to the `path` system variable.

And because the plugin manage the Cloud SDK installation and keeps it updated, it would be very convenient have a way to see and copy the `bin` path, to facility the setup of the `path` system variable.


![image](https://user-images.githubusercontent.com/293840/93031773-36dba600-f5e2-11ea-953e-754deddadac8.png)

**Comment by etanshaul** [comment]
@i0n- thanks for the info. Makes sense. The goal of the managed cloud sdk was really to be used internally by Cloud Code (not necessarily to be used externally on your system). 

But depending on what specifically you are trying to do with it, one potential feature we discussed that may make things a bit nicer is creating "Cloud Code" terminal within IntelliJ - this will give you a standard terminal prompt, but with all of Cloud Code's managed dependencies path'd in and accessible. Would you find this useful?

**Comment by i0n-** [comment]
Sorry for my delay.
Yes, "Cloud Code terminal" sounds good, We always love a ready to use solution!
And the directory path is welcome too, to setup the command line too.

**Comment by etanshaul** [comment]
sounds good @i0n- . This is timely because we are currently evaluating a prototype of this terminal feature. Will keep you updated if it makes it into the release.

**Comment by i0n-** [comment]
Thanks, Let me know if I can help with something.

**Comment by etanshaul** [comment]
hi @i0n- we released this `Cloud Code Terminal` feature with release `12.20.2` yesterday. You can find the feature under Tools: **Cloud Code** > **Tools** > **Cloud Code Terminal**. Closing this issue for now, but feel free to follow up with us any time.
