### ISSUE TITLE
Confusing Project Creation Screen

### ISSUE THREAD

**Issue by gamesbrainiac** [GoogleCloudPlatform/cloud-code-intellij#2835]
### Expected Behavior

Confusing Project Creation Screen

### Actual Behavior

Options should look like buttons. Furthermore, when create new project is selected for Cloud Run, it should go right into the Cloud Run Part of the Wizard and not Pure Python.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): PyCharm
- IDE version: 2020.2.3
- Cloud Code version (Settings > Plugins > Cloud Code):  20.9.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: Google Cloud SDK 314.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): N/A
- Operating System: MacOS Catalina

Hey there!

Hey there! Demonstration here -> https://youtu.be/kM7N_5Jvuyc

cc @jamesward and @saturnism

**Comment by ivanporty** [comment]
Thanks for reporting this @gamesbrainiac! We are aware of the problem in non-IntelliJ IDEs - we were not able to pre-select the correct project in the new project wizard yet but we are looking into it.

**Comment by ivanporty** [comment]
Interesting suggestion about samples not looking like buttons - were you expecting them to be radio buttons instead of a list? Maybe preselecting a first sample in the list would give a better impression that this is a selection?

**Comment by gamesbrainiac** [comment]
The options have to be outside the "Additional Options" submenu, and visible to the user. And yes, a radial buttons would help.

**Comment by ivanporty** [comment]
@gamesbrainiac we are still looking at this and cannot find a solution - do you potentially have any suggestions from PyCharm developers on how we can select specific project type when opening New Project dialog?

**Comment by ivanporty** [comment]
More information here: https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2576

**Comment by ivanporty** [comment]
And here https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2631

**Comment by ivanporty** [comment]
> The options have to be outside the "Additional Options" submenu, and visible to the user.

Interestingly enough, PyCharm extensions themselves do not follow your suggestions, hinting it might be not possible at the moment:

<img width="804" alt="Screen Shot 2020-11-06 at 10 41 22 AM" src="https://user-images.githubusercontent.com/11686100/98412405-e020a480-2045-11eb-8c49-805f72898e4e.png">

**Comment by etanshaul** [comment]
hi @gamesbrainiac thanks for filing this. Any additional input / tips for us based on the responses from @ivanporty above?

**Comment by gamesbrainiac** [comment]
Hi @ivanporty, sorry for the late reply. I've been on vacation for the past few days, and haven't had the time to check up on my email. I think I can arrange a meeting between you and the PC team. What times would you be available this month?

As for the React App, that just runs the `create-react-app` option, so there's not much needed for the project to be created.

@etanshaul I think the next step is to talk to the PC team to see what _can_ be done, so that we can go forward with this.

Again, apologies for the late reply.

**Comment by etanshaul** [comment]
sure sounds good. There is another part of this issue that I didn't catch initially:

> when create new project is selected for Cloud Run, it should go right into the Cloud Run Part of the Wizard and not Pure Python.

This indeed frustrated us when we implemented this. @grmoon investigated this but only found a way to achieve this in IntelliJ (no easy / consistent way to do this in the other IDEs).

We'd be happy to meet with the team - I wonder if we could first benefit from a quick meeting with you to go over any blockers and get a better understanding of what you are looking for. In parallel we could maybe ask the PyCharm eng team if they have any tips on this specific GitHub issue (it _might_ be something simple they could just point us to here).

I'll work with @abbycar to take this to email so we can schedule something.

**Comment by etanshaul** [comment]
plan for this, as discussed:

- [ ] Extract the UI from the collapsed `settings..` section
- [ ] Make the template selection clearer (right now it looks like a wall of text and not immediately obvious that they need to be clicked on)
- [ ] Consider applying a default value

**Comment by etanshaul** [comment]
this has been fixed; will be out in the next release
