### ISSUE TITLE
Failed deployments do not always stop the deployment process in IntelliJ

### ISSUE THREAD

**Issue by Alos** [GoogleCloudPlatform/cloud-code-intellij#2837]
### Expected Behavior

When the the deployment fails, CC should stop. 

### Actual Behavior

After trying to start a development workflow and deploy to GKE, CC indicated that there was a problem with the deployment, however the stop icon continued to show up indicating that the process was still running. 

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm):
 IntelliJ

- IDE version:
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on May 31, 2020

- Cloud Code version (Settings > Plugins > Cloud Code):  20201026-2019.3 → 20201027-2019.3
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.15.0
- Operating System: MacOS

**Comment by etanshaul** [comment]
thanks @Alos . Has this still been happening? 

@GoogleCloudPlatform/cloud-code-for-intellij has anyone started looking into this?

**Comment by etanshaul** [comment]
hi @Alos just checking back to see if this issue has persisted for you.

**Comment by Alos** [comment]
I have not observed this happening again but mostly because of the new login mechanism implemented in the new versions of the plugin. Feel free to close this and I'll reopen if I see it again.

**Comment by etanshaul** [comment]
sg. thanks @Alos

**Comment by matthewmichihara** [comment]
We just hit this in testing so I'm going to reopen

**Comment by etanshaul** [comment]
thanks. also reopened the internal one and added to the January milestone

**Comment by peterlin741** [comment]
Fixed in the next release
