### ISSUE TITLE
Unable to sign in to gcloud via IDE

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2840]
Cloud Code 20.10.1-202
OS: Fedora ___
Python 3.9

User has installed gcloud manually and is able to use it in his terminal. However, when he opens the Cloud Code -> Cloud SDK settings, he is:
- Unable to install or update the Managed SDK
- Unable to use a custom Cloud SDK path - when he sets the path to his Cloud SDK in the field, it is unrecognized.

Additional notes:
- He originally had Python 3.9 installed, which apparently gcloud is not compatible with, so he had to set `CLOUDSDK_PYTHON=python2` in his zsh config.
- Related gcloud issue: https://issuetracker.google.com/issues/170125513

**Comment by ivanporty** [comment]
Looks like related to https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2834

**Comment by ivanporty** [comment]
> * He originally had Python 3.9 installed, which apparently gcloud is not compatible with, so he had to set `CLOUDSDK_PYTHON=python2` in his zsh config.

Did it help?

**Comment by matthewmichihara** [comment]
It resolved his issues when trying to use gcloud from the command line but
he was still unable to configure the Cloud SDK in Cloud Code. I sent a
followup email to try to get more details around this, and to see if it is
a regression from the new release.

**Comment by ivanporty** [comment]
I could imagine it won't work in CC since we do not support inserting arbitrary environment variables when running gcloud so it still runs it with the default python (assuming it's 3.9). #2834 video has some instructions on how to change the python version globally for the system if that's an option for them.

**Comment by ivanporty** [comment]
Or alternatively try running IDE from a shell where they configured `CLOUDSDK_PYTHON` variable so it will be present by default in all processes.

**Comment by AviMoto** [comment]
> Cloud Code 20.10.1-202
> OS: Fedora ___
> Python 3.9
> 
> User has installed gcloud manually and is able to use it in his terminal. However, when he opens the Cloud Code -> Cloud SDK settings, he is:
> 
> * Unable to install or update the Managed SDK
> * Unable to use a custom Cloud SDK path - when he sets the path to his Cloud SDK in the field, it is unrecognized.
> 
> Additional notes:
> 
> * He originally had Python 3.9 installed, which apparently gcloud is not compatible with, so he had to set `CLOUDSDK_PYTHON=python2` in his zsh config.

- The Fedora version is 33. in this version the default python version set to 3.9.

- I prefer to stay in this python version and not set lower version globally as the new release  of the OS may depend on it. 

- The starting IDE from cli can by temp workaround, Can I set it in the IDE environment variable instead?

**Comment by ivanporty** [comment]
> * The starting IDE from cli can by temp workaround, Can I set it in the IDE environment variable instead?

I don't think there's an easy way to add an environment variable to IDE. There are VM options but they do not allow passing in an environment variable for child processes as far as I know. Other option is to generate a shell script to start IDE using `Tools -> Create Command Line Launcher` menu or `Toolbox` app if you're using it:

<img width="442" alt="Screen Shot 2020-10-29 at 5 29 34 PM" src="https://user-images.githubusercontent.com/11686100/97634754-a4198e00-1a0c-11eb-8ad7-a6c2fbe89c93.png">
<img width="267" alt="Screen Shot 2020-10-29 at 5 30 05 PM" src="https://user-images.githubusercontent.com/11686100/97634755-a4b22480-1a0c-11eb-86a0-db41f7ab940a.png">

Please let us know if this works for you. We are looking more into this together with Cloud SDK team.

**Comment by matthewmichihara** [comment]
User confirmed that starting IDEA from the command line did succeed as a workaround

**Comment by ivanporty** [comment]
Cloud SDK team is working on bundled Python and adding a fix for Python 3.9 - hopefully this is going to be out soon.

**Comment by AviMoto** [comment]
Workaround for Fedora 33:

1. Install latest python interpreters supported by google-cloud-sdk ([Docs](https://cloud.google.com/sdk/docs/install#linux))
`sudo dnf install -y python3.8`

1. Edit your ~/.zshrc or ~/.bashrc and add:
`export CLOUDSDK_PYTHON=/usr/bin/python3.8`
close your terminal or open new terminal in new tab.

1. Change directory to project directory and run idea IDE required CLI: (example)
`$ cd ~/istio`
`$ gloand`

1. Enter to settings Ctrl+Alt+S > Other Settings | Cloud Code | Cloud SDK and verify that you see google-cloud-sdk version correctly.
![Screenshot from 2020-11-06 16-18-52](https://user-images.githubusercontent.com/1693242/98376195-d69a3b00-204b-11eb-80fc-3031d50e7aa6.png)

**Comment by ivanporty** [comment]
Thanks @AviMoto for the detailed explanation, this will be helpful for other users as well! Cloud SDK 318.0.0 should have some fixes for 3.9 available. 

Does managed SDK work for you normally as well when you use Python 3.8?

**Comment by ivanporty** [comment]
@AviMoto Cloud SDK 318.0.0 is out today and it should work properly with Python 3.9. Please confirm if you have a minute, and thanks again!

**Comment by ivanporty** [comment]
We confirmed Cloud Code updates for the next version (318.0.0), it detects the broken Cloud SDK with Python 3.9, removes it completely, and then and re-installs the latest Cloud SDK (318.0.0) which works correctly with Python 3.9. If you don't see a notification to update Cloud SDK, you might need to restart IDE once in order for it to happen quicker or use Settings -> Cloud Code -> Cloud SDK.
