### ISSUE TITLE
Skaffold trying to use minikube builder instead of jib

### ISSUE THREAD

**Issue by viniciusccarvalho** [GoogleCloudPlatform/cloud-code-intellij#2847]
### Expected Behavior
Trying to run application on cloud run fails
### Additional Information

Setting up on a fresh machine, when trying to launch skaffold tries to use a minikube builder, but project is set to use jib.

jib works fine on the project, and the cloud run explorer shows the project

Screenshot with the error: 

![Screen Shot 2020-11-06 at 6 23 22 PM](https://user-images.githubusercontent.com/803893/98423725-8f1caa80-205d-11eb-982c-7685f7676fe3.png)

- IDE type Intellij
- IDE version: 2020.2.3 Ultimate
- Cloud Code version (Settings > Plugins > Cloud Code):  20.10.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK: 317.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Mac Os 10.15.6

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3002)

**Comment by etanshaul** [comment]
that is odd. we'll look into this. in the meantime, could you possibly share a screenshot (or list the settings selected) in the Cloud Run run configuration that you are executing? thanks.

**Comment by etanshaul** [comment]
Hi @viniciusccarvalho just checking back with you to see if this is still something you are encountering? And if so, if you could please provide a bit more information as requested in the last comment. Thanks!

**Comment by matthewmichihara** [comment]
Closing this but happy to re-open if we get a bit more info on how to reproduce.
