### ISSUE TITLE
Docker file location setting not followed at run

### ISSUE THREAD

**Issue by devcog** [GoogleCloudPlatform/cloud-code-intellij#2853]
![Screen Shot 2020-11-20 at 6 30 30 PM](https://user-images.githubusercontent.com/18356098/99862453-6e754a00-2b5f-11eb-8e61-97cdc9ad1998.png)

### Expected Behavior
The configured Docker file path is used when running locally in CloudRum emulator  

### Actual Behavior

When configuring the Docker file location the IDE correctly recognizes and sets the file path, however when trying to run it throws an error 'does not exist'. 

In the error message you can see it is not taking in the config setting, it seem to just default to looking at the root of the project.

### Additional Information
Using WebStorm 2020.2
Cloud Code alpha 
OSX 10.15.4
Google Cloud SDK 290.0.1

**Comment by etanshaul** [comment]
thanks for reporting @devcog 

@fsladkey this _sounds_ like you recent fix to explicitly specify the dockerfile location to `gcloud code export` will address this? (this will be out in the next release, if so).

**Comment by fsladkey** [comment]
Hey there, sorry for the delay.

Yes, this should be fixed in the next release, same issue as https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2818. If you're interested, you can download the nightly release which has this change and try it out, instructions are in the readme. :)

**Comment by etanshaul** [comment]
hi @devcog this was fixed release `12.20.2` which went out yesterday. Closing for now, but please let us know if you have any questions or run into any issues. Thanks.
