### ISSUE TITLE
Run configuration does not show '8 Gi' option for cloud deployment

### ISSUE THREAD

**Issue by Guthman** [GoogleCloudPlatform/cloud-code-intellij#2876]
### Expected Behavior
-Set 'CPU allocated' to to 2 or higher
-Click the dropdown for 'Memory allocated'

Expect to see a '8 Gi' option. 

### Actual Behavior
![image](https://user-images.githubusercontent.com/4036809/105889593-a345c780-600e-11eb-9a03-4e766c390818.png)
Only options up to 4 Gi are visible.

### Additional Information

- IDE type: PyCharm
- IDE version: 2020.3.1
- Cloud Code version (Settings > Plugins > Cloud Code):  21.1.1-202

  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 324.0.0
- Operating System: Windows 10 Pro (Version 10.0.19042 Build 19042)

**Comment by matthewmichihara** [comment]
This will be fixed in our next release, which should be out in the next few days.

**Comment by etanshaul** [comment]
if this is blocking your workflow, you can grab our [nightly](https://github.com/GoogleCloudPlatform/cloud-code-intellij#pre-releases) build. (just remember to remove the nightly build repo when done when you want to go back to the stable channel).
