### ISSUE TITLE
Please add options to disable certain notifications in the event log

### ISSUE THREAD

**Issue by yozzozo** [GoogleCloudPlatform/cloud-code-intellij#2879]
Every time the IDE starts up, I get a couple log lines in my event log, which is otherwise empty:

12:29 PM	Google Cloud SDK: Waiting for Cloud SDK to become available to read GCP credentials...

12:31 PM	Cloud Code initialization: Cloud Code has finished setting up managed Kubernetes dependencies.

It would be great if there were options to disable these notifications.  I don't want to disable all Cloud Code notifications in Preferences, only these logs which are not useful to me.  I'd expect stuff in the event log (which has a persistent badge on it, so you have to clear them every time) to reflect actions that I need to take, or things I need to take note of that are abnormal.  Like, if "there was a problem setting up managed Kubernetes dependencies, click here to edit settings" that would make sense :)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): JetBrains Rider
- IDE version: 2020.3.2
- Cloud Code version (Settings > Plugins > Cloud Code): 21.2.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK: 326.0.0
- Operating System: macOS 11.2

**Comment by matthewmichihara** [comment]
Thanks @yozzozo, this is good feedback, and I agree. I think it would be great to

1. properly split our notifications into groups by area so that their settings can be configured on a more granular level.
2. re-examine how useful these current event log messages are.

**Comment by ivanporty** [comment]
Obsolete.
