### ISSUE TITLE
Sign in stopped working

### ISSUE THREAD

**Issue by viniciusccarvalho** [GoogleCloudPlatform/cloud-code-intellij#2881]
When I try to sign in to any service (Cloud Run for instance) the browser opens, I select the right account, but the opening window keeps asking for sign-in. Tried to repeat the process several times. Closed all the open tabs on my browser, restarted the browser and still nothing works.

Via the console I can do gcloud auth login, that appears to work. But the windows do not reflect that, still asks to select a Google Cloud Project. 

Any way around this?

Thanks

(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 20.12.2-202
- Google Cloud SDK version: 326.0.0
- OS: Mac OS X 10.16

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
Hi @viniciusccarvalho , thanks for reporting. I see you are using plugin version `20.12.20-202`. There indeed was a breaking change in the gcloud API that caused this issue. We have fixed this issue in the latest release `21.2.1-202`. Are you able to upgrade to the latest plugin version?

**Comment by viniciusccarvalho** [comment]
@etanshaul thanks man, I just updated and indeed its working again.

Cheers

**Comment by etanshaul** [comment]
any time. glad that resolved it.
