### ISSUE TITLE
Cannot connect local Cloud Run app to local services

### ISSUE THREAD

**Issue by mryerse** [GoogleCloudPlatform/cloud-code-intellij#2886]
More of a how-to question since I cannot find answers on stackoverflow nor the Internet, and it doesn't work with what I consider a rather standard/default configuration.

### Expected Behavior
Connect to a redis instance from a locally deployed Cloud Run service, where the redis instance is running in docker on the same system that Cloud Code is running on (in my case all in MacOS).

### Actual Behavior
Times out when connecting to 127.0.0.1:6379 from Cloud Run deployed locally, even though the redis instance responds to connections from the python shell (opened in standard MacOS terminal).

### Additional Information
I've setup a redis instance in docker using the following command:
`docker run --name my-redis -p 6379:6379 --restart always --detach redis`
What Cloud Code, docker, or minikube configurations do I need to make to allow the Cloud Run instance deployed locally to be able to connect to this?  Or alternatively, how should I deploy redis differently so that Cloud Run can access it?
`redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.`
Is there a firewall or missing route that prevents connections to locally running services from within Cloud Run?

- IDE type: IntelliJ
- IDE version: pr 2020.3
- Cloud Code version (Settings > Plugins > Cloud Code): 21.2.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
 - Are you allowing the plugin to manage the Cloud SDK: Yes
 - Version of the Cloud SDK: 328.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 1.19
- Operating System: MacOS 10.15.7

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by mryerse** [comment]
Someone was able to help me out on stackoverflow [here](https://stackoverflow.com/questions/66267954/connect-to-redis-from-cloud-run-locally/66277314#66277314).  I'm going to leave this open in case your team this scenario can be improved somehow.  From my perspective I don't need anything else on this topic.

**Comment by etanshaul** [comment]
@mryerse thank you for sharing this. I'm going to keep this open and discuss with the team to see if there is a way we can improve this. For non-local scenarios running on Cloud Run proper, are you setting up a VPC connector?

**Comment by etanshaul** [comment]
@matthewmichihara, since the VPC connector setting was implemented and released in Cloud Code `21.3.1`, can we close this now?

**Comment by medyagh** [comment]
I see yes that could get complicated, if wanting to connect traffic outside minikube to inside minikube, I think we could suggest the following 

1- create the reddis inside kubernetes (minikube) instead of outside 
2- create a doc explaining how to connect cloud run services inside our emulator to outside world

**Comment by matthewmichihara** [comment]
Right now the best solution is to connect to the internal network that minikube creates as mentioned in the stackoverflow [post](https://stackoverflow.com/questions/66267954/connect-to-redis-from-cloud-run-locally/66277314#66277314).
