### ISSUE TITLE
Copying items in Kubernetes Explorer copy internal names instead of visible labels

### ISSUE THREAD

**Issue by nyurik** [GoogleCloudPlatform/cloud-code-intellij#2898]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)
![image](https://user-images.githubusercontent.com/1641515/110551835-4c023f00-8104-11eb-864a-f8585abf75f4.png)

### Expected Behavior
In Kubernetes Explorer, using `Ctrl+C` should copy the visible label of the tree item.  In the view above, it should copy the word `default`.  Note that it actually works for the non-instance labels -- copying the parent node places `Service Account` into clipboard.

### Actual Behavior
Internal java instance name is copied. In the snapshot shown above, `ctrl+C` copies `com.google.cloud.tools.intellij.kubernetes.model.ServiceAccount@3a69bcfc`.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ
- IDE version: 2020.3
- Cloud Code version (Settings > Plugins > Cloud Code): 
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: 
  - Version of the Cloud SDK:
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Linux Mint

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3625)

**Comment by nyurik** [comment]
Update -- turns out this bug also makes it impossible to copy multiple items -- the rightclick + copy resource name only copies one item, not all selected ones. The Ctrl+C copies all selected, but it copies class names instead of the resource names.

**Comment by ivanporty** [comment]
This will be fixed in the next (April) release. Thanks for letting us know!
