### ISSUE TITLE
Kubernetes Debugging On Pycharm

### ISSUE THREAD

**Issue by cpvandehey** [GoogleCloudPlatform/cloud-code-intellij#2911]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
[According to the docs, jetbrains k8s debugging is available for java, go and node.js developers.](https://cloud.google.com/code/docs/intellij/kubernetes-debugging). Pycharm **can** successfully _run_ the "Develop On Kubernetes" debugging features, but nothing attaches to the running pod. Since cloud code is supported in pycharm, the lack of debugging is a critical feature holding back onboarding. I recognize that this may be a jetbrains flexibility issue and not GCP/GoogleContainerTools problem. The lack of tracking (closed/open) on Google's end is the purpose of this github issue. Perhaps more documentation on the current level of support for Pycharm is needed as well.

Skaffold.dev documentation currently makes one note:
>The DAP is supported by Visual Studio Code, Eclipse LSP4e, and other editors and IDEs. DAP is not yet supported by JetBrains IDEs like PyCharm.

After searching, I was unable to find any tickets or progress on this on Jetbrain's side. I find their remote debugger to be overly complex and less user friendly than `debugpy`. Is there any work in progress that this team knows of that I couldn't find? I use vscode almost exclusively for py developing because of this issue.

Thank you for the help! 

### Additional Information

- IDE type: Pycharm
- IDE version: 2020.1.1 professional
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes):  v1.21.0

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
hi @cpvandehey thanks for the report. We are actually tracking this here:
https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2675

We ran into some technical hurdles (as you hinted at) which is why that issue has been open for some time, but we recently made good progress on this and hope to release support soon if all goes well.

**Comment by etanshaul** [comment]
> Perhaps more documentation on the current level of support for Pycharm is needed as well.

agreed. it currently should be everything but debugging, but it would help if we had some kind of doc page that explained this clearly / up front

**Comment by etanshaul** [comment]
@cpvandehey ok with you if we close this given that we are tracking this in the linked issue (#2675)? Feel free to add any more feedback even after its closed. I added some more details on why the problem was difficult and briefly on our current progress / status in my above comment.

**Comment by cpvandehey** [comment]
Thanks for linking the existing issue (_the intellij naming threw me off_).

Go ahead and close the issue. It sounds like you fully understand the thoughts

**Comment by etanshaul** [comment]
closing as dup of issue mentioned above
