### ISSUE TITLE
There is no tutorial to configure a CloudSQL database for cloud code. I keep getting an error 

### ISSUE THREAD

**Issue by estaar** [GoogleCloudPlatform/cloud-code-intellij#2914]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 21.3.1-202
- Google Cloud SDK version: 336.0.0
- OS: Windows 10 10.0

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Cloud Code doesn't support Cloud SQL features explicitly, but we do support Cloud SQL connections for Cloud Run, if that's what you're looking for. You can specify a Cloud SQL connection in advanced Cloud Run service revision settings when you deploy:

<img width="756" alt="Screen Shot 2021-04-15 at 11 32 04 AM" src="https://user-images.githubusercontent.com/11686100/114896294-36a4c280-9dde-11eb-980c-eaee527e0648.png">

This [Cloud SQL link](https://cloud.google.com/sql/docs/mysql/connect-run) contains more information on how to configure Cloud SQL instance for Cloud Run.

If you are looking for more advanced support for Cloud SQL, such as running queries and autocompletion, IntelliJ Ultimate edition and most other JetBrains IDE (or DataGrip) contains `Database` tool window that allow you to connect and inspect database types supported by Cloud Run. However, before connecting, you need to run Cloud SQL Proxy. Here are a few helpful resources for that:

* [Connecting to Cloud SQL correctly](https://medium.com/google-cloud/connecting-google-cloud-sql-94025ba27071)
* [GCP Official Video - Cloud Run + Cloud SQL Setup](https://www.youtube.com/watch?v=cBrn5IM4mA8)

**Comment by etanshaul** [comment]
@estaar please let us know if you have any more questions about this. I'm going to close in the meantime as the above instructions from @ivanporty should help you get up and running (and there is no bug or FR to track here).
