### ISSUE TITLE
Cloud Code Plugin does not recognize a custom cloud sdk installation.

### ISSUE THREAD

**Issue by WhyUnspoken** [GoogleCloudPlatform/cloud-code-intellij#2925]
### Expected Behavior
The Cloud Code Dependencies Page is correctly retrieving the Cloud SDK Version from a custom local SDK installation.
When selecting a Cloud Project in the Google Cloud Storage Pane, a browser is launched and I am able to login.

### Actual Behavior
The Cloud Code Plugin Dependencies Page is not able to find the Cloud SDK Version of a custom local SDK installation.
It says "Cloud SDK Version: not installed"
This is on Windows 10. The installed Cloud SDK Version is Google Cloud SDK 338.0.0 (gcloud version).
The plugin is also not able to sign in into the google cloud.

The ide.log records this error when trying to log into the google cloud via the plugin:

2021-04-29 17:24:27,124 [2149919] WARN - ellij.login.GoogleLoginService - Failure running login()
java.lang.IllegalArgumentException: Pattern "**not installed**" is not a valid CloudSdkVersion.
at com.google.cloud.tools.appengine.operations.cloudsdk.serialization.CloudSdkVersion.(CloudSdkVersion.java:66)
at com.google.cloud.tools.intellij.cloud.sdk.CloudSdkVersionInfo.extractSdkVersion(CloudSdkVersionInfo.kt:63)
at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.logIn(CloudSdkAuthWrapper.kt:71)
at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService.logIn(CloudSdkLoginService.kt:57)
at com.google.cloud.tools.intellij.login.LoginUtilsKt$logInWithProgress$1$run$logInJob$1.invokeSuspend(LoginUtils.kt:51)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

The sdk is correctly installed and can access the cloud, login and access cloud storage from the command line.

### Additional Information
Plugin Version is 21.3.1-202, IntelliJ IDEA Version is 2020.3.4

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ
- IDE version: 2020.3.4
- Cloud Code version (Settings > Plugins > Cloud Code): 21.3.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: No. It is a custom installation
  - Version of the Cloud SDK: 338.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Windows 10

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._
![image](https://user-images.githubusercontent.com/80349773/116579342-950b8e00-a912-11eb-9814-2ed6da255a88.png)
![image](https://user-images.githubusercontent.com/80349773/116580161-6346f700-a913-11eb-858f-2776479a64c1.png)

**Comment by matthewmichihara** [comment]
@WhyUnspoken Thanks for the detailed report.  What does `C:\Users\xn07881\google-cloud-sdk\bin\gcloud version` return?

**Comment by WhyUnspoken** [comment]
Google Cloud SDK 338.0.0
app-engine-java 1.9.88
app-engine-python 1.9.91
bq 2.0.67
cloud-datastore-emulator 2.1.0
core 2021.04.23
gsutil 4.61

**Comment by etanshaul** [comment]
@WhyUnspoken how did you install the Cloud SDK? did you use a certain package manager or anything? We're looking into the logic to see what might be causing this.

**Comment by etanshaul** [comment]
Also, could you please confirm if using the managed SDK works or not?

**Comment by WhyUnspoken** [comment]
@etanshaul I downloaded the zip file and used the contained install. bat.
The managed cloud sdk installation fails on my windows computer, therefore I installed it myself.

**Comment by ivanporty** [comment]
Can we please take a look at your IDE logs (`Help -> Show Log.. -> idea.log`) to diagnose better? You could just attach your log file right here.

**Comment by WhyUnspoken** [comment]
I restarted the IDE and tried to select a Google Cloud Project. This is the logfile:
[idea.log](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/6401497/idea.log)

**Comment by WhyUnspoken** [comment]
By the way: in the meantime I upgraded the cloud code plugin to version 21.4.1-202 - still the same issues.

**Comment by ivanporty** [comment]
@WhyUnspoken we see the following in your logs:
```
2021-04-29 22:27:23,637 [ 527065]   INFO -                         STDERR - Apr. 29, 2021 10:27:23 NACHM. com.google.cloud.tools.managedcloudsdk.install.SdkInstaller install 
2021-04-29 22:27:23,637 [ 527065]   INFO -                         STDERR - INFORMATION: Removing stale archive: C:\Users\xn07881\AppData\Local\google\ct4j-cloud-sdk\downloads\google-cloud-sdk-windows-x86_64-bundled-python.zip 
2021-04-29 22:27:23,647 [ 527075]   INFO -                         STDERR - Apr. 29, 2021 10:27:23 NACHM. com.google.cloud.tools.managedcloudsdk.install.SdkInstaller install 
2021-04-29 22:27:23,647 [ 527075]   INFO -                         STDERR - INFORMATION: Removing stale install: C:\Users\xn07881\AppData\Local\google\ct4j-cloud-sdk\LATEST 
2021-04-29 22:27:29,380 [ 532808]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: google for id: google.settings 
2021-04-29 22:27:29,381 [ 532809]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2021-04-29 22:27:29,384 [ 532812]   WARN - ConfigurableExtensionPointUtil - use other group instead of unexpected one: build.android 
2021-04-29 22:27:31,697 [ 535125]   WARN - oud.sdk.ManagedCloudSdkService - Error while installing/updating managed Cloud SDK 
java.nio.file.FileSystemException: C:\Users\xn07881\AppData\Local\google\ct4j-cloud-sdk\LATEST: failed to delete one or more files; see suppressed exceptions for details
```

SDK installer tries to clean the directory where the previous stale archives still exist, and cannot do that for some reason, maybe a permission issue? Could you please quitting your IDE, then manually removing `C:\Users\xn07881\AppData\Local\google\ct4j-cloud-sdk\LATEST` directory with all files, and then restart IDE and see if this helps managed SDK to be installed correctly?

**Comment by ivanporty** [comment]
Another question - it seems Cloud Code times out reading your custom SDK version for some reason. How long does running this command in a terminal take for you and what is the output?
`gcloud version --format=json`

**Comment by ivanporty** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3895)

**Comment by WhyUnspoken** [comment]
Removed the installation but did not help. The managed installation failed.
[idea.log](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/6407717/idea.log)

**Comment by WhyUnspoken** [comment]
> Another question - it seems Cloud Code times out reading your custom SDK version for some reason. How long does running this command in a terminal take for you and what is the output?
> `gcloud version --format=json`

It takes about 2 seconds:
{
  "Google Cloud SDK": "338.0.0",
  "app-engine-java": "1.9.88",
  "app-engine-python": "1.9.91",
  "bq": "2.0.67",
  "cloud-datastore-emulator": "2.1.0",
  "core": "2021.04.23",
  "gsutil": "4.61"
}

**Comment by WhyUnspoken** [comment]
From the cmd prompt I can access Cloud Storage with no issues, e.g. `gcloud list` works perfectly.

**Comment by ivanporty** [comment]
Great, thank you! Another question - if you go to managed SDK directory (`C:\Users\xn07881\AppData\Local\google\ct4j-cloud-sdk\`), and find installer archive there, `google-cloud-sdk-windows-x86_64-bundled-python.zip`, is it unpacked? If yes, could you please run `install.bat` manually and see if succeeds? If you don't see it, could you please try `https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk-windows-x86_64-bundled-python.zip`, unpack it and try running `install.bat` from any location, will it work successfully?

**Comment by WhyUnspoken** [comment]
The zip was unpacked. I executed install.bat successfully.
Only the PATH variable could not be set by the install.bat : 
The installer is unable to automatically update your system PATH. Please add
  C:\Users\xn07881\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\bin
to your system PATH to enable easy use of the Cloud SDK Command Line Tools.

**Comment by ivanporty** [comment]
Great, the installer uses Python, and I assume you are a Python user, what is the python version you have on your PATH?

**Comment by WhyUnspoken** [comment]
I removed all python installations and python from the path already yesterday. Executing `python` from the cmd prompt finds no executable.

**Comment by WhyUnspoken** [comment]
I tried `gcloud auth login` from the cmd prompt in the bin directory of the managed installation. Did work flawlessly.

**Comment by ivanporty** [comment]
ah I see, thanks so much for being so responsive! 
So I assume the installer should use its own bundled python. Could you please try running the command line we attempt to run when installing on windows?

`cmd /c --path-update=false --command-completion=false  --quiet --usage-reporting=false --override-components core gcloud-deps bq gcloud gsutil`

**Comment by WhyUnspoken** [comment]
Thanks a lot for your help!
Executed the command: 
![image](https://user-images.githubusercontent.com/80349773/116750760-3c67ee00-aa03-11eb-93ee-cbb891efe12c.png)

**Comment by ivanporty** [comment]
Thanks, seems normal.. Could you please check an exit code of this command? (I think it's `echo %errorlevel%`..)

**Comment by WhyUnspoken** [comment]
It is "0".
![image](https://user-images.githubusercontent.com/80349773/116751258-0c6d1a80-aa04-11eb-8aa1-4b5ff6dadf99.png)

**Comment by ivanporty** [comment]
Thank you again for detailed follow up on the issue, this is really helpful for finding the problem!
We have an update that could allow you to log in and use your Custom SDK, and could give us a bit more details on why version check doesn't work. It will be available in the nightly channel tomorrow, instructions are here:
https://github.com/GoogleCloudPlatform/cloud-code-intellij#pre-releases

Please try using `nightly` channel plugin update tomorrow, and whatever happens, it would be great to know if it helped using your custom SDK and see your `idea.log` once again. In the meanwhile, we will think about possible reasons for your failing managed SDK install.

**Comment by ivanporty** [comment]
@WhyUnspoken let us know if you were able to use nightly build or we can try something else

**Comment by WhyUnspoken** [comment]
@ivanporty 
I installed the nightly. 
The cloud SDK is now recognized: 
![grafik](https://user-images.githubusercontent.com/80349773/117339497-15e10180-aea0-11eb-82ec-96c6cc3941f8.png)

The cloud code version is 20210506-2020.2

When selecting the tab "Google Cloud Storage" and then "Select a Google Cloud Project", the Browser opens (Firefox), I log in successfully but nothing happens afterwards, the screen won't disappear:

![grafik](https://user-images.githubusercontent.com/80349773/117339285-dc0ffb00-ae9f-11eb-932d-dbba9c3dec70.png)

[idea.log](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/6436589/idea.log)

**Comment by ivanporty** [comment]
Thank you @WhyUnspoken! It seems Cloud Code is having general issues running some gcloud commands for some reason, maybe Windows specific. We'll keep looking into this. 
In the meanwhile, if you login from the command like (`gcloud auth login`), are you able to authenticate with Firefox? Does `gcloud auth list` work properly? If it does, if you restart your IDE, is Cloud Code able to see your authentication (i.e. project selection pops up project / account selection dialog)?

**Comment by ivanporty** [comment]
@WhyUnspoken how are things going for you with Cloud Code based authentication? Does it work? If not, could you please provide us with some more information from comment https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2925#issuecomment-834671028?

**Comment by ivanporty** [comment]
Closing this as initial issue has been resolved. Please reopen if you're still seeing login problem in Windows.
