### ISSUE TITLE
High CPU usage when editing skaffold.yaml, causing IDE to freeze

### ISSUE THREAD

**Issue by Ezard** [GoogleCloudPlatform/cloud-code-intellij#2952]
### Expected Behavior

I should be able to edit `skaffold.yaml` without high CPU usage

### Actual Behavior

- Whenever I try to make a change to `skaffold.yaml`, or even just save the file without making any changes, Cloud Code's CPU usage rises to 100% (as reported by the IDE's activity monitor), and this freezes the entire IDE for ~10s
- This freeze occurs on every keypress in the `skaffold.yaml` file
- Only `skaffold.yaml` is affected - editing any of the actual K8s manifests or Kustomization files is fine

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): WebStorm
- IDE version: 2021.1.2
- Cloud Code version (Settings > Plugins > Cloud Code): 21.6.1
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: I've tested both options here, and neither solves the issue
  - Version of the Cloud SDK: 347.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 1.27.0
- Operating System: Windows 10 Pro

I noticed this issue a while back, but have only just gotten around to reporting it - I appreciate that this probably makes things more difficult for you, so I'd like to apologise in advance for that

**Comment by etanshaul** [comment]
Thank you for reporting this! We definitely want to investigate. Do you have a sample skaffold.yaml file that we can try this out with (removing any sensitive data from it)? Or even a full project that we can clone that reproduces this.

We will try and reproduce in the meantime.

**Comment by etanshaul** [comment]
Just a guess at the moment, but when you have a `skaffold.yaml` file open Cloud Code runs a check to determine if the version can be updated. Perhaps the command is acting up for some reason. If you can, could you please:

1) Open the Cloud Code terminal: Tools > Cloud Code > Tools > Cloud Code Terminal (this opens up a terminal with Cloud Code's dependencies path'd in, including Skaffold)
2) Run `skaffold schema list -o json` at the root of your project (or wherever your `skaffold.yaml` is located). Anything unusual here with the execution? It should run very quickly with minimal CPU overhead (and print out some JSON).

**Comment by Ezard** [comment]
@etanshaul `skaffold schema list -o json` runs instantly

I'll see if I can setup a repro project over the weekend

I assume the zip archive that's attached to each release is a valid plugin? If so then I'll try manually installing older versions of the plugin to see if I can find out which version caused this issue

Thanks!

**Comment by Ezard** [comment]
@etanshaul after some investigation, the issue appears to be related to the number of files in the project

I tested this by copying files from a relatively small Node.js project:
Step | Result
-- | --
Copied `skaffold.yaml` to empty project | IDE did not freeze when saving `skaffold.yaml`
Copied K8s manifests to project | IDE had an ever so slight freeze when saving `skaffold.yaml` (probably <100ms)
Copied `node_modules` directory to project | IDE freeze for ~6s when saving `skaffold.yaml`
Copied source code to project | IDE freeze for ~7s when saving `skaffold.yaml`

Testing on a larger project with more dependencies (and therefore a bigger `node_modules` folder with more files), I clocked ~16s freeze when editing `skaffold.yaml` with the `node_modules` directory in the project, and then ~1s freeze when I deleted that directory

Testing on an even larger project (that actually has 2 different `node_modules` directories), I clocked ~32s freeze when both `node_modules` directories existed, ~12s freeze when I deleted one of the `node_modules` directories (which likely had the most deps in it), and then ~5s freeze when both `node_modules` directories had been deleted

Could there be some kind of indexing going on by the plugin that scans all of the files on every edit?

I've attached [package.zip](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/6760715/package.zip), which is from the smallest project that I tested; you can (hopefully) reproduce this issue by extracting the 2 files in that archive to an empty project with a `skaffold.yaml` file in it, running `npm ci` to install the deps (you'll need Node.js v14), and then making an edit to the `skaffold.yaml` file

**Comment by etanshaul** [comment]
> Could there be some kind of indexing going on by the plugin that scans all of the files on every edit?

We do have indexing looking for the existence of a `skaffold.yaml`. But it should happen once, and definitely not on every edit. On edit of `skaffold.yaml` we speak over the LSP (language server protocol) to get editing support (autocompletion, docs, etc.), but this should be a constant time hit in terms of the number of files - it shouldn't matter how many files in the project.

This gives is a lot to go by and investigate. Thank you (and we'll report back)!

**Comment by Ezard** [comment]
Thanks @etanshaul - let me know if I can provide any more info!

**Comment by matthewmichihara** [comment]
@Ezard Thank you for the very detailed report and sample project. We were able to reproduce the issue and we think we've fixed the issue in the latest Cloud Code nightly build. Can you give it a try and report back if you're still seeing the issue?

You can get the latest nightly by adding this custom plugin repository: https://plugins.jetbrains.com/plugins/nightly/8079

**Comment by Ezard** [comment]
@matthewmichihara I've just tested, and the issue appears to be resolved

I'm no longer noticing any freezing across any of my projects, even one that has 3 different `node_modules` directories

Thanks for the fast turnaround!

**Comment by matthewmichihara** [comment]
Great to hear!
