### ISSUE TITLE
Breakpoints not hit in Python app deployed to GKE

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2961]
Posted by a user. See full initial discussion here:

@etanshaul I am having trouble debugging the application on my GKE cluster from **PyCharm**, it seems like the debugger is attached but no breakpoint is hit.
I've tried source mappings with different remote paths but it still doesn't seem to work and the only reference I see here: https://cloud.google.com/code/docs/intellij/kubernetes-debugging#python is for java based projects..

I am debugging the application just fine from VSCode though.. any idea what may be the cause?

_Originally posted by @talboren in https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2675#issuecomment-878381525_

**Comment by fossilet** [comment]
Same problem. With the sample app at https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/python/python-hello-world breakpoints are hit, but the button for interactive Python shell is missing from PyCharm UI, so I cannot use the python shell:
![图片](https://user-images.githubusercontent.com/948336/132325079-837df289-aa5c-4515-ac13-7ee21d190e18.png)

**Comment by ltieman** [comment]
Same Problem.  PyCharm 2021.3.2. Cloud Code 22.2.1-213.  Skaffold v1.35.2 macOS 11.6.4 x86

**Comment by Timonsc** [comment]
Did anybody already find a solution to this issue?

**Comment by etanshaul** [comment]
We will look into this. If someone has a sample app to share the reproduces this, that would be helpful.

**Comment by etanshaul** [comment]
I see. 

Just to confirm, have you ensured that the prerequisite setup is done as mentioned here?
https://cloud.google.com/code/docs/intellij/kubernetes-debugging#python

Screenshot from above link:
<img width="890" alt="Screen Shot 2022-02-24 at 4 22 55 PM" src="https://user-images.githubusercontent.com/1735744/155609943-89cf08a9-5029-4c39-9c86-9f132f540092.png">

**Comment by Timonsc** [comment]
Yes. I'm on MacOS btw. And I also tried to put `ENV PYCHARM_DEBUG=true` in the Dockerfile

**Comment by Timonsc** [comment]
Here is some of the logging:
```
[server] Applying patching to hide pydevd threads (Py3 version).
[server] Successfully Loaded helper lib to set tracing to all threads.
[server]  * Serving Flask app 'app' (lazy loading)
[server]  * Environment: production
[server]    WARNING: This is a development server. Do not use it in a production deployment.
[server]    Use a production WSGI server instead.
[server]  * Debug mode: on
[server]  * Running on all addresses.
[server]    WARNING: This is a development server. Do not use it in a production deployment.
[server]  * Running on http://172.17.0.6:8080/ (Press CTRL+C to quit)
[server]  * Restarting with stat
[server]  * Debugger is active!
[server]  * Debugger PIN: 332-947-575
[install-python-debug-support] Installing runtime debugging support files in /dbg
[install-python-debug-support] Installation complete
Port forwarding pod/python-hello-world-5f7cc95b8-vhz4d in namespace default, remote port 5678 -> http://127.0.0.1:5678
[server] Connection (from wait_for_attach) accepted.
[server] debugger: received >>501	1	0.1	UNIX<<
[server] 
[server] Received command: CMD_VERSION 501	1	0.1	UNIX
[server] 
[server] sending cmd (quoted-line) -->          CMD_VERSION @@BUILD_NUMBER@@
[server] 
[server] debugger: received >>501	3	0.1	UNIX<<
[server] 
[server] Received command: CMD_VERSION 501	3	0.1	UNIX
[server] 
[server] sending cmd (quoted-line) -->          CMD_VERSION @@BUILD_NUMBER@@
[server] 
[server] debugger: received >>111	5	python-line	/app/app.py	17	hello	THREAD	None	None<<
[server] 
[server] Received command: CMD_SET_BREAK 111	5	python-line	/app/app.py	17	hello	THREAD	None	None
[server] 
[server] Request for breakpoint in: /app/app.py line: 17
[server] Breakpoint (after path translation) in: /app/app.py line: 17
[server] Added breakpoint:/app/app.py - line:17 - func_name:hello
[server] 
[server] debugger: received >>111	7	python-line	/app/app.py	19	hello	THREAD	None	None<<
[server] 
[server] Received command: CMD_SET_BREAK 111	7	python-line	/app/app.py	19	hello	THREAD	None	None
[server] 
[server] Request for breakpoint in: /app/app.py line: 19
[server] Breakpoint (after path translation) in: /app/app.py line: 19
[server] Added breakpoint:/app/app.py - line:19 - func_name:hello
[server] 
[server] debugger: received >>122	9	python-BaseException	None	None	0	1	0<<
[server] 
[server] Received command: CMD_ADD_EXCEPTION_BREAK 122	9	python-BaseException	None	None	0	1	0
[server] 
[server] Exceptions to hook on terminate: {'BaseException': <_pydevd_bundle.pydevd_breakpoints.ExceptionBreakpoint object at 0x7f44b8f41c40>}.
[server] debugger: received >>146	11	SHOW_RETURN_VALUES	0<<
[server] 
[server] Received command: CMD_SHOW_RETURN_VALUES 146	11	SHOW_RETURN_VALUES	0
[server] 
[server] Show return values: False
[server] debugger: received >>101	13	<<
[server] 
[server] Received command: CMD_RUN 101	13	
[server] 
[server] sending cmd (quoted-line) -->    CMD_THREAD_CREATE <xml><thread name="MainThread" id="pid_13_id_139933199792640" /></xml>
[server] 
[server] 127.0.0.1 - - [24/Feb/2022 21:36:01] "GET / HTTP/1.1" 200 -
[server] 127.0.0.1 - - [24/Feb/2022 21:36:01] "GET /static/KE-hello-world.svg HTTP/1.1" 304 -
[server] 127.0.0.1 - - [24/Feb/2022 21:36:01] "GET /static/cloud_bg.svg HTTP/1.1" 304 -
```

**Comment by etanshaul** [comment]
thanks. I do know we've tested extensively on these guestbook / hello world samples. So this should be easily to reproduce hopefully if there is a problem. We'll give a try and investigate.

@Timonsc Could you also share what version of the IDE as well as the flavor (IntelliJ Ultimate / Pycharm)?

**Comment by Timonsc** [comment]
Thanks for the swift replies! Pycharm 2021.3.2 Professional edition.

**Comment by etanshaul** [comment]
I just ran the same IDE / version against the Python+Flask hello world sample and was able to hit a break point. My specific steps below, in case there is a disconnect somewhere.

Another question please: what kind of cluster are you deploying to? Is it a local cluster (like minikube), or a remote cluster (e.g. GKE)?

My Steps:

1) Clone the Python/Flask hello world sample in PyCharm pro 2021.3.2
2) Configure my Python Interpreter:
<img width="987" alt="Screen Shot 2022-02-24 at 5 05 08 PM" src="https://user-images.githubusercontent.com/1735744/155615975-5a51fe0d-fcb3-4d0d-a221-187adff9eaec.png">
3) Run the app (I did not configure any custom path mappings under the debug tab of the Run Config settings)
4) Accept the default path mapping suggestion:
<img width="426" alt="Screen Shot 2022-02-24 at 5 07 47 PM" src="https://user-images.githubusercontent.com/1735744/155616037-5ee195d8-6400-41b1-b830-ca117bb05d1e.png">
5) Run the app with a breakpoint set:
<img width="1309" alt="Screen Shot 2022-02-24 at 5 07 58 PM" src="https://user-images.githubusercontent.com/1735744/155616055-e7f1205d-5f18-4062-9934-e4fb7476e63b.png">

**Comment by etanshaul** [comment]
Also helpful to know - did you modify the sample app in any way (like the Dockerfile perhaps)

**Comment by Timonsc** [comment]
I'm using a simple minikube cluster (docker). I just added that `ENV PYCHARM_DEBUG=true` lint to the Dockerfile.

**Comment by Timonsc** [comment]
This was the problem
<img width="722" alt="image" src="https://user-images.githubusercontent.com/12909049/155625834-a7461d16-8108-4304-9802-4314d5aec5c9.png">
I probably made a mistake and thought I had to change debug to True where it should have stayed on False... Thank you for your help!

**Comment by etanshaul** [comment]
That is interesting! I’ll look into why that is interfering. Thanks for the update

**Comment by etanshaul** [comment]
Hi all. It appears as though most (or all) of these issues are solved by:
1) Ensuring that your setup follows the steps outlined here: https://cloud.google.com/code/docs/intellij/kubernetes-debugging#python
2) _NOT_ setting `debug=True` on the flask server as mentioned here (https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2961#issuecomment-1050368027). We will investigate this issue separately: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/3062

I am closing this thread in the meantime, but if you are still experience issues different from either (1) or (2) feel free to comment on this thread. Thanks.
