### ISSUE TITLE
Run gcloud scripts in plugin

### ISSUE THREAD

**Issue by kschaab** [GoogleCloudPlatform/cloud-code-intellij#2964]
From cloud-code-vscode created by [ProbStub](https://github.com/ProbStub): GoogleCloudPlatform/cloud-code-vscode#451  

**Use case**
I have a number of infrastructure configurations that required gcloud commands. I like to run these commands and observe output. (currently working on PyCharm/MACOS)

**Feature**
A command line option would already be great but I dodnt find anything in the docs. Apologies if this is a RTFM case and kindly direct to the right space.

**Comment by kschaab** [comment]
Hi @ProbStub,

Could you explain your use case in a little more detail? 

Do you want to use the script after Kubernetes/Cloud Run deployments?

**Comment by kschaab** [comment]
Cloning to IntelliJ repo for PyCharm.  @ProbStub fyi.

**Comment by ProbStub** [comment]
@kschaab. Thanks for cloning to the right team. You might want to review the [cloud.google.com IntelliJ link](https://cloud.google.com/code/docs/intellij/features) as well.

Regarding my use case. Consider the following:
During coded infrastructure setup one might want to configure DNS, firewall and routing _before_ launching any K8 deployments. Specifically assume one first wants to create a DNS zone (gcloud dns managed-zones create my_zone --dns-name my.zone.com. --description "My zone!"). How would would this be done in the plugin?

**Comment by ProbStub** [comment]
I think I found the feature and would propose to close the request. Cloud Shell (on PyCharm) can be found in: Tools -> Cloud Code -> Tools -> Cloud Code Terminal

**Comment by etanshaul** [comment]
hi @ProbStub thanks for the ticket. I see, so your aim here was to be able to run commands from a terminal (using the cloud code managed dependencies)? Just want to make sure we aren't missing anything. Will close in the meantime, but feel free to follow up.
