### ISSUE TITLE
Cannot patches sample projects from New Project Wizard

### ISSUE THREAD

**Issue by wonsuc** [GoogleCloudPlatform/cloud-code-intellij#2970]
When I try to open a new project from samples on New Project Wizard.

It shows this error message.

```
Error fetching Cloud Code samples. Please ensure network is available, and try opening the New Project Wizard again, or clone the Cloud Code Samples repository:
```

I'm not sure if it's the reason but my company blocked "https://cloud.google.com" from web browsers.

Nevertheless, `gcloud init` or `gcloud projects list` commands work on CLI.

My company's network is behind a proxy.

**Comment by ivanporty** [comment]
We use `https://github.com/GoogleCloudPlatform/cloud-code-samples` to store our samples, does your company block github in general or this specific project? It would be also interesting to take a look at your IDE logs (`Menu -> Logs -> Show Logs in Finder`). In the meanwhile, if you can access the mentioned repository, you can try cloning it manually and try some of the samples from there directly.

**Comment by wonsuc** [comment]
Thanks for the reply. 
I added a certification of `github.com:443` to my `C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.2\jbr\lib\security\cacerts` and it's working now!
