### ISSUE TITLE
Link not up

### ISSUE THREAD

**Issue by yishengshimeng** [GoogleCloudPlatform/cloud-code-intellij#2986]
Can’t connect, please log out of my account, I don’t need it anymore

**Comment by ivanporty** [comment]
@yishengshimeng could you please provide more details and step how to reproduce your issue? Version of the Cloud Code plugin and your JetBrains IDE could be helpful as well.

**Comment by emmanuelbaah** [comment]
Please let us know if you encounter the issue again
