### ISSUE TITLE
Missing node.js Cloud run from Pycharm Professinal edition

### ISSUE THREAD

**Issue by Baluditor** [GoogleCloudPlatform/cloud-code-intellij#2989]
Hi,

I've installed the plugin yesterday to my PyCharm (Professional Edition) and I can't find the way to start a new Cloud Run project with node.js.  I've checked with my Webstorm, there I can see the option. 

### Expected Behavior
I can create a node.js Cloud Run project with my PyCharm (Professional Edition)

### Actual Behavior
I can't create a node.js Cloud Run project. 

- IDE type: PyCharm (Professional Edition)
- IDE version: PyCharm 2021.2.1 (Professional Edition) Build #PY-212.5080.64.
- Cloud Code version (Settings > Plugins > Cloud Code): 21.9.2.
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes.
  - Version of the Cloud SDK: 356.0.0.
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): N/A.
- Operating System: Windows 10.
![image](https://user-images.githubusercontent.com/34071416/133208818-36dc38b0-1c08-4d82-84f8-2609b001541d.png)

**Comment by matthewmichihara** [comment]
Thanks for the report. We shouldn't be filtering out NodeJS here if you have the NodeJS plugin installed. We'll try to fix.

In the meantime, you can either directly clone the nodejs cloud run sample code from https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/nodejs/nodejs-cloud-run-hello-world, or clone first with WebStorm then open in PyCharm.

**Comment by Baluditor** [comment]
Thank you for the suggestion, Matthew.

**Comment by etanshaul** [comment]
Notes from triage: workaround identified, but core problem still exists. May add to next sprint.

**Comment by peterlin741** [comment]
closing, since we already have a workaround
