### ISSUE TITLE
Explore Improving UX for Kubernetes Artifact Table

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2995]
## Cloud Code users, we are looking for your feedback and current experience on artifact table!

This exploration will aim to improve the user experience, ease of use, UI layout, and look and feel of the artifact table in Kubernetes run configurations for new and current users. 

### Current Design

<img width="883" alt="Screen Shot 2021-09-21 at 11 21 49 AM" src="https://user-images.githubusercontent.com/11686100/134199314-9aca29c1-9c6a-466c-9955-7f6080c81ddb.png">

The artifact table is located in the Build/Deploy tab, below the selectors for `skaffold.yaml` configurations and skaffold profiles.
The table lists the images that are built by skaffold, the builders used for that (i.e. Docker, Buildpacks, Jib), and additional builder information (second column). For default profile, one can click edit icon and change the builder type (i.e. `Dockerfile` -> `Buildpacks`)

Items we're looking to explore are below.

**Comment by peterlin741** [comment]
sounds good, we'll keep this in mind as we go through the manifest generation UX mocks

**Comment by ivanporty** [comment]
### A. Replace table with a statically looking image list

Table looks confusing and editing builders seems to be a rare activity, used mostly when creating / initializing project task. Selecting a builder is still a part of Cloud Code Kubernetes bootstrapping.

Instead of the table, have a static list of images built by skaffold, with no editing, and reduced size/visibility.

**Comment by ivanporty** [comment]
### B. Keep the artifact table, improve table representation and actions

Move edit button into the table, as a cell. 
Split second column into more cells, with builder, context, additional information cells.
Add more description and links on top of the table to clarify its functionality.

**Comment by ivanporty** [comment]
### C. Remove the artifact table completely

Assume images built are visible from `skaffold.yaml` configuration(s), and most users edit `skaffold.yaml` manually anyway to change their builder type and its settings.
