### ISSUE TITLE
getting hash for artifact ... getting hash for "node_modules\\.bin\\btoa": open node_modules\.bin\btoa: Das System kann auf die Datei nicht zugreifen.

### ISSUE THREAD

**Issue by black-snow** [GoogleCloudPlatform/cloud-code-intellij#3007]
✅ (Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 21.10.1
- Google Cloud SDK version: 360.0.0
- OS: Windows 10 10.0

**What did you do?**

Run a Cloud Run deployment via IntelliJ Cloud Code Plugin.

**What did you expect to see?**

Image built & deployed.

**What did you see instead?**
> Preparing Google Cloud SDK (this may take several minutes for first time setup)...
>
> Creating skaffold file: C:\Users\xxx\AppData\Local\Temp\skaffold1003598795432080873.tmp...
>
> Configuring image push settings in C:\Users\xxx\AppData\Local\Temp\skaffold1003598795432080873.tmp...
>
> Authenticating Artifact Registry repository...
>
> C:\Users\xxx\AppData\Local\cloud-code\bin\versions\0991fad040597caf6507a2978b6c8aefecf577549a14fdeabf5050cc920bc043\skaffold.exe build --filename C:\Users\xxx\AppData\Local\Temp\skaffold1003598795432080873.tmp --tag latest --skip-tests=true
> Generating tags...
> - europe-west3-docker.pkg.dev/xxx -> europe-west3-docker.pkg.dev/xxx:latest
> Checking cache...
> - europe-west3-docker.pkg.dev/xxx: Error checking cache.
> getting hash for artifact "europe-west3-docker.pkg.dev/xxx": getting hash for "node_modules\\.bin\\btoa": open node_modules\.bin\btoa: Das System kann auf die Datei nicht zugreifen.
> 
> Failed to build and push Cloud Run container image. Please ensure your builder settings are correct, network is available, you are logged in to a valid GCP project, and try again.

There's nothing fancy about my settings imo; a service account is set, build env is local (not cloud build), buildpacks, build.gradle

**Comment by peterlin741** [comment]
In the run configurations for cloud run, you'll want make sure the url format is correct. Your url should have the following format: `https://europe-west3-docker.pkg.dev/{PROJECT_ID}/{REPO_NAME}/{IMAGE_NAME}`

For example, I am using:
![image](https://user-images.githubusercontent.com/58699538/137526449-1abf9758-72fc-4311-ada1-a21704a9c1c9.png)

You can get this url from the GCP console:
![image](https://user-images.githubusercontent.com/58699538/137526806-21a8df38-ae2e-46f7-b678-75fd9a06331e.png)

Please note that unlike kubernetes deployments, you'll have to append an `{IMAGE_NAME}` to the url (which can be named anything).

If this doesn't work, please also check if you have the correct permissions configured on your service account by following: https://cloud.google.com/artifact-registry/docs/access-control#grant
