### ISSUE TITLE
Setting breakpoint in Kotlin code asks to set a Java line breakpoint

### ISSUE THREAD

**Issue by rocketraman** [GoogleCloudPlatform/cloud-code-intellij#3009]
### Expected Behavior

When I set a breakpoint in Kotlin code using the IntelliJ IDEA EAP (2021.3), the breakpoint is set normally.

### Actual Behavior

When I use the IntelliJ IDEA EAP (2021.3), and I set a breakpoint in Kotlin code with the Google Cloud Code plugin active, I get a dialog box like this:

![image](https://user-images.githubusercontent.com/53049/137992907-aa793006-cd46-4d43-9eb2-cfb47d7b3f2a.png)

There is no java code here, so this dialog box is spurious.

If the Google Cloud code plugin is disabled, the breakpoint is set without ceremony as expected.

This issue was originally reported at https://youtrack.jetbrains.com/issue/KTIJ-19911, but moved here once the issue was isolated to Google Cloud Code.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): `IntelliJ`
- IDE version: `IU-213.4928.7, JRE 11.0.12+7-b1729.1x64 JetBrains s.r.o., OS Linux(amd64) v5.12.6-200.fc33.x86_64, screens 2560.0x1440.0, 2560.0x1440.0, 2560.0x1440.0`
- Cloud Code version (Settings > Plugins > Cloud Code):  `21.10.1`
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: `No`
  - Version of the Cloud SDK: `360.0.0`
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): n/a
- Operating System: `Linux 5.12.6-200.fc33.x86_64 #1 SMP Sat May 22 20:43:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/4882)

**Comment by etanshaul** [comment]
fixed in release `21.11.1`
