### ISSUE TITLE
Cloud Run: Docker not detected properly on Windows 

### ISSUE THREAD

**Issue by ilpersi** [GoogleCloudPlatform/cloud-code-intellij#3041]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

### Expected Behavior
When I run the "Cloud Run: Run Locally" configuration, my project is deployed and run locally

### Actual Behavior
Plugin is complaining that Docker is missing with the following message

It looks like you don't have Docker installed. Please install and start Docker to use this feature.

Below an example of the error. As you can see from the same screenshot, Docker is correctly installed and running.

![image](https://user-images.githubusercontent.com/43588107/145385436-736ffb0a-827b-4044-b5a1-45f625fcfc7d.png)

![image](https://user-images.githubusercontent.com/43588107/145386496-bf271ee4-629c-455b-a2db-bfb533c57a6a.png)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Pycharm
- IDE version: 2021.3
- Cloud Code version (Settings > Plugins > Cloud Code):  21.11.2-213
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: I am using a custom local installation path
  - Version of the Cloud SDK: 366.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): I am not using this
- Operating System: Windows 10

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/5183)

**Comment by etanshaul** [comment]
thanks @ilpersi we are looking into a workaround for the next release coming very soon. The issue appears to be that our Docker detection is not reliable on Windows - incorrectly assuming that Docker is missing when it is actually installed. In the short term we might update the logic to simply warn and not block - as your Cloud Run session should work despite this invalid detection warning.

**Comment by ilpersi** [comment]
@etanshaul I am not sure if this can help. I just tested on Pycharm 2021.2.3 (same machine, parallel installation) and Docker detection is working flawlessly.

**Comment by etanshaul** [comment]
also windows?

**Comment by etanshaul** [comment]
@ilpersi please try this out on the just release version `21.12.1-xxx` where this issue should be resolved, and let us know if you still have any issues. Closing in the meantime. Thanks.

**Comment by ilpersi** [comment]
@etanshaul wow, this was fast! 👍🏻 
Thank you very much for this, it works like a charm now on 21.12.1-213
