### ISSUE TITLE
Support for Jetbrains gateway

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#3057]
### Discussed in https://github.com/GoogleCloudPlatform/cloud-code-intellij/discussions/3056

<div type='discussions-op-text'>

<sup>Originally posted by **chattarajoy** February 23, 2022</sup>
Are there any plans to support this on Jetbrains gateway? 

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/8450903/155319250-03260f4f-c006-4eb7-92e7-fbcdc0448d9a.png">
</div>

**Comment by etanshaul** [comment]
comment copied over from discussion:

Hey @chattarajoy yes, it is on our radar. We haven't yet done the investigation to see what it would take to support it properly. I am going to migrate this to an issue to track the effort and provide updates when we have them. Thanks for the request.

**Comment by nelsonjchen** [comment]
Hopefully this has pinged again on that radar? 

https://blog.jetbrains.com/idea/2022/10/remote-development-in-jetbrains-ides-now-available-to-google-cloud-workstations-users/

https://cloud.google.com/workstations/docs/develop-remotely-with-jetbrains-ides

**Comment by nelsonjchen** [comment]
<img width="1094" alt="Screen Shot 2022-10-24 at 11 30 12 AM" src="https://user-images.githubusercontent.com/5363/197599259-b1df3c57-2363-4281-81d9-2aee006f5105.png">

Huh, looks like it's already there on Google Cloud Workstations.

**Comment by etanshaul** [comment]
Hi @nelsonjchen yep you are right - we very recently made Cloud Code work with Gateway in support of the recently launched Cloud Workstations product (https://cloud.google.com/workstations).

While Cloud Workstations is the only "officially" supported backend at the moment (we'd love any feedback!), there is nothing preventing you from installing Cloud Code on a backend IDE running elsewhere.

Also to note: we have 1p support for initiating remote development sessions from Gateway to Cloud Workstations using this new Gateway plugin: https://plugins.jetbrains.com/plugin/19900-cloud-workstations

**Comment by etanshaul** [comment]
And here is a link to the blogpost of the announcement: https://blog.jetbrains.com/idea/2022/10/remote-development-in-jetbrains-ides-now-available-to-google-cloud-workstations-users/

**Comment by etanshaul** [comment]
I am going to close this issue and use this as an announcement to followers that Cloud Code now supports remote development on Cloud Workstations via JetBrains Gateway! Link to blog point announcement above.

If you have any questions / feedback please reach out.

**Comment by nelsonjchen** [comment]
Haven't had much if any time to run and play with it.

That said, I wish the pricing per workstation cluster aligned with other "cloud workstation" products and you didn't have to pay for a cluster; my suggestion on that would be to match GKE and make the first cluster free. An offering like that would make it much more palatable for the personal lab instead of a constant ~$140/mo drain which no other "cloud workstation" imposes. Super big chilling effect. Anyway, that's not on Cloud Code for IntelliJ itself, it's more on the product. 

Other than that, I like what I see, and of course there are bugs, but I hope they get worked out. As for this issue, looks good to close to me!

**Comment by etanshaul** [comment]
Thanks for that initial feedback. I will pass that on to the Cloud Workstations PM and team.
