### ISSUE TITLE
Cannot choose deployment profile

### ISSUE THREAD

**Issue by vesperusiak** [GoogleCloudPlatform/cloud-code-intellij#3065]
### Expected Behavior
After choosing the scaffold configuration in the dialog. I can choose a deployment profile.

### Actual Behavior
<img width="1038" alt="Screenshot 2022-03-11 at 15 53 25" src="https://user-images.githubusercontent.com/1943070/157891207-b2d73466-2166-4902-bdd6-d544a6611766.png">

When I choose a configuration (configurations work ok on different machine) nothing happens. There is a message: "Invalid Data: Select or create a skaffold profile on the Build/Deploy tab". I cannot select/add profile even though configuration was choosen.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): GoLand
- IDE version: 2021.3.3
- Cloud Code version (Settings > Plugins > Cloud Code): 22.2.1-213
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK: 376.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.34.0
- Operating System: mac os Catalina 10.15.7

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
hi @vesperusiak thanks for reporting. Is this still happening?

You mentioned:

> configurations work ok on different machine

So I'm wondering maybe if this was a transient error. 

If you can still reproduce, could you maybe share relevant snippets from the IDE logs? You can access them from the Help menu: `Help > Show Log in Editor`, and then trigger this failure and hopefully there should be some information in the logs.

**Comment by vesperusiak** [comment]
The issue is solved. The problem was that I installed gcloud outside the Goland, it somehow broke the tool. Before writing this issue I removed the outside gcloud installation so in logs i found only calls to non existing gcloud installation. Cleanup after old installation and reinstall of the tool helped.

**Comment by vesperusiak** [comment]
@etanshaul There is another thing. I uninstalled gcloud, followed all steps here: https://cloud.google.com/sdk/docs/uninstall-cloud-sdk and installed it again in different folder. The cloud code still tries to use the old version though (in old location). From where the Cloud Code takes gcloud location? I would like to change the entry there.

**Comment by etanshaul** [comment]
hey @vesperusiak. Yeah, by default Cloud Code will use its own managed dependencies.

However, you can update this in the Preferences under Tools > Cloud Code > Dependencies:
<img width="803" alt="Screen Shot 2022-03-24 at 11 55 59 AM" src="https://user-images.githubusercontent.com/1735744/159957781-039ce91e-44ce-421e-9570-0b03b10535c8.png">

To use your own Cloud SDK installation, select `Use a custom local isntallation` and browse to it.

**Comment by vesperusiak** [comment]
Ok, so i selected `Use a custom local installation`, used a new one, existing installation, but it still uses the old one. The error msg says:
`error executing access token command "/Users/idego/Documents/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /Users/idego/Documents/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=`
the error pops up when i try to run/debug with cloud code: Kubernetes config at stage when it starts deploy.

**Comment by vesperusiak** [comment]
Sure, the path that i entered is `/Users/idego/google-cloud-sdk`.

**Comment by etanshaul** [comment]
Thank you. That is odd. I will try to reproduce this.

**Comment by etanshaul** [comment]
Silly question. But if you go back into your settings, to view the path saved under `Use a custom local installation`, does it show the one under `~/google-cloud-sdk` or `~/Documents/google-cloud-sdk`?

I cannot reproduce this. I'm asking the above in case something didn't get persisted and saved properly.

**Comment by jwgvandenberg** [comment]
I have this same issue on IntelliJ IDEA 2021.2.4 (Ultimate Edition). It tells me to select a profile, but that dropdown is greyed out.
The plugin was installed from within IntelliJ in my case though. I have tried reinstalling the plugin anyway, but to no avail. Currently therefore on version 22.4.2-212 of the plugin, though the problem started appearing before (not sure exactly from what version on)
