### ISSUE TITLE
Latest version of the cloud plugin doesn't work with Java 8

### ISSUE THREAD

**Issue by nivsa** [GoogleCloudPlatform/cloud-code-intellij#3077]
Latest version of the cloud plugin doesn't work with Java 8

After upgrade IJ fails on:
```
Cause: com/google/cloud/tools/intellij/appengine/java/gradle/AppEngineGradleModel has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Let me know if you need more info

**Comment by etanshaul** [comment]
@nivsa thanks for the report. Could you please share exactly which features / steps you were following to encounter this error? Thanks.

**Comment by etanshaul** [comment]
@Zweib thanks for the details. To follow up - were you trying to use any Cloud Code specific features (like deployment to App Engine), or did this happen just as part of your "normal" workflow (not using Cloud Code).

**Comment by etanshaul** [comment]
Update: I can reproduce this. We are investigating a fix and will put one out as soon as possible.

**Comment by emmanuelbaah** [comment]
Please update to version 22.4.2 for the fix. I'll be closing this but feel free to reopen if this issue persists.

**Comment by atrujillofalcon** [comment]
Its reproducible again with Cloud Code 23.4.3-222 and Gradle JVM 1.8

IntelliJ 2023.1.1 Ultimate Edition
