### ISSUE TITLE
Intellij fails to recognize successfull authentication, despite firefox reaching auth_success

### ISSUE THREAD

**Issue by signal1** [GoogleCloudPlatform/cloud-code-intellij#3081]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Ide: Intellij (version:Build #IU-221.5591.52, plugins:Cloud Code (version:22.4.2-213) )
- Brower: Firefox (version:100.0, plugins:none, settings:default)
- OS: Windows 10 10.0

**What did you do?**
1) Attempted to create Cloud Run configuration.. ide / plugin seem unaware of brower having opened and successfully authenticated.
2) Also attempted (intellij > Tools >  Cloud Code > Sign Into Google) which also does not seem to recognize browerser's successfull authentication (reached auth_success)

**What did you expect to see?**
Intellij Ide plugin to either 1) acknowledge successfull login, or 2) display an error detailing what failed, or what my next steps should be.  Lastly, I would also expect the IDE status bar to also reflect something other than "Sign in via opened browser... " after I have already signed in. 

**What did you see instead?**
Intellij Ide plugin to either 1) acknowledge successfull login and function, or 2) display an error detailing what failed or what I should do to proceed.  I would also expect the IDE status bar to also reflect something other than "Sign in via opened browser... " after I have signed in. Lastly, if the above are not possible, perhaps indicate in the ide's log where things are or where they may have gone wrong?

**Comment by signal1** [comment]
![image](https://user-images.githubusercontent.com/479700/170802577-b4c11229-c29c-4a4f-9b9d-a0b981cc5894.png)
![image](https://user-images.githubusercontent.com/479700/170802592-5c6bbc8a-ca1a-429c-a2a2-b433511fe133.png)

**Comment by signal1** [comment]
2022-05-27 20:43:53,866 [3293823]   INFO - #c.g.c.t.i.k.s.SkaffoldTrackingStartupActivity - updating skaffold session for helpme-world-1 due to login status change
2022-05-27 20:44:07,304 [3307261]   INFO - #c.i.c.ComponentStoreImpl - Saving appFileTypeManager took 15 ms, XDebuggerSettings took 15 ms
2022-05-27 20:44:09,411 [3309368]   INFO - #c.i.c.ComponentStoreImpl - Saving appEditorColorsManagerImpl took 15 ms, ProjectCreationInfoState took 16 ms
2022-05-27 20:44:21,348 [3321305]   INFO - #c.i.i.a.RevealFileAction - Exit code 1

**Comment by signal1** [comment]
Suspect the issue is related to the browser's https only mode being enabled. After disabling, & restarting intellij, attempt to authenticate succeeded.

**Comment by FlorianSchaetz** [comment]
Unfortunately, I can report that this issue happens without "https only mode" enabled in firefox. I don't have this feature enabled in my Firefox and the issue is happening.
