### ISSUE TITLE
Cannot debug Multi config in different namespaces

### ISSUE THREAD

**Issue by JJRdec** [GoogleCloudPlatform/cloud-code-intellij#3089]
### Context

- Using [multi config](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/multi-config-microservices) setup with deployments in separate namespaces. 
- Using Cloud Code Kubernetes debug feature
- Local Kubernetes cluster
- Spring boot applications 

### Expected Behavior

Be able to debug both applications in different namespaces.

### Actual Behavior

Only one application can be debugged.

We can see only one app debug session starts for core-app and not identity-app

![CC-kube-debugpng](https://user-images.githubusercontent.com/94698858/184376760-d241756e-b882-4c3e-bebf-72dc9eeaec64.png)

Debugging will work if use skaffold setup like this [example ](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/microservices). But this is not an option for us as we need microservice (projects repos) to be independent. 

Here it is working with my use case
![184379224-5ea4638e-f3d0-4717-bd0f-bba717181c46](https://user-images.githubusercontent.com/94698858/184385215-0977991d-6588-436b-a121-536fc31c371b.png)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ
- IDE version: 2022.1.3 (UE)
- Cloud Code version (Settings > Plugins > Cloud Code): 22.8.1-221
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 397.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 1.39.1
- Operating System: Windows 11 (10.0.22000)

### Reproduce

1. Create a project similar to [multi config](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/multi-config-microservices).
2. Have sub projects deploy into separate namespaces.
3. Start debug session

PS: This is most likely a skaffold issue but it is affecting Cloud Code features. See issue [here](https://github.com/GoogleContainerTools/skaffold/issues/7660)

**Comment by ivanporty** [comment]
Thanks @JJRdec! Most likely this is related to skaffold, and thanks for filing an issue in skaffold repo as well. We'll investigate more.

**Comment by ivanporty** [comment]
Closing as this use case is not a planned feature for Cloud Code for now.
