### ISSUE TITLE
Support multiple skaffold profiles in run config

### ISSUE THREAD

**Issue by wollowizard** [GoogleCloudPlatform/cloud-code-intellij#3092]
It would be nice to be able to select multiple skaffold profiles in the Cloud code: Kubernetes Run configuration, Build/Deploy tab.
As of now, only one profile can be chosen, but of course skaffold supports multiple profiles.
<img width="993" alt="image" src="https://user-images.githubusercontent.com/2480280/186128443-a5f3570f-ab0e-4e39-b9d8-82023be7e406.png">

For now, I found a workaround by defining an environment variable in the run configuration, and setting an activation rule for the 2nd profile that checks that environment variable.

**Comment by peterlin741** [comment]
Thanks for the feature request, We are tracking this in https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2748

Will close out this issue as a duplicate
