### ISSUE TITLE
Unknown skaffold config API version "skaffold/v3"

### ISSUE THREAD

**Issue by iosifnicolae2** [GoogleCloudPlatform/cloud-code-intellij#3112]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 22.10.1-222
- Google Cloud SDK version: 406.0.0
- OS: Mac OS X 13.0

**What did you do?**
Run a skaffold run configuration using v3 schema.

**What did you expect to see?**
I would expect the skaffold manifest to be deployed in Kubernetes.

**What did you see instead?**
I've received the following error:
```
/Users/XXX/Library/Application Support/cloud-code/bin/versions/a18f8fc090f126823b72f4df8f514da5333fe2c07f467d5851a471cd7267682a/skaffold dev --filename skaffold-postgres-db.yaml --label ide=idea --label ideVersion=2022.2.3.0.0 --label ijPluginVersion=22.10.1-222 --cleanup=false --auto-build=false --auto-deploy=false --auto-sync=false --default-repo dev-registry.c1.r.b.XXXX.app --rpc-port 50051 --port-forward=true --wait-for-deletions-max=2m0s --status-check=true --verbosity warn
parsing skaffold config: error parsing skaffold configuration file: unknown skaffold config API version "skaffold/v3". Set the config 'apiVersion' to a known value. Check https://skaffold.dev/docs/references/yaml/ for the list of valid API versions. Otherwise, check that your skaffold version is up-to-date.
```

**Comment by iosifnicolae2** [comment]
I've solved the problem by pointing Cloud Code to the latest skaffold binary:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/7108834/198851699-20af2a8d-26ff-436b-999b-0e88813fc710.png">

**Comment by etanshaul** [comment]
@iosifnicolae2 thanks for the update. We are in the process of update Cloud Code in general to work with Skaffold V2, so you may still hit a couple bugs here. Once we make these updates, we will also update Cloud Code to bundle the latest version of Skaffold.

**Comment by etanshaul** [comment]
just circling back here that Cloud Code officially supports and bundles skaffold v2. Closing the issue (feel free to reach out with any other questions).
