### ISSUE TITLE
Compute Engine 'All VM Instances' Won't Load

### ISSUE THREAD

**Issue by jbeatty88** [GoogleCloudPlatform/cloud-code-intellij#3119]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 22.12.1-222
- Google Cloud SDK version: 412.0.0
- OS: Mac OS X 13.0.1

**What did you do?**
'All VM Instances' for Compute Engine stops loading and the only way to get it to work again, though briefly, is to completely close the IDE and re-open it. It happens more frequently when multiple file project windows are merged but I've also observed it when the project windows are separate as well. It has happened when switching between cloud projects as well.

'Favorite VM Instances' usually seems to be solid though.

**What did you expect to see?**
The full list of VM instances for the selected project

**What did you see instead?**
A frozen spinner next to the 'All VM Instances' that never loads.

![image](https://user-images.githubusercontent.com/37627395/207658342-45338581-7921-473d-b620-3283564eecc8.png)

**Comment by ivanporty** [comment]
Thank you for the report @jbeatty88! Do you see any exceptions in the IDE log file (Help -> Show Logs.. -> idea.log)?

A bit more clarity for this could also help:
> It happens more frequently when multiple file project windows are merged

Could you please give us detailed steps on how you merge your project windows so we could try to reproduce more easily?

**Comment by jbeatty88** [comment]
Thanks for the reply!

I don't see any exceptions coming from the Cloud Code plugin in the logs however, I do have a more clear path to consistently reproduce the issue:
1. Open multiple project windows (in my case, I had 2 GoLand windows open)
2. In one of the windows, open the Cloud Code Compute Engine tab and select a project
3. Right click a VM and 'Open SSH connection'
4. Wait for the terminal to pop up with a connection to the VM
5. Now select a different Google Cloud project
6. All VM Instances stuck loading 
![image](https://user-images.githubusercontent.com/37627395/209410780-28719644-3ad4-43c3-99c3-fea1cc198f71.png)

As for the merging of the project windows, this currently does not exist for the new UI but here is how I used to do it:
* Window -> 'Merge All Project Windows'
> Note: even without their merge-all-project-windows feature, with those steps above I can get the 'All VM Instances' to freeze

**Comment by ivanporty** [comment]
Thank you for reproducing this! We are looking into this and once prioritized, we'll let you know. In the meanwhile, if you don't mind, what is the specific use case for you to change GCP projects while keeping the SSH open - do you need multiple SSH sessions between various GCP projects?

**Comment by jbeatty88** [comment]
No problem! Dang, bummed my repro steps didn't work for you. I am able to switch projects in a single GoLand window and have the 'All VM Instances' load unless I have another GoLand window open for a separate project that has connected to a GCP Compute Engine instance. 

* No specific/special circumstances for any of these projects
* No but I can still see the list of favorites.. the full list of VMs stays like this: 
![image](https://user-images.githubusercontent.com/37627395/212956318-28b5a6bf-e056-4fb5-86e4-05394a256e88.png)
* Never more than 2

While in the same project, I typically don't have a need to change GCP projects; usually its after opening a new GoLand instance for a project that uses resources in a different GCP project and then when I try to change to the GCP project in the new window, I can't get the full list of VMs. I do occasionally need multiple sessions between various GCP projects but not regularly.
