### ISSUE TITLE
Incompatible: requires IDE build 223.6646.* or earlier

### ISSUE THREAD

**Issue by tygern** [GoogleCloudPlatform/cloud-code-intellij#3120]
**Version Information**

JetBrains Gateway version: JetBrains Gateway 2022.3 (Build #GW-223.7571.203, built on November 30, 2022)

Cloud Workstations plugin version: 22.10.4-api-version-222

**Details**

I'm not able to enable the plugin and I see this error: "Incompatible: requires IDE build 223.6646.* or earlier"

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1655826/208345402-d2b8ac3c-f316-4e31-9250-c21ce183b2e4.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1655826/208345455-b9eff796-e191-45c0-98df-066490868c01.png">

**Comment by etanshaul** [comment]
@tygern I assume you solved this, but for anyone else that might face this:

the latest plugin update for Cloud Workstations supports all 2022.3 versions: `22.11.1-7255-api-version-223`
