### ISSUE TITLE
Can't Create appengine-web.xml

### ISSUE THREAD

**Issue by rwbcwhite** [GoogleCloudPlatform/cloud-code-intellij#3126]
IU-223.8214.52, JRE 17.0.5+1-b653.23x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 , screens 1200.0x1920.0, 5760.0x3240.0

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ Ultimate
- IDE version: 2022.3
- Cloud Code version (Settings > Plugins > Cloud Code): 22.12.2-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK: 413.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes):  n/a
- Operating System: Win10

After creating a new project (java) and immediately using "Add Framework Support" to add

- Java EE / Web Application
- Google App Engine Standard (all libs)

I get the following notification:

> Error generating appengine-web.xml
>
> There was an error generating the appengine-web.xml file for App Engine standard support. Some operations such as deploy and
> local-run may not work properly. Please try again or generate the file manually in the WEB-INF directory of your module's web
> resource directory. If you are using Maven or Gradle, make sure to first sync the project with IDEA by pressing refresh in the
> corresponding tool window.

There's no indication of the actual error encountered.

It would be nice if the error message also specified how to generate the file manually.

(originally posted on [IntelliJ YouTrack](https://youtrack.jetbrains.com/issue/IDEA-310886))

**Comment by ivanporty** [comment]
Thanks for the report @rwbcwhite! A few more details could be helpful - do you create a completely new, empty Java EE app? Where do you add `Google App Engine Standard (all libs)` - when creating an application, or later using a notification / menu to add AppEngine support?

**Comment by rwbcwhite** [comment]
It was a just-created project and the very first thing was "Add Framework Support" from the project's context (right-click) menu.

**Comment by ivanporty** [comment]
Thanks! It seems there is some incompatibility in the newer platform code that causes an error when generating. We'll be working on the fix once we identify it. As a workaround, please add appenging configuration file manually (as a simple example https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/appengine-java8/helloworld/src/main/webapp/WEB-INF).
