### ISSUE TITLE
Cloud run deploy not loading regions

### ISSUE THREAD

**Issue by therealmarktully** [GoogleCloudPlatform/cloud-code-intellij#3127]
I updated to the latest version of IJ and updated my plugins and when I try and deploy previously working deployment, after selecting my Google project and google account, Loading regions never finishes. 

### Expected Behavior
Loading Regions should display a list of regions for me to choose from

### Actual Behavior
when I open my Run/Debug for Cloud Code: Cloud Run. I am logged in to a GCP Project but the loading regions process never finishes and as a result I cannot deploy from intellij.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ IDEA 
-  
- IDE version:  2022.3.1 (Ultimate Edition: Build #IU-223.8214.52

- Cloud Code version (Settings > Plugins > Cloud Code):  22.12.1-IB.3 (Insiders Release)
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  yes
  - Version of the Cloud SDK:  415.0.0
  -   -   - 
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System:  Windows 11

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
There is a known issue with the platform compatibility in 22.12.1-IB.3. We are preparing a new release (including insiders) which will fix this, it is coming soon. Thank you for your report!

**Comment by therealmarktully** [comment]
Thanks Ivan, apologies if I missed the previously reported issue.  Is there a recommendation on a work-around?  can I downgrade, the plugin, IDE or SDK?

**Comment by ivanporty** [comment]
For now only downgrade would work -  IB.2 - you will need to download it manually unfortunately - https://plugins.jetbrains.com/plugin/8079-cloud-code/versions/insiders/274191. We are very close to releasing the new version, and you can update to 22.3.1-IB or regular once it's out. Please let us know if the issue goes away

**Comment by ivanporty** [comment]
@therealmarktully we have just released 23.1.1 and it should fix the issue that you were seeing. Please try to update (insiders release has been updated as well) and let us know if you issue is fixed.

**Comment by ivanporty** [comment]
We are going to close this issue for now assuming this is fixed. Please reopen if it's not.
