### ISSUE TITLE
Cloud Code Custom Sample is not being added

### ISSUE THREAD

**Issue by gustavostz** [GoogleCloudPlatform/cloud-code-intellij#3129]
I'm experiencing an issue with the Cloud Code Custom Sample feature.

When I try to add a custom sample, such as the repository at https://github.com/GoogleCloudPlatform/cloud-run-microservice-template-java, the cloning process starts but the screen remains frozen on the modal for adding a repository. The cloning process finishes in the background, but there's no success or error message displayed.

![image showing the modal frezzed and the loading of the cloning of the repository](https://user-images.githubusercontent.com/48111506/216143222-caedf603-c301-4da9-9178-39be57b1d39e.png)

After the clone process finish in the background, the modal stay frozen forever:

![image of the modal frozen](https://user-images.githubusercontent.com/48111506/216146819-af91400c-02e0-483b-90a9-0a0925d4fe83.png)

### Versions:

**Cloud Code (Settings > Plugins > Cloud Code):** 23.1.1-222

**IntelliJ IDEA 2022.3.1** (Ultimate Edition)

### Additional Information:

**Operating System:** Windows 11

**Cloud SDK (Settings > Cloud Code > Cloud SDK):** "Allow the plugin to manage and install the Cloud SDK"

**Comment by ivanporty** [comment]
Thank you for the report, we'll be looking into this shortly.

**Comment by ivanporty** [comment]
We cannot reproduce this issue when adding repo from the settings, with a project already open in background. Could you please clarify when it happens for you - when you try creating a new project, and add custom sample from there?

**Comment by gustavostz** [comment]
After upgrading IntelliJ IDEA 2022.3.1 (Ultimate Edition) to IntelliJ IDEA 2022.3.2 (Ultimate Edition), the error stopped occurring. So I will close the issue. Thanks for the response.
