### ISSUE TITLE
No App Engine Project Creation

### ISSUE THREAD

**Issue by ReelMan25** [GoogleCloudPlatform/cloud-code-intellij#3130]
I have intellij 2022.3.2.  Trying to follow documentation I have the "latest and greatest" for the Cloud Code plugin.  There doesn't seem to be the option to create a new App Engine project:
![image](https://user-images.githubusercontent.com/70004492/216148295-c2e82a33-8ad7-4acc-82bb-98302adbf439.png)

**Comment by ivanporty** [comment]
What exactly is missing in the list of sample project according to the documentation source you're using, could you give us a link to them please?

**Comment by ivanporty** [comment]
If this is here https://www.jetbrains.com/help/idea/2022.2/getting-started-with-google-app-engine.html, it's not Google Cloud Code, but Jetbrains AppEngine plugin. However, support for AppEngine in both Google Cloud Code plugin and Jetbrains plugin is limited, and we recommend you to take a look at our Cloud Run support as an alternative (https://cloud.google.com/code/docs/intellij/deploy-cloud-run-app)

**Comment by ivanporty** [comment]
There is no more Java EE / App Engine projects in the list of new projects. We just updated our documentation to reflect how to create new AppEngine project using Jakarta EE (replacement for Java EE) option, web application, and adding support via Cloud Code menu items.

See IntelliJ details here https://www.google.com/url?sa=D&q=https%3A%2F%2Fwww.jetbrains.com%2Fhelp%2Fidea%2Fcreating-and-running-your-first-java-ee-application.html

See updated documentation here https://cloud.google.com/code/docs/intellij/create-standard
