### ISSUE TITLE
Feature - Add ApigeeX support  (similar to vscode) 

### ISSUE THREAD

**Issue by gosunilgo** [GoogleCloudPlatform/cloud-code-intellij#3132]
### Expected Behavior

Please include support for apigeeX development -  Similar to vscode experience, which users can 

- Author apiproxies
- Create KVM, api-keys, developers, apiproducts
- Deploy to Apigee Emulator 

### Additional Information

see vscode link - https://github.com/GoogleCloudPlatform/cloud-code-vscode

-IntelliJ 2023 
- Latest cloud Code 

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
Thanks for the request @gosunilgo . This is not on our near term roadmap, however we will log this request and take into consideration for future planning.

**Comment by gosunilgo** [comment]
thanks @etanshaul
