### ISSUE TITLE
Copying from VM information table

### ISSUE THREAD

**Issue by mjste** [GoogleCloudPlatform/cloud-code-intellij#3134]
### Expected Behavior

When clicking on VM instance in Compute Engine -> All VM Instances -> <instance> I can see below table with General Information with values below instances list.
->When I select IP address of VM instance I can copy IP address. Just four numbers with dots e.g. 8.8.8.8

### Actual Behavior

->When I select IP address I copy whole value in format 
(Copying to this browser text editor field)
"<html>
<body>

nic0 - internal IP | 8.8.8.8
-- | --

</body>
</html>"

or copying to notepad
"nic0 - internal IP	8.8.8.8"

### Additional Information

- IDE type = IntelliJ
- IDE version: 2023.1 Ultimate
- Cloud Code version: 23.3.3-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  Yes
  - Version of the Cloud SDK: 427.0.0
- Operating System: Windows 10

**Comment by etanshaul** [comment]
hi @mjste . I agree with the desired behavior. I'll file an internal issue to track improving this.

**Comment by ivanporty** [comment]
Released in the new version 23.5.2. Please let us know if it works for you!

**Comment by mjste** [comment]
Yes, thank you
