### ISSUE TITLE
Allow the plugin to manage and install the Cloud SDK fails

### ISSUE THREAD

**Issue by rohanmoore** [GoogleCloudPlatform/cloud-code-intellij#3135]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
Following plugin installation, for the Google Cloud SDK to be downloaded and installed.

### Actual Behavior
Installation and update fail, with error notification: Managed Google Cloud SDK update failed: _com.google.cloud. tools.managedcloudsdk.command.Command ExitException: Process failed with exit code: 127_

### Additional Information

- IDE type: IntelliJ IDEA 
- IDE version: 2023.1 (Ultimate Edition)
- Cloud Code version: 23.4.1-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Trying!
  - Version of the Cloud SDK: 427.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Mac OS 13.3.1 (22E261)

**Comment by etanshaul** [comment]
hi @rohanmoore I see you are using the latest release that was put out this week. Is this new behavior for you? We'll see if there is a regression somewhere.

**Comment by ivanporty** [comment]
Cloud SDK requires python usually preinstalled with Mac, but with the newest Mac OS it might not be there. Can you please try installing command line tools for Mac, restart an IDE and see if it helps?

**Comment by ivanporty** [comment]
Also, could you please get us your IDE log file (Help -> Show Log in Finder -> idea.log)? Thanks!

**Comment by rohanmoore** [comment]
Hi Etan, thanks for your note. I’m new IntelliJ and to Google Cloud, so unfortunately I’ve no prior experience to benchmark against.

On 21 Apr 2023, at 17:42, Etan Shaul ***@***.***> wrote:



hi @rohanmoore<https://github.com/rohanmoore> I see you are using the latest release that was put out this week. Is this new behavior for you? We'll see if there is a regression somewhere.

**Comment by rohanmoore** [comment]
Hi Ivan, thanks for your note. Python3 is verified installed (version 3.10.10).

On 21 Apr 2023, at 17:45, Ivan Porty ***@***.***> wrote:



Cloud SDK requires python usually preinstalled with Mac, but with the newest Mac OS it might not be there. Can you please try installing command line tools for Mac, restart an IDE and see if it helps?

**Comment by rohanmoore** [comment]
Log attached.


On 21 Apr 2023, at 18:06, Ivan Porty ***@***.***> wrote:



Also, could you please get us your IDE log file (Help -> Show Log in Finder -> idea.log)? Thanks!

**Comment by rohanmoore** [comment]
[idea.log](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/11298730/idea.log)

**Comment by ivanporty** [comment]
This is what happens in the log `Downloading https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz to /Users/rohanmoore/Library/Application Support/google-cloud-tools-java/managed-cloud-sdk/downloads/google-cloud-sdk.tar.gz`. After this we extract the archive and try to install it, but it seems like it fails with a quick Python/some other system error.

Could you please try doing this yourself to diagnose more? Download `https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz`, unpack it and run `install.sh` and please let us know if it fails and error messages if it does. Thank you!

**Comment by ivanporty** [comment]
@rohanmoore I am going to close this issue as our metrics indicate majority of Mac based gcloud installations succeed. If you can give us more details from the last comment, that'd be very helpful. Thank you!
