### ISSUE TITLE
Intellij run configuration fails - Skipping Jib: no JVM

### ISSUE THREAD

**Issue by bogdhy** [GoogleCloudPlatform/cloud-code-intellij#3142]
When I run the configurations `Develop on Kubernetes` generated by the plugin, I receive the following error: Skipping Jib: no JVM: [java -version] failed: exec: "java": executable file not found in $PATH

But if I run the same skaffold command manually from the terminal everything works as expected.

![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12337250/c5a3f3f0-6f99-481c-bbfd-4e2e832c9124)

### Expected Behavior
To be able to run the helm charts using the JIB compiler with any issues, running the command from the terminal manually:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12337250/527fc899-6ba3-4e23-adf6-11a41fe6da6c)

### Actual Behavior
Running from the IDE
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12337250/1ef7af73-dd99-4d34-961d-64e83e6ffee8)

![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12337250/2579b714-b9df-4b05-baf5-73488f347e2c)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ
- IDE version: 2023.1.2
- Cloud Code version (Settings > Plugins > Cloud Code): 23.5.2-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 435.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v2.1.0
- Operating System: Ubuntu 22.04.2

**Comment by etanshaul** [comment]
hi @bogdhy . this is an interesting one. when you run `java -version` from the IDE terminal it finds it on the path?

**Comment by bogdhy** [comment]
> hi @bogdhy . this is an interesting one. when you run `java -version` from the IDE terminal it finds it on the path?

Hello, I just found out the issue, while testing what you said above, I started to look at the IDE terminal settings and saw that the $PATH env is different in the IDE than the one I have in the terminal.

After adding the JDK path to the $PATH manually in the IDE it worked:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12337250/7003c50f-e525-4f7f-b34c-3a08d07acaba)

Thank you for your help!

I guess the issue is with the IDE and not the the google cloud plugin.

**Comment by etanshaul** [comment]
glad it worked! thanks for the update

**Comment by bogdhy** [comment]
> glad it worked! thanks for the update

Hello, quick update, with the latest IDE update (2023.2), the fix did not work anymore.

The new solution was to override the "PATH" env at the run configuration level like this:

![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12337250/fad7b405-a5bb-4c43-8745-990af5cb6e80)

Hope this would save some headaches :smile:

**Comment by etanshaul** [comment]
thanks for providing the workaround. Unclear what the change was that affected this yet. @ivanporty do you know by any chance?

**Comment by ivanporty** [comment]
We might be changing PATH to include some of the tools needed for skaffold, but that should not affect the original PATH. We will double check this.
