### ISSUE TITLE
[CC Terminals] set PATH not working anymore on windows

### ISSUE THREAD

**Issue by mirdones** [GoogleCloudPlatform/cloud-code-intellij#3147]
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/35742992/cdfaddd5-3511-4a3d-907e-cf82281ebb87)

I clicked on my database to connect to it as I always did, it would open a terminal and connect to it.
Now I am getting an error related to PATH after updating to the latest plugin version.

### Expected Behavior
Connect to CloudSQL

Should use the following command on windows:

$Env:PATH+=

### Actual Behavior
set PATH

%PATH%: The term '%PATH%' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Additional Information

- IDE type: Pycharm
- IDE version: 2023.1.3 (Professional Edition)
- Cloud Code version (Settings > Plugins > Cloud Code): 23.6.2-api-version-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK): 
  - Are you allowing the plugin to manage the Cloud SDK:  Yes
  - Version of the Cloud SDK: 436.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Windows 11

**Comment by ivanporty** [comment]
It looks like the plugin doesn't recognize this terminal as Powershell for some reason and falls back to standard Windows. We'll investigate, thanks for the report!

**Comment by cedriclevarlet** [comment]
Same issue here. Adding to this, when I swap to the standard terminal instead of powershell I do not get any feedback (it happens for every command executed by the plugin):

![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/7115312/5233cc87-8cf2-4d67-aa4d-e415aff61922)

**Comment by mirdones** [comment]
The last version that worked is not working with the new pycharm version.
please correct this ASAP.

**Comment by ivanporty** [comment]
We do not see an issue with Powershell commands so far. 
@mirdones > The last version that worked is not working with the new pycharm version. - 
could you please tell us what version of (a) the plugin (b) PyCharm (c) windows are you using?

**Comment by mirdones** [comment]
@ivanporty 

Any version of the plugin after google-cloud-code-23.5.2-222 has this problem.

To circumvent this I am using google-cloud-code-23.5.2-222 along with pycharm 2023.1.4, which was the last combination that worked.

Steps for reproducing the problem:

1 - Open Google cloud databases in the left:

<img width="229" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/35742992/a5e85402-b44d-465f-9902-42ad2a707e27">

2 - Double click on the database you want to connect

3 - Error occurs on Powershell. On cmd there is no response as @cedriclevarlet also reported.

**Comment by mirdones** [comment]
@ivanporty do you have any news on the fix for this bug?

**Comment by ivanporty** [comment]
@mirdones the CMD fix is scheduled for the next release. Sorry for the wait. The powershell is working for us in tests and we are still looking into why we cannot identify it on setups such as yours, and hopefully will add the fix as well.

**Comment by ivanporty** [comment]
@mirdones @cedriclevarlet we've released CMD fix in 23.9.1, if you want to use it.

**Comment by peterlin741** [comment]
There was another fix in `23.10.1`. Please reopen if you are still seeing issues.
