### ISSUE TITLE
Can't Type in Git Commit Message Box

### ISSUE THREAD

**Issue by waqasisme** [GoogleCloudPlatform/cloud-code-intellij#3148]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 23.6.1-api-version-222
- Google Cloud SDK version: 436.0.0
- OS: Linux 5.19.0-45-generic

**What did you do?**
Nothing

**What did you expect to see?**
Being able to type in git commit message box

**What did you see instead?**
Can't type in git commit message box

(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
thanks for reporting. this was fixed with patch release 23.6.1, sorry for the issue. Please update the plugin to the latest version.

see https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/3144
