### ISSUE TITLE
Cloud SQL viewer doesn't list instances without Cloud SQL Admin API enabled

### ISSUE THREAD

**Issue by jonathan064** [GoogleCloudPlatform/cloud-code-intellij#3154]
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 23.7.1-api-version-222
- Google Cloud SDK version: 440.0.0
- OS: Windows 11 10.0

**What did you do?**
Updated intellij IDE to latest version 
**What did you expect to see?**
Google cloud connections that I was working on previously
**What did you see instead?**
Didnt display any connections for the cloud sql database I was using 
![Screenshot (152)](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/124532790/96834037-6bb8-48ea-a5fc-4d98854c4e48)

(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ruomengz** [comment]
Can you please try to sign in again, we changed the auth flow recently.
If it does not help, can you please try to attach some idea.log to help us debug?

**Comment by jonathan064** [comment]
I tried signing in and it didn't do anything, it was working fine yesterday before around 6:00pm cst though. I'm not sure where to find idea.log

**Comment by ruomengz** [comment]
You can find the idea.log by `Help > Show log in Explorer`.
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by jonathan064** [comment]
I downgraded to the previous google cloud version and it works fine now
[idea.log](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/12174237/idea.log)

**Comment by ruomengz** [comment]
Thanks for the logs!

It seems like the Cloud SQL Admin API is not enabled in your project.
Could you [enable the API](https://cloud.google.com/sql/docs/mysql/admin-api#enable_the_api) in Cloud Console and try again?

**Comment by jonathan064** [comment]
Oh thank you I enabled it and now its working fine

**Comment by ivanporty** [comment]
Thanks @jonathan064. We'll add the API enabled check in one of the upcoming releases. In the meanwhile, I updated the title of your issue in order for other users to find it if needed.

**Comment by ivanporty** [comment]
the latest release will check for the API being enabled and offer to enable it if it's not. Closing.
