### ISSUE TITLE
Secret Manager doesn't show all secrets

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/cloud-code-intellij#3160]
### Expected Behavior
I can see a list of all my secrets in a single project, or at least a search will search all of them

### Actual Behavior
The list of secrets in my project is cut off around 100 (hard to know for sure since I can't copy/paste out of the panel), and despite taking several seconds to perform a search, it only returns secrets from the list

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Goland
- IDE version: 2023.2.1
- Cloud Code version (Settings > Plugins > Cloud Code):  23.8.2 (this should be something I can copy/paste, but I can't)
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: No
  - Version of the Cloud SDK: 444.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: MacOS

**Comment by ivanporty** [comment]
@derekperkins there was a change in the recent release in how we list secrets to make it faster. We are looking into it. You can downgrade to version `23.7.1` if this is causing an inconvenience for you while we are looking into it.

**Comment by ivanporty** [comment]
@derekperkins The fix should be available in the next release.

**Comment by derekperkins** [comment]
Awesome, thanks

**Comment by ivanporty** [comment]
@derekperkins this should be fixed in the latest release (23.9.1). Please try and let know if it works for you!

**Comment by derekperkins** [comment]
Confirmed. Thanks for the quick turnaround!
