### ISSUE TITLE
Sign in to Google to use Cloud Code every time I am starting my VM. Is this expected ?

### ISSUE THREAD

**Issue by tarrade** [GoogleCloudPlatform/cloud-code-intellij#3161]
### Expected Behavior
Do this step only one time on my VM
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/89a88469-e82c-4bbc-aabe-3b6c101082e0)

### Actual Behavior
Every time I am starting my remote VM (Vertex AI Notebook) on GCP, I need to sign in in Google to use Cloud code.

What happen is that:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/e9cdb8dc-4f3d-459c-99fa-a3039662473a)

After sign in, credentials.json contain the credential
-rw-rw-r-- 1 jupyter jupyter    0 Sep  7 07:35 access_token_file
-rw------- 1 jupyter jupyter  289 Sep  7 07:37 application_default_credentials.json
-rw------- 1 jupyter jupyter  440 Sep  7 11:24 credentials.json

but when I restart the VM, credentials.json is empty:
-rw-rw-r-- 1 jupyter jupyter    0 Sep  7 12:39 access_token_file
-rw------- 1 jupyter jupyter  289 Sep  7 12:39 application_default_credentials.json
-rw------- 1 jupyter jupyter    0 Sep  7 12:39 credentials.json

This is maybe a normal behavious with what is set in application_default_credentials.json but:
- it is painful to do it once a day
- for the Google SDK, I do the following once on my VM and I don't have to do it again
gcloud auth login fabien.tarrade@email.com --update-adc 

Q1: is it a bug or a feature
Q2: if this is a feature why for the Cloud SDK we need to do the authentification once but for the Cloud Code plugin we need to do it at every start of the VM ?
Q3: if this is a feature a there a way to change it ? 

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm):
I am using the latest version of Pycharm/JetBrain Gateway (see the details below)
- IDE version:
JetBrains Client 2023.2.1
Build #JBC-232.9559.58, built on August 22, 2023
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
Controller in Remote Development (PY), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    com.github.copilot (1.2.21.2995)
    org.toml.lang (232.8660.88)
    com.github.camork.fileExpander (2.2)
    krasa.CpuUsageIndicator (1.17.2023)
    com.jetbrains.sh (232.8660.88)
    izhangzhihao.rainbow.brackets (2023.3.4)
    com.intellij.ideolog (222.1.0.0)

- Cloud Code version (Settings > Plugins > Cloud Code): 
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/51bb40f9-ba77-4013-97bd-619538a9b8b1)

- Cloud SDK (Settings > Cloud Code > Cloud SDK)
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/0e08bcf9-e7e1-4ea3-b892-b74146892020)

- Operating System:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by etanshaul** [comment]
@tarrade thanks for the issue.

This is a known bug. Were you trying out Duet AI features by any chance? We are debugging this overly-frequent login issue and have narrowed it down to one place and just wanted to confirm.

Also what is the version of the backend (not Gateway client) IDE you are connecting to? Thanks.

**Comment by etanshaul** [comment]
update: it might also be a bug causing the notification to pop up even when you don't need to sign in again. we are looking into it.

**Comment by tarrade** [comment]
@etanshaul , thanks for the follow up. Sorry I didn't find the existing bug report.

Yes I have am  having access to Duet AI, my project got whitelisted but my company didn't grant me the IAM permission and they want to review the data residency first. Not sure if this is because of the IAM permission but when I clicked on the symbol nothing happen (sometime it happen but I got AI assistant stuff). Anyway happy to help if I can
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/f65373d9-fb2d-403c-8a25-05936b15376a)

Here my IDE:
![Uploading image.png…]()


Let me know if you need more or something else

**Comment by etanshaul** [comment]
thanks! that helps a lot. We have narrowed down this issue and will patch as soon as we can put validate a fix. Thanks for the feedback on this.

**Comment by etanshaul** [comment]
@tarrade just a side note so you don't run into any surprises: Duet AI currently doesn't work in Cloud Workstations due to limitations in capabilities of gateway with the APIs we are using. We'll update the docs to clarify this. For now, you will need to use a desktop JB IDE for Duet.

**Comment by tarrade** [comment]
@etanshaul , thanks for the info and very good to know. Is there a public bug report on JetBrains so I can follow the progress ?

By the way, do you know if Google is providing a white paper that explain data residency with Duet AI ? (I know they published something for PaLM 2 fine tuning). Duet AI is troggering a lot of question and there is very few details in the official documentation i.e:
•	How das Duet AI works from the IDE 
•	What data is sent
•	How is the data stored, used and deleted (code, answers, temetry)
•	Are there any filters for PII
•	Can we have data deleted afterwards, … 
•	How is copyright infringement managed

**Comment by etanshaul** [comment]
some info on data governance is already outlined here: https://cloud.google.com/duet-ai/docs/discover/data-governance

**Comment by etanshaul** [comment]
hi @tarrade an update that we just released a new version that should fix the issue where you are asked to sign in too frequently.

**Comment by tarrade** [comment]
Hi @etanshaul ,

great, so far everything looks great and I didn't have to login for the moment.

Thanks raising the points for Duet AI internally. I will watch the official documentation. There already few things but not specific for our legal and gouvernance team. I may contact Duet AI if we have specific questions that are not anwsered.

For JB, I guess the same bug affect Copilot. I am also waiting for the coming new version 2023.2.3 for support for Markdown so hopefully everything will be in this release for the end of this year.

Last point, it seems that on Github, there is a missing entry for the latest version 23.9.1

Thanks again and closing

**Comment by etanshaul** [comment]
> Last point, it seems that on Github, there is a missing entry for the latest version 23.9.1

Opps, our mistake. See: https://github.com/GoogleCloudPlatform/cloud-code-intellij/releases/tag/v23.9.1

> I may contact Duet AI if we have specific questions that are not anwsered.

Thanks for all of the feedback here. We'll keep you in the loop with any relevant updates.

**Comment by tarrade** [comment]
Hi @etanshaul ,

unfortunately, when restarting my VM this morning, I had to logging again. Same empty credentials.json before I redo the authentification. I check to see the list of my VMs with Cloud Code  but authentification was necessary so it is not an unnecessary pop up windows  in my case,

I am using 
latest cloud plugin 23.9.1-IB.1-api-version-222
latest pycharm version Build #JBC-232.9921.36, built on September 11, 2023
latest JetBrains Gateway as before

Thanks

**Comment by etanshaul** [comment]
this may be more specific to gateway then. we will investigate. (the original issue of non-gateway + Duet appears to be resolved, but we'll use this issue to track the gateway flavor of it). thanks.

**Comment by tarrade** [comment]
Hi @etanshaul,

yes it is working fine with Pycharm on my local PC (same  version as for the Gateway).

Now, I realized that when using Gateway the issue was on my side. In fact, I am using a local proxy so I need to SSH the remote machine with port forwarding. If I SSH the machine first and then open remote Pycharm is work fine.

If I don't SSH first, I guess when I start remote Pycharm, it cannot access internet to do the authentification or do some check. 

Sorry for the false alarm and thanks for the fix
