### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023.3 EAP 4

### ISSUE THREAD

**Issue by villesau** [GoogleCloudPlatform/cloud-code-intellij#3165]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior

Should be compatible with IntelliJ IDEA 2023.3 EAP 4

### Actual Behavior

Not compatible with IntelliJ IDEA 2023.3 EAP 4, so cannot update to latest IntelliJ.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm):
- IDE version:
- Cloud Code version (Settings > Plugins > Cloud Code): 
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: 
  - Version of the Cloud SDK:
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System:

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Thank you for the report @villesau! We will try to make the plugin compatible as soon as possible and let you know.

**Comment by villesau** [comment]
Any news? Looks like cloud code is the only plugin that is incompatible in our setup.

**Comment by ivanporty** [comment]
Hi @villesau! We are planning the next release mid-December, and it will include support for the EAP/upcoming 2023.3 release.

**Comment by villesau** [comment]
IntelliJ IDEA 2023.3 seems to be generally available now.

**Comment by ivanporty** [comment]
Thank you! Our update is about to be released, sorry for the delay.

**Comment by ivanporty** [comment]
We just released version 23.12.2 that supports 2023.3 to the marketplace, you should be able to update and use Cloud Code now.
