### ISSUE TITLE
Duet AI feature doesn't work in PyCharm 2023.2.2 

### ISSUE THREAD

**Issue by hclockzz** [GoogleCloudPlatform/cloud-code-intellij#3167]
I have tested with Duet AI features on VS Code, and it's working as expected. While in PyCharm, code generation is not working. Can follow this link, https://cloud.google.com/code/docs/intellij/write-code-duet-ai#prompt-duet-ai-in-code-file, to test with it. No error logs and notifications when hit the icon for code generation (a pen with a star), but just no reaction.

### Expected Behavior
how it works in VSCode
<img width="1186" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/11131684/457a3103-efbc-414b-b9b9-fdf7b4c6d124">

### Actual Behavior
No response and reaction
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/11131684/5a593ebb-987a-4e43-ac48-1203ea1676d1)

### Additional Information

- IDE type & version (e.g. IntelliJ, Pycharm): PyCharm 2023.2.2 (Community Edition, Build #PC-232.9921.89, built on October 1, 2023)
- Cloud Code version (Settings > Plugins > Cloud Code): 23.10.1
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: No
  - Version of the Cloud SDK: 416.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v2.7.1
- Operating System: OSX 13.6 (22G120)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment]
@hclockzz thanks for the report. We have several fixing coming around feedback / error handling.

In the meantime, to figure out this specific issue, could you please share the logs? The best way to do this:

1) Click the magic wand to trigger something from Duet
2) Use the Duet status bar to submit a feedback report (which will automatically attach the logs):
<img width="207" alt="Screenshot 2023-10-26 at 5 40 35 PM" src="https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/1735744/71f8912d-666f-42c9-a0eb-2f8e6bac48b0">

Some other things to check:
- ensure that you have your GCP project entered in the Duet AI settings. To get there, use the same status bar above > Settings. And ensure the `Cloud Project` field is populated with the correct GCP project where Duet AI is enabled.

**Comment by hclockzz** [comment]
I did side-by-side comparison with vscode and pycharm setting and find out the issue. It turns out may relate to two things:
- The most straightforward one is the project field needs to be project id, not just the project name. But I have tried with project id before, so the issue may also relate to the second thing. 
- I switch Cloud SDK from "use a custom local installation" to "Allow the plugin to manage and install the Cloud SDK", and then the IDE installed a newer version.

I am not in favor of making dependencies managed by a plugin in real development. But at least this issue is resolved by this way.

**Comment by etanshaul** [comment]
> I switch Cloud SDK from "use a custom local installation" to "Allow the plugin to manage and install the Cloud SDK", and then the IDE installed a newer version.

This is interesting. There is no reliance by any Duet features on the cloud sdk at all - you don't even need it installed. We'll double check though

Update: I just tested this quickly and can confirm that Duet works without having the plugin manage any dependencies. Now that you have Duet working, would you mind trying to unset managed dependencies and seeing if it continues to work? thanks.

**Comment by etanshaul** [comment]
> The most straightforward one is the project field needs to be project id, not just the project name. But I have tried with project id before, so the issue may also relate to the second thing.

When you use the project selection widget, does it do the right thing?
<img width="742" alt="Screenshot 2023-10-30 at 7 58 04 PM" src="https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/1735744/31d322bc-f87c-49bf-a5d2-7313411e65fe">

(we'll double check on the name vs id requirement for freeform text entry; update - you are right, this field needs ID, not name. Mainly because ID is unique but name is not. We'll update the wording on this text field to make it clearer. Great callout.).

**Comment by ivanporty** [comment]
Closing as we didn't have more comments, and significantly improved onboarding process with our 23.10.2 release.
