### ISSUE TITLE
How can I install it in Android Studio?

### ISSUE THREAD

**Issue by cselti** [GoogleCloudPlatform/cloud-code-intellij#3170]
### Expected Behavior
I can install the plugin in Android Studio.

### Actual Behavior
I searched for the Google Cloud Code plugin in the plugin marketplace, but I didn't get any results. 
I tried with IntelliJ community edition - I can install it without a problem.

### Additional Information

- IDE type: Android Studio
- IDE version: Giraffe, Hedgehog, Iguana
- Operating System: MacOS Monterey 12.7.1 - Apple M1 Pro, MacOS 13 Ventura Intel Core-i7. Ubuntu 22.04 x64

**Comment by ivanporty** [comment]
We don't support Android Studio at the moment unfortunately.

**Comment by ivanporty** [comment]
AS support is now on our near-term roadmap. Please stay tuned, we will let you know when it's ready

**Comment by peterlin741** [comment]
Cloud Code is now supported in Android Studio

https://cloud.google.com/code/docs/intellij/ides
