### ISSUE TITLE
Duet AI Chat not working with remote PyCharm (JetBrains Gateway)

### ISSUE THREAD

**Issue by tarrade** [GoogleCloudPlatform/cloud-code-intellij#3172]
### Expected Behavior
Being able to use Duet AI chat with remote Pycharm using JetBrains Gateway

### Actual Behavior
When using Duet AI chat, I am getting: "Error getting response from Duet AI"

![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/62208142-1476-4b08-aaff-a40821b3bda6)

Looks like this is a similar issue  than for Duet AI auto completion where first JetBrains need to implement something in JetBrains Gateway to have later Duet AI fully working with remote Pycharm. Opening a ticket to keep track of future progress on these 2 topics .

I already submitted some feedback directly from th UI

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Pycharm but remote using JetBrains Gateway
JetBrains Gateway 2023.2.4
Build #GW-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
- IDE version: Pycharm 2023.2.5
- Cloud Code version (Settings > Plugins > Cloud Code):  
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/dd44a85d-0176-4f66-8a64-3e1961ff6862)
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: 
  - Version of the Cloud SDK:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/c11c97dd-f089-4247-8d6c-633ec6ae24fb)

- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/f7549403-0250-4362-8de4-faa3cc91ed0e)

- Operating System:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Comment by ivanporty** [comment]
Thank you for the report @tarrade! Duet AI in remote IDEs is not supported at the moment, and we will let you know when this changes.

**Comment by tarrade** [comment]
Seems to be working now (at least some component like the "chat" and "explain this code". This is maybe still experimental but nice to see this coming. I am using the  latest JetBrains  Gateway EAP version, the latest Pycharm version and the latest Cloud Code plugin.

**Comment by tarrade** [comment]
Hi @ivanporty, any tentative roadmap concerning Gemini Code Assist in remote IDEs ? Looks like chat is working well since some time but not auto-completion.

Thanks

**Comment by ivanporty** [comment]
@tarrade please try the latest 24.8.1, it uses IDE's built-in native code completion framework that should work in the remote environments and let us know how it goes please

**Comment by tarrade** [comment]
@ivanporty this new version looks really great (options design) but no yet fully working for me. Maybe I still have some bad configuration of maybe it is not fully compatible with Pycharm 2024.2

![image](https://github.com/user-attachments/assets/1169e855-3707-478b-8f73-363f246894e5)

![image](https://github.com/user-attachments/assets/622cd004-8dda-415d-8f65-04cd624a022d)


I am using
```
PyCharm 2024.2
Build #JBC-242.20224.347, built on August 9, 2024
```

```
JetBrains Gateway 2024.1.2
Build #GW-241.17011.87, built on May 23, 2024
```

Plugings (Host)
![image](https://github.com/user-attachments/assets/b85742b3-433b-4dd1-85ce-cc5077a8cd84)


Pycharm 2024.2
- chat is working great and I like the design
- same for "Explain This" and "Generate Unit Tests"
- "Generate code" doesn't work -> nothing happen
- auto complementation doesn't work (nothing happen and I don't see the start at the beginning of the line

Using remote Pycharm 2024.2 (I see the similar things)
- chat is working great and I like the design
- same for "Explain This" and "Generate Unit Tests"
- "Generate code" doesn't work -> nothing happen
- auto complementation doesn't work (nothing happen and I don't see the start at the beginning of the line
- after the initial panel, in the setting, the Gemini section is empty
![image](https://github.com/user-attachments/assets/c59ebfa8-c72e-4643-89cc-43b27da632ee)

Congrats and looking forward to have it fully working

ps: I will try the Gateway 2024.2 Beta and this is maybe the missing piece
edit : using Gateway 2024.2 Beta don't solve the issue (maybe the issue with Gemini console panel is gone)
![image](https://github.com/user-attachments/assets/851154b2-bda1-4deb-adcc-f1334105be8e)

**Comment by ivanporty** [comment]
Hi @tarrade glad you like the new update so far. Gateway doesn't support standard plugins - it is only used to connect to remote IDEs and you cannot use it for editing/etc., so we don't expect to support it.

Regarding auto complementation doesn't work - we see it's working fine. Do you see any autocompletion at all, in any of the files? Can you give us an example file with example code to try to reproduce? Does opening/adding more open files or closing them changes that? Thanks! I assume the problem is same and should work across local/remote environments.

As for Gemini remote setting view, we might need to add something else for it to work properly, but it looks like the things are almost there.

**Comment by tarrade** [comment]
Hi @ivanporty,

I just want to work local (Windows) or remote (Ubuntu). I switch today to the 2024.2 JetBrains Gateway to be 100% sure.

I recorded a small video when working locally on Windows with Pycharm (not remote Pycharm to simplify) so you can see what I am trying to do. I was using Github copilot until recently. With Gemini Code Assist,  the only things that I don't managed to have working is autocompletion. As you can see in the video, I see nothing at all (I removed the AI Assistant and Coplilot pluging to be 100%.

![image](https://github.com/user-attachments/assets/4ecad762-cf09-4281-936f-08f2dc4d3674)

I am not sure how I can share the video but I will find out

I am missing something but I don't know what

**Comment by ivanporty** [comment]
Thanks @tarrade I got the video. I can see the code generation works great (5:04). Btw, you don't need to select the prompt, Gemini sees where your cursor is and should be able to understand that's a prompt if you put your cursor on the next line after the prompt.

I also see code completion working (2:34, 2:48). It is very basic but this is expected as you don't have much in that file, no other files open, and completion model cannot offer much in this scenario. It looks like all scenarios are working fine. You can try using more complex files, open relevant files, and see better autocompletions too.

Does completion/generation also work for you via Gateway?

**Comment by tarrade** [comment]
@ivanporty thanks for taking the time to look at it. You are right it is working fine and my code was too simple.
This is also working fine with the remote Pycharm.

In fact, I was looking too much at the GCP [doc](https://cloud.google.com/code/docs/intellij/write-code-gemini) and I was expecting to see the Gemini symbole on after the line number but doesn't seems to be the case anymore
![image](https://github.com/user-attachments/assets/19f93fcd-2191-4497-842a-8a09f774656a)

Anyway, everything is looking fine so closing this ticket and thanks again

**Comment by ivanporty** [comment]
Thanks! This was an experimental icon and we removed it. We will update the documentation.
