### ISSUE TITLE
PHPStorm 2023.3 is not supported

### ISSUE THREAD

**Issue by andrey-bondar** [GoogleCloudPlatform/cloud-code-intellij#3174]
### Expected Behavior
Plugin works on new IDE version
### Actual Behavior
![Screenshot from 2023-12-06 17-58-57](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/3185843/bc984c53-56be-4378-a3cb-74a373168aa9)

### Additional Information
- PHPStorm 2023.3

**Comment by ivanporty** [comment]
Thank you for the report! Our update is about to be released, sorry for the delay. We will update you once it's on the marketplace

**Comment by ivanporty** [comment]
We just released version 23.12.2 that supports 2023.3 to the marketplace, you should be able to update and use Cloud Code now.
