### ISSUE TITLE
Duet AI accepting the code completion is not working (JetBrains Rider)

### ISSUE THREAD

**Issue by arseniio-dev** [GoogleCloudPlatform/cloud-code-intellij#3175]
![rider-duet-ai-tab-issue](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/59434045/e77ae80f-9c8a-461f-9fb2-426a6fde9897)

### Expected Behavior
I Expect while I've received AI generated code completion I can accept it by "Tab" or e.g. "Enter"

### Actual Behavior
"Tab" is not working, the same goes for "Enter" it just tabbing the code completion text like it was the previously written code

### Additional Information
I've checked available options for "Google Cloud Plugin" in IDE editor keymap for me, there is option to assign shortcut to generate the code, but there is no options to assign any shortcus to accept it, previosly i had GitHub Copilot which allows me to assign key to accept code completion (default was "Tab" which I've used), for the issue submiting purposes GitHub Copilot was on first try disabled then unsinstalled completely, but the issue with DuetAI still persist

- IDE type: JetBrains Rider 
- IDE version: 2023.2.3 | Build #RD-232.10203.29
- Cloud Code version: 23.12.3-api-version-223 
- Cloud SDK: N\A
- Skaffold version: N\A 
- Operating System: Windows 11 22H2 | Build 22621.2861

**Comment by MrXLR8** [comment]
Same problem. Here. Work around is to use Shift+Enter to accept only one line. Waiting for a solution

**Comment by ivanporty** [comment]
We've found a conflicting Tab action in Rider and working on the fix. It should be available in the next release.

**Comment by drakgoku** [comment]
It happens the same to me.

Shift + Enter does not seem to be the best key combination to place line by line. Couldn't it be fixed so that with tab or enter it would place all the lines?

**Comment by PabloVKF** [comment]
Even Shift + Enter doesn't seem to be working correctly. Unlike the tab, it generates, but throws all the data to the next line, even when it is only filling part of it.
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/71087529/f7986c88-3003-42c0-9720-15c90681b26a)
In the simple example shown in the image above, only the word statusCode is completed, the :": 200}" that was already written is moved to the next line when I try to use Shit + Enter to validate the AI's suggestion. This behavior doesn't seem correct to me, I expected the word to be completed without throwing all the dice on the line down

**Comment by ivanporty** [comment]
We are expecting fix to be available in the upcoming release due next week.

**Comment by ivanporty** [comment]
The tab issue should be fixed in the new release (24.1.4) - please let us know if you still experience issues.

**Comment by ivanporty** [comment]
No new comments, we consider this fixed.
