### ISSUE TITLE
Database content not loading

### ISSUE THREAD

**Issue by villesau** [GoogleCloudPlatform/cloud-code-intellij#3176]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior

1. connect to the database via IntelliJ + proxy (Google Cloud Databases)
2. wait for `The proxy has started successfully and is ready for new connections!`
3. open databases
4. select table you want to see
5. It loads the table content

### Actual Behavior

1. connect to the database via IntelliJ + proxy (Google Cloud Databases)
2. wait for `The proxy has started successfully and is ready for new connections!`
3. open databases
4. select table you want to see
5. It gets stuck on "Processing"

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ IDEA 2023.3.2 (Ultimate Edition)
- IDE version: Build #IU-233.13135.103, built on December 20, 2023
- Cloud Code version (Settings > Plugins > Cloud Code): 23.12.3-api-version-223
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  yes
  - Version of the Cloud SDK: does not show, stuck in "Loading version..."
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: macOS 13.6.1

Note that this has been a long standing issue (maybe forever?), but also with the latest versions. However, previously it happened randomly, now it happens every time.

**Comment by villesau** [comment]
Actually, it might still eventually connect. But it takes **10+minutes**:

```
2023/12/22 10:18:12 The proxy has started successfully and is ready for new connections!
2023/12/22 10:29:25 [retracted] accepted connection from <ip-address>
```

**Comment by ivanporty** [comment]
Thanks @villesau! We cannot reproduce this and connection is instant for us so the reason might be in communication between GCP and your local client - depending on the database region, database instance type, etc. Does it reproduce if your create another database instance or use another Cloud SQL database type?

**Comment by villesau** [comment]
I'm not the only one this happens to. Also my colleague is having similar problems. We are physically quite close to the data center (definitely not 10 minutes away light speed...). The DB is performant in prod. We are using managed postgres.

**Comment by ivanporty** [comment]
This might be something related to the proxy version or its performance. If you have a chance, could you please try with the newest version of proxy from here https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases, copying the command line Cloud Code generates in the terminal when you establish a connection, and see if this makes any difference?

**Comment by villesau** [comment]
Oh, indeed when trying out with the latest version and manually running the script the connection was instant! 🤯 This is not the case with the latest one that ships with the gcloud toolset.

**Comment by ivanporty** [comment]
Thanks for confirming this! We'll schedule Cloud SQL proxy update for the next release and hopefully this will get rid of latency issues.

**Comment by pouyan021** [comment]
I confirm this happens to me as well. Also, it makes the whole intellij freeze completely, I have to 'force quit' it and reopen to continue doing my job. I knew this issue existed in at least the last 3-4 versions of the plugin and I would run the command from a casual terminal instance to make the connection. Tried my luck again today and the odds were not in my favor

**Comment by villesau** [comment]
> Also, it makes the whole intellij freeze completely, I have to 'force quit' it and reopen to continue doing my job.

This happens (or happened, not sure yet with the latest proxy) to me too, but I'm not been able to 100% pinpoint it to cloud code.

**Comment by pouyan021** [comment]
> > Also, it makes the whole intellij freeze completely, I have to 'force quit' it and reopen to continue doing my job.
> 
> This happens (or happened, not sure yet with the latest proxy) to me too, but I'm not been able to 100% pinpoint it to cloud code.

There's something to do with this plugin. Running the command in a separate terminal and coming to IntelliJ and trying to connect has always worked seamlessly for me, but the minute I try to connect the db in Intellij after establishing a connection using the plugin, the same disaster happens again regardless of the version of the ide or the plugin (at least for the last 3-4 releases as I mentioned, because I remember a time when this wasn't happening)

**Comment by ivanporty** [comment]
Thanks for the report @pouyan021. This might be a system specific error when terminal doesn't respond - we do look for terminal output and process status and it might vary from system to system. Could you please tell us your IDE, OS, and plugin version?

**Comment by pouyan021** [comment]
> Thanks for the report @pouyan021. This might be a system specific error when terminal doesn't respond - we do look for terminal output and process status and it might vary from system to system. Could you please tell us your IDE, OS, and plugin version?

I'm on a MacBook Pro 2019 
CPU: intel core i9
os: Sonoma 14.2.1
IDE: IntelliJ IDEA 2023.3.2
plugin: 23.12.3-api-version-223

**Comment by pouyan021** [comment]
Just checked randomly today and seems this happens no more

**Comment by ivanporty** [comment]
Thanks for double checking. Will close and please reopen if happens again. We now do automatic Cloud SQL Proxy updates each release and that should help with any related issues.
