### ISSUE TITLE
debug log is not working on remote dev

### ISSUE THREAD

**Issue by fgette-delfingen** [GoogleCloudPlatform/cloud-code-intellij#3178]
**Version Information**

JetBrains Gateway version:
JetBrains Gateway 2023.3.2
Build #GW-233.13135.102, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2008M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.google.cloud.workstations.ide.jetbrains.connector (23.11.1-api-version-231)

Cloud Workstations plugin version:
23.11.1-api-version-231

**Details**
Using latest version of image europe-west1-docker.pkg.dev/cloud-workstations-images/predefined/intellij-ultimate in the configuration of our workstation. 
Installed tomcat 9 in the home/user folder using https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.84/bin/apache-tomcat-9.0.84.tar.gz

When I "run" a webapp in Intellij, I see correctly the logs:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/19801933/db62a4ec-820d-49f7-affb-1f9d34e908b2)

But when I "debug" this same webapp, I don't see the logs:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/19801933/7cf5286b-6397-4678-b0a0-5ba608a58087)

See also https://youtrack.jetbrains.com/issue/IDEA-338990/debug-log-is-now-wokring-on-remote-dev

**Comment by ivanporty** [comment]
Thanks for the report @fgette-delfingen! It looks like some windows are not projected, we noticed that before for other debugging scenarios such as Kubernetes/CR debugging, and it looks like a Gateway limitation. We assume the same scenario would work with local IDE?

**Comment by fgette-delfingen** [comment]
Hello @ivanporty.
Correct: the same scenario is working flawlessly with a local Intellij.

**Comment by fgette-delfingen** [comment]
Hello
I got an updated version of Jetbrains today (client and backend version 2023.2.1 -> 2023.3.2)
This bug is now fixed (of course this version contains new bugs :-) )
We can close this issue.
Thank you

**Comment by ivanporty** [comment]
Great news!
