### ISSUE TITLE
Missing release note for 24.1.2-api-version-223 on Github and this version of the plugin not available with remote Pycharm (JetBrains Gateway)

### ISSUE THREAD

**Issue by tarrade** [GoogleCloudPlatform/cloud-code-intellij#3180]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
1) have new features and bug fixes described here: https://github.com/GoogleCloudPlatform/cloud-code-intellij/releases
2) be able to "see" and install 24.1.2-api-version-223 plugin on Pycharm remote using JetBrains Gatewy

### Actual Behavior
1) Release 24.1.2-api-version-223 is not documented
2) I don't see the new version of the plugin when using Pycharm remote using JetBrains Gateway (no issue with a local Pycharm)
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/12021701/bcf81771-ca17-4bfb-b552-9af6a3af9786)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Pycharm
- IDE version:
PyCharm 2023.3.3
Build #JBC-233.13763.5, built on January 13, 2024
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
Controller in Remote Development (PY), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8

JetBrains Gateway 2023.3.2
Build #GW-233.13135.102, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8

- OS
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Thanks for the report @tarrade. We've updated release notes. As for the second item
> be able to "see" and install 24.1.2-api-version-223 plugin on Pycharm remote using JetBrains Gatewy

It seems like you are using insiders build, and cannot see a new insiders build available to you, is this correct?

**Comment by tarrade** [comment]
Thanks @ivanporty 

Yep, it seems Pycharm mess-up the release. I wanted to installed pycharm 2023.3.3 RC candidate both locally and remote but gt different releases. I am able to see the plugin with EAP releases. Anyway the issue is somewhere else.

Thanks and closing

**Comment by ivanporty** [comment]
We just released a small update (24.1.3), and also updated insiders build - you might want to try to update one more time. Thanks!

**Comment by tarrade** [comment]
Thanks, yes this now working.
