### ISSUE TITLE
Plugin breaks yaml validation for AWS CloudFormation (cfn-lint)

### ISSUE THREAD

**Issue by Enigo** [GoogleCloudPlatform/cloud-code-intellij#3183]
Good day!
See the screenshot:
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/15067216/9bee4be2-487e-4bbc-ba60-e02389a2e0ca)

The error is `unknown tag <!Split>` and many more of those custom AWS CF.
Yeah, we have multiple clouds atm.

### Expected Behavior
Don't interfere with the existing linting - I'm using [cfn-lint](https://plugins.jetbrains.com/plugin/10973-cfn-lint) plugin for this

### Actual Behavior
It seems to overrides what other plugins are doing (?) 

### Additional Information
What would make the most sense for this plugin imo is to have a modularity. E.g. I don't actually need k8s related things on my project, only Cloud DB. But I'm forced to get everything instead. Not particularly user-friendly.

I could also somewhat disable it by setting **YAML file matcher** to something that doesn't match any yaml files.

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ IDEA 2023.3.3 (Ultimate Edition)
- IDE version: Build #IU-233.14015.106, built on January 25, 2024
- Cloud Code version (Settings > Plugins > Cloud Code):  24.2.1-api-version-223
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK: -
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): default
- Operating System: Ubuntu 22

**Comment by ivanporty** [comment]
Thanks for the report @Enigo. We are aware that Yaml validation could sometime run into a conflict. There is an ongoing effort to make it smoother, we'll let you know when it's ready.

**Comment by Enigo** [comment]
thanks @ivanporty 
are you also considering to split this plugin into smaller ones or have an option to only load some modules?

**Comment by ivanporty** [comment]
Yes, we might be making features to be available on demand rather than enabling them all together - do you think such approach would fit your needs? I.e. you may enable Cloud databases only and Cloud Run, but don't see/use other features until enabling them.

**Comment by Enigo** [comment]
Absolutely! That's especially important if/when you add more services to the plugin. 
I would personally prefer to have multiple smaller plugins per service instead of one huge one with option to disable parts of it.
But I imagine that's harder to maintain

**Comment by peterlin741** [comment]
In the latest release (`24.4.2`), we have added the ability to disable YAML support through the settings (Settings > Tools > Google Cloud Code > Kubernetes). [docs here](https://cloud.google.com/code/docs/intellij/yaml-editing#enable_or_disable_yaml_support)
