### ISSUE TITLE
[Duet AI ] List of file extension to be ignore and .duetaiignore

### ISSUE THREAD

**Issue by tarrade** [GoogleCloudPlatform/cloud-code-intellij#3185]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Feature requestr
We would like to be able to provide a list of file extension so Duet AI (from any IDE) ignore such files. The idea is to protect sensitive information in file like .env but also sensitive data or customer data that could be in Excel or Jupyter notebook files.

At the Admin level Copilot is providing something like below that will be nice to have as well in Duet AI admin console
```
"*":
 - "*.csv"
 - "*.json"
 - "*.xml"
 - "*.log"
 - "*.txt"
 - "*.properties"
 - "*.env"
 - "*.ipynb"
 - "*.xls"
 - "*.xlsx"
 - "*.xlsm"
 - "*.pem"
 - "*.der"
 - "*.cer"
 - "*.crt"
 - "**/*.csv"
 - "**/*.json"
 - "**/*.xml"
 - "**/*.log"
 - "**/*.properties"
 - "**/*.env"
 - "**/*.ipynb"
 - "**/*.txt"
 - "**/*.pem"
 - "**/*.crt"
 - "**/*.der"
 - "**/*.cer"
 - "**/*.xls"
 - "**/*.xlsx"
 - "**/*.xlsm"

```

For regulated industry this is very important. 

This is should be (also) at the IDE level (VS Code and Pycharm) like .duetaiignore. There is heavily discussion on the copilot side [1]

[1] https://github.com/orgs/community/discussions/10305

**Comment by ivanporty** [comment]
Thanks @tarrade! We are working on this at the moment and will update you.

**Comment by tarrade** [comment]
Hi @ivanporty, any public roadmap for this feature ? Q4 2024 ? Thanks

**Comment by ivanporty** [comment]
We just released completely reworked Gemini Code Assist functionality in the Cloud Code. It has native IDE completion support, no conflicts with Tab actions, brand new chat UX, chat history and query history, and also .aiexclude file support (24.8.1 and later). See details for .aiexclude here while we are creating a page for Gemini - https://developer.android.com/studio/preview/gemini/aiexclude

**Comment by tarrade** [comment]
@ivanporty this is fantastic. Thanks for the feature and closing.
