### ISSUE TITLE
[DuetAI] Conflict with Jetbrain's inline code completion

### ISSUE THREAD

**Issue by cedriclevarlet** [GoogleCloudPlatform/cloud-code-intellij#3189]
After installing Google Cloud Code, the DuetAI feature seems to conflict with Jetbrain's own Built-in local inline code completion. Since the GCC plugin includes features unrelated to DuetAI, it does not make sense for the plugin to affect core features of the Jetbrain's IDEs.

![Screenshot 2024-03-11 at 11 35 07](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/7115312/3df604c0-4da6-4098-a062-af518da41d2e)

### Expected Behavior

DuetAI should only disable the built-in code completion features of Jetbrains once it is enabled and not upon installing the cloud code plugin.

If it is not possible to support this behavior, the duetai functionality should be split into a new plugin.

### Actual Behavior

As soon as the cloud code plugin is installed, the built-in inline code compleition is disabled.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): PyCharm
- IDE version: 2024.1 EAP
- Cloud Code version (Settings > Plugins > Cloud Code): 24.2.2-api-version-223
- Operating System: MacOS

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Thank you @cedriclevarlet. This is Jetbrains decision to move the plugin into "unsupported" list for full inline completions, there is no actual conflict we see, we will communicate with them more, and use better approach here soon.

To clarify, what setting is causing this (Full Line Completions) - where is it in the IDE settings?

**Comment by ghost** [comment]
I've added a ticket to JetBrains' YouTrack: [[PY-72947] Full Line Code Completion conflict with Gemini Code Assist/Cloud Code plugin](https://youtrack.jetbrains.com/issue/PY-72947/Full-Line-Code-Completion-conflict-with-Gemini-Code-Assist-Cloud-Code-plugin)

**Comment by ivanporty** [comment]
This should be resolved in the latest IDE and Cloud Code/Gemini Code Assist versions.
