### ISSUE TITLE
Caret jumps back to the original position when pressing tab

### ISSUE THREAD

**Issue by debakkerb** [GoogleCloudPlatform/cloud-code-intellij#3191]
**Version Information**

JetBrains Gateway version: 2024.1 (Build: #GW-241.14494.255, built on March 30,  2024)

Cloud Workstations plugin version: 24.4.1-IB.1-api-version-223

**Details**

Every time I try to press tab, the caret is automatically moved back to the original position immediately.  Initially I thought it was a problem with JetBrains Gateway, so I removed my entire local installation (Toolbox, Gateway, Intellij and JetBrains related files in ~/Library).  I also removed the .idea-folder on my workstation, to make sure that no settings were left behind.

After reinstalling everything, the problem was still there.  I disabled the Cloud Code plugin and that fixed the problem. 

You can see a recording of the screen here: 

https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/42766321/75f6d70c-fb3a-4755-9c49-13c03dde513d

**Comment by ivanporty** [comment]
Thanks for the report @debakkerb. We are investigating the root cause for this and will get back to you

**Comment by ivanporty** [comment]
We released completely updated version that uses IDE's built-in completion support (24.8.1 and later). Tab should not be conflicting anymore and you can use other shortcuts for completions.
