### ISSUE TITLE
Emacs tab completion for PyCharm 2024.1 doesn't expand inline suggestion

### ISSUE THREAD

**Issue by ddennerline3** [GoogleCloudPlatform/cloud-code-intellij#3197]
When attempting to expand the inline suggestion with PyCharm and emacs profile, the `<tab>` key doesn't auto complete suggestion. If the profile is changed to MacOS, then the tab key works as expected.

![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/60669968/fa4c7c83-dc64-4f65-9a00-356271efa9be)

### Expected Behavior
- Start PyCharm
- Change Settings->keymap->emacs
- Create a example.py file
- Type `class Address:`
- Wait for gemini to suggest a standard address initializer
- Press the tab
- Verify that five lines of address variables are inserted into current window

### Actual Behavior
The actual behavior is that the `<tab>` key is ignored in the emacs keymap.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Pycharm 
- IDE version: 2024.1
- Cloud Code version (Settings > Plugins > Cloud Code): 24.4.2-api-version-223
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 471.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 2.11
- Operating System: MacOS ARM Sonoma 14.4.1

**Comment by ivanporty** [comment]
Thanks for the report @ddennerline3. We are aware of the conflict with emacs plugin and working on the fix. Will update once we are done.

**Comment by ivanporty** [comment]
We just released completely reworked Gemini Code Assist functionality in the Cloud Code. It has native IDE completion support, no conflicts with Tab actions-  please try the new version and let us know if this fixes the issue.
