### ISSUE TITLE
Rider is unstable when running plugin

### ISSUE THREAD

**Issue by rharpertm** [GoogleCloudPlatform/cloud-code-intellij#3198]
### Expected Behavior
Specifically, I'm wanting to use the AI code completion and chat features. 

### Actual Behavior
Currently I'm noticing a lot of instability with Rider. I have noticed a few specific actions that seem to cause the IDE to become unresponsive, requiring a restart to get going again. These are:
- Deleting files from the commit pane
- Viewing large files in the IDE

The IDE seems to also loose code completion from time to time, though I haven't been able to pinpoint specific actions that cause this.

### Additional Information

- IDE type: Rider
- IDE version: JetBrains Rider 2024.1.2
- Cloud Code version (Settings > Plugins > Cloud Code): 24.5.1-api-version-223
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: Google Cloud SDK 466.0.0
- Operating System: Windows 11

**Comment by ivanporty** [comment]
We are looking into this at the moment, thank you.

**Comment by ivanporty** [comment]
This should be fixed in the latest release 24.6.1. Please update the plugin and let is know if this works for you or otherwise reopen. Thank you for your report again.
