### ISSUE TITLE
Apologies, Gemini in IntelliJ IDEA is currently not available in your country.

### ISSUE THREAD

**Issue by Kmulla237941** [GoogleCloudPlatform/cloud-code-intellij#3227]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Additional Information: Century is India 

- IDE type (e.g. IntelliJ, Pycharm):
- IDE version: 2024.2.0.0
- Gemini code Asist not working, Giving below error.
![image](https://github.com/user-attachments/assets/558f4493-2a61-42e6-adf3-2240a5cfd518)
Apologies, Gemini in IntelliJ IDEA is currently not available in your country.

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Thanks for the report @Kmulla237941. This error message is misleading, there are no more country restrictions, please check that you have enabled Gemini API in GCP project you selected for use with GCA. Let us know more details if this doesn't work - Click Gemini status bar -> Submit feedback, and attach aiplugin.log, or submit it with a comment mentioning this issue in GitHub.

**Comment by ivanporty** [comment]
The error message should be fixed in the new release (1.1.0), and please re-open with more details if not fixed
