### ISSUE TITLE
COnflicts with intellij idea 2024.2.1

### ISSUE THREAD

**Issue by mirdones** [GoogleCloudPlatform/cloud-code-intellij#3229]
### Expected Behavior
Load Plugin

### Actual Behavior
Plugin does not load

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Intellij IDEA Ultimate
- IDE version: 2024.2.1
- Cloud Code version (Settings > Plugins > Cloud Code): 24.8.2-233-api-version-223
- Operating System: WIndows 11

Gemini code assist: IDE contains conflicting module 'org.jetbrains.android'
Gemini code assist/Cloud Code: Not loaded. The required plugin 'com.intellij.modules.vcs' is disabled.

Git is enabled.

![image](https://github.com/user-attachments/assets/717a3f3d-2211-4944-9cb9-e05168f03857)

**Comment by ivanporty** [comment]
Thank you for the report @mirdones, we are aware of the conflict between Android plugin and Gemini Code Assist. To avoid issues like #3222, we explicitly made these 2 plugins incompatible to avoid breaking the IDE. We are working with Android team to remove the conflicts and will update #3222 when done.

**Comment by ivanporty** [comment]
Duplicate #3222
