### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by denis-zhdanov** [GoogleCloudPlatform/cloud-code-intellij#3231]
The plugin doesn't work with the latest IntelliJL

<img width="480" alt="intellij-version" src="https://github.com/user-attachments/assets/914e8ece-30c4-4777-993e-ff76c7bb2b45">

<img width="983" alt="intellij-plugins" src="https://github.com/user-attachments/assets/8375b4ea-14fb-48e3-9355-20411fda2347">

**Comment by ivanporty** [comment]
Thank you for the report @denis-zhdanov, could you please provide details on what is not working for you?

**Comment by denis-zhdanov** [comment]
sorry, edited the description and attached the screenshots to it

**Comment by ivanporty** [comment]
Yes, we have the issue for this - at the moment, we have a conflict with Android plugin and work with Android team to resolve it. We disabled the combination of plugins in order to avoid the IDE crash in this scenario. Please track #3222

**Comment by ivanporty** [comment]
Duplicate #3222
