### ISSUE TITLE
Getting Authenticaion error 

### ISSUE THREAD

**Issue by shivani-sahu2096** [GoogleCloudPlatform/cloud-code-intellij#3232]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

**Expected Behavior**
Gemini should work
**Actual Behavior**
Its giving below issue
### Additional Information

- IDE type: Intellij
- IDE version:2024.2.0.2
- I have logged in from my account still facing this issue
-Gemini code Asist not working, Giving below error.
![a](https://github.com/user-attachments/assets/082d76ea-28d4-4b29-91c8-dfd65742a305)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
@shivani-sahu2096 we are working on better error handling for the next release, in this scenario, if re-login is required, you will have an option to login again.

**Comment by ivanporty** [comment]
This should be fixed in the new release (1.1.0)
