### ISSUE TITLE
Cloud Workstations Plugin not compatible with the latest version of JetBrains Gateway 2024.3 and Intellij 2024.3  

### ISSUE THREAD

**Issue by aperrillat** [GoogleCloudPlatform/cloud-code-intellij#3239]
**Version Information**

JetBrains Gateway version: 2024.3

Cloud Workstations plugin version: 24.8.1-api-version-231

**Details**

The Cloud Workstations Plugin is not compatible with the latest version of of JetBrains Gateway 2024.3 and Intellij 2024.3.  In plugins settings there is the following error message.
 
![image](https://github.com/user-attachments/assets/ca3accea-961f-42ce-8663-604cb8cd346f)

**Comment by ivanporty** [comment]
In progress, should be out soon.

**Comment by ivanporty** [comment]
Updated version released, let us know if this works for you

**Comment by aperrillat** [comment]
Yes now it works. Thanks
