### ISSUE TITLE
Can't sign out of account when signed in

### ISSUE THREAD

**Issue by DoritosXL** [GoogleCloudPlatform/cloud-code-intellij#3241]
### Expected Behavior
A button to sign out of your linked account

### Actual Behavior
No option to sign out

### Additional Information
Tried disabling the plugin, uninstalling the plugin, uninstalling the IntelliJ IDE but the code assist plugin always has me signed in without an option to sign out. 

- IDE typeIntelliJ
- IDE version: 2024.3 - Build #IU-243.21565.193, built on November 13, 2024
- Operating System: Macos Sonoma 14.7.1

**Comment by ttosta-google** [comment]
Hello @DoritosXL 

Please try deleting the file `credentials.json` located at `~/Library/Application\ Support/cloud-code/intellij` (macOS) and then restarting the IDE.

We are working on a fix for this issue. Thanks for your patience.

Please let us know if it works for you.

**Comment by DoritosXL** [comment]
This works for me, thanks for the quick work around!
