### ISSUE TITLE
Code Asisst does not have logout button in IntelliJ

### ISSUE THREAD

**Issue by mahesh-shelke** [GoogleCloudPlatform/cloud-code-intellij#3242]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ
- IDE version:
- Cloud Code version (Settings > Plugins > Cloud Code): 
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: 
  - Version of the Cloud SDK:
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Mac OS

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Hi @mahesh-shelke we do have a sign out button in the Gemini status bar menu - do you see it?

**Comment by mahesh-shelke** [comment]
Here are the two screens. I dont see logout button.
I deleted credentials files which logged me out.

<img width="632" alt="image" src="https://github.com/user-attachments/assets/7ddc188c-cb2e-4e57-9d4f-a8c4efce7089">
<img width="976" alt="image" src="https://github.com/user-attachments/assets/590de53a-4432-4864-afcc-2f86aef37278">

**Comment by ivanporty** [comment]
Gemini status bar: 
![8w4FqfQCnu3uJHh](https://github.com/user-attachments/assets/03225581-f862-47d1-a145-c47abb2a7742)

**Comment by ivanporty** [comment]
@mahesh-shelke please try the latest version - you should be able to see the sign out action in the status bar regardless of the login step you are on and be able to logout and re-login as needed.
