### ISSUE TITLE
No "Retake the snapshot" button

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#340]
If I understand correctly, this means that once a snapshot is taken, it isn't possible to take another one.

There must be something I'm missing, as I don't remember this was the behaviour before. But using the Developers Console, I can only take a new snapshot once I click the "retake this snapshot" button.

**Comment by patflynn** [comment]
you should be able to set another one, but you have to explicitly say so.

**Comment by joaoandremartins** [comment]
Do you feel any improvements are necessary here?

After reading the docs and having experience in CDB, I know that I need to reset a breakpoint if I want a new snapshot in the same place. But I feel like we should point this out somewhere in IJ in order to improve new user experience.

I thought of adding some text to the "New Snapshot Added" green box that appears, but it won't look great and wouldn't work when breakpoint is hit offline.

**Comment by patflynn** [comment]
I think a visual cue on the breakpoint icon would be helpful. Something
that makes it clear that not only has it been triggered, but it is not
inactive until reset.

**Comment by etanshaul** [comment]
closed as "won't fix" low priority, and stale
