### ISSUE TITLE
Implement snapshot sharing

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#344]
The CDB docs boast a snapshot sharing feature and I think we should support this too.

We can get the proto version of the snapshot by calling the REST API, but we should really add a button and open a browser window with the snapshot in the Developers Console, as documented in [1].

[1] https://cloud.google.com/tools/cloud-debugger/debugging#share_snapshots

**Comment by etanshaul** [comment]
closed as "won't fix"
