### ISSUE TITLE
Remove Jackson1 dependency

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/cloud-code-intellij#350]
We really shouldn't have to include jackson1 json parsers : https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/master/google-account-plugin/build.gradle

This is a result of the static selection of the parser in :
https://github.com/GoogleCloudPlatform/google-plugin-for-eclipse/blob/master/plugins/com.google.gdt.eclipse.login/src/com/google/gdt/eclipse/login/common/GoogleLoginState.java

It would be nice if the constructor accepted transport and jsonParser as parameters like the other google client libraries.

**Comment by elharo** [comment]
Doable. I wonder if maybe we should pull the purely login, non-Eclipse parts of that project out into a separate project? Looks like the jar already does that. How is this currently released and built?

**Comment by patflynn** [comment]
+1. We should absolutely do this. what I'd like to see us do is create a
well designed, from scratch, login library for Java.

**Comment by elharo** [comment]
This would likely be a combination what's currently in com.google.gdt.eclipse.login.common and in the account plugin (e.g. CredentialedUser). Essentially all the pieces that don't depend on Eclipse or IntelliJ. 

Let me look around and see if anyone has done this already. If not, it's probably worth a simple design doc.

**Comment by patflynn** [comment]
We've been talks with usable auth and identity teams about this.  the
usable auth java library has some pieces, but we'd have to provide the
rest.  Talk to appu who may be looking at this as part of his library work.

**Comment by etanshaul** [comment]
closed as stale
