### ISSUE TITLE
Lack of OAuth permissions leads to error not prominent enough when opening debug attach dialog

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/cloud-code-intellij#415]
Preconditions:
- user has conducted a Cloud Debugger session, so that the next time he launches IJ and opens the attach dialog the name of the most recently used project will be added to the project selector
  - user is logged into his Google Account from IJ
  - OAuth permissions are revoked from IJ through the dev console

Observed behavior:
- user lanuches IJ
- opens the attach dialog by clicking on the Debug icon when the Cloud Debugger run configuration is selected
- the dialog opens, the most recently used project's name is displayed in the project selector
- the target/module selector remains blank and disabled, no error message is shown
- if the user tries to select a different project, an error message becomes visible informing the user that "Could not connect to Google. Please make sure you have a working internet connection."
- actually only the first half of the error message is visible, the rest is clipped by the selector's border

Expected behavior:
- when user opens the attach dialog a message is immediately visible informing the user about the error
- the error message is fully visible

Cause:
- when the dialog opens, the last debug session state is loaded from the local file store and the project name is set as the text for the selector (#setText(...))
- when the call to the backend to query the projects the user has access to result in an error, an item for the error is added to the project selectors data model, but it is not selected, thus won't become visible until the user opens the selector's dropdown panel

Possible fix:
- when the error is added to the dropdown, set it as the selected item of the project selector.

**Question**: should this be rather a account plugin error and handled there that the stored credentials became invalid and prompt the user to login again?

**Comment by etanshaul** [comment]
closed as stale
