### ISSUE TITLE
Need to define manual testing scripts for release verification

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#462]
We need a set of testing scripts that will run through the major flows of our feature set. 

Including:
- Debugging
- VCS integration
- Login/logout.
- App Engine deployment

**Comment by patflynn** [comment]
related to #551

**Comment by patflynn** [comment]
Anybody who wants to work on this should talk to @etanshaul, as he has a first stab at a format for the scenario doc.

**Comment by patflynn** [comment]
@aslo

**Comment by etanshaul** [comment]
stale and already complete
