### ISSUE TITLE
Pressing ESC on the stop debug session confirmation dialog will take one of the actions

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/cloud-code-intellij#466]
If a user, maybe accidentally clicks on the "Stop IDE Debugging" button (red square), he's shown a dialog where he can choose whether he wants the session to continue listen in the background or stop listening. There is no option to cancel the action altogether, i.e. continue the debug session. There is not button to click on for this option, and pressing ESC is handled as clicking on the "Stop listening" button.

**Comment by etanshaul** [comment]
this is more of an enhancement, no? nice to have though I agree

**Comment by akerekes** [comment]
If you are running a debug session, and click on the button, you either will terminate the session or set it to listen in the background. If you clicked on it accidentally, you cannot cancel the action, either you'll have to restart the debug session (if you chose to terminate it) or you'll need to reattach to it.
Considering the fact, that this is not a debug session in the conventional sense, probably not a big issue, you won't loose state. I still think it's a bug, but mark it as low priority.

**Comment by etanshaul** [comment]
closed as "wont fix"
