### ISSUE TITLE
cloud debugger; sometimes the 'changes detected' balloon doesn't show up even though it appears in the event log

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#649]
If I stop a cloud debugger session, but continue listening.  I can frequently trigger a snapshot without getting the notification. But if I look at the event log the notifcation is there.

![screenshot from 2016-04-22 15 13 28](https://cloud.githubusercontent.com/assets/7862557/14752369/f0117ee8-089c-11e6-891d-cc9a8160b18e.png)

**Comment by chanseokoh** [comment]
I can't seem to reproduce this. Judging from your screenshot, I believe you sometimes don't get a notification at all, right? Perhaps I should see how you reproduce this in person.

**Comment by patflynn** [comment]
Yeah this was an intermittent issue, but I do not know exactly how to reproduce it.

**Comment by etanshaul** [comment]
closed as not reproducible
