### ISSUE TITLE
Our App Engine Deployment support should allow the selecting of Maven and Gradle modules configured with our new app-maven/gradle-plugins 

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#666]
Maven and Gradle apps that use App Engine standard (and therefore have an appengine-web.xml), and are configured with our app-maven/gradle-plugin should be deployable.

**Comment by etanshaul** [comment]
I wonder how relevant this is still. AE standard apps that are properly are always "natively" deployable.

**Comment by patflynn** [comment]
Yeah I think you're right.

**Comment by patflynn** [comment]
I guess one question is whether users will want to be able to deploy the results of the mvn build vs the custom exploded-war type.

**Comment by patflynn** [comment]
I think that it's conceivable they would. It depends on the fidelity of the native IntelliJ artifact.

**Comment by etanshaul** [comment]
closed as "won't fix"
