### ISSUE TITLE
App Engine flexible environment staging should use the common app-tools library

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#717]

**Comment by chanseokoh** [comment]
This should also address #703, shouldn't it?

**Comment by etanshaul** [comment]
I don't know if its that simple because we also have the issue of selection of a Dockerfile vs Dockerfile + directory context. The latter will affect the UI.

**Comment by etanshaul** [comment]
closed due to deprioritization
