### ISSUE TITLE
The static App Engine utility methods that perform IO should be factored out as collaborators that can be mocked

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#731]
Two reasons to do this:
1) Testing:  If we want to be able to unit test effectively we need to be able to swap out the stuff that depends on the deep IJ class hierarchy and infratructure.  Also as a general principle static methods should be pure functions.  They must not depend on hidden state or have side-effects.
2) Modeling:  I think it may actually improve readability if we move some of the static code into some of the model objects since the static methods are often describing a property of those objects.

**Comment by patflynn** [comment]
I'm going to tinker around with this this morning.

**Comment by etanshaul** [comment]
@patflynn are you working on this? If not, I can start with it.

**Comment by patflynn** [comment]
Yeah go ahead. Planning has interrupted this.

What do you think about refactoring most of the 'Helper' features as an IJ
service with minimal context?  Also some of the utility methods look like
they belong on the objects they query.

I'd like the work to address this architectural issue to take a decent stab
at improving the test coverage of the infrastructure we're providing for
App Engine support.

And finally in small PRs when possible. (I know that's hard)

**Comment by etanshaul** [comment]
Yes. I agree with your points here. I'll tackle this.

**Comment by etanshaul** [comment]
closed as fixed
