### ISSUE TITLE
Sync with maven / gradle plugins

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#805]
If the project has the maven or gradle plugins configured, then we can bootstrap our configuration with the settings from these plugins. E.g. for a flex app we can create the cloud type, extract the sdk config, the app.yaml location etc. to save any redundant configuration by the user in the IDE.

**Comment by aslo** [comment]
@etanshaul Can you provide a list of the configs that we want to get from maven/gradle? Is is pretty much just the parameters that the user specifies when setting up a deployment run configuration?

Also is this only for flex deployments, or for standard also?

**Comment by etanshaul** [comment]
It is for flex and standard.

I have not yet researched this much but the basic idea is to inspect the configuration provided by the maven and gradle plugins and use this info to bootstrap our deployment configuration. What specific config this entails I do not yet know.

**Comment by aslo** [comment]
Sounds good!

**Comment by etanshaul** [comment]
closed as "won't fix"
