### ISSUE TITLE
GAE facet isn't being added to Gradle modules

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#835]
It is apparently added to generic/Maven generated modules.

This causes the users to have to manually add the facet to the Gradle generated module, which is unnecessary extra work. On top of that, there is an issue where multiple modules can be added with the same content roots, and any changes to those modules can't be applied/persisted if the content roots are the same, so the facet can't effectively be added and the user must choose which artifact they want to use.

**Comment by etanshaul** [comment]
@joaoandremartins 

Can you maybe breakdown this issue a bit more. I tested the simple case of opening an AE standard gradle project, adding AE framework support (via the popup), and deploying. The facet was present (albeit with an additional "web gradle" facet):

![image](https://cloud.githubusercontent.com/assets/1735744/18357780/36d8137e-75c0-11e6-9fa4-1b4aec59c5c1.png)

And then when deploying, I could select the exploded war (even though gradle seems to "mark" the artifact), and successful deploy it to AE standard:

![image](https://cloud.githubusercontent.com/assets/1735744/18357811/5c8bdf10-75c0-11e6-9b53-047a4af51f7c.png)

![image](https://cloud.githubusercontent.com/assets/1735744/18357866/8e71b2b6-75c0-11e6-82fe-b3379956b0eb.png)

**Comment by joaoandremartins** [comment]
I can't remember very well where I wanted to go with this. Tried playing around with it now for a while, but couldn't find the same behaviour again.
I seem to have though that the GAE facet gets automatically added to Maven projects, which isn't true, so this issue is probably invalid.

I'll reopen if I see the same behaviour happening again.

**Comment by etanshaul** [comment]
closed as stale / not reproducible
