### ISSUE TITLE
Add "Application Servers" output to GAE Application Server

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-code-intellij#836]
Right now, the App Engine local run configurations don't produce any output to the Application Servers window, but rather to the Run/Debug windows.

However, the Tomcat and Jetty integrations produce output to the Application Servers window. We should probably do the same. This might or not have something to do with the DeploymentProvider object required by the Application Servers framework.

**Comment by joaoandremartins** [comment]
Lowering priority here and removing from 1.0-GA milestone.

DeploymentProvider doesn't add a lot of value here, and might even complicate local runs a bit.

Should be worked on when no other pressing issues exist.

**Comment by patflynn** [comment]
Please check with me before removing things from milestones.  

I think that you're right about priority. But let's aspirationally try to get this in after we've addressed more pressing issues.

**Comment by joaoandremartins** [comment]
Sounds good!

**Comment by etanshaul** [comment]
closed as "won't fix" due to changing priorities
