### ISSUE TITLE
With multiple windows, login toolbar button not being updated properly

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/cloud-code-intellij#859]
If you have multiple projects opened in different windows (or workbenches), the toolbar button doesn't seem to be updated properly. For me, it's easy to reproduce by starting fresh: log out, close all windows, open at least two windows, and then try log in/out.

After login, the tooltip says "Sign in to Google...", and no avatar image.

![selection_002](https://cloud.githubusercontent.com/assets/10523105/18184936/0dfb959a-7069-11e6-99c2-7a64c86e6609.png)

After logging out, the tooltip displays an email address, and an avatar is shown.

![selection_005](https://cloud.githubusercontent.com/assets/10523105/18185009/6abd3a4a-7069-11e6-91a4-2e660894bb7f.png)

**Comment by etanshaul** [comment]
closed as stale / not reproducible (anymore?)
