### ISSUE TITLE
The configuration of the app engine local development server should include JDK to use

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#926]
Other local server run configs let the user specify which of the project's JDKs to use to run:

<img width="713" alt="screen shot 2016-09-22 at 9 47 01 am" src="https://cloud.githubusercontent.com/assets/7862557/18757632/9bcd4648-80a9-11e6-8e44-208eca01378a.png">

Also is it safe to assume that the dev app server configuration is using the module jdk for the java process currently?

**Comment by etanshaul** [comment]
I think its not using the module jdk but the system jdk instead. When debugging https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/920 I noticed that the version of java configured in the module does not affect the issue (whereas changing the system jdk does).

**Comment by patflynn** [comment]
ok I'll create a new bug for that.

**Comment by patflynn** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/927

**Comment by joaoandremartins** [comment]
As I mentioned in #927, I don't know if this is currently feasible, given dev_appserver.py's interface.

**Comment by etanshaul** [comment]
closed as "won't fix"
