### ISSUE TITLE
Starting a task that requires the Cloud SDK should fail with clear steps on how to fix a config

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#939]
![screenshot from 2016-09-28 11 31 07](https://cloud.githubusercontent.com/assets/7862557/18920334/118e80e4-856f-11e6-9e39-04ed0c549754.png)

If possible it would be nice to include a link to the Cloud SDK configuration UI from the error.

**Comment by etanshaul** [comment]
closed as stale / pre-managed-cloud-sdk
