### ISSUE TITLE
Source Context in Stack Driver debugger doesn't appear to work without pushing the code to GCR

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#973]
Steps to reproduce:
1. Create a new App Engine standard project from wizard
2. Create a git repo and commit the project code locally
3. Deploy using our deployment run config
4. select the deployed version using stackdriver debug attach dailog

observed results:
5. Observe that the stackdriver debug dialog warns 'it could not locate a remote repository'
6. also observe it does not offer to stash local changes or sync to the version of the deployment

expected results:
I should be able to stash and sync my local changes.

**Comment by etanshaul** [comment]
closed as stale / not reproducible (anymore?)
