### ISSUE TITLE
Console Info logging statements are red

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/cloud-code-intellij#974]
Are the console statements that are info intended to be red? 

![screen shot 2016-10-10 at 10 26 11 am](https://cloud.githubusercontent.com/assets/1326504/19245058/10b6e90e-8ed4-11e6-9f14-8c0e430d9fde.png)

**Comment by branflake2267** [comment]
By the way, it appears that the server is starting even tho the port is being taken by another server.

**Comment by jmah-cc** [comment]
Bulk closing issues older than 2 years. Feel free to re-open if this issue is still repro'ing or important.
