### ISSUE TITLE
Improve Java 8 Support Messaging

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/cloud-code-intellij#988]
Improve the warning that users see when trying to use Java 8 code in an AE standard project. Also, add a confirmation dialog that something changed when the link is clicked.
## Current warning dialog text:

![screenshot from 2016-10-11 12 22 00](https://cloud.githubusercontent.com/assets/1039411/19278987/6fd6d582-8fad-11e6-9661-e0125a3badff.png)
## Desired warning dialog text:

**Java Language Level Not Supported**
The following modules in this project are using a version of App Engine that does not support Java 8:
- myAppEngineModule1
- myOtherAEModule2

Please _click here_ to update these modules to use the Java 7 language level, to ensure that they will be supported on App Engine. The JDK used by these modules will remain the same.
## Desired confirmation dialog text:

Language level for the following modules has been successfully changed to Java 7:
- myAppEngineModule1
- myOtherAEModule2

**Comment by aslo** [comment]
cc @etan @patflynn A nice-to-have, to clarify the expected behavior of clicking the link.

**Comment by patflynn** [comment]
SGTM

**Comment by heikkitx** [comment]
Doesn't App Engine support Java 8 already.

I do get this warning.

> Java language level not supported: One or more modules in this project use a version of App Engine that does not support Java 8. Please click here to automatically change them to use the Java 7 language level.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000014680-IntelliJ-gives-an-warning-about-some-module-not-supporting-Java-8-without-identifying-the-trouble-module

**Comment by patflynn** [comment]
Hi @heikkitx,

You have to add <runtime>java8</runtime> to your appengine-web.xml to use java8.

**Comment by patflynn** [comment]
@etanshaul could be nice to change this warning to suggest fixing the runtime instead of changing the module language level to 7.

**Comment by heikkitx** [comment]
I have that. And Java 8 features like annotations work well.

**Comment by etanshaul** [comment]
@heikkitx is it a multi-module project by any chance? I'm wondering if the warning is coming from a module you weren't expecting (that doesn't have the runtime set to java8).

**Comment by etanshaul** [comment]
closed as "won't fix"
