### ISSUE TITLE
Old App Engine dev server configurations are selectable by the new App Engine develoment server run config

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#991]
![screenshot from 2016-10-11 13 48 28](https://cloud.githubusercontent.com/assets/7862557/19281736/9aa2a01e-8fb9-11e6-92a1-e087797f96a6.png)

Steps to reproduce:
1. Create an app engine project with using the JB old app engine plugin 
2. configure the app engine sdk
3. install our plugin
4. disable the old plugin and restart
5. observe that there is a new plugin based development server run config
6. observe that the SDK of the run config is pointing to the old App Engine based SDK

expected result:
I'd have to create a new Cloud SDK based server and the App Engine SDK based one would not be selectable.

**Comment by etanshaul** [comment]
closing as obsolete / stale
